SET DEFINE OFF;
SET ECHO ON;
insert into pdc_lookup values('DIAG_HEM', 'CA13135C', 'Hemolysis', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', 'hemolysis', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '29', '');
insert into pdc_lookup values('DIAG_HEM', 'CA13136C', 'Lipemia Index', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', 'lipemia_index', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '29', '');
insert into pdc_lookup values('DIAG_URINALYSIS', 'CA13150C', 'Leu', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', 'leu', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '29', '');
insert into pdc_lookup values('DIAG_URINALYSIS', 'CA13151C', 'Nit', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', 'nit', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '29', '');
insert into pdc_lookup values('DIAG_URINALYSIS', 'CA13152C', 'pH', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', 'ph_result', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '29', '');
insert into pdc_lookup values('DIAG_URINALYSIS', 'CA13158C', 'Blo', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', 'blo', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '29', '');
insert into pdc_lookup values('HEMOLYSIS', 'CA13137C', 'HEMOLYSIS_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '29', '');
insert into pdc_lookup values('HEMOLYSIS', 'CA13139C', '25', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '29', '');
insert into pdc_lookup values('HEMOLYSIS', 'CA13140C', '50', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '29', '');
insert into pdc_lookup values('HEMOLYSIS', 'CA13141C', '100', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '29', '');
insert into pdc_lookup values('HEMOLYSIS', 'CA13142C', '200', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '29', '');
insert into pdc_lookup values('HEMOLYSIS', 'CA13143C', '400', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '29', '');
insert into pdc_lookup values('HEMOLYSIS', 'CA13144C', '800', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '29', '');
insert into pdc_lookup values('LIPEMIA_INDEX', 'CA13145C', 'LIPEMIA_INDEX_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '29', '');
insert into pdc_lookup values('LIPEMIA_INDEX', 'CA13146C', 'Less than 30', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '29', '');
insert into pdc_lookup values('LIPEMIA_INDEX', 'CA13147C', '30-60', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '29', '');
insert into pdc_lookup values('LIPEMIA_INDEX', 'CA13148C', '60-120', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '29', '');
insert into pdc_lookup values('LIPEMIA_INDEX', 'CA13149C', 'Greater than 120', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '29', '');
insert into pdc_lookup values('LEU_RESULT', 'CA13153C', 'LEU_RESULT_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '29', '');
insert into pdc_lookup values('LEU_RESULT', 'CA13154C', 'Trace', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '29', '');
insert into pdc_lookup values('LEU_RESULT', 'CA13155C', 'Small', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '29', '');
insert into pdc_lookup values('LEU_RESULT', 'CA13156C', 'Modertae', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '29', '');
insert into pdc_lookup values('LEU_RESULT', 'CA13157C', 'Large', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '29', '');
insert into pdc_lookup values('PH_RESULT', 'CA13166C', 'PH_RESULT_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '29', '');
insert into pdc_lookup values('PH_RESULT', 'CA13167C', '5', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '29', '');
insert into pdc_lookup values('PH_RESULT', 'CA13168C', '6', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '29', '');
insert into pdc_lookup values('PH_RESULT', 'CA13169C', '6.5', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '29', '');
insert into pdc_lookup values('PH_RESULT', 'CA13170C', '7', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '29', '');
insert into pdc_lookup values('PH_RESULT', 'CA13171C', '7.5', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '29', '');
insert into pdc_lookup values('PH_RESULT', 'CA13172C', '8', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '29', '');
insert into pdc_lookup values('PH_RESULT', 'CA13173C', '8.5', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '29', '');
insert into pdc_lookup values('BLO_RESULT', 'CA13159C', 'BLO_RESULT_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '29', '');
insert into pdc_lookup values('BLO_RESULT', 'CA13160C', 'Negative', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '29', '');
insert into pdc_lookup values('BLO_RESULT', 'CA13161C', 'Trace', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '29', '');
insert into pdc_lookup values('BLO_RESULT', 'CA13162C', 'Moderate', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '29', '');
insert into pdc_lookup values('BLO_RESULT', 'CA13163C', 'Hemolyzed trace', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '29', '');
insert into pdc_lookup values('BLO_RESULT', 'CA13164C', 'Small', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '29', '');
insert into pdc_lookup values('BLO_RESULT', 'CA13165C', 'Large', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '29', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA13132C', 'Alfano, Robert - A1717', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '29', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA13133C', 'Buehring, Gertrude - A1419', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '29', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA13129C', 'Elnitski, Laura - A2017', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '29', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA13130C', 'Glickson, Jerry - A2019', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '29', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA13127C', 'Jala, Shadia - A2012', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '29', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA13124C', 'Klein, Eric - F0040', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '29', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA13134C', 'Lin, Weei-Chin - A2032', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '29', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA13126C', 'Roth, David - A2023', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '29', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA13131C', 'Stacey, Dennis - F0041', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '29', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA13125C', 'Williams, Jennie - A2015', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '29', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA13128C', 'Zeisel, Steven - A2025', '', '', 'ARD_CAP', 'A', 'P', '', '1.71', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '29', '');
commit;
