
ALTER TABLE CIR_SAMPLE_INFO
 ADD (EXP_DISTRIBUTION_CUI  VARCHAR2(30 BYTE));

ALTER TABLE CIR_SAMPLE_INFO
 ADD (TCGA_COLLECTION_PROC_CUI  VARCHAR2(30 BYTE));

CREATE TABLE CIR_BIOMARKER_ADE
(
  ID                   NUMBER,
  FORM_ID              VARCHAR2(10 BYTE),
  PARENT_ID            NUMBER,
  DATA_ELEMENT_CUI     VARCHAR2(30 BYTE),
  BIOMARKER_SCORE_CUI  VARCHAR2(30 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE CIR_PT_INFO
 ADD (DONOR_CAP_FLDS_COMP_CUI  VARCHAR2(30 BYTE));

ALTER TABLE CIR_SAMPLE_INFO
 ADD (TCGA_SURGERY_CUI  VARCHAR2(30 BYTE));

ALTER TABLE CIR_SAMPLE_INFO
 ADD (TCGA_VOLUME  NUMBER);

ALTER TABLE CIR_SAMPLE_INFO
 ADD (TCGA_VOLUME_CUI  VARCHAR2(30 BYTE));

ALTER TABLE CIR_CASE_INFO
 ADD (RPT_SURG_PATH_COMP_CUI  VARCHAR2(30 BYTE));
