CREATE OR REPLACE FORCE VIEW FORM_V
(FORM_ID, DOMAIN_OBJECT_ID, DOMAIN_OBJECT_TYPE, CREATION_DATETIME,MODIFICATION_DATETIME)
AS
(SELECT FORM_ID, DOMAIN_OBJECT_ID, DOMAIN_OBJECT_TYPE, CREATION_DATETIME, MODIFICATION_DATETIME
FROM CIR_FORM);
/