CREATE OR REPLACE VIEW LIMS_BIGR_LIBRARY_V ( SAMPLE_ID,VIABLETUMERCELLS,
VIABLELESIONALCELLS, VIABLENORMALCOMP,
CELLULARSTROMA, ACELLULARSTROMA, 
NECROSIS, COMMENTS, INTERNAL_COMMENTS, TISSUE_ORIGIN_CONCEPT_ID, 
TISSUE_FINDING_CONCEPT_ID, DX_OTHER, TC_OTHER_ORIGIN, TC_OTHER_FINDING ) 
AS (SELECT SAMPLE_BARCODE_ID, 
     TUMOR_CELLS, 
     LESION_CELLS,  
     NORMAL_CELLS,  
     CELLULARSTROMA_CELLS, 
     HYPOACELLULARSTROMA_CELLS, 
     NECROSIS_CELLS, 
     EXTERNAL_COMMENTS, 
     INTERNAL_COMMENTS, 
     TISSUE_ORIGIN_CONCEPT_ID, 
     TISSUE_FINDING_CONCEPT_ID, 
     OTHER_DIAGNOSIS_NAME, 
     OTHER_TISSUE_ORIGIN_NAME,
     OTHER_TISSUE_FINDING_NAME
FROM LIMS_PATHOLOGY_EVALUATION
WHERE REPORTED_YN = 'Y') 
/
