CREATE OR REPLACE VIEW LIMS_ADS_ILTDS_V ( SLIDE_ID, 
CONSENT_ID, ORGAN_SITE, SPECIMEN_TYPE, ASM_DESIGNATION, 
BLOCK_LABEL, ORIGINAL_DIAGNOSIS, PATHOLOGIST_ID, PATHOLOGIST_NAME
 ) AS SELECT
	  SLIDE.SLIDE_ID,
	  ILTDS_ASM.CONSENT_ID ARDAIS_CASE_ID,
	  Y.LOOKUP_TYPE_CD_DESC ORGAN_SITE,
	  ILTDS_ASM.SPECIMEN_TYPE SPECIMEN_TYPE,
	  ILTDS_SAMPLE.ASM_POSITION DESINATION,
	  ILTDS_SAMPLE.SAMPLE_BARCODE_ID BLOCK_LABEL,
	  NVL(Z.LOOKUP_TYPE_CD_DESC, X.LOOKUP_TYPE_CD_DESC) DIAGNOSIS	,
  	  NVL(EVAL.CREATE_USER, SLIDE.CREATE_USER) USERID,
	  NVL(EVAL.CREATE_USER, SLIDE.CREATE_USER) USERID
FROM ILTDS_SAMPLE,
  	 ILTDS_ASM,
	 ILTDS_INFORMED_CONSENT,
	 PDC_LOOKUP X,
	 PDC_LOOKUP Y,
	 PDC_LOOKUP Z,
	 PDC_PATHOLOGY_REPORT,
	 LIMS_SLIDE SLIDE,
	 (SELECT SLIDE_ID, CREATE_USER FROM LIMS_PATHOLOGY_EVALUATION
	 WHERE PE_ID IN (SELECT MAX(PE_ID) FROM LIMS_PATHOLOGY_EVALUATION
	 GROUP BY SLIDE_ID  ))EVAL
WHERE SLIDE.SLIDE_ID = EVAL.SLIDE_ID(+)
AND SLIDE.SAMPLE_BARCODE_ID = ILTDS_SAMPLE.SAMPLE_BARCODE_ID
AND   ILTDS_SAMPLE.ASM_ID = ILTDS_ASM.ASM_ID
AND   ILTDS_INFORMED_CONSENT.CONSENT_ID = ILTDS_ASM.CONSENT_ID
AND   ILTDS_INFORMED_CONSENT.CONSENT_ID = PDC_PATHOLOGY_REPORT.CONSENT_ID(+)
AND   PDC_PATHOLOGY_REPORT.DIAGNOSIS_CONCEPT_ID = Z.LOOKUP_TYPE_CD(+)
AND   ILTDS_INFORMED_CONSENT.DISEASE_CONCEPT_ID = X.LOOKUP_TYPE_CD(+)
AND   ILTDS_ASM.ORGAN_SITE_CONCEPT_ID = Y.LOOKUP_TYPE_CD(+)
/