CREATE OR REPLACE FORCE VIEW ROLE_PRIVILEGE_V (ROLE_ID,
                                               PRIVILEGE_NAME)
AS
   SELECT ROLE_ID,
          OBJECT_DESCRIPTION PRIVILEGE_NAME
     FROM BIGR_ROLE_PRIVILEGE BRP, ARD_OBJECTS AO
     WHERE BRP.PRIVILEGE_ID = AO.OBJECT_ID
/
