CREATE OR REPLACE FORCE VIEW user_v (user_id,
                                     account_id,
                                     active_yn,
                                     last_name,
                                     first_name,
                                     title,
                                     functional_title,
                                     affiliation,
                                     phone_number,
                                     phone_extension,
                                     fax_number,
                                     mobile_number,
                                     email_address,
                                     department,
                                     address_1,
                                     address_2,
                                     city,
                                     state,
                                     zip_code,
                                     country
                                     )
AS
   SELECT eau.ardais_user_id user_id, 
          eau.ardais_acct_key account_id,
          eau.user_active_ind active_yn, 
          eau.user_lastname last_name,
          eau.user_firstname first_name, 
          eau.user_title title,
          eau.user_functional_title functional_title,
          eau.user_affiliation affiliation,
          eau.user_phone_number phone_number,
          eau.user_phone_ext phone_extension, 
          eau.user_fax_number fax_number,
          eau.user_mobile_number mobile_number,
          eau.user_email_address email_address,
          eau.user_department department, 
          aa.address_1, 
          aa.address_2,
          aa.addr_city city, 
          aa.addr_state state, 
          aa.addr_zip_code zip_code,
          aa.addr_country country
     FROM es_ardais_user eau, ardais_address aa
    WHERE eau.user_address_id = aa.address_id(+)
/
