SET DEFINE OFF;
SET ECHO ON;
insert into pdc_lookup values('SAMPLE_INFO', 'CA12974C', 'A260/A280 Ratio', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', 'a260_a280_ratio', '1', 'N', 'float', '', 'Element', '', '', '', '', '', '', 'N', '', '26', '');
insert into pdc_lookup values('CELL_TYPE', 'CA12975C', 'Cell Type', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', 'cell_type', '1', 'Y', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '26', '');
insert into pdc_lookup values('ELUTION_BUFFER', 'CA12976C', 'Elution Buffer', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', 'elution_buffer', '1', 'Y', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '26', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12966C', 'Freezing Media', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', 'freezing_media', '1', 'N', 'text', '', 'Element', '', '', '', '', '', '', 'N', '', '26', '');
insert into pdc_lookup values('PHENOTYPIC_PATTERN', 'CA13007C', 'Phenotypic Pattern', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', 'phenotypic_pattern', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '26', '');
insert into pdc_lookup values('CELL_TYPE', 'CA12961C', 'CELL_TYPE_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('CELL_TYPE', 'CA12962C', 'PRE_B_ALL', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('CELL_TYPE', 'CA12963C', 'T_ALL', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('CELL_TYPE', 'CA12964C', 'AML', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('CELL_TYPE', 'CA12965C', 'Other', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', 'Y', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('ELUTION_BUFFER', 'CA12967C', 'ELUTION_BUFFER_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('ELUTION_BUFFER', 'CA12968C', 'Low TE', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('ELUTION_BUFFER', 'CA12969C', 'Promega TE', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('ELUTION_BUFFER', 'CA12970C', 'Qiagen TE', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('ELUTION_BUFFER', 'CA12971C', 'Water', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('ELUTION_BUFFER', 'CA12972C', 'None', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('ELUTION_BUFFER', 'CA12973C', 'Other', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', 'Y', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12986C', 'AFB stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12985C', 'Alcian blue PAS stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12982C', 'Aldehyde Fuchsin stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA13005C', 'BAF47 stain (INI-1)', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12994C', 'CD20 stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12993C', 'CD3 stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12998C', 'CD31 stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12997C', 'CD34 stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12996C', 'CD45 stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA13002C', 'CD68 stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12995C', 'CD79a stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12989C', 'D240 stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA13001C', 'GFAP stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12988C', 'GLUT-1 stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12981C', 'Gram stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12987C', 'Iron stain (Prussian blue)', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12990C', 'Ki-67 stain (MIB-1)', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12983C', 'Movat Pentachrome stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12984C', 'Mucicarmine stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA13004C', 'Myogenin stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12979C', 'PAS', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12992C', 'Pax-5 stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA13006C', 'PGP9.5 stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12999C', 'SMA stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA13000C', 'Synaptophysin stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12991C', 'Tdt stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12980C', 'Trichrome - Gomori stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA13003C', 'Vimentin stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('STORAGE_TYPE', 'CA12978C', 'Other', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', 'Y', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('PHENOTYPIC_PATTERN', 'CA13008C', 'PHENOTYPIC_PATTERN_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('PHENOTYPIC_PATTERN', 'CA13009C', 'CD1a', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('PHENOTYPIC_PATTERN', 'CA13010C', 'CD2', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('PHENOTYPIC_PATTERN', 'CA13011C', 'CD3', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('PHENOTYPIC_PATTERN', 'CA13012C', 'CD4', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('PHENOTYPIC_PATTERN', 'CA13013C', 'CD5', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('PHENOTYPIC_PATTERN', 'CA13014C', 'CD7', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('PHENOTYPIC_PATTERN', 'CA13015C', 'CD8', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('PHENOTYPIC_PATTERN', 'CA13016C', 'CD10', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('PHENOTYPIC_PATTERN', 'CA13017C', 'CD11b', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('PHENOTYPIC_PATTERN', 'CA13018C', 'CD13', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('PHENOTYPIC_PATTERN', 'CA13019C', 'CD14', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('PHENOTYPIC_PATTERN', 'CA13020C', 'CD15', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('PHENOTYPIC_PATTERN', 'CA13021C', 'CD16', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('PHENOTYPIC_PATTERN', 'CA13022C', 'CD18', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('PHENOTYPIC_PATTERN', 'CA13023C', 'CD19', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('PHENOTYPIC_PATTERN', 'CA13024C', 'CD20', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('PHENOTYPIC_PATTERN', 'CA13025C', 'CD22', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('PHENOTYPIC_PATTERN', 'CA13026C', 'CD30', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('PHENOTYPIC_PATTERN', 'CA13027C', 'CD34', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('PHENOTYPIC_PATTERN', 'CA13028C', 'CD36', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('PHENOTYPIC_PATTERN', 'CA13029C', 'CD41a', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('PHENOTYPIC_PATTERN', 'CA13030C', 'CD42b', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('PHENOTYPIC_PATTERN', 'CA13031C', 'CD45', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('PHENOTYPIC_PATTERN', 'CA13032C', 'CD56', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('PHENOTYPIC_PATTERN', 'CA13033C', 'CD61', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('PHENOTYPIC_PATTERN', 'CA13034C', 'CD69', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('PHENOTYPIC_PATTERN', 'CA13035C', 'CD71', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('PHENOTYPIC_PATTERN', 'CA13036C', 'CD117', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('PHENOTYPIC_PATTERN', 'CA13037C', 'Cy CD22', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('PHENOTYPIC_PATTERN', 'CA13038C', 'Cy Tdt', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('PHENOTYPIC_PATTERN', 'CA13039C', 'Cy MPO', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('PHENOTYPIC_PATTERN', 'CA13040C', 'Cy CD3', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('PHENOTYPIC_PATTERN', 'CA13041C', 'Cy CD79a', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '26', '');
insert into pdc_lookup values('PROTEIN_BUFFER', 'CA12977C', 'Other', '', '', 'ARD_CAP', 'A', 'P', '', '1.64', '', '', '', '', '', 'Y', 'Value', '', '', '', '', '', '', '', '', '26', '');
commit;
