
ALTER TABLE CIR_SAMPLE_INFO
 ADD (FREEZING_MEDIA  VARCHAR2(4000 BYTE));

ALTER TABLE CIR_SAMPLE_INFO
 ADD (OTHER_ELUTION_BUFFER  VARCHAR2(200 BYTE));

ALTER TABLE CIR_SAMPLE_INFO
 ADD (OTHER_CELL_TYPE  VARCHAR2(200 BYTE));

ALTER TABLE CIR_SAMPLE_INFO
 ADD (ELUTION_BUFFER_CUI  VARCHAR2(30 BYTE));

ALTER TABLE CIR_SAMPLE_INFO
 ADD (A260_A280_RATIO  NUMBER);

ALTER TABLE CIR_SAMPLE_INFO
 ADD (CELL_TYPE_CUI  VARCHAR2(30 BYTE));

ALTER TABLE CIR_SAMPLE_INFO
 ADD (FREEZING_MEDIA_CUI  VARCHAR2(30 BYTE));

ALTER TABLE CIR_SAMPLE_INFO
 ADD (A260_A280_RATIO_CUI  VARCHAR2(30 BYTE));

ALTER TABLE CIR_SAMPLE_INFO
 ADD (PHENOTYPIC_PATTERN_CUI  VARCHAR2(30 BYTE));

ALTER TABLE CIR_SAMPLE_INFO
 ADD (OTHER_PROTEIN_BUFFER  VARCHAR2(200 BYTE));

ALTER TABLE CIR_SAMPLE_INFO
 ADD (OTHER_STORAGE_TYPE  VARCHAR2(200 BYTE));
