REM ************************************************************************************
REM * Generated KnowledgeCapture database views for DET version 26
REM ************************************************************************************

REM ************************************************************************************
REM * CREATE VIEW for category pt_info (conventional)
REM ************************************************************************************
CREATE OR REPLACE VIEW PT_INFO_V (
ID
,FORM_ID
,MRN
,MRN_CUI
,OTHER_MRN
,OTHER_MRN_CUI
,PARTICIPANT_ID
,PARTICIPANT_ID_CUI
,PT_ID
,PT_ID_CUI
,LAST_NAME
,LAST_NAME_CUI
,MIDDLE_INITIAL
,MIDDLE_INITIAL_CUI
,FIRST_NAME
,FIRST_NAME_CUI
,SSN
,SSN_CUI
,FORM_COMPLETED_BY
,FORM_COMPLETED_BY_CUI
,DONOR_NOTE
,DONOR_NOTE_CUI
,GENDER_CUI
,OTHER_GENDER
,ETHNICITY_CUI
,DATE_BIRTH
,DATE_BIRTH_CUI
,YEAR_BIRTH
,YEAR_BIRTH_CUI
,AGE_VISIT
,AGE_VISIT_CUI
,AGE_SURG
,AGE_SURG_CUI
,CURRENT_AGE
,CURRENT_AGE_CUI
,POSTAL_CODE
,POSTAL_CODE_CUI
,GESTATIONAL_AGE
,GESTATIONAL_AGE_CUI
,PT_CONSENTED_CUI
,DONATE_BLOOD_CUI
,AGREE_BLOOD_OBTAIN_CUI
,AGREE_NEEDLE_CUI
,DONATE_URINE_CUI
,DONATE_TISSUE_CUI
,DONATE_SALIVA_CUI
,DONATE_CSF_CUI
,DONATE_AMNIOTIC_CUI
,AGREE_GENE_TEST_CUI
,GENE_INFO_CUI
,REVIEW_MED_REC_CUI
,CONTACT_IN_FUTURE_CUI
,PERM_PI_CURR_RESE_CUI
,PERM_PI_FUTU_UNRE_CUI
,PERM_OTHR_PI_FUTU_CUI
)
AS (SELECT
ID
,FORM_ID
,MRN
,MRN_CUI
,OTHER_MRN
,OTHER_MRN_CUI
,PARTICIPANT_ID
,PARTICIPANT_ID_CUI
,PT_ID
,PT_ID_CUI
,LAST_NAME
,LAST_NAME_CUI
,MIDDLE_INITIAL
,MIDDLE_INITIAL_CUI
,FIRST_NAME
,FIRST_NAME_CUI
,SSN
,SSN_CUI
,FORM_COMPLETED_BY
,FORM_COMPLETED_BY_CUI
,DONOR_NOTE
,DONOR_NOTE_CUI
,GENDER_CUI
,OTHER_GENDER
,ETHNICITY_CUI
,DATE_BIRTH
,DATE_BIRTH_CUI
,YEAR_BIRTH
,YEAR_BIRTH_CUI
,AGE_VISIT
,AGE_VISIT_CUI
,AGE_SURG
,AGE_SURG_CUI
,CURRENT_AGE
,CURRENT_AGE_CUI
,POSTAL_CODE
,POSTAL_CODE_CUI
,GESTATIONAL_AGE
,GESTATIONAL_AGE_CUI
,PT_CONSENTED_CUI
,DONATE_BLOOD_CUI
,AGREE_BLOOD_OBTAIN_CUI
,AGREE_NEEDLE_CUI
,DONATE_URINE_CUI
,DONATE_TISSUE_CUI
,DONATE_SALIVA_CUI
,DONATE_CSF_CUI
,DONATE_AMNIOTIC_CUI
,AGREE_GENE_TEST_CUI
,GENE_INFO_CUI
,REVIEW_MED_REC_CUI
,CONTACT_IN_FUTURE_CUI
,PERM_PI_CURR_RESE_CUI
,PERM_PI_FUTU_UNRE_CUI
,PERM_OTHR_PI_FUTU_CUI
FROM CIR_PT_INFO);
/


CREATE OR REPLACE VIEW PT_INFO_MULTI_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
)
AS (SELECT 
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
FROM CIR_PT_INFO_MULTI);
/

CREATE OR REPLACE VIEW PT_INFO_NOTE_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
)
AS (SELECT 
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
FROM CIR_PT_INFO_NOTE);
/

REM ************************************************************************************
REM * CREATE VIEW for category problem (conventional)
REM ************************************************************************************
CREATE OR REPLACE VIEW PROBLEM_V (
ID
,FORM_ID
,DIAGNOSIS_CUI
,OTHER_DIAGNOSIS
,AGE_DIAG
,AGE_DIAG_CUI
,CATEGORY_DIS_CUI
,IF_LUNG_OR_PLEU_INF_CUI
,TRAU_REQU_OR_INTE_CUI
)
AS (SELECT
ID
,FORM_ID
,DIAGNOSIS_CUI
,OTHER_DIAGNOSIS
,AGE_DIAG
,AGE_DIAG_CUI
,CATEGORY_DIS_CUI
,IF_LUNG_OR_PLEU_INF_CUI
,TRAU_REQU_OR_INTE_CUI
FROM CIR_PROBLEM);
/



CREATE OR REPLACE VIEW PROBLEM_NOTE_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
)
AS (SELECT 
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
FROM CIR_PROBLEM_NOTE);
/

REM ************************************************************************************
REM * CREATE VIEW for category clin_pres (conventional)
REM ************************************************************************************
CREATE OR REPLACE VIEW CLIN_PRES_V (
ID
,FORM_ID
,SYMPTOM_PRIMARY_CUI
,OTHER_SYMPTOM_PRIMARY
,CLIN_COMMENTS
,CLIN_COMMENTS_CUI
,HEIGHT
,HEIGHT_CUI
,HEIGHT_INCHES
,HEIGHT_INCHES_CUI
,WEIGHT
,WEIGHT_CUI
,WEIGHT_POUNDS
,WEIGHT_POUNDS_CUI
,WEIG_LOSS_OVER3
,WEIG_LOSS_OVER3_CUI
,BMI
,BMI_CUI
,BODY_SURF_AREA
,BODY_SURF_AREA_CUI
,BLOO_PRES_SYST
,BLOO_PRES_SYST_CUI
,BLOO_PRES_DIAS
,BLOO_PRES_DIAS_CUI
,PULSE_PRESSURE
,PULSE_PRESSURE_CUI
,PALPATED_PULSE
,PALPATED_PULSE_CUI
,PULSE_OXIMETRY
,PULSE_OXIMETRY_CUI
,WAIST_CIRCUMFERENCE
,WAIST_CIRCUMFERENCE_CUI
,HEENT_CUI
,CNS_CUI
,NECK_CUI
,BREASTS_CUI
,CARDIOVASCULAR_CUI
,RESPIRATORY_CUI
,GASTROINTESTINAL_CUI
,URINARY_CUI
,GENITALIA_CUI
,MUSCULOSKELETAL_CUI
,NEUROLOGIC_CUI
,DERMATOLOGIC_CUI
,HEMA_LYMP_CUI
,ENDO_META_CUI
,PSYCHOLOGIC_CUI
)
AS (SELECT
ID
,FORM_ID
,SYMPTOM_PRIMARY_CUI
,OTHER_SYMPTOM_PRIMARY
,CLIN_COMMENTS
,CLIN_COMMENTS_CUI
,HEIGHT
,HEIGHT_CUI
,HEIGHT_INCHES
,HEIGHT_INCHES_CUI
,WEIGHT
,WEIGHT_CUI
,WEIGHT_POUNDS
,WEIGHT_POUNDS_CUI
,WEIG_LOSS_OVER3
,WEIG_LOSS_OVER3_CUI
,BMI
,BMI_CUI
,BODY_SURF_AREA
,BODY_SURF_AREA_CUI
,BLOO_PRES_SYST
,BLOO_PRES_SYST_CUI
,BLOO_PRES_DIAS
,BLOO_PRES_DIAS_CUI
,PULSE_PRESSURE
,PULSE_PRESSURE_CUI
,PALPATED_PULSE
,PALPATED_PULSE_CUI
,PULSE_OXIMETRY
,PULSE_OXIMETRY_CUI
,WAIST_CIRCUMFERENCE
,WAIST_CIRCUMFERENCE_CUI
,HEENT_CUI
,CNS_CUI
,NECK_CUI
,BREASTS_CUI
,CARDIOVASCULAR_CUI
,RESPIRATORY_CUI
,GASTROINTESTINAL_CUI
,URINARY_CUI
,GENITALIA_CUI
,MUSCULOSKELETAL_CUI
,NEUROLOGIC_CUI
,DERMATOLOGIC_CUI
,HEMA_LYMP_CUI
,ENDO_META_CUI
,PSYCHOLOGIC_CUI
FROM CIR_CLIN_PRES);
/


CREATE OR REPLACE VIEW CLIN_PRES_MULTI_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
)
AS (SELECT 
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
FROM CIR_CLIN_PRES_MULTI);
/

CREATE OR REPLACE VIEW CLIN_PRES_NOTE_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
)
AS (SELECT 
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
FROM CIR_CLIN_PRES_NOTE);
/

REM ************************************************************************************
REM * CREATE VIEW for category clin_dis_prog (eav)
REM ************************************************************************************
CREATE OR REPLACE VIEW CLIN_DIS_PROG_EAV_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,DATA_VALUE_DATE
,DATA_VALUE_DATE_DPC
,DATA_VALUE_CLOB
,DATA_VALUE_TEXT
,DATA_VALUE
,OTHER_DATA_VALUE
)
AS (SELECT
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,DATA_VALUE_DATE
,DATA_VALUE_DATE_DPC
,DATA_VALUE_CLOB
,DATA_VALUE_TEXT
,DATA_VALUE
,OTHER_DATA_VALUE
FROM CIR_CLIN_DIS_PROG_EAV);
/

CREATE OR REPLACE VIEW CLIN_DIS_PROG_MULTI_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
)
AS (SELECT 
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
FROM CIR_CLIN_DIS_PROG_MULTI);
/

CREATE OR REPLACE VIEW CLIN_DIS_PROG_NOTE_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
)
AS (SELECT 
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
FROM CIR_CLIN_DIS_PROG_NOTE);
/

REM ************************************************************************************
REM * CREATE VIEW for category treatment (conventional)
REM ************************************************************************************
CREATE OR REPLACE VIEW TREATMENT_V (
ID
,FORM_ID
,ELEC_THER_CUI
)
AS (SELECT
ID
,FORM_ID
,ELEC_THER_CUI
FROM CIR_TREATMENT);
/


CREATE OR REPLACE VIEW TREATMENT_MULTI_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
)
AS (SELECT 
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
FROM CIR_TREATMENT_MULTI);
/

CREATE OR REPLACE VIEW TREATMENT_NOTE_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
)
AS (SELECT 
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
FROM CIR_TREATMENT_NOTE);
/

REM ************************************************************************************
REM * CREATE VIEW for category ancillary_studies (eav)
REM ************************************************************************************
CREATE OR REPLACE VIEW ANCILLARY_STUDIES_EAV_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,DATA_VALUE_DATE
,DATA_VALUE_DATE_DPC
,DATA_VALUE_CLOB
,DATA_VALUE_TEXT
,DATA_VALUE
,OTHER_DATA_VALUE
)
AS (SELECT
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,DATA_VALUE_DATE
,DATA_VALUE_DATE_DPC
,DATA_VALUE_CLOB
,DATA_VALUE_TEXT
,DATA_VALUE
,OTHER_DATA_VALUE
FROM CIR_ANCILLARY_STUDIES_EAV);
/


CREATE OR REPLACE VIEW ANCILLARY_STUDIES_NOTE_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
)
AS (SELECT 
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
FROM CIR_ANCILLARY_STUDIES_NOTE);
/

REM ************************************************************************************
REM * CREATE VIEW for category bloo_gase_arte (eav)
REM ************************************************************************************
CREATE OR REPLACE VIEW BLOO_GASE_ARTE_EAV_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,DATA_VALUE_DATE
,DATA_VALUE_DATE_DPC
,DATA_VALUE_CLOB
,DATA_VALUE_TEXT
,DATA_VALUE
,OTHER_DATA_VALUE
)
AS (SELECT
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,DATA_VALUE_DATE
,DATA_VALUE_DATE_DPC
,DATA_VALUE_CLOB
,DATA_VALUE_TEXT
,DATA_VALUE
,OTHER_DATA_VALUE
FROM CIR_BLOO_GASE_ARTE_EAV);
/


CREATE OR REPLACE VIEW BLOO_GASE_ARTE_NOTE_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
)
AS (SELECT 
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
FROM CIR_BLOO_GASE_ARTE_NOTE);
/

REM ************************************************************************************
REM * CREATE VIEW for category chemistry_survey (eav)
REM ************************************************************************************
CREATE OR REPLACE VIEW CHEMISTRY_SURVEY_EAV_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,DATA_VALUE_DATE
,DATA_VALUE_DATE_DPC
,DATA_VALUE_CLOB
,DATA_VALUE_TEXT
,DATA_VALUE
,OTHER_DATA_VALUE
)
AS (SELECT
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,DATA_VALUE_DATE
,DATA_VALUE_DATE_DPC
,DATA_VALUE_CLOB
,DATA_VALUE_TEXT
,DATA_VALUE
,OTHER_DATA_VALUE
FROM CIR_CHEMISTRY_SURVEY_EAV);
/


CREATE OR REPLACE VIEW CHEMISTRY_SURVEY_NOTE_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
)
AS (SELECT 
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
FROM CIR_CHEMISTRY_SURVEY_NOTE);
/

REM ************************************************************************************
REM * CREATE VIEW for category chemistry (eav)
REM ************************************************************************************
CREATE OR REPLACE VIEW CHEMISTRY_EAV_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,DATA_VALUE_DATE
,DATA_VALUE_DATE_DPC
,DATA_VALUE_CLOB
,DATA_VALUE_TEXT
,DATA_VALUE
,OTHER_DATA_VALUE
)
AS (SELECT
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,DATA_VALUE_DATE
,DATA_VALUE_DATE_DPC
,DATA_VALUE_CLOB
,DATA_VALUE_TEXT
,DATA_VALUE
,OTHER_DATA_VALUE
FROM CIR_CHEMISTRY_EAV);
/


CREATE OR REPLACE VIEW CHEMISTRY_NOTE_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
)
AS (SELECT 
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
FROM CIR_CHEMISTRY_NOTE);
/

REM ************************************************************************************
REM * CREATE VIEW for category chromosome_studies (eav)
REM ************************************************************************************
CREATE OR REPLACE VIEW CHROMOSOME_STUDIES_EAV_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,DATA_VALUE_DATE
,DATA_VALUE_DATE_DPC
,DATA_VALUE_CLOB
,DATA_VALUE_TEXT
,DATA_VALUE
,OTHER_DATA_VALUE
)
AS (SELECT
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,DATA_VALUE_DATE
,DATA_VALUE_DATE_DPC
,DATA_VALUE_CLOB
,DATA_VALUE_TEXT
,DATA_VALUE
,OTHER_DATA_VALUE
FROM CIR_CHROMOSOME_STUDIES_EAV);
/

CREATE OR REPLACE VIEW CHROMOSOME_STUDIES_MULTI_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
)
AS (SELECT 
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
FROM CIR_CHROMOSOME_STUDIES_MULTI);
/

CREATE OR REPLACE VIEW CHROMOSOME_STUDIES_NOTE_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
)
AS (SELECT 
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
FROM CIR_CHROMOSOME_STUDIES_NOTE);
/

REM ************************************************************************************
REM * CREATE VIEW for category coagulation (eav)
REM ************************************************************************************
CREATE OR REPLACE VIEW COAGULATION_EAV_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,DATA_VALUE_DATE
,DATA_VALUE_DATE_DPC
,DATA_VALUE_CLOB
,DATA_VALUE_TEXT
,DATA_VALUE
,OTHER_DATA_VALUE
)
AS (SELECT
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,DATA_VALUE_DATE
,DATA_VALUE_DATE_DPC
,DATA_VALUE_CLOB
,DATA_VALUE_TEXT
,DATA_VALUE
,OTHER_DATA_VALUE
FROM CIR_COAGULATION_EAV);
/


CREATE OR REPLACE VIEW COAGULATION_NOTE_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
)
AS (SELECT 
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
FROM CIR_COAGULATION_NOTE);
/

REM ************************************************************************************
REM * CREATE VIEW for category cytology (eav)
REM ************************************************************************************
CREATE OR REPLACE VIEW CYTOLOGY_EAV_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,DATA_VALUE_DATE
,DATA_VALUE_DATE_DPC
,DATA_VALUE_CLOB
,DATA_VALUE_TEXT
,DATA_VALUE
,OTHER_DATA_VALUE
)
AS (SELECT
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,DATA_VALUE_DATE
,DATA_VALUE_DATE_DPC
,DATA_VALUE_CLOB
,DATA_VALUE_TEXT
,DATA_VALUE
,OTHER_DATA_VALUE
FROM CIR_CYTOLOGY_EAV);
/


CREATE OR REPLACE VIEW CYTOLOGY_NOTE_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
)
AS (SELECT 
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
FROM CIR_CYTOLOGY_NOTE);
/


CREATE OR REPLACE VIEW GENE_STUDIES_MULTI_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
)
AS (SELECT 
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
FROM CIR_GENE_STUDIES_MULTI);
/

CREATE OR REPLACE VIEW GENE_STUDIES_NOTE_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
)
AS (SELECT 
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
FROM CIR_GENE_STUDIES_NOTE);
/

REM ************************************************************************************
REM * CREATE VIEW for category hematology_survey (eav)
REM ************************************************************************************
CREATE OR REPLACE VIEW HEMATOLOGY_SURVEY_EAV_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,DATA_VALUE_DATE
,DATA_VALUE_DATE_DPC
,DATA_VALUE_CLOB
,DATA_VALUE_TEXT
,DATA_VALUE
,OTHER_DATA_VALUE
)
AS (SELECT
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,DATA_VALUE_DATE
,DATA_VALUE_DATE_DPC
,DATA_VALUE_CLOB
,DATA_VALUE_TEXT
,DATA_VALUE
,OTHER_DATA_VALUE
FROM CIR_HEMATOLOGY_SURVEY_EAV);
/


CREATE OR REPLACE VIEW HEMATOLOGY_SURVEY_NOTE_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
)
AS (SELECT 
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
FROM CIR_HEMATOLOGY_SURVEY_NOTE);
/

REM ************************************************************************************
REM * CREATE VIEW for category hematology (eav)
REM ************************************************************************************
CREATE OR REPLACE VIEW HEMATOLOGY_EAV_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,DATA_VALUE_DATE
,DATA_VALUE_DATE_DPC
,DATA_VALUE_CLOB
,DATA_VALUE_TEXT
,DATA_VALUE
,OTHER_DATA_VALUE
)
AS (SELECT
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,DATA_VALUE_DATE
,DATA_VALUE_DATE_DPC
,DATA_VALUE_CLOB
,DATA_VALUE_TEXT
,DATA_VALUE
,OTHER_DATA_VALUE
FROM CIR_HEMATOLOGY_EAV);
/


CREATE OR REPLACE VIEW HEMATOLOGY_NOTE_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
)
AS (SELECT 
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
FROM CIR_HEMATOLOGY_NOTE);
/

REM ************************************************************************************
REM * CREATE VIEW for category histochemistry (eav)
REM ************************************************************************************
CREATE OR REPLACE VIEW HISTOCHEMISTRY_EAV_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,DATA_VALUE_DATE
,DATA_VALUE_DATE_DPC
,DATA_VALUE_CLOB
,DATA_VALUE_TEXT
,DATA_VALUE
,OTHER_DATA_VALUE
)
AS (SELECT
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,DATA_VALUE_DATE
,DATA_VALUE_DATE_DPC
,DATA_VALUE_CLOB
,DATA_VALUE_TEXT
,DATA_VALUE
,OTHER_DATA_VALUE
FROM CIR_HISTOCHEMISTRY_EAV);
/


CREATE OR REPLACE VIEW HISTOCHEMISTRY_NOTE_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
)
AS (SELECT 
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
FROM CIR_HISTOCHEMISTRY_NOTE);
/

REM ************************************************************************************
REM * CREATE VIEW for category immunohistochemistry (eav)
REM ************************************************************************************
CREATE OR REPLACE VIEW IMMUNOHISTOCHEMISTRY_EAV_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,DATA_VALUE_DATE
,DATA_VALUE_DATE_DPC
,DATA_VALUE_CLOB
,DATA_VALUE_TEXT
,DATA_VALUE
,OTHER_DATA_VALUE
)
AS (SELECT
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,DATA_VALUE_DATE
,DATA_VALUE_DATE_DPC
,DATA_VALUE_CLOB
,DATA_VALUE_TEXT
,DATA_VALUE
,OTHER_DATA_VALUE
FROM CIR_IMMUNOHISTOCHEMISTRY_EAV);
/


CREATE OR REPLACE VIEW IMMUNOHISTOCHEMISTRY_NOTE_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
)
AS (SELECT 
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
FROM CIR_IMMUNOHISTOCHEMISTRY_NOTE);
/

REM ************************************************************************************
REM * CREATE VIEW for category immunophenotype (eav)
REM ************************************************************************************
CREATE OR REPLACE VIEW IMMUNOPHENOTYPE_EAV_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,DATA_VALUE_DATE
,DATA_VALUE_DATE_DPC
,DATA_VALUE_CLOB
,DATA_VALUE_TEXT
,DATA_VALUE
,OTHER_DATA_VALUE
)
AS (SELECT
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,DATA_VALUE_DATE
,DATA_VALUE_DATE_DPC
,DATA_VALUE_CLOB
,DATA_VALUE_TEXT
,DATA_VALUE
,OTHER_DATA_VALUE
FROM CIR_IMMUNOPHENOTYPE_EAV);
/


CREATE OR REPLACE VIEW IMMUNOPHENOTYPE_NOTE_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
)
AS (SELECT 
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
FROM CIR_IMMUNOPHENOTYPE_NOTE);
/

REM ************************************************************************************
REM * CREATE VIEW for category microbiology (eav)
REM ************************************************************************************
CREATE OR REPLACE VIEW MICROBIOLOGY_EAV_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,DATA_VALUE_DATE
,DATA_VALUE_DATE_DPC
,DATA_VALUE_CLOB
,DATA_VALUE_TEXT
,DATA_VALUE
,OTHER_DATA_VALUE
)
AS (SELECT
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,DATA_VALUE_DATE
,DATA_VALUE_DATE_DPC
,DATA_VALUE_CLOB
,DATA_VALUE_TEXT
,DATA_VALUE
,OTHER_DATA_VALUE
FROM CIR_MICROBIOLOGY_EAV);
/


CREATE OR REPLACE VIEW MICROBIOLOGY_NOTE_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
)
AS (SELECT 
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
FROM CIR_MICROBIOLOGY_NOTE);
/

REM ************************************************************************************
REM * CREATE VIEW for category stains (eav)
REM ************************************************************************************
CREATE OR REPLACE VIEW STAINS_EAV_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,DATA_VALUE_DATE
,DATA_VALUE_DATE_DPC
,DATA_VALUE_CLOB
,DATA_VALUE_TEXT
,DATA_VALUE
,OTHER_DATA_VALUE
)
AS (SELECT
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,DATA_VALUE_DATE
,DATA_VALUE_DATE_DPC
,DATA_VALUE_CLOB
,DATA_VALUE_TEXT
,DATA_VALUE
,OTHER_DATA_VALUE
FROM CIR_STAINS_EAV);
/


CREATE OR REPLACE VIEW STAINS_NOTE_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
)
AS (SELECT 
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
FROM CIR_STAINS_NOTE);
/

REM ************************************************************************************
REM * CREATE VIEW for category urinalysis (eav)
REM ************************************************************************************
CREATE OR REPLACE VIEW URINALYSIS_EAV_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,DATA_VALUE_DATE
,DATA_VALUE_DATE_DPC
,DATA_VALUE_CLOB
,DATA_VALUE_TEXT
,DATA_VALUE
,OTHER_DATA_VALUE
)
AS (SELECT
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,DATA_VALUE_DATE
,DATA_VALUE_DATE_DPC
,DATA_VALUE_CLOB
,DATA_VALUE_TEXT
,DATA_VALUE
,OTHER_DATA_VALUE
FROM CIR_URINALYSIS_EAV);
/

CREATE OR REPLACE VIEW URINALYSIS_MULTI_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
)
AS (SELECT 
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
FROM CIR_URINALYSIS_MULTI);
/

CREATE OR REPLACE VIEW URINALYSIS_NOTE_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
)
AS (SELECT 
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
FROM CIR_URINALYSIS_NOTE);
/

REM ************************************************************************************
REM * CREATE VIEW for category imaging_studies (eav)
REM ************************************************************************************
CREATE OR REPLACE VIEW IMAGING_STUDIES_EAV_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,DATA_VALUE_DATE
,DATA_VALUE_DATE_DPC
,DATA_VALUE_CLOB
,DATA_VALUE_TEXT
,DATA_VALUE
,OTHER_DATA_VALUE
)
AS (SELECT
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,DATA_VALUE_DATE
,DATA_VALUE_DATE_DPC
,DATA_VALUE_CLOB
,DATA_VALUE_TEXT
,DATA_VALUE
,OTHER_DATA_VALUE
FROM CIR_IMAGING_STUDIES_EAV);
/

CREATE OR REPLACE VIEW IMAGING_STUDIES_MULTI_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
)
AS (SELECT 
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
FROM CIR_IMAGING_STUDIES_MULTI);
/

CREATE OR REPLACE VIEW IMAGING_STUDIES_NOTE_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
)
AS (SELECT 
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
FROM CIR_IMAGING_STUDIES_NOTE);
/

REM ************************************************************************************
REM * CREATE VIEW for category skin_tests (eav)
REM ************************************************************************************
CREATE OR REPLACE VIEW SKIN_TESTS_EAV_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,DATA_VALUE_DATE
,DATA_VALUE_DATE_DPC
,DATA_VALUE_CLOB
,DATA_VALUE_TEXT
,DATA_VALUE
,OTHER_DATA_VALUE
)
AS (SELECT
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,DATA_VALUE_DATE
,DATA_VALUE_DATE_DPC
,DATA_VALUE_CLOB
,DATA_VALUE_TEXT
,DATA_VALUE
,OTHER_DATA_VALUE
FROM CIR_SKIN_TESTS_EAV);
/


CREATE OR REPLACE VIEW SKIN_TESTS_NOTE_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
)
AS (SELECT 
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
FROM CIR_SKIN_TESTS_NOTE);
/

REM ************************************************************************************
REM * CREATE VIEW for category surgical_studies (eav)
REM ************************************************************************************
CREATE OR REPLACE VIEW SURGICAL_STUDIES_EAV_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,DATA_VALUE_DATE
,DATA_VALUE_DATE_DPC
,DATA_VALUE_CLOB
,DATA_VALUE_TEXT
,DATA_VALUE
,OTHER_DATA_VALUE
)
AS (SELECT
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,DATA_VALUE_DATE
,DATA_VALUE_DATE_DPC
,DATA_VALUE_CLOB
,DATA_VALUE_TEXT
,DATA_VALUE
,OTHER_DATA_VALUE
FROM CIR_SURGICAL_STUDIES_EAV);
/

CREATE OR REPLACE VIEW SURGICAL_STUDIES_MULTI_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
)
AS (SELECT 
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
FROM CIR_SURGICAL_STUDIES_MULTI);
/

CREATE OR REPLACE VIEW SURGICAL_STUDIES_NOTE_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
)
AS (SELECT 
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
FROM CIR_SURGICAL_STUDIES_NOTE);
/

REM ************************************************************************************
REM * CREATE VIEW for category past_medi_hist (conventional)
REM ************************************************************************************
CREATE OR REPLACE VIEW PAST_MEDI_HIST_V (
ID
,FORM_ID
,ALC_DRINK_PER_DAY_CUI
,TOBA_USE_INDI_CUI
,BORN_PREMATURELY_CUI
,CANCER_INDICATOR_CUI
,DIAB_MELL_INDI_CUI
,HYPE_INDI_CUI
,CERE_HIST_CUI
,RENA_INSU_HIST_CUI
,MULT_BIRTH_CUI
,GRAVIDA
,GRAVIDA_CUI
,PARA
,PARA_CUI
,AGE_FIRS_PREG
,AGE_FIRS_PREG_CUI
,PREGNANT_NOW_CUI
,LACTATING_NOW_CUI
,AGE_MENA
,AGE_MENA_CUI
,AGE_MENO
,AGE_MENO_CUI
,LASTMENS_FIRSTDAY
,LASTMENS_FIRSTDAY_CUI
,DAYS_SIN_LAST_MENS
,DAYS_SIN_LAST_MENS_CUI
,DAYS_BETW_PERI
,DAYS_BETW_PERI_CUI
,LENG_REPR_LIFE
,LENG_REPR_LIFE_CUI
,HORM_CONT_USE_CUI
,HORM_REPL_THER_CUI
,EXERCISE_LEVEL_CUI
,CHEMO_HIST_CUI
,RADIATION_HIST_CUI
)
AS (SELECT
ID
,FORM_ID
,ALC_DRINK_PER_DAY_CUI
,TOBA_USE_INDI_CUI
,BORN_PREMATURELY_CUI
,CANCER_INDICATOR_CUI
,DIAB_MELL_INDI_CUI
,HYPE_INDI_CUI
,CERE_HIST_CUI
,RENA_INSU_HIST_CUI
,MULT_BIRTH_CUI
,GRAVIDA
,GRAVIDA_CUI
,PARA
,PARA_CUI
,AGE_FIRS_PREG
,AGE_FIRS_PREG_CUI
,PREGNANT_NOW_CUI
,LACTATING_NOW_CUI
,AGE_MENA
,AGE_MENA_CUI
,AGE_MENO
,AGE_MENO_CUI
,LASTMENS_FIRSTDAY
,LASTMENS_FIRSTDAY_CUI
,DAYS_SIN_LAST_MENS
,DAYS_SIN_LAST_MENS_CUI
,DAYS_BETW_PERI
,DAYS_BETW_PERI_CUI
,LENG_REPR_LIFE
,LENG_REPR_LIFE_CUI
,HORM_CONT_USE_CUI
,HORM_REPL_THER_CUI
,EXERCISE_LEVEL_CUI
,CHEMO_HIST_CUI
,RADIATION_HIST_CUI
FROM CIR_PAST_MEDI_HIST);
/


CREATE OR REPLACE VIEW PAST_MEDI_HIST_MULTI_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
)
AS (SELECT 
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
FROM CIR_PAST_MEDI_HIST_MULTI);
/

CREATE OR REPLACE VIEW PAST_MEDI_HIST_NOTE_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
)
AS (SELECT 
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
FROM CIR_PAST_MEDI_HIST_NOTE);
/

REM ************************************************************************************
REM * CREATE VIEW for category hospitalization_info (conventional)
REM ************************************************************************************
CREATE OR REPLACE VIEW HOSPITALIZATION_INFO_V (
ID
,FORM_ID
,HOSPITAL
,HOSPITAL_CUI
,HOSPITAL_POSTAL_CODE
,HOSPITAL_POSTAL_CODE_CUI
,DATE_ADM
,DATE_ADM_CUI
,DATE_DISCH
,DATE_DISCH_CUI
,STATUS_DISCH_CUI
,STAT30_DAYS_AFTE_CUI
,LENGTH_STAY
,LENGTH_STAY_CUI
,TIME_SINC_SURG_TREAT
,TIME_SINC_SURG_TREAT_CUI
,CHEST_TUBE_IND_CUI
,DISPOSITION_CUI
,OTHER_DISPOSITION
,MEDICATIONS_CUI
,PAIN_SCORE_CUI
)
AS (SELECT
ID
,FORM_ID
,HOSPITAL
,HOSPITAL_CUI
,HOSPITAL_POSTAL_CODE
,HOSPITAL_POSTAL_CODE_CUI
,DATE_ADM
,DATE_ADM_CUI
,DATE_DISCH
,DATE_DISCH_CUI
,STATUS_DISCH_CUI
,STAT30_DAYS_AFTE_CUI
,LENGTH_STAY
,LENGTH_STAY_CUI
,TIME_SINC_SURG_TREAT
,TIME_SINC_SURG_TREAT_CUI
,CHEST_TUBE_IND_CUI
,DISPOSITION_CUI
,OTHER_DISPOSITION
,MEDICATIONS_CUI
,PAIN_SCORE_CUI
FROM CIR_HOSPITALIZATION_INFO);
/


CREATE OR REPLACE VIEW HOSPITALIZATION_INFO_MULTI_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
)
AS (SELECT 
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
FROM CIR_HOSPITALIZATION_INFO_MULTI);
/

CREATE OR REPLACE VIEW HOSPITALIZATION_INFO_NOTE_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
)
AS (SELECT 
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
FROM CIR_HOSPITALIZATION_INFO_NOTE);
/

REM ************************************************************************************
REM * CREATE VIEW for category case_info (conventional)
REM ************************************************************************************
CREATE OR REPLACE VIEW CASE_INFO_V (
ID
,FORM_ID
,CASE_ID
,CASE_ID_CUI
,NUMBER_CASE
,NUMBER_CASE_CUI
,DATE_SURG
,DATE_SURG_CUI
,CASE_DX_CUI
,OTHER_CASE_DX
,SURGEON
,SURGEON_CUI
,BLOOD_DRAWN_CUI
,PERI_TRAN
,PERI_TRAN_CUI
,SPEC_NAME
,SPEC_NAME_CUI
,NODE_POST_OP_CUI
,NODE_INTRA_OP_CUI
,PRIMARY_STS_PROC_CUI
,OTHER_PRIMARY_STS_PROC
,ASA_CLASS_CUI
,ISCHEMIC_TIME
,ISCHEMIC_TIME_CUI
,TIME_PT_ENTE_OR_HOUR
,TIME_PT_ENTE_OR_HOUR_CUI
,TIME_PT_ENTE_OR_MIN
,TIME_PT_ENTE_OR_MIN_CUI
,TIME_SKIN_INCI_STAR
,TIME_SKIN_INCI_STAR_CUI
,TIME_SKIN_INCI_STA
,TIME_SKIN_INCI_STA_CUI
,TIME_SKIN_INCI_STOP
,TIME_SKIN_INCI_STOP_CUI
,TIME_SKIN_INCI_STO
,TIME_SKIN_INCI_STO_CUI
,TIME_PT_EXIT_OR_HOUR
,TIME_PT_EXIT_OR_HOUR_CUI
,TIME_PT_EXITS_OR_MIN
,TIME_PT_EXITS_OR_MIN_CUI
,MULTIDAY_OPERATION_CUI
,STATUS_OPERATION_CUI
,REOPERATION_CUI
,BLOO_TRAN_INTR_OP_CUI
,CASE_COMMENT
,CASE_COMMENT_CUI
,CASE_INFORMATION_CUI
,OTHER_CASE_INFORMATION
,REPORT_SURG_PATH_CUI
)
AS (SELECT
ID
,FORM_ID
,CASE_ID
,CASE_ID_CUI
,NUMBER_CASE
,NUMBER_CASE_CUI
,DATE_SURG
,DATE_SURG_CUI
,CASE_DX_CUI
,OTHER_CASE_DX
,SURGEON
,SURGEON_CUI
,BLOOD_DRAWN_CUI
,PERI_TRAN
,PERI_TRAN_CUI
,SPEC_NAME
,SPEC_NAME_CUI
,NODE_POST_OP_CUI
,NODE_INTRA_OP_CUI
,PRIMARY_STS_PROC_CUI
,OTHER_PRIMARY_STS_PROC
,ASA_CLASS_CUI
,ISCHEMIC_TIME
,ISCHEMIC_TIME_CUI
,TIME_PT_ENTE_OR_HOUR
,TIME_PT_ENTE_OR_HOUR_CUI
,TIME_PT_ENTE_OR_MIN
,TIME_PT_ENTE_OR_MIN_CUI
,TIME_SKIN_INCI_STAR
,TIME_SKIN_INCI_STAR_CUI
,TIME_SKIN_INCI_STA
,TIME_SKIN_INCI_STA_CUI
,TIME_SKIN_INCI_STOP
,TIME_SKIN_INCI_STOP_CUI
,TIME_SKIN_INCI_STO
,TIME_SKIN_INCI_STO_CUI
,TIME_PT_EXIT_OR_HOUR
,TIME_PT_EXIT_OR_HOUR_CUI
,TIME_PT_EXITS_OR_MIN
,TIME_PT_EXITS_OR_MIN_CUI
,MULTIDAY_OPERATION_CUI
,STATUS_OPERATION_CUI
,REOPERATION_CUI
,BLOO_TRAN_INTR_OP_CUI
,CASE_COMMENT
,CASE_COMMENT_CUI
,CASE_INFORMATION_CUI
,OTHER_CASE_INFORMATION
,REPORT_SURG_PATH_CUI
FROM CIR_CASE_INFO);
/


CREATE OR REPLACE VIEW CASE_INFO_MULTI_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
)
AS (SELECT 
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
FROM CIR_CASE_INFO_MULTI);
/

CREATE OR REPLACE VIEW CASE_INFO_NOTE_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
)
AS (SELECT 
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
FROM CIR_CASE_INFO_NOTE);
/

REM ************************************************************************************
REM * CREATE VIEW for category sample_info (conventional)
REM ************************************************************************************
CREATE OR REPLACE VIEW SAMPLE_INFO_V (
ID
,FORM_ID
,A260_A280_RATIO
,A260_A280_RATIO_CUI
,BLOOD_TUBE_PLMI_CUI
,OTHER_BLOOD_TUBE_PLMI
,BLOOD_SAMPLE_SOURCE_CUI
,BLOOD_TUBE_CRI_CUI
,OTHER_BLOOD_TUBE_CRI
,BUFFER_TYPE_CUI
,OTHER_BUFFER_TYPE
,CELLS_PER_ML
,CELLS_PER_ML_CUI
,CELL_TYPE_CUI
,OTHER_CELL_TYPE
,COLLECTION_FORMAT_CUI
,CONCENTRATION
,CONCENTRATION_CUI
,DATE_COLLECTION
,DATE_COLLECTION_CUI
,DATE_PRESERVE
,DATE_PRESERVE_CUI
,DERIV_OP_CUI
,EXTRACTION_METHOD_CUI
,ELUTION_BUFFER_CUI
,OTHER_ELUTION_BUFFER
,EXT_INVESTIGATOR_CUI
,CRI_FIXATIVE_CUI
,FIXATIVE_TYPE_CUI
,FIXED_TISSUE_PREP_CUI
,FORMAT_DETAIL_CUI
,FREEZING_MEDIA
,FREEZING_MEDIA_CUI
,FROZEN_TISSUE_PREP_CUI
,OTHER_FROZEN_TISSUE_PREP
,GROSS_APPEAR_CUI
,HEMOLYZED_STATUS_CUI
,INVESTIGATOR_ID_CUI
,OTHER_INVESTIGATOR_ID
,NA_BUFFER_CUI
,OTHER_NA_BUFFER
,PARENT_TISSUE_DETAIL_CUI
,PERCENT_VIABLE
,PERCENT_VIABLE_CUI
,PHENOTYPIC_PATTERN_CUI
,PREPARED_BY
,PREPARED_BY_CUI
,PRESERVATION_METHOD_CUI
,PROJECT_NUMBER
,PROJECT_NUMBER_CUI
,PROTEIN_BUFFER_CUI
,OTHER_PROTEIN_BUFFER
,PROJECT_REQUEST
,PROJECT_REQUEST_CUI
,SAMPLE_COMMENT
,SAMPLE_COMMENT_CUI
,SAMPLE_DIMENSIONS
,SAMPLE_DIMENSIONS_CUI
,SAMPLE_FORMAT_CUI
,OTHER_SAMPLE_FORMAT
,SAMP_GROSS_APPEAR_CUI
,SAMPLE_SOURCE
,SAMPLE_SOURCE_CUI
,SAMPLE_SUBTYPE
,SAMPLE_SUBTYPE_CUI
,SAMPLE_TYPE_CUI
,SAMPLE_VOLUME
,SAMPLE_VOLUME_CUI
,SAMPLE_VOLUME_UNIT_CUI
,SAMPLE_WEIGHT
,SAMPLE_WEIGHT_CUI
,SAMPLE_WEIGHT_UNIT_CUI
,SLIDE_PREP_CUI
,OTHER_SLIDE_PREP
,STAIN_TYPE_CUI
,OTHER_STAIN_TYPE
,SPECIES_CUI
,OTHER_SPECIES
,SPECIMEN_DIMENSIONS
,SPECIMEN_DIMENSIONS_CUI
,SPECIMEN_DIM_UNIT_CUI
,STORAGE_FORM_CUI
,OTHER_STORAGE_FORM
,STORAGE_TYPE_CUI
,OTHER_STORAGE_TYPE
,SUSPENSION_MEDIUM_CUI
,OTHER_SUSPENSION_MEDIUM
,SAMPLE_TECHNIQUE_CUI
,OTHER_SAMPLE_TECHNIQUE
,TIME_BLOOD_DRAW_CUI
,TIME_COLLECT_AMPM_CUI
,TIME_COLLECT_HOUR
,TIME_COLLECT_HOUR_CUI
,TIME_COLLECT_MIN
,TIME_COLLECT_MIN_CUI
,TIME_PRESERVE_AMPM_CUI
,TIME_PRESERVE_HOUR
,TIME_PRESERVE_HOUR_CUI
,TIME_PRESERVE_MIN
,TIME_PRESERVE_MIN_CUI
,TOTAL_CELLS_EXPONENT_CUI
,TOTAL_NUM_CELLS
,TOTAL_NUM_CELLS_CUI
,YIELD
,YIELD_CUI
)
AS (SELECT
ID
,FORM_ID
,A260_A280_RATIO
,A260_A280_RATIO_CUI
,BLOOD_TUBE_PLMI_CUI
,OTHER_BLOOD_TUBE_PLMI
,BLOOD_SAMPLE_SOURCE_CUI
,BLOOD_TUBE_CRI_CUI
,OTHER_BLOOD_TUBE_CRI
,BUFFER_TYPE_CUI
,OTHER_BUFFER_TYPE
,CELLS_PER_ML
,CELLS_PER_ML_CUI
,CELL_TYPE_CUI
,OTHER_CELL_TYPE
,COLLECTION_FORMAT_CUI
,CONCENTRATION
,CONCENTRATION_CUI
,DATE_COLLECTION
,DATE_COLLECTION_CUI
,DATE_PRESERVE
,DATE_PRESERVE_CUI
,DERIV_OP_CUI
,EXTRACTION_METHOD_CUI
,ELUTION_BUFFER_CUI
,OTHER_ELUTION_BUFFER
,EXT_INVESTIGATOR_CUI
,CRI_FIXATIVE_CUI
,FIXATIVE_TYPE_CUI
,FIXED_TISSUE_PREP_CUI
,FORMAT_DETAIL_CUI
,FREEZING_MEDIA
,FREEZING_MEDIA_CUI
,FROZEN_TISSUE_PREP_CUI
,OTHER_FROZEN_TISSUE_PREP
,GROSS_APPEAR_CUI
,HEMOLYZED_STATUS_CUI
,INVESTIGATOR_ID_CUI
,OTHER_INVESTIGATOR_ID
,NA_BUFFER_CUI
,OTHER_NA_BUFFER
,PARENT_TISSUE_DETAIL_CUI
,PERCENT_VIABLE
,PERCENT_VIABLE_CUI
,PHENOTYPIC_PATTERN_CUI
,PREPARED_BY
,PREPARED_BY_CUI
,PRESERVATION_METHOD_CUI
,PROJECT_NUMBER
,PROJECT_NUMBER_CUI
,PROTEIN_BUFFER_CUI
,OTHER_PROTEIN_BUFFER
,PROJECT_REQUEST
,PROJECT_REQUEST_CUI
,SAMPLE_COMMENT
,SAMPLE_COMMENT_CUI
,SAMPLE_DIMENSIONS
,SAMPLE_DIMENSIONS_CUI
,SAMPLE_FORMAT_CUI
,OTHER_SAMPLE_FORMAT
,SAMP_GROSS_APPEAR_CUI
,SAMPLE_SOURCE
,SAMPLE_SOURCE_CUI
,SAMPLE_SUBTYPE
,SAMPLE_SUBTYPE_CUI
,SAMPLE_TYPE_CUI
,SAMPLE_VOLUME
,SAMPLE_VOLUME_CUI
,SAMPLE_VOLUME_UNIT_CUI
,SAMPLE_WEIGHT
,SAMPLE_WEIGHT_CUI
,SAMPLE_WEIGHT_UNIT_CUI
,SLIDE_PREP_CUI
,OTHER_SLIDE_PREP
,STAIN_TYPE_CUI
,OTHER_STAIN_TYPE
,SPECIES_CUI
,OTHER_SPECIES
,SPECIMEN_DIMENSIONS
,SPECIMEN_DIMENSIONS_CUI
,SPECIMEN_DIM_UNIT_CUI
,STORAGE_FORM_CUI
,OTHER_STORAGE_FORM
,STORAGE_TYPE_CUI
,OTHER_STORAGE_TYPE
,SUSPENSION_MEDIUM_CUI
,OTHER_SUSPENSION_MEDIUM
,SAMPLE_TECHNIQUE_CUI
,OTHER_SAMPLE_TECHNIQUE
,TIME_BLOOD_DRAW_CUI
,TIME_COLLECT_AMPM_CUI
,TIME_COLLECT_HOUR
,TIME_COLLECT_HOUR_CUI
,TIME_COLLECT_MIN
,TIME_COLLECT_MIN_CUI
,TIME_PRESERVE_AMPM_CUI
,TIME_PRESERVE_HOUR
,TIME_PRESERVE_HOUR_CUI
,TIME_PRESERVE_MIN
,TIME_PRESERVE_MIN_CUI
,TOTAL_CELLS_EXPONENT_CUI
,TOTAL_NUM_CELLS
,TOTAL_NUM_CELLS_CUI
,YIELD
,YIELD_CUI
FROM CIR_SAMPLE_INFO);
/



CREATE OR REPLACE VIEW SAMPLE_INFO_NOTE_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
)
AS (SELECT 
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
FROM CIR_SAMPLE_INFO_NOTE);
/

REM ************************************************************************************
REM * CREATE VIEW for category surgical_pathology (conventional)
REM ************************************************************************************
CREATE OR REPLACE VIEW SURGICAL_PATHOLOGY_V (
ID
,FORM_ID
,PATH_REPO_DIAG_CUI
,OTHER_PATH_REPO_DIAG
,PATH_REPO_TEXT
,PATH_REPO_TEXT_CUI
,TISSUE_ORIG_CUI
,OTHER_TISSUE_ORIG
,SITE_FIND_CUI
,OTHER_SITE_FIND
,SURGICAL_PROCEDURE_CUI
,OTHER_SURGICAL_PROCEDURE
,NEED_BIOP_NUMB
,NEED_BIOP_NUMB_CUI
,NUMB_CORE_POS
,NUMB_CORE_POS_CUI
,NUMB_CORE_TAKE
,NUMB_CORE_TAKE_CUI
,PERC_CORE_POS
,PERC_CORE_POS_CUI
,PATH_STG_APPL_IND_CUI
,PATH_COMMENTS
,PATH_COMMENTS_CUI
,LESI_DIAM1
,LESI_DIAM1_CUI
,LESI_DIAM2
,LESI_DIAM2_CUI
,LESI_DIAM3
,LESI_DIAM3_CUI
,HEART_WEIGHT
,HEART_WEIGHT_CUI
,LEFT_ATRI_DIAM
,LEFT_ATRI_DIAM_CUI
,LEFT_VENT_DIAM
,LEFT_VENT_DIAM_CUI
,LEFT_VENT_WALL_THIC
,LEFT_VENT_WALL_THIC_CUI
,RIGH_ATRI_DIAM
,RIGH_ATRI_DIAM_CUI
,RIGH_VENT_DIAM
,RIGH_VENT_DIAM_CUI
,RIGH_VENT_WALL_THIC
,RIGH_VENT_WALL_THIC_CUI
,NUMB_POLYPS
,NUMB_POLYPS_CUI
,SIZE_LEUK_CUI
,A6_PATH_TUMO_STG_CUI
,MACF_PATH_TUMO_STG_CUI
,A6_PATH_LYM_NODE_STG_CUI
,HAN_PATH_LN_LOCA_CUI
,LYM_NODE_INVO
,LYM_NODE_INVO_CUI
,NUMBER_STG_NODES
,NUMBER_STG_NODES_CUI
,NUMB_POS_STAG_NODE
,NUMB_POS_STAG_NODE_CUI
,NUMB_MEDI_NODE
,NUMB_MEDI_NODE_CUI
,NUMB_POS_MEDI_NODE
,NUMB_POS_MEDI_NODE_CUI
,NUMB_RESE_NODE
,NUMB_RESE_NODE_CUI
,NUMB_POS_RESE_NODE
,NUMB_POS_RESE_NODE_CUI
,NUMB_TOT_NODE_EXAM
,NUMB_TOT_NODE_EXAM_CUI
,NUMB_TOT_POS_NODE
,NUMB_TOT_POS_NODE_CUI
,MACF_PATH_LN_STG_CUI
,MF_PATH_LYM_NODE_STG_CUI
,PERC_LYM_NODE_INVO
,PERC_LYM_NODE_INVO_CUI
,AJCC6_PATH_CUI
,KADISH_STAGE_CUI
,MACF_PATH_MET_STG_CUI
,THOR_ESOP_PATH_MET_CUI
,A6_PATH_STG_GROUP_CUI
,BURK_LYMP_PATH_CUI
,EXGONGERM_PATHSG_CUI
,MACF_PATH_STG_GROUP_CUI
,MASA_THYM_STG_GROUP_CUI
,OLEP_STG_GROUP_CUI
,BIL_CIRR_PATH_E_CUI
,AP_ALLO_GLOM_SCOR_CUI
,AP_ART_HYAL_THK_SCOR_CUI
,AP_E_ALLOGLOM_SCOR_CUI
,AP_INTIM_THICK_SCOR_CUI
,AP_INTE_FIBR_SCOR_CUI
,AP_INTI_ARTE_SCOR_CUI
,AP_MESMATR_INCR_SCOR_CUI
,AP_MC_IN_INFLAM_SCOR_CUI
,AP_TUBU_ATRO_SCOR_CUI
,ALLO_PATH_TUBU_SCOR_CUI
,BANF97_REN_ALLO_CLAS_CUI
,BONEGIANT_TUM_GRAD_CUI
,BRAA_BRAA_ALZH_STG_CUI
,BRAA_BRAA_PARK_STG_CUI
,BRESLOWS_THICKNESS
,BRESLOWS_THICKNESS_CUI
,CANC_UK_PRIPATH_CLAS_CUI
,OTHER_CANC_UK_PRIPATH_CLAS
,CARC_HIST_CLAS_CUI
,CERA_PLAQ_SCOR_CUI
,CERV_INTR_NEOP_GRAD_CUI
,CHONDROSARCOMA_GRADE_CUI
,CHRO_GAST_TYPE_CUI
,CLARK_LEVEL_CUI
,DEPTH_TUMOR_INVA_CUI
,ENDO_ADEN_HIST_GRAD_CUI
,ENNE_STAG_MUSC_SARC_CUI
,ESOP_DYSP_GRAD_CUI
,FIBROSIS_GRADE_CUI
,FIBROSIS_SCORE_CUI
,FOLL_LYMP_HIST_GRAD_CUI
,GLAS_GLOM_JUGU_CLAS_CUI
,GLEA_PRIMARY_SCORE
,GLEA_PRIMARY_SCORE_CUI
,GLEA_SECOND_SCORE
,GLEA_SECOND_SCORE_CUI
,GLEASON_SCORE
,GLEASON_SCORE_CUI
,HISTOLOGIC_GRADE_CUI
,HUNT_DIS_PATH_GRAD_CUI
,IMMA_TERA_HIST_GRAD_CUI
,INTR_NECR_CUI
,JAP_CLASS_DYSP_CUI
,LYMPHATIC_INVASION_CUI
,NIA_REAG_NEUR_CRIT_CUI
,NOTT_COMB_HIST_GRAD_CUI
,NUMB_INDI_TUMO_PRES
,NUMB_INDI_TUMO_PRES_CUI
,OLEP_PATHOLOGY_CUI
,PADO_INTE_DYSP_CLAS_CUI
,PERC_TISSUE_POS
,PERC_TISSUE_POS_CUI
,PERIPORTAL_NECROSIS_CUI
,PERITONEAL_DISS_CUI
,PORTAL_INFLAMMATION_CUI
,RESIDUAL_TUMOR_CUI
,SEROSAL_INVASION_CUI
,SHIMADA_CLASS_CUI
,TUMOR_LATERALITY_CUI
,TUMOR_GRADE_CUI
,OTHER_TUMOR_GRADE
,UTER_DEGR_DIFF_CUI
,VAGI_INTR_NEOP_GRAD_CUI
,VENOUS_INVASION_CUI
,VIENNA_DYSP_CLASS_CUI
,VULV_INTR_NEOP_GRAD_CUI
,WHO_CNS_GRAD_CUI
,WHO_HISTCLAS_DCNEO_CUI
,WHO_HISTCLAS_MYELDIS_CUI
,WHO_MDS_HIST_CLAS_CUI
,WHO_NASO_CARC_GRAD_CUI
,WHO_PNS_GRAD_CUI
,WHO_THYM_CLAS_CUI
,AGNOR_COUNT
,AGNOR_COUNT_CUI
,APOPTOSIS_CUI
,OTHER_APOPTOSIS
,AVER_MITO_PER_HPF_CUI
,CALCIFICATION_CUI
,CELL_ORIGIN_CUI
,OTHER_CELL_ORIGIN
,CELL_PROLIF_EL_CUI
,CELL_SIZE_CUI
,OTHER_CELL_SIZE
,FIBROCYSTIC_CHANGES_CUI
,MITOTIC_INDEX_CUI
,MYEL_CELL_MASS
,MYEL_CELL_MASS_CUI
,PLAS_CELL_INDE_CUI
,PROLIFERATION_INDEX
,PROLIFERATION_INDEX_CUI
,SPHASE_CUI
,TELOMERASE_ACTIVITY_CUI
,TUMO_MASS_SIZE_MICRO
,TUMO_MASS_SIZE_MICRO_CUI
,TUMOR_NECROSIS_CUI
,ELEC_MICR_REPO
,ELEC_MICR_REPO_CUI
)
AS (SELECT
ID
,FORM_ID
,PATH_REPO_DIAG_CUI
,OTHER_PATH_REPO_DIAG
,PATH_REPO_TEXT
,PATH_REPO_TEXT_CUI
,TISSUE_ORIG_CUI
,OTHER_TISSUE_ORIG
,SITE_FIND_CUI
,OTHER_SITE_FIND
,SURGICAL_PROCEDURE_CUI
,OTHER_SURGICAL_PROCEDURE
,NEED_BIOP_NUMB
,NEED_BIOP_NUMB_CUI
,NUMB_CORE_POS
,NUMB_CORE_POS_CUI
,NUMB_CORE_TAKE
,NUMB_CORE_TAKE_CUI
,PERC_CORE_POS
,PERC_CORE_POS_CUI
,PATH_STG_APPL_IND_CUI
,PATH_COMMENTS
,PATH_COMMENTS_CUI
,LESI_DIAM1
,LESI_DIAM1_CUI
,LESI_DIAM2
,LESI_DIAM2_CUI
,LESI_DIAM3
,LESI_DIAM3_CUI
,HEART_WEIGHT
,HEART_WEIGHT_CUI
,LEFT_ATRI_DIAM
,LEFT_ATRI_DIAM_CUI
,LEFT_VENT_DIAM
,LEFT_VENT_DIAM_CUI
,LEFT_VENT_WALL_THIC
,LEFT_VENT_WALL_THIC_CUI
,RIGH_ATRI_DIAM
,RIGH_ATRI_DIAM_CUI
,RIGH_VENT_DIAM
,RIGH_VENT_DIAM_CUI
,RIGH_VENT_WALL_THIC
,RIGH_VENT_WALL_THIC_CUI
,NUMB_POLYPS
,NUMB_POLYPS_CUI
,SIZE_LEUK_CUI
,A6_PATH_TUMO_STG_CUI
,MACF_PATH_TUMO_STG_CUI
,A6_PATH_LYM_NODE_STG_CUI
,HAN_PATH_LN_LOCA_CUI
,LYM_NODE_INVO
,LYM_NODE_INVO_CUI
,NUMBER_STG_NODES
,NUMBER_STG_NODES_CUI
,NUMB_POS_STAG_NODE
,NUMB_POS_STAG_NODE_CUI
,NUMB_MEDI_NODE
,NUMB_MEDI_NODE_CUI
,NUMB_POS_MEDI_NODE
,NUMB_POS_MEDI_NODE_CUI
,NUMB_RESE_NODE
,NUMB_RESE_NODE_CUI
,NUMB_POS_RESE_NODE
,NUMB_POS_RESE_NODE_CUI
,NUMB_TOT_NODE_EXAM
,NUMB_TOT_NODE_EXAM_CUI
,NUMB_TOT_POS_NODE
,NUMB_TOT_POS_NODE_CUI
,MACF_PATH_LN_STG_CUI
,MF_PATH_LYM_NODE_STG_CUI
,PERC_LYM_NODE_INVO
,PERC_LYM_NODE_INVO_CUI
,AJCC6_PATH_CUI
,KADISH_STAGE_CUI
,MACF_PATH_MET_STG_CUI
,THOR_ESOP_PATH_MET_CUI
,A6_PATH_STG_GROUP_CUI
,BURK_LYMP_PATH_CUI
,EXGONGERM_PATHSG_CUI
,MACF_PATH_STG_GROUP_CUI
,MASA_THYM_STG_GROUP_CUI
,OLEP_STG_GROUP_CUI
,BIL_CIRR_PATH_E_CUI
,AP_ALLO_GLOM_SCOR_CUI
,AP_ART_HYAL_THK_SCOR_CUI
,AP_E_ALLOGLOM_SCOR_CUI
,AP_INTIM_THICK_SCOR_CUI
,AP_INTE_FIBR_SCOR_CUI
,AP_INTI_ARTE_SCOR_CUI
,AP_MESMATR_INCR_SCOR_CUI
,AP_MC_IN_INFLAM_SCOR_CUI
,AP_TUBU_ATRO_SCOR_CUI
,ALLO_PATH_TUBU_SCOR_CUI
,BANF97_REN_ALLO_CLAS_CUI
,BONEGIANT_TUM_GRAD_CUI
,BRAA_BRAA_ALZH_STG_CUI
,BRAA_BRAA_PARK_STG_CUI
,BRESLOWS_THICKNESS
,BRESLOWS_THICKNESS_CUI
,CANC_UK_PRIPATH_CLAS_CUI
,OTHER_CANC_UK_PRIPATH_CLAS
,CARC_HIST_CLAS_CUI
,CERA_PLAQ_SCOR_CUI
,CERV_INTR_NEOP_GRAD_CUI
,CHONDROSARCOMA_GRADE_CUI
,CHRO_GAST_TYPE_CUI
,CLARK_LEVEL_CUI
,DEPTH_TUMOR_INVA_CUI
,ENDO_ADEN_HIST_GRAD_CUI
,ENNE_STAG_MUSC_SARC_CUI
,ESOP_DYSP_GRAD_CUI
,FIBROSIS_GRADE_CUI
,FIBROSIS_SCORE_CUI
,FOLL_LYMP_HIST_GRAD_CUI
,GLAS_GLOM_JUGU_CLAS_CUI
,GLEA_PRIMARY_SCORE
,GLEA_PRIMARY_SCORE_CUI
,GLEA_SECOND_SCORE
,GLEA_SECOND_SCORE_CUI
,GLEASON_SCORE
,GLEASON_SCORE_CUI
,HISTOLOGIC_GRADE_CUI
,HUNT_DIS_PATH_GRAD_CUI
,IMMA_TERA_HIST_GRAD_CUI
,INTR_NECR_CUI
,JAP_CLASS_DYSP_CUI
,LYMPHATIC_INVASION_CUI
,NIA_REAG_NEUR_CRIT_CUI
,NOTT_COMB_HIST_GRAD_CUI
,NUMB_INDI_TUMO_PRES
,NUMB_INDI_TUMO_PRES_CUI
,OLEP_PATHOLOGY_CUI
,PADO_INTE_DYSP_CLAS_CUI
,PERC_TISSUE_POS
,PERC_TISSUE_POS_CUI
,PERIPORTAL_NECROSIS_CUI
,PERITONEAL_DISS_CUI
,PORTAL_INFLAMMATION_CUI
,RESIDUAL_TUMOR_CUI
,SEROSAL_INVASION_CUI
,SHIMADA_CLASS_CUI
,TUMOR_LATERALITY_CUI
,TUMOR_GRADE_CUI
,OTHER_TUMOR_GRADE
,UTER_DEGR_DIFF_CUI
,VAGI_INTR_NEOP_GRAD_CUI
,VENOUS_INVASION_CUI
,VIENNA_DYSP_CLASS_CUI
,VULV_INTR_NEOP_GRAD_CUI
,WHO_CNS_GRAD_CUI
,WHO_HISTCLAS_DCNEO_CUI
,WHO_HISTCLAS_MYELDIS_CUI
,WHO_MDS_HIST_CLAS_CUI
,WHO_NASO_CARC_GRAD_CUI
,WHO_PNS_GRAD_CUI
,WHO_THYM_CLAS_CUI
,AGNOR_COUNT
,AGNOR_COUNT_CUI
,APOPTOSIS_CUI
,OTHER_APOPTOSIS
,AVER_MITO_PER_HPF_CUI
,CALCIFICATION_CUI
,CELL_ORIGIN_CUI
,OTHER_CELL_ORIGIN
,CELL_PROLIF_EL_CUI
,CELL_SIZE_CUI
,OTHER_CELL_SIZE
,FIBROCYSTIC_CHANGES_CUI
,MITOTIC_INDEX_CUI
,MYEL_CELL_MASS
,MYEL_CELL_MASS_CUI
,PLAS_CELL_INDE_CUI
,PROLIFERATION_INDEX
,PROLIFERATION_INDEX_CUI
,SPHASE_CUI
,TELOMERASE_ACTIVITY_CUI
,TUMO_MASS_SIZE_MICRO
,TUMO_MASS_SIZE_MICRO_CUI
,TUMOR_NECROSIS_CUI
,ELEC_MICR_REPO
,ELEC_MICR_REPO_CUI
FROM CIR_SURGICAL_PATHOLOGY);
/


CREATE OR REPLACE VIEW SURGICAL_PATHOLOGY_MULTI_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
)
AS (SELECT 
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
FROM CIR_SURGICAL_PATHOLOGY_MULTI);
/

CREATE OR REPLACE VIEW SURGICAL_PATHOLOGY_NOTE_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
)
AS (SELECT 
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
FROM CIR_SURGICAL_PATHOLOGY_NOTE);
/

REM ************************************************************************************
REM * CREATE VIEW for category path_verification (conventional)
REM ************************************************************************************
CREATE OR REPLACE VIEW PATH_VERIFICATION_V (
ID
,FORM_ID
,SAMPLE_DX_CUI
,OTHER_SAMPLE_DX
,SAMPLE_TOO_CUI
,OTHER_SAMPLE_TOO
,SAMPLE_SOF_CUI
,OTHER_SAMPLE_SOF
,CELL_SOURCE_CUI
,OTHER_CELL_SOURCE
,NORMA
,NORMA_CUI
,LESION
,LESION_CUI
,TUMOR
,TUMOR_CUI
,NO_NL_ARCH_IN_LESION_CUI
,CELLULAR_STROMA
,CELLULAR_STROMA_CUI
,HYPO_STROMA
,HYPO_STROMA_CUI
,NECROSIS
,NECROSIS_CUI
,TOTAL_PERCENT
,TOTAL_PERCENT_CUI
,APPEARANCE_CUI
,OTHER_APPEARANCE
,SLIDE_ALIAS
,SLIDE_ALIAS_CUI
,SUPPLIER_NOTE
,SUPPLIER_NOTE_CUI
,INTERNAL_NOTE
,INTERNAL_NOTE_CUI
)
AS (SELECT
ID
,FORM_ID
,SAMPLE_DX_CUI
,OTHER_SAMPLE_DX
,SAMPLE_TOO_CUI
,OTHER_SAMPLE_TOO
,SAMPLE_SOF_CUI
,OTHER_SAMPLE_SOF
,CELL_SOURCE_CUI
,OTHER_CELL_SOURCE
,NORMA
,NORMA_CUI
,LESION
,LESION_CUI
,TUMOR
,TUMOR_CUI
,NO_NL_ARCH_IN_LESION_CUI
,CELLULAR_STROMA
,CELLULAR_STROMA_CUI
,HYPO_STROMA
,HYPO_STROMA_CUI
,NECROSIS
,NECROSIS_CUI
,TOTAL_PERCENT
,TOTAL_PERCENT_CUI
,APPEARANCE_CUI
,OTHER_APPEARANCE
,SLIDE_ALIAS
,SLIDE_ALIAS_CUI
,SUPPLIER_NOTE
,SUPPLIER_NOTE_CUI
,INTERNAL_NOTE
,INTERNAL_NOTE_CUI
FROM CIR_PATH_VERIFICATION);
/


CREATE OR REPLACE VIEW PATH_VERIFICATION_MULTI_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
)
AS (SELECT 
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
FROM CIR_PATH_VERIFICATION_MULTI);
/

CREATE OR REPLACE VIEW PATH_VERIFICATION_NOTE_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
)
AS (SELECT 
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
FROM CIR_PATH_VERIFICATION_NOTE);
/

REM ************************************************************************************
REM * CREATE VIEW for category followup_info (conventional)
REM ************************************************************************************
CREATE OR REPLACE VIEW FOLLOWUP_INFO_V (
ID
,FORM_ID
,DATE_LAST_FOLLOWUP
,DATE_LAST_FOLLOWUP_CUI
,TIME_SINC_LAST_SURG
,TIME_SINC_LAST_SURG_CUI
,TIME_SINC_LAST_DATE
,TIME_SINC_LAST_DATE_CUI
,VITAL_STATUS_CUI
,VITAL_STATUS_WO_ADE_CUI
,DATE_DEATH
,DATE_DEATH_CUI
,RECUR_CUI
,MD_COMMENTS
,MD_COMMENTS_CUI
)
AS (SELECT
ID
,FORM_ID
,DATE_LAST_FOLLOWUP
,DATE_LAST_FOLLOWUP_CUI
,TIME_SINC_LAST_SURG
,TIME_SINC_LAST_SURG_CUI
,TIME_SINC_LAST_DATE
,TIME_SINC_LAST_DATE_CUI
,VITAL_STATUS_CUI
,VITAL_STATUS_WO_ADE_CUI
,DATE_DEATH
,DATE_DEATH_CUI
,RECUR_CUI
,MD_COMMENTS
,MD_COMMENTS_CUI
FROM CIR_FOLLOWUP_INFO);
/



CREATE OR REPLACE VIEW FOLLOWUP_INFO_NOTE_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
)
AS (SELECT 
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
FROM CIR_FOLLOWUP_INFO_NOTE);
/

REM ************************************************************************************
REM * CREATE VIEW for category blank_fields (conventional)
REM ************************************************************************************
CREATE OR REPLACE VIEW BLANK_FIELDS_V (
ID
,FORM_ID
,BLANK_CV1_ONE_CUI
,BLANK_CV1_TWO_CUI
,BLANK_CV1_THREE_CUI
,BLANK_CV1_FOUR_CUI
,BLANK_CV1_FIVE_CUI
,OTHER_BLANK_CV1_FIVE
,BLANK_TEXT_ONE
,BLANK_TEXT_ONE_CUI
,BLANK_TEXT_TWO
,BLANK_TEXT_TWO_CUI
,BLANK_TEXT_THREE
,BLANK_TEXT_THREE_CUI
,BLANK_TEXT_FOUR
,BLANK_TEXT_FOUR_CUI
,BLANK_TEXT_FIVE
,BLANK_TEXT_FIVE_CUI
,BLANK_REPORT_ONE
,BLANK_REPORT_ONE_CUI
,BLANK_REPORT_TWO
,BLANK_REPORT_TWO_CUI
,BLANK_REPORT_THREE
,BLANK_REPORT_THREE_CUI
,BLANK_DATE_ONE
,BLANK_DATE_ONE_CUI
,BLANK_DATE_TWO
,BLANK_DATE_TWO_CUI
,BLANK_DATE_THREE
,BLANK_DATE_THREE_CUI
,BLANK_FLOAT_ONE
,BLANK_FLOAT_ONE_CUI
,BLANK_FLOAT_TWO
,BLANK_FLOAT_TWO_CUI
,BLANK_FLOAT_THREE
,BLANK_FLOAT_THREE_CUI
,BLANK_INTEGER_ONE
,BLANK_INTEGER_ONE_CUI
,BLANK_INTEGER_TWO
,BLANK_INTEGER_TWO_CUI
,BLANK_INTEGER_THREE
,BLANK_INTEGER_THREE_CUI
,BLANK_YN_CUI
,BLANK_YNDK_CUI
,BLANK_AR_ONE_CUI
,BLANK_AR_TWO_CUI
,BLANK_AR_THREE_CUI
,BLANK_PERC_FLOAT_ONE
,BLANK_PERC_FLOAT_ONE_CUI
,BLANK_PERC_FLOAT_TWO
,BLANK_PERC_FLOAT_TWO_CUI
,BLANK_PERC_INT_ONE
,BLANK_PERC_INT_ONE_CUI
,BLANK_PERC_INT_TWO
,BLANK_PERC_INT_TWO_CUI
,BLANK_FLOAT_FOUR
,BLANK_FLOAT_FOUR_CUI
,BLANK_FLOAT_FIVE
,BLANK_FLOAT_FIVE_CUI
,BLANK_INTEGER_FOUR
,BLANK_INTEGER_FOUR_CUI
,BLANK_INTEGER_FIVE
,BLANK_INTEGER_FIVE_CUI
,BLANK_CV1_DATE_ADE_CUI
,BLANK_CV1_ADE_ONE_CUI
,BLANK_CV1_ADE_TWO_CUI
,OTHER_BLANK_CV1_ADE_TWO
,BLANK_FLOAT_DATE_ADE
,BLANK_FLOAT_DATE_ADE_CUI
,BLANK_FLOAT_ADE
,BLANK_FLOAT_ADE_CUI
,BLANK_CV1_ST_RPT_ADE_CUI
)
AS (SELECT
ID
,FORM_ID
,BLANK_CV1_ONE_CUI
,BLANK_CV1_TWO_CUI
,BLANK_CV1_THREE_CUI
,BLANK_CV1_FOUR_CUI
,BLANK_CV1_FIVE_CUI
,OTHER_BLANK_CV1_FIVE
,BLANK_TEXT_ONE
,BLANK_TEXT_ONE_CUI
,BLANK_TEXT_TWO
,BLANK_TEXT_TWO_CUI
,BLANK_TEXT_THREE
,BLANK_TEXT_THREE_CUI
,BLANK_TEXT_FOUR
,BLANK_TEXT_FOUR_CUI
,BLANK_TEXT_FIVE
,BLANK_TEXT_FIVE_CUI
,BLANK_REPORT_ONE
,BLANK_REPORT_ONE_CUI
,BLANK_REPORT_TWO
,BLANK_REPORT_TWO_CUI
,BLANK_REPORT_THREE
,BLANK_REPORT_THREE_CUI
,BLANK_DATE_ONE
,BLANK_DATE_ONE_CUI
,BLANK_DATE_TWO
,BLANK_DATE_TWO_CUI
,BLANK_DATE_THREE
,BLANK_DATE_THREE_CUI
,BLANK_FLOAT_ONE
,BLANK_FLOAT_ONE_CUI
,BLANK_FLOAT_TWO
,BLANK_FLOAT_TWO_CUI
,BLANK_FLOAT_THREE
,BLANK_FLOAT_THREE_CUI
,BLANK_INTEGER_ONE
,BLANK_INTEGER_ONE_CUI
,BLANK_INTEGER_TWO
,BLANK_INTEGER_TWO_CUI
,BLANK_INTEGER_THREE
,BLANK_INTEGER_THREE_CUI
,BLANK_YN_CUI
,BLANK_YNDK_CUI
,BLANK_AR_ONE_CUI
,BLANK_AR_TWO_CUI
,BLANK_AR_THREE_CUI
,BLANK_PERC_FLOAT_ONE
,BLANK_PERC_FLOAT_ONE_CUI
,BLANK_PERC_FLOAT_TWO
,BLANK_PERC_FLOAT_TWO_CUI
,BLANK_PERC_INT_ONE
,BLANK_PERC_INT_ONE_CUI
,BLANK_PERC_INT_TWO
,BLANK_PERC_INT_TWO_CUI
,BLANK_FLOAT_FOUR
,BLANK_FLOAT_FOUR_CUI
,BLANK_FLOAT_FIVE
,BLANK_FLOAT_FIVE_CUI
,BLANK_INTEGER_FOUR
,BLANK_INTEGER_FOUR_CUI
,BLANK_INTEGER_FIVE
,BLANK_INTEGER_FIVE_CUI
,BLANK_CV1_DATE_ADE_CUI
,BLANK_CV1_ADE_ONE_CUI
,BLANK_CV1_ADE_TWO_CUI
,OTHER_BLANK_CV1_ADE_TWO
,BLANK_FLOAT_DATE_ADE
,BLANK_FLOAT_DATE_ADE_CUI
,BLANK_FLOAT_ADE
,BLANK_FLOAT_ADE_CUI
,BLANK_CV1_ST_RPT_ADE_CUI
FROM CIR_BLANK_FIELDS);
/


CREATE OR REPLACE VIEW BLANK_FIELDS_MULTI_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
)
AS (SELECT 
ID
,FORM_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
FROM CIR_BLANK_FIELDS_MULTI);
/

CREATE OR REPLACE VIEW BLANK_FIELDS_NOTE_V (
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
)
AS (SELECT 
ID
,FORM_ID
,DATA_ELEMENT_CUI
,NOTE
FROM CIR_BLANK_FIELDS_NOTE);
/

CREATE OR REPLACE VIEW DATE_ADE_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATE_ELEMENT
,DATE_ELEMENT_DPC
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATE_ELEMENT
,DATE_ELEMENT_DPC
FROM CIR_DATE_ADE);
/

CREATE OR REPLACE VIEW PHYSICAL_ADE_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,AGE_FIND_APPE
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,AGE_FIND_APPE
FROM CIR_PHYSICAL_ADE);
/

CREATE OR REPLACE VIEW SX_SCORE_ADE_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,SYMPTOM_SCORE_CUI
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,SYMPTOM_SCORE_CUI
FROM CIR_SX_SCORE_ADE);
/

CREATE OR REPLACE VIEW CA_RX_RESPONSE_ADE_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATE_RX_START
,DATE_RX_START_DPC
,DATE_RECENT_RX
,DATE_RECENT_RX_DPC
,RX_RESPONSE_CUI
,OTHER_RX_RESPONSE
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATE_RX_START
,DATE_RX_START_DPC
,DATE_RECENT_RX
,DATE_RECENT_RX_DPC
,RX_RESPONSE_CUI
,OTHER_RX_RESPONSE
FROM CIR_CA_RX_RESPONSE_ADE);
/

CREATE OR REPLACE VIEW CHEMO_ADE_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,TIMING_CHEMO_CUI
,DATE_CHEMO_START
,DATE_CHEMO_START_DPC
,DATE_CHEMO_END
,DATE_CHEMO_END_DPC
,DAYS_SINCLST_CHEMO
,ROUT_ADMI_CUI
,OTHER_ROUT_ADMI
,RESP_CHEMO_CUI
,OTHER_RESP_CHEMO
,OFF_TREAT_REASON_CUI
,OTHER_OFF_TREAT_REASON
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,TIMING_CHEMO_CUI
,DATE_CHEMO_START
,DATE_CHEMO_START_DPC
,DATE_CHEMO_END
,DATE_CHEMO_END_DPC
,DAYS_SINCLST_CHEMO
,ROUT_ADMI_CUI
,OTHER_ROUT_ADMI
,RESP_CHEMO_CUI
,OTHER_RESP_CHEMO
,OFF_TREAT_REASON_CUI
,OTHER_OFF_TREAT_REASON
FROM CIR_CHEMO_ADE);
/

CREATE OR REPLACE VIEW MEDICATION_ADE_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATE_MEDI_START
,DATE_MEDI_START_DPC
,DATE_MEDI_END
,DATE_MEDI_END_DPC
,DAYS_SINCLST_MEDI
,RESP_MEDI_CUI
,OTHER_RESP_MEDI
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATE_MEDI_START
,DATE_MEDI_START_DPC
,DATE_MEDI_END
,DATE_MEDI_END_DPC
,DAYS_SINCLST_MEDI
,RESP_MEDI_CUI
,OTHER_RESP_MEDI
FROM CIR_MEDICATION_ADE);
/

CREATE OR REPLACE VIEW MED_DATES_ADE_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATE_MEDS_START
,DATE_MEDS_START_DPC
,DATE_RECENT_MEDS
,DATE_RECENT_MEDS_DPC
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATE_MEDS_START
,DATE_MEDS_START_DPC
,DATE_RECENT_MEDS
,DATE_RECENT_MEDS_DPC
FROM CIR_MED_DATES_ADE);
/

CREATE OR REPLACE VIEW TREATMENT_ADE_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATE_TREAT
,DATE_TREAT_DPC
,RESP_TREAT_CUI
,OTHER_RESP_TREAT
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATE_TREAT
,DATE_TREAT_DPC
,RESP_TREAT_CUI
,OTHER_RESP_TREAT
FROM CIR_TREATMENT_ADE);
/

CREATE OR REPLACE VIEW RADIOTHERAPY_ADE_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,TIMING_RADIOTHERAPY_CUI
,DATE_RADIO_START
,DATE_RADIO_START_DPC
,DATE_RADIO_END
,DATE_RADIO_END_DPC
,DAYS_SINCLST_RADIO
,TOTL_RADIO_DOS
,RESP_RADIO_CUI
,OTHER_RESP_RADIO
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,TIMING_RADIOTHERAPY_CUI
,DATE_RADIO_START
,DATE_RADIO_START_DPC
,DATE_RADIO_END
,DATE_RADIO_END_DPC
,DAYS_SINCLST_RADIO
,TOTL_RADIO_DOS
,RESP_RADIO_CUI
,OTHER_RESP_RADIO
FROM CIR_RADIOTHERAPY_ADE);
/

CREATE OR REPLACE VIEW RADIOTHERAPY_ADE_MULTI_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
FROM CIR_RADIOTHERAPY_ADE_MULTI);
/
CREATE OR REPLACE VIEW SURGERY_ADE_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATE_OF_SURGERY
,DATE_OF_SURGERY_DPC
,OPERATIVE_NOTE
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATE_OF_SURGERY
,DATE_OF_SURGERY_DPC
,OPERATIVE_NOTE
FROM CIR_SURGERY_ADE);
/

CREATE OR REPLACE VIEW TRANSPLANT_ADE_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATE_TRANSPLANT
,DATE_TRANSPLANT_DPC
,TRANSPLANT_SOURCE_CUI
,OTHER_TRANSPLANT_SOURCE
,TRANS_OPERAT_NOTE
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATE_TRANSPLANT
,DATE_TRANSPLANT_DPC
,TRANSPLANT_SOURCE_CUI
,OTHER_TRANSPLANT_SOURCE
,TRANS_OPERAT_NOTE
FROM CIR_TRANSPLANT_ADE);
/

CREATE OR REPLACE VIEW BLOOD_DRAW_ADE_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,TIMING_BLOOD_DRAW_CUI
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,TIMING_BLOOD_DRAW_CUI
FROM CIR_BLOOD_DRAW_ADE);
/

CREATE OR REPLACE VIEW ESOPH_PH_ADE_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATE_OF_ESOPH_PH
,DEMEESTER_SCORE
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATE_OF_ESOPH_PH
,DEMEESTER_SCORE
FROM CIR_ESOPH_PH_ADE);
/

CREATE OR REPLACE VIEW ESOPH_US_ADE_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATE_OF_ESOPH_US
,US_T_STAGE_CUI
,US_N_STAGE_CUI
,ESOPH_US_REPORT
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATE_OF_ESOPH_US
,US_T_STAGE_CUI
,US_N_STAGE_CUI
,ESOPH_US_REPORT
FROM CIR_ESOPH_US_ADE);
/

CREATE OR REPLACE VIEW LAB_CT_ADE_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATE_OF_CT
,LAB_CT_TIMEPOINT_CUI
,LIVER_MET_CUI
,LUNG_MET_CUI
,LAB_CT_REPORT
,CT_COMMENT
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATE_OF_CT
,LAB_CT_TIMEPOINT_CUI
,LIVER_MET_CUI
,LUNG_MET_CUI
,LAB_CT_REPORT
,CT_COMMENT
FROM CIR_LAB_CT_ADE);
/

CREATE OR REPLACE VIEW LAB_CT_ADE_MULTI_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
FROM CIR_LAB_CT_ADE_MULTI);
/
CREATE OR REPLACE VIEW LAB_PET_ADE_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATE_OF_PET
,LAB_PET_TIMEPOINT_CUI
,LAB_PET_REPORT
,PET_COMMENT
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATE_OF_PET
,LAB_PET_TIMEPOINT_CUI
,LAB_PET_REPORT
,PET_COMMENT
FROM CIR_LAB_PET_ADE);
/

CREATE OR REPLACE VIEW LAB_PET_MASS_ADE_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,SUV
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,SUV
FROM CIR_LAB_PET_MASS_ADE);
/

CREATE OR REPLACE VIEW OBJ_STUDY_REPORT_ADE_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATE_OBJECT_STUDY
,OBJECT_STUDY_CUI
,OTHER_OBJECT_STUDY
,OBJECT_STUDY_RPRT
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATE_OBJECT_STUDY
,OBJECT_STUDY_CUI
,OTHER_OBJECT_STUDY
,OBJECT_STUDY_RPRT
FROM CIR_OBJ_STUDY_REPORT_ADE);
/

CREATE OR REPLACE VIEW STUDY_REPORT_ADE_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATE_STUDY
,STUDY_RPRT
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATE_STUDY
,STUDY_RPRT
FROM CIR_STUDY_REPORT_ADE);
/

CREATE OR REPLACE VIEW LAB_NUMERIC_ADE_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATE_NUME_RESU_TEST
,DATE_NUME_RESU_TEST_DPC
,CLIN_TEST_RESU_CUI
,TEST_NORM_RANG
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATE_NUME_RESU_TEST
,DATE_NUME_RESU_TEST_DPC
,CLIN_TEST_RESU_CUI
,TEST_NORM_RANG
FROM CIR_LAB_NUMERIC_ADE);
/

CREATE OR REPLACE VIEW LAB_TECHNIQUE_ADE_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATE_TECH_SPEC_TEST
,DATE_TECH_SPEC_TEST_DPC
,TEST_TECHNIQUE_CUI
,OTHER_TEST_TECHNIQUE
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATE_TECH_SPEC_TEST
,DATE_TECH_SPEC_TEST_DPC
,TEST_TECHNIQUE_CUI
,OTHER_TEST_TECHNIQUE
FROM CIR_LAB_TECHNIQUE_ADE);
/

CREATE OR REPLACE VIEW LAB_MICRO_ADE_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATE_MICR_TEST
,CULTURE_RESULT_CUI
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATE_MICR_TEST
,CULTURE_RESULT_CUI
FROM CIR_LAB_MICRO_ADE);
/

CREATE OR REPLACE VIEW ALCOHOL_HX_ADE_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,ALCOHOL_AMOUNT
,ALCOHOL_DURATION
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,ALCOHOL_AMOUNT
,ALCOHOL_DURATION
FROM CIR_ALCOHOL_HX_ADE);
/

CREATE OR REPLACE VIEW TOBACCO_HX_ADE_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,TOBACCO_AMOUNT
,TIMING_SMOKING_CUI
,TOBACCO_STOPPED
,TOBACCO_STOPPED_DPC
,YEAR_NOT_SMOK
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,TOBACCO_AMOUNT
,TIMING_SMOKING_CUI
,TOBACCO_STOPPED
,TOBACCO_STOPPED_DPC
,YEAR_NOT_SMOK
FROM CIR_TOBACCO_HX_ADE);
/

CREATE OR REPLACE VIEW TOBACCO_HX_ADE_MULTI_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
FROM CIR_TOBACCO_HX_ADE_MULTI);
/
CREATE OR REPLACE VIEW OCCUPATION_ADE_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,YEARS_AT_OCC
,YEARS_SINCE_OCC
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,YEARS_AT_OCC
,YEARS_SINCE_OCC
FROM CIR_OCCUPATION_ADE);
/

CREATE OR REPLACE VIEW EXPOSURE_HX_ADE_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,YEAR_EXPOSED
,YEAR_SINC_EXPOSED
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,YEAR_EXPOSED
,YEAR_SINC_EXPOSED
FROM CIR_EXPOSURE_HX_ADE);
/

CREATE OR REPLACE VIEW CANCER_HX_ADE_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATE_DIAG
,DATE_DIAG_DPC
,AGE_AT_DIAGNOSIS
,CANCER_STATUS_CUI
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATE_DIAG
,DATE_DIAG_DPC
,AGE_AT_DIAGNOSIS
,CANCER_STATUS_CUI
FROM CIR_CANCER_HX_ADE);
/

CREATE OR REPLACE VIEW CANCER_HX_ADE_MULTI_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
FROM CIR_CANCER_HX_ADE_MULTI);
/
CREATE OR REPLACE VIEW DIABETES_HX_ADE_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DIAB_MELL_DUR
,DIAB_MELL_TYPE_CUI
,OTHER_DIAB_MELL_TYPE
,DIAB_MELL_CONT_CUI
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DIAB_MELL_DUR
,DIAB_MELL_TYPE_CUI
,OTHER_DIAB_MELL_TYPE
,DIAB_MELL_CONT_CUI
FROM CIR_DIABETES_HX_ADE);
/

CREATE OR REPLACE VIEW DIABETES_HX_ADE_MULTI_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
FROM CIR_DIABETES_HX_ADE_MULTI);
/
CREATE OR REPLACE VIEW HCU_ADE_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATE_HCU_START
,DATE_HCU_START_DPC
,DATE_RECENT_HCU
,DATE_RECENT_HCU_DPC
,DAYS_SINC_HCU
,DURATION_TREATMENT
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATE_HCU_START
,DATE_HCU_START_DPC
,DATE_RECENT_HCU
,DATE_RECENT_HCU_DPC
,DAYS_SINC_HCU
,DURATION_TREATMENT
FROM CIR_HCU_ADE);
/

CREATE OR REPLACE VIEW HCU_ADE_MULTI_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
FROM CIR_HCU_ADE_MULTI);
/
CREATE OR REPLACE VIEW HRT_ADE_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATE_HRT_START
,DATE_HRT_START_DPC
,DATE_RECENT_HRT
,DATE_RECENT_HRT_DPC
,DAYS_SINC_HRT
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATE_HRT_START
,DATE_HRT_START_DPC
,DATE_RECENT_HRT
,DATE_RECENT_HRT_DPC
,DAYS_SINC_HRT
FROM CIR_HRT_ADE);
/

CREATE OR REPLACE VIEW HRT_ADE_MULTI_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
FROM CIR_HRT_ADE_MULTI);
/
CREATE OR REPLACE VIEW HYPERTENSION_HX_ADE_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,HYPE_DUR
,HYPERTENSION_TYPE_CUI
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,HYPE_DUR
,HYPERTENSION_TYPE_CUI
FROM CIR_HYPERTENSION_HX_ADE);
/

CREATE OR REPLACE VIEW PAST_CONDITIONS_ADE_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATE_ONSET
,DATE_ONSET_DPC
,AGE_DIAG_PAST_COND
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATE_ONSET
,DATE_ONSET_DPC
,AGE_DIAG_PAST_COND
FROM CIR_PAST_CONDITIONS_ADE);
/

CREATE OR REPLACE VIEW FAMILY_HX_ADE_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,AGE_DIAG_FAMI_HIST
,DEGR_RELAT_CUI
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,AGE_DIAG_FAMI_HIST
,DEGR_RELAT_CUI
FROM CIR_FAMILY_HX_ADE);
/

CREATE OR REPLACE VIEW CHEMO_HX_ADE_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATE_PR_CHEMO_START
,DATE_PR_CHEMO_START_DPC
,DATE_PR_CHEMO_END
,DATE_PR_CHEMO_END_DPC
,DAYS_SINCLSTPR_CHEMO
,RESP_PRIO_CHEMO_CUI
,OTHER_RESP_PRIO_CHEMO
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATE_PR_CHEMO_START
,DATE_PR_CHEMO_START_DPC
,DATE_PR_CHEMO_END
,DATE_PR_CHEMO_END_DPC
,DAYS_SINCLSTPR_CHEMO
,RESP_PRIO_CHEMO_CUI
,OTHER_RESP_PRIO_CHEMO
FROM CIR_CHEMO_HX_ADE);
/

CREATE OR REPLACE VIEW RADIOTHERAPY_HX_ADE_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATE_PR_RADIO_START
,DATE_PR_RADIO_START_DPC
,DATE_PR_RADIO_END
,DATE_PR_RADIO_END_DPC
,DAYS_SINCLSTPR_RADIO
,RESP_PRIO_RADIO_CUI
,OTHER_RESP_PRIO_RADIO
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATE_PR_RADIO_START
,DATE_PR_RADIO_START_DPC
,DATE_PR_RADIO_END
,DATE_PR_RADIO_END_DPC
,DAYS_SINCLSTPR_RADIO
,RESP_PRIO_RADIO_CUI
,OTHER_RESP_PRIO_RADIO
FROM CIR_RADIOTHERAPY_HX_ADE);
/

CREATE OR REPLACE VIEW CHEST_TUBE_ADE_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DISC_WITH_CHES_TUBE_CUI
,DATE_CHEST_TUBE_DC
,NUMB_CHES_TUBE_DAYS
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DISC_WITH_CHES_TUBE_CUI
,DATE_CHEST_TUBE_DC
,NUMB_CHES_TUBE_DAYS
FROM CIR_CHEST_TUBE_ADE);
/

CREATE OR REPLACE VIEW DEATH_ADE_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATE_DEAT
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATE_DEAT
FROM CIR_DEATH_ADE);
/

CREATE OR REPLACE VIEW PAIN_SCORE_ADE_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATE_PAIN_SCORE
,TIME_SINC_PAIN_SCOR
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATE_PAIN_SCORE
,TIME_SINC_PAIN_SCOR
FROM CIR_PAIN_SCORE_ADE);
/

CREATE OR REPLACE VIEW PRIMARY_PROC_ADE_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,APPROACH_CUI
,OTHER_APPROACH
,LATERALITY_CUI
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,APPROACH_CUI
,OTHER_APPROACH
,LATERALITY_CUI
FROM CIR_PRIMARY_PROC_ADE);
/

CREATE OR REPLACE VIEW PERCENT_ADE_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,PERCENT_INCLUSIVE
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,PERCENT_INCLUSIVE
FROM CIR_PERCENT_ADE);
/

CREATE OR REPLACE VIEW INFLAM_SEVERITY_ADE_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,SEVERITY_CUI
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,SEVERITY_CUI
FROM CIR_INFLAM_SEVERITY_ADE);
/

CREATE OR REPLACE VIEW RECUR_ADE_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,RECUR_STATUS_CUI
,DATE_RECUR
,RECUR_TYPE_CUI
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,RECUR_STATUS_CUI
,DATE_RECUR
,RECUR_TYPE_CUI
FROM CIR_RECUR_ADE);
/

CREATE OR REPLACE VIEW RECUR_ADE_MULTI_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
FROM CIR_RECUR_ADE_MULTI);
/
CREATE OR REPLACE VIEW BLANK_ADE_ONE_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,BLANK_ADE_E1_CUI
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,BLANK_ADE_E1_CUI
FROM CIR_BLANK_ADE_ONE);
/

CREATE OR REPLACE VIEW BLANK_ADE_ONE_MULTI_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
FROM CIR_BLANK_ADE_ONE_MULTI);
/
CREATE OR REPLACE VIEW BLANK_ADE_TWO_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,BLANK_ADE_E3_CUI
,BLANK_ADE_E4_CUI
,BLANK_ADE_E6
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,BLANK_ADE_E3_CUI
,BLANK_ADE_E4_CUI
,BLANK_ADE_E6
FROM CIR_BLANK_ADE_TWO);
/

CREATE OR REPLACE VIEW BLANK_ADE_TWO_MULTI_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
FROM CIR_BLANK_ADE_TWO_MULTI);
/
CREATE OR REPLACE VIEW BLANK_ADE_THREE_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,BLANK_ADE_E7_CUI
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,BLANK_ADE_E7_CUI
FROM CIR_BLANK_ADE_THREE);
/

CREATE OR REPLACE VIEW BLANK_ADE_THREE_MULTI_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
FROM CIR_BLANK_ADE_THREE_MULTI);
/
CREATE OR REPLACE VIEW BLANK_ADE_FOUR_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,BLANK_ADE_E9_CUI
,BLANK_ADE_E10_CUI
,BLANK_ADE_E12
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,BLANK_ADE_E9_CUI
,BLANK_ADE_E10_CUI
,BLANK_ADE_E12
FROM CIR_BLANK_ADE_FOUR);
/

CREATE OR REPLACE VIEW BLANK_ADE_FOUR_MULTI_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
FROM CIR_BLANK_ADE_FOUR_MULTI);
/
CREATE OR REPLACE VIEW BLANK_ADE_FIVE_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,BLANK_ADE_E13_CUI
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,BLANK_ADE_E13_CUI
FROM CIR_BLANK_ADE_FIVE);
/

CREATE OR REPLACE VIEW BLANK_ADE_FIVE_MULTI_V (
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
)
AS (SELECT
ID
,FORM_ID
,PARENT_ID
,DATA_ELEMENT_CUI
,DATA_VALUE_CUI
,OTHER_DATA_VALUE
FROM CIR_BLANK_ADE_FIVE_MULTI);
/
