SET DEFINE OFF;
SET ECHO ON;
insert into pdc_lookup values('PATIENT_INFORMATION', 'CA12658C', 'Other MRN', '', '', 'ARD_CAP', 'A', 'P', '', '1.58', '', 'other_mrn', '1', 'N', 'text', '', 'Element', '', '', '', '', '', '', 'N', '', '22', '');
insert into pdc_lookup values('CASE_INFORMATION', 'CA12652C', 'Case category', '', '', 'ARD_CAP', 'A', 'P', '', '1.58', '', 'case_information', '1', 'Y', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '22', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12659C', 'Sample format', '', '', 'ARD_CAP', 'A', 'P', '', '1.58', '', 'sample_format', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '22', '');
insert into pdc_lookup values('CASE_INFORMATION', 'CA12653C', 'CASE_CATEGORY_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.58', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '22', '');
insert into pdc_lookup values('CASE_INFORMATION', 'CA12654C', 'Perinatal', '', '', 'ARD_CAP', 'A', 'P', '', '1.58', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '22', '');
insert into pdc_lookup values('CASE_INFORMATION', 'CA12655C', 'Tumor', '', '', 'ARD_CAP', 'A', 'P', '', '1.58', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '22', '');
insert into pdc_lookup values('CASE_INFORMATION', 'CA12656C', 'Vascular', '', '', 'ARD_CAP', 'A', 'P', '', '1.58', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '22', '');
insert into pdc_lookup values('CASE_INFORMATION', 'CA12657C', 'Other case category', '', '', 'ARD_CAP', 'A', 'P', '', '1.58', '', '', '', '', '', 'Y', 'Value', '', '', '', '', '', '', '', '', '22', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12660C', 'SAMPLE_FORMAT_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.58', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '22', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12661C', 'SNAP frozen, Isopenthane', '', '', 'ARD_CAP', 'A', 'P', '', '1.58', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '22', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12662C', 'SNAP frozen, liquid N2', '', '', 'ARD_CAP', 'A', 'P', '', '1.58', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '22', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12663C', 'SNAP frozen, prefixed in 4% PFA, isopenthane', '', '', 'ARD_CAP', 'A', 'P', '', '1.58', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '22', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12664C', 'SNAP frozen, prefixed in 4% PFA, liquid N2', '', '', 'ARD_CAP', 'A', 'P', '', '1.58', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '22', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12665C', 'SNAP frozen, Other (add comment)', '', '', 'ARD_CAP', 'A', 'P', '', '1.58', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '22', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12666C', 'OCT frozen, on dry ice', '', '', 'ARD_CAP', 'A', 'P', '', '1.58', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '22', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12667C', 'OCT frozen, in cryostat', '', '', 'ARD_CAP', 'A', 'P', '', '1.58', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '22', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12668C', 'OCT frozen, liquid N2', '', '', 'ARD_CAP', 'A', 'P', '', '1.58', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '22', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12669C', 'OCT frozen, other (add comment)', '', '', 'ARD_CAP', 'A', 'P', '', '1.58', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '22', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12670C', 'RNA stabilizer, -80', '', '', 'ARD_CAP', 'A', 'P', '', '1.58', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '22', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA1261C', 'RNA stabilizer, other (add comment)', '', '', 'ARD_CAP', 'A', 'P', '', '1.58', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '22', '');
commit;
