SET DEFINE OFF; and SET ECHO ON;

insert into pdc_lookup values('TREATMENT_HISTORY', 'CA12675C', 'History of chemotherapy', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', 'chemo_hist', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '23', '');
insert into pdc_lookup values('TREATMENT_HISTORY', 'CA12674C', 'History of radiation therapy', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', 'radiation_hist', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '23', '');
insert into pdc_lookup values('CASE_INFORMATION', 'CA12676C', 'Surgical pathology report required', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', 'report_surg_path', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '23', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12695C', 'Blood collection tube', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', 'blood_tube_plmi', '1', 'Y', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '23', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12711C', 'External investigator', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', 'ext_investigator', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '23', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12684C', 'Fixed tissue preparation', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', 'fixed_tissue_prep', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '23', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12710C', 'Frozen tissue preparation', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', 'frozen_tissue_prep', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '23', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12703C', 'Investigator ID', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', 'investigator_id', '1', 'Y', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '23', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12707C', 'Project number', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', 'project_number', '1', 'N', 'text', '', 'Element', '', '', '', '', '', '', 'N', '', '23', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12708C', 'Request number', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', 'project_request', '1', 'N', 'text', '', 'Element', '', '', '', '', '', '', 'N', '', '23', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12683C', 'Sample dimensions', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', 'sample_dimensions', '1', 'N', 'text', '', 'Element', '', '', '', '', '', '', 'N', '', '23', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12677C', 'Sample gross appearance', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', 'samp_gross_appear', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '23', '');
insert into pdc_lookup values('PROCEDURE', '359572002', 'Enterectomy','118673008','', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PROCEDURE', 'CA12862P', 'Face transplant','118950002','', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PROCEDURE', '282435000', 'Maxillectomy','118950002','', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PROCEDURE', 'CA12860P', 'Gland excision','CA01041P','', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PROCEDURE', 'CA12863P', 'Stereotactic biopsy','CA01041P','','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PROCEDURE', 'CA12861P', 'Tumor excision','CA01041P','','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PROCEDURE', '69466000', 'Unknown procedure','CA01041P','','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('TRANSPLANT_PROCEDURE', 'CA12868C', 'Face transplantation', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12696C', 'PLMI_BLOOD_TUBE_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('BLOOD_TUBE', 'CA12697C', 'Blood (Gold)', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('BLOOD_TUBE', 'CA12698C', 'Blood (Green)', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('BLOOD_TUBE', 'CA12699C', 'Blood (Purple)', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('BLOOD_TUBE', 'CA12700C', 'Blood (Red)', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('BLOOD_TUBE', 'CA12701C', 'Blood (Yellow)', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('BLOOD_TUBE', 'CA12705C', 'Blood (Pink)', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('BLOOD_TUBE', 'CA12706C', 'Blood (Tiger-Serum Separator)', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('BLOOD_TUBE', 'CA12859C', 'Other blood collection tube', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', 'Y', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12685C', 'FIXED_PREP_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('FIXED_PREP', 'CA12686C', 'Fixed in alcohol', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('FIXED_PREP', 'CA12687C', 'Fixed in formalin', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('FIXED_PREP', 'CA12688C', 'Fixed in gluteraldehyde', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('FIXED_PREP', 'CA12689C', 'Fixed in paraformaldehyde', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12690C', 'FROZEN_PREP_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('FROZEN_PREP', 'CA12691C', 'Fresh (snap) frozen', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('FROZEN_PREP', 'CA12692C', 'OCT', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('FROZEN_PREP', 'CA12693C', 'RNA Stabilizer', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12704C', 'PLMI_INVESTIGATOR_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12712C', 'Aaronson, Stuart - A1864', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12713C', 'Abaffy, Tatjana - A1921', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12714C', 'Agarwal, Anil - A1953', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12715C', 'Ahmed, Tasneem - F0016', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12716C', 'Aikhionbare, Felix - A1558', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12717C', 'Akins, Robert - INV772', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12718C', 'Alahari, Suresh - A1879', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12719C', 'Andl, Thomas - A1909', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12720C', 'Barnett, Gene - F1212', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12721C', 'Batra. Surinder - A1318', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12722C', 'Bell, Daphne - A1854', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12723C', 'Borden, Ernest - F0014', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12724C', 'Broccoli, Dominique - A1859', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12725C', 'Bronner, Mary - F1625', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12726C', 'Cao, Deliang - A1777', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12727C', 'Carrigan, Christina - AC1749', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12728C', 'Chan, Edward - A1811', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12729C', 'Chan, Curtis - AC1762', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12730C', 'Chang, Ken - INV264', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12731C', 'Charles, Ronald - F0026', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12732C', 'COG, COG - F0010', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12733C', 'CORS, CORS - F1147', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12734C', 'Croce, Carlo - C1644', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12735C', 'Crouser, Elliott - B1644', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12736C', 'Davis, Deborah - 3069', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12737C', 'Deleon, Daisy - A689', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12738C', 'Delwart, Eric - IN3190', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12739C', 'DePinho, Ronald - A1903', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12740C', 'Desai, Nina - F0020', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12741C', 'Drachman, Johathan - AC1742', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12742C', 'Drezek, Rebekah - A1738', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12743C', 'Falany, Charles - A1913', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12744C', 'Falk, Gary - F0013', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12745C', 'Finke, James - F1133', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12746C', 'Fowler, Bruce - A1367', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12747C', 'Frozen Archive, CCF - F0000', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12748C', 'Ganapathi, Ram - F0001', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12869C', 'Gardner, Paul - A1886', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12870C', 'Gelb, Arnold - AC1764', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12751C', 'Gera, Joseph - A1792', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12752C', 'Giordano, Thomas - A1594', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12753C', 'Glover, Sarah - A1916', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12754C', 'Greenfield, Lawrence - INV267', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12755C', 'Guo, Nancy Lan - A1867', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12756C', 'Gurney, Austin - AC1687', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12757C', 'Hansel, Donna - F0004', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12758C', 'Harris, Curtis - A141', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12759C', 'Harris, Chris - A1755', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12760C', 'High, Katherine - A1912', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12761C', 'Hsi, Eric - A1485', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12762C', 'Huang, Ying - A1934', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12763C', 'Hutteman, Maik - A1839', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12764C', 'IRB 6000, IRB 6000 - F0003', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12765C', 'Jabado, Nada - A1672', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12766C', 'Jacob, Samson - C1643', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12767C', 'James, Paul - A1906', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12768C', 'Janigro, Damir - F1220', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12769C', 'Johnson, Mahlon - A1896', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12770C', 'Kadlubar, Fred - A1894', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12771C', 'Kai, Mihoko - 3051', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12772C', 'Kennedy, Giulia - AD1757', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12773C', 'Kerfoot, Christopher - AD1706', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12774C', 'Kimmins, Sarah - A1881', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12775C', 'King, Mary-Claire - A116', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12776C', 'Landi, Maria Teresa - A1897', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12777C', 'Languino, Lucia - A1729', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12778C', 'Larigan,J. Douglas - AC961', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12779C', 'Lindner, Daniel - F1156', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12780C', 'Lorch, Gwendolen - B1674', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'Ca12781C', 'Maciejewski, Jaroslaw - F0019', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12782C', 'Magi-Galluzzi - F1630', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12783C', 'Mai, Sabine - A1962', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12784C', 'Marsh, Clay - B1647', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12785C', 'Medarova, Zdravka - A1914', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12786C', 'Menon, Narayanan - F0029', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12787C', 'Merchant, Nipun - A1925', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12788C', 'Meyerson, Matthew - A1869', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12789C', 'Mikhail, Adel - AC1593', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12790C', 'Misek, David - A1949', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12791C', 'Mivechi, Nahid - A1087', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12792C', 'Mikoma, Amosy - IN465', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12793C', 'Morin, Pat - A1108', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12794C', 'Moskal, Joseph - A907', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12795C', 'Najim, Imad - F1155', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12796C', 'Nana-Sinkam, Serge - B1671', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12797C', 'Nathanson, Kate - A1784', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12798C', 'Natowicz, Marvin - F0006', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12799C', 'Ningaraj, Nagendra - A1919', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12800C', 'Nuttman, Gaylee - AC537', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12801C', 'Parsons, Barbara - A1712', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12802C', 'Pham, Nancy - F0021', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12803C', 'Poirier, Miriam - A1493', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12804C', 'Powers, Scott - A1910', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12805C', 'Prabhakar, Bellur - A915', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12806C', 'Price, Thomas - A1908', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12807C', 'Puri, Raj - A1375', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12808C', 'QC - Q1000', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12809C', 'Reizes, Ofer - F0028', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12810C', 'Relling, Mary - A224', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12811C', 'Repository, LAM - F0025', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12812C', 'Roberts, Stephen - A1841', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12813C', 'Robertson, Gavin - A1480', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12814C', 'Rojko, Jennifer - AC1447', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12815C', 'Rubin, Brian - F0027', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12816C', 'Sang, Qing-Xaing - A1801', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12817C', 'Schneider, Bryan - A1942', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12818C', 'Sen, Chandan - IN1542', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12819C', 'Sengupta, Saubhik - F0022', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12820C', 'Sferruzza, Anthony - AC1677', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12821C', 'Shen, Bo - F0015', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12822C', 'Silverman, Robert - F0002', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12823C', 'Smith,Ellen - F1234', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12824C', 'Smith, Johnathan - F0017', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12825C', 'Sontheimer, Harold - A1716', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12826C', 'Staugaitis, Susan - F861', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12827C', 'Strong, Scott - F945', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12828C', 'Sukumar, Saraswati - A1321', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12829C', 'Sweeney, Colleen - A1816', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12830A', 'Tanaka, Hisashi - F0018', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12831C', 'Tay, Joyce - AC1747', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12832C', 'Teh, Bin - A1149', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12833C', 'Terentis, Andrew - A1922', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12834C', 'Thakker, Dhiren - A1814', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12835C', 'Trapp, Bruce - F1476', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12836C', 'Tubbs, Richard - F1228', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12837C', 'Turkson, James - A1943', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12838C', 'Turner, Tim - A1853', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12839C', 'Tuthill, Ralph - F0023', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12840C', 'Varki, Nissi - A758', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12841C', 'Von Hoff, Daniel - A1815', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12842C', 'Vonderhaar, Barbara - A1075', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12843C', 'Waggie, Kimberly - AC1208', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12844C', 'Waghorne, Carol - AC1734', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12845C', 'Waldman, Scott - A1041', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12846C', 'Walker, Ameae - A1817', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12847C', 'Wands, Jack - A1776', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12848C', 'Wang, Xi-Tao - AC1698', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12849C', 'Williams, David - A1800', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12850C', 'Yaswee, Paul - A1830', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12851C', 'Yates, Allen - C083', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12852C', 'Younossi, Zobair - A1448', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12853C', 'Zhou, Ming - F1631', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12854C', 'Zhou, Qiqi - B1672', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12855C', 'Zhu, Xiaocheng - F0030', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('PLMI_INVESTIGATOR', 'CA12856C', 'Other Investigator ID', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', 'Y', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12678C', 'SAMPLE_GROSS_APPEARANCE_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('SAMPLE_GROSS_APPEAR', 'CA12679C', 'Gross benign', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('SAMPLE_GROSS_APPEAR', 'CA12680C', 'Gross malignant', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('SAMPLE_GROSS_APPEAR', 'CA12681C', 'Gross normal-adjacent to tumor', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('SAMPLE_GROSS_APPEAR', 'CA12682C', 'Gross normal-distant to tumor', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('SAMPLE_TYPE', 'CA12702C', 'Cell Prep Slide, Touch Prep', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('SAMPLE_TYPE', 'CA12694C', 'Fixed Tissue', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('SAMPLE_TYPE', 'CA12857C', 'Frozen tissue stained slide', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('SAMPLE_TYPE', 'CA12858C', 'Frozen tissue unstained slide', '', '', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('TISSUE_LIST', '389026000', 'Ascites','20139000','', 'ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '126926005^CA00142M^', 'Tumor of breast','126926005^^','','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', 'CA12864D^^', 'Carcinoma of liver, hepatitis B associated','128348002^^','','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', 'CA12865D^^', 'Carcinoma of liver, hepatitis C associated','128348002^^','','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '420120006^^', 'Gastrointestinal stromal tumor','128348002^^','','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '126846004^CA00142M^', 'Tumor of Appendix','128348002^^','','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '126851005^CA00142M^', 'Tumor of liver','128348002^^','','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '126832004^CA00142M^', 'Tumor of small intestine','128348002^^','','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '57789003^CA00142M^', 'Tumor of urothelium','126879004^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '127018007^CA00142M^', 'Adenocarcinoma of thyroid','387927001^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '127021009^CA00142M^', 'Tumor of adrenal gland','387927001^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '12337004^44598004^', 'Leiomyoma of uterus','126907002^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '123844007^CA00142M^', 'Tumor of endometrium','126907002^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '126692004^CA00142M^', 'Tumor of larynx','255055008^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '254464000^CA00142M^', 'Tumor of submandibular gland','255055008^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '21964009^^', 'Lymphoma','129154003^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '126900000^^', 'Carcinoma of testis','126895004^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '19929002^^', 'Angiomyolipoma','CA01026D^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '115239009^CA00142M^', 'Tumor of Bone','CA01026D^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '40009002^^', 'Craniopharyngioma','126950007^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '128781004^^', 'Craniopharyngioma, adamantinomatous','126950007^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '128782006^^', 'Craniopharyngioma papillary','126950007^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '1623000^^', 'Ependymoma, myxopapillary','126950007^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '254935002^CA00142M^', 'Tumor of brain','126950007^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '62064005^^', 'Mesothelioma','126667002^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '126885006^CA00142M^', 'Tumor of Bladder','126879004^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '126880001^CA00142M^', 'Tumor of kidney','126879004^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '32048006^^', 'Adenoma','CA00120D^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', 'CA12867D^^', 'Adenocarcinoma','CA00120D^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '31470003^^', 'Adenosarcoma','CA00120D^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '68453008^^', 'Carcinoma','CA00120D^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '79282002^^', 'Carcinoma, metastatic','CA00120D^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '253000007^^', 'Carcinoma, neuroendocrine','CA00120D^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '25910003^^', 'Carcinoma, papillary','CA00120D^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '90282004^^', 'Carcinoma, papillary serous','CA00120D^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '28899001^^', 'Carcinoma, squamous cell','CA00120D^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '307593001^^', 'Carcinomatosis','CA00120D^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '47620003^^', 'Cystadenoma','CA00120D^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '60718004^^', 'Dysgerminoma','CA00120D^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '403981003^^', 'Epithelioid hemangioendothelioma','CA00120D^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '44598004^^', 'Leiomyoma','CA00120D^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '400102008^^', 'Lipoblastoma','CA00120D^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '55818009^^', 'Teratoma of unknown origin','CA00120D^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '443492008^^', 'Tumor, carcinoid','CA00120D^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '88897007^^', 'Tumor, spindle cell','CA00120D^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '255051004^CA00142M^', 'Tumor of unknown origin','CA00120D^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '64226004^^', 'Colitis','53619000^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '64766004^^', 'Colitis, ulcerative','53619000^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '64613007^^', 'Enteritis','53619000^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '50711007^^', 'Hepatitis C','53619000^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '360436002^^', 'Hirschprungs disease  ~  Congenital megacolon','53619000^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '303078007^^', 'Perforation of large intestine','53619000^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '416209007^^', 'Synovitis','CA01088D^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '95412009^^', 'Synovitis, pigmented','CA01088D^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '78275009^^', 'Obstructive sleep apnea','50043002^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '441457006^^', 'Cyst','56019007^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '428794004^^', 'Fistula','56019007^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '76197007^^', 'Hyperplasia','56019007^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '9831005^^', 'Myxoid degeneration','56019007^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '441456002^^', 'Polyp','56019007^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '29696001^^', 'Prolapse','56019007^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '56246009^^', 'Hypertrophy of tissue','56019007^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '40733004^^', 'Infection','56019007^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');
insert into pdc_lookup values('DIAGNOSIS', '23583003^^', 'Inflammation','56019007^^', '','ARD_CAP', 'A', 'P', '', '1.60', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '23', '');


--insert into pdc_dx_tc_hierarchy values ('OWNER_CODE', 'FULLY_SPECIFIED_NAME', 'PARENT_CODE', 'LEVEL_CODE', 'TYPE_CODE', 'ORDER_BY', 'DESIRE_SCORE', 'ACT', 'PRF', 'GRP', 'VER', 'REV');
insert into pdc_dx_tc_hierarchy values ('359572002', 'Enterectomy', '118673008', '2', 'P', '646', '', 'A', 'P', 'DIG', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('CA12862P', 'Face transplant', '118950002', '2', 'P', '1251', '', 'A', 'P', 'HAN', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('282435000', 'Maxillectomy', '118950002', '2', 'P', '1285', '', 'A', 'P', 'HAN', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('CA12860P', 'Gland excision', 'CA01041P', '2', 'P', '2395', '', 'A', 'P', 'XPOTH', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('CA12863P', 'Stereotactic biopsy', 'CA01041P', '2', 'P', '2445', '', 'A', 'P', 'XPOTH', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('CA12861P', 'Tumor excision', 'CA01041P', '2', 'P', '2460', '', 'A', 'P', 'XPOTH', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('69466000', 'Unknown procedure', 'CA01041P', '2', 'P', '2470', '', 'A', 'P', 'XPOTH', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('126926005^CA00142M^', 'Tumor of breast', '126926005^^', '3', 'D', '585', '', 'A', 'P', 'ANBRT', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('CA12864D^^', 'Carcinoma of liver, hepatitis B associated', '128348002^^', '3', 'D', '1565', '', 'A', 'P', 'ANDIG', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('CA12865D^^', 'Carcinoma of liver, hepatitis C associated', '128348002^^', '3', 'D', '1566', '', 'A', 'P', 'ANDIG', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('420120006^^', 'Gastrointestinal stromal tumor', '128348002^^', '3', 'D', '1779', '', 'A', 'P', 'ANDIG', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('126846004^CA00142M^', 'Tumor of Appendix', '128348002^^', '3', 'D', '1965', '', 'A', 'P', 'ANDIG', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('126851005^CA00142M^', 'Tumor of liver', '128348002^^', '3', 'D', '2046', '', 'A', 'P', 'ANDIG', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('126832004^CA00142M^', 'Tumor of small intestine', '128348002^^', '3', 'D', '2145', '', 'A', 'P', 'ANDIG', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('57789003^CA00142M^', 'Tumor of urothelium', '126879004^^', '3', 'D', '8925', '', 'A', 'P', 'ANURN', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('127018007^CA00142M^', 'Adenocarcinoma of thyroid', '387927001^^', '3', 'D', '2219', '', 'A', 'P', 'ANEND', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('127021009^CA00142M^', 'Tumor of adrenal gland', '387927001^^', '3', 'D', '2605', '', 'A', 'P', 'ANEND', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('12337004^44598004^', 'Leiomyoma of uterus', '126907002^^', '3', 'D', '4285', '', 'A', 'P', 'ANFRS', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('123844007^CA00142M^', 'Tumor of endometrium', '126907002^^', '3', 'D', '4465', '', 'A', 'P', 'ANFRS', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('126692004^CA00142M^', 'Tumor of larynx', '255055008^^', '3', 'D', '5245', '', 'A', 'P', 'ANHAN', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('21964009^^', 'Lymphoma', '129154003^^', '3', 'D', '5405', '', 'A', 'P', 'ANHEM', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('254464000^CA00142M^', 'Tumor of submandibular gland', '255055008^^', '3', 'D', '5275', '', 'A', 'P', 'ANHAN', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('126900000^^', 'Carcinoma of testis', '126895004^^', '3', 'D', '5825', '', 'A', 'P', 'ANMRS', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('19929002^^', 'Angiomyolipoma', 'CA01026D^^', '3', 'D', '6005', '', 'A', 'P', 'ANMST', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('115239009^CA00142M^', 'Tumor of Bone', 'CA01026D^^', '3', 'D', '6785', '', 'A', 'P', 'ANMST', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('40009002^^', 'Craniopharyngioma', '126950007^^', '3', 'D', '6925', '', 'A', 'P', 'ANNER', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('128781004^^', 'Craniopharyngioma, adamantinomatous', '126950007^^', '3', 'D', '6926', '', 'A', 'P', 'ANNER', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('128782006^^', 'Craniopharyngioma papillary', '126950007^^', '3', 'D', '6927', '', 'A', 'P', 'ANNER', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('1623000^^', 'Ependymoma, myxopapillary', '126950007^^', '3', 'D', '6935', '', 'A', 'P', 'ANNER', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('254935002^CA00142M^', 'Tumor of brain', '126950007^^', '3', 'D', '7255', '', 'A', 'P', 'ANNER', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('62064005^^', 'Mesothelioma', '126667002^^', '3', 'D', '7846', '', 'A', 'P', 'ANRES', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('126885006^CA00142M^', 'Tumor of Bladder', '126879004^^', '3', 'D', '8915', '', 'A', 'P', 'ANURN', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('126880001^CA00142M^', 'Tumor of kidney', '126879004^^', '3', 'D', '8916', '', 'A', 'P', 'ANURN', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('32048006^^', 'Adenoma', 'CA00120D^^', '3', 'D', '9025', '', 'A', 'P', 'ANXUK', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('CA12867D^^', 'Adenocarcinoma', 'CA00120D^^', '3', 'D', '8945', '', 'A', 'P', 'ANXUK', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('31470003^^', 'Adenosarcoma', 'CA00120D^^', '3', 'D', '9026', '', 'A', 'P', 'ANXUK', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('68453008^^', 'Carcinoma', 'CA00120D^^', '3', 'D', '9027', '', 'A', 'P', 'ANXUK', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('79282002^^', 'Carcinoma, metastatic', 'CA00120D^^', '3', 'D', '9121', '', 'A', 'P', 'ANXUK', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('253000007^^', 'Carcinoma, neuroendocrine', 'CA00120D^^', '3', 'D', '9122', '', 'A', 'P', 'ANXUK', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('25910003^^', 'Carcinoma, papillary', 'CA00120D^^', '3', 'D', '9123', '', 'A', 'P', 'ANXUK', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('90282004^^', 'Carcinoma, papillary serous', 'CA00120D^^', '3', 'D', '9124', '', 'A', 'P', 'ANXUK', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('28899001^^', 'Carcinoma, squamous cell', 'CA00120D^^', '3', 'D', '9125', '', 'A', 'P', 'ANXUK', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('307593001^^', 'Carcinomatosis', 'CA00120D^^', '3', 'D', '9126', '', 'A', 'P', 'ANXUK', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('47620003^^', 'Cystadenoma', 'CA00120D^^', '3', 'D', '9131', '', 'A', 'P', 'ANXUK', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('60718004^^', 'Dysgerminoma', 'CA00120D^^', '3', 'D', '9132', '', 'A', 'P', 'ANXUK', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('403981003^^', 'Epithelioid hemangioendothelioma', 'CA00120D^^', '3', 'D', '9133', '', 'A', 'P', 'ANXUK', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('44598004^^', 'Leiomyoma', 'CA00120D^^', '3', 'D', '9134', '', 'A', 'P', 'ANXUK', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('400102008^^', 'Lipoblastoma', 'CA00120D^^', '3', 'D', '9136', '', 'A', 'P', 'ANXUK', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('55818009^^', 'Teratoma of unknown origin', 'CA00120D^^', '3', 'D', '9139', '', 'A', 'P', 'ANXUK', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('443492008^^', 'Tumor, carcinoid', 'CA00120D^^', '3', 'D', '9231', '', 'A', 'P', 'ANXUK', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('88897007^^', 'Tumor, spindle cell', 'CA00120D^^', '3', 'D', '9232', '', 'A', 'P', 'ANXUK', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('255051004^CA00142M^', 'Tumor of unknown origin', 'CA00120D^^', '3', 'D', '9233', '', 'A', 'P', 'ANXUK', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('64226004^^', 'Colitis', '53619000^^', '3', 'D', '10245', '', 'A', 'P', 'DDIG', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('64766004^^', 'Colitis, ulcerative', '53619000^^', '3', 'D', '10325', '', 'A', 'P', 'DDIG', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('64613007^^', 'Enteritis', '53619000^^', '3', 'D', '10565', '', 'A', 'P', 'DDIG', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('50711007^^', 'Hepatitis C', '53619000^^', '3', 'D', '10795', '', 'A', 'P', 'DDIG', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('360436002^^', 'Hirschprungs disease ~ Congenital megacolon', '53619000^^', '3', 'D', '10845', '', 'A', 'P', 'DDIG', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('303078007^^', 'Perforation of large intestine', '53619000^^', '3', 'D', '11105', '', 'A', 'P', 'DDIG', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('416209007^^', 'Synovitis', 'CA01088D^^', '3', 'D', '13695', '', 'A', 'P', 'DMST', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('95412009^^', 'Synovitis, pigmented', 'CA01088D^^', '3', 'D', '13725', '', 'A', 'P', 'DMST', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('78275009^^', 'Obstructive sleep apnea', '50043002^^', '3', 'D', '14365', '', 'A', 'P', 'DRES', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('441457006^^', 'Cyst', '56019007^^', '3', 'D', '15575', '', 'A', 'P', 'DXSYS', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('428794004^^', 'Fistula', '56019007^^', '3', 'D', '15585', '', 'A', 'P', 'DXSYS', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('76197007^^', 'Hyperplasia', '56019007^^', '3', 'D', '15593', '', 'A', 'P', 'DXSYS', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('9831005^^', 'Myxoid degeneration', '56019007^^', '3', 'D', '15594', '', 'A', 'P', 'DXSYS', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('441456002^^', 'Polyp', '56019007^^', '3', 'D', '15595', '', 'A', 'P', 'DXSYS', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('29696001^^', 'Prolapse', '56019007^^', '3', 'D', '15596', '', 'A', 'P', 'DXSYS', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('56246009^^', 'Hypertrophy of tissue', '56019007^^', '3', 'D', '15586', '', 'A', 'P', 'DXSYS', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('40733004^^', 'Infection', '56019007^^', '3', 'D', '15597', '', 'A', 'P', 'DXSYS', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('23583003^^', 'Inflammation', '56019007^^', '3', 'D', '15598', '', 'A', 'P', 'DXSYS', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('389026000', 'Ascites', '20139000', '2', 'T', '3235', '', 'A', 'P', 'RES', '1.60', '');

insert into pdc_dx_tc_hierarchy values ('CA09817C', 'Hypophysectomy', '118675001', '2', 'P', '1005', '', 'A', 'P', 'END', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('CA08125C', 'Pharyngectomy', '118950002', '2', 'P', '1335', '', 'A', 'P', 'HAN', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('CA09807C', 'Craniectomy', '118950002', '2', 'P', '1235', '', 'A', 'P', 'HAN', '1.60', '');
insert into pdc_dx_tc_hierarchy values ('CA08126C', 'Glossectomy', '118950002', '2', 'P', '1265', '', 'A', 'P', 'HAN', '1.60', '');

UPDATE PDC_LOOKUP SET DOMAIN_REF = '118681009' WHERE LOOKUP_TYPE_CD = 'CA09817C';
UPDATE PDC_LOOKUP SET DOMAIN_REF = '118675001' WHERE LOOKUP_TYPE_CD = 'CA12507C';
UPDATE PDC_LOOKUP SET DOMAIN_REF = '118950002' WHERE LOOKUP_TYPE_CD = 'CA08125C';
UPDATE PDC_LOOKUP SET DOMAIN_REF = '118950002' WHERE LOOKUP_TYPE_CD = 'CA09807C';
UPDATE PDC_LOOKUP SET DOMAIN_REF = '118950002' WHERE LOOKUP_TYPE_CD = 'CA08126C';
UPDATE PDC_LOOKUP SET DOMAIN_REF = '128348002^^' WHERE LOOKUP_TYPE_CD = '126817006^CA00142M^';
UPDATE PDC_LOOKUP SET DOMAIN_REF = '128348002^^' WHERE LOOKUP_TYPE_CD = '126824007^CA00142M^';

commit;
