--------------------------------------------------------------------------
-- Play this script in BIGR_OWNER@DETBIGR to make it look like DET_OWNER@DETBIGR
--                                                                      --
-- Please review the script before using it to make sure it won't       --
-- cause any unacceptable data loss.                                    --
--                                                                      --
-- BIGR_OWNER@DETBIGR Schema Extracted by User BIGR_OWNER 
-- DET_OWNER@DETBIGR Schema Extracted by User DET_OWNER 
--                                                                      --
-- Note : Script is view-only because you do not have access to         --
--        dba module functions in TOAD.                                 --
ALTER TABLE CIR_PT_INFO
 ADD (OTHER_MRN  VARCHAR2(4000 BYTE));

ALTER TABLE CIR_PT_INFO
 ADD (OTHER_MRN_CUI  VARCHAR2(30 BYTE));

ALTER TABLE CIR_PAST_MEDI_HIST
 ADD (CHEMO_HIST_CUI  VARCHAR2(30 BYTE));

ALTER TABLE CIR_PAST_MEDI_HIST
 ADD (RADIATION_HIST_CUI  VARCHAR2(30 BYTE));

ALTER TABLE CIR_CASE_INFO
 ADD (CASE_INFORMATION_CUI  VARCHAR2(30 BYTE));

ALTER TABLE CIR_CASE_INFO
 ADD (OTHER_CASE_INFORMATION  VARCHAR2(200 BYTE));

ALTER TABLE CIR_CASE_INFO
 ADD (REPORT_SURG_PATH_CUI  VARCHAR2(30 BYTE));

ALTER TABLE CIR_SAMPLE_INFO
 ADD (BLOOD_TUBE_PLMI_CUI  VARCHAR2(30 BYTE));

ALTER TABLE CIR_SAMPLE_INFO
 ADD (OTHER_BLOOD_TUBE_PLMI  VARCHAR2(200 BYTE));

ALTER TABLE CIR_SAMPLE_INFO
 ADD (EXT_INVESTIGATOR_CUI  VARCHAR2(30 BYTE));

ALTER TABLE CIR_SAMPLE_INFO
 ADD (FIXED_TISSUE_PREP_CUI  VARCHAR2(30 BYTE));

ALTER TABLE CIR_SAMPLE_INFO
 ADD (FROZEN_TISSUE_PREP_CUI  VARCHAR2(30 BYTE));

ALTER TABLE CIR_SAMPLE_INFO
 ADD (INVESTIGATOR_ID_CUI  VARCHAR2(30 BYTE));

ALTER TABLE CIR_SAMPLE_INFO
 ADD (OTHER_INVESTIGATOR_ID  VARCHAR2(200 BYTE));

ALTER TABLE CIR_SAMPLE_INFO
 ADD (PROJECT_NUMBER  VARCHAR2(4000 BYTE));

ALTER TABLE CIR_SAMPLE_INFO
 ADD (PROJECT_NUMBER_CUI  VARCHAR2(30 BYTE));

ALTER TABLE CIR_SAMPLE_INFO
 ADD (PROJECT_REQUEST  VARCHAR2(4000 BYTE));

ALTER TABLE CIR_SAMPLE_INFO
 ADD (PROJECT_REQUEST_CUI  VARCHAR2(30 BYTE));

ALTER TABLE CIR_SAMPLE_INFO
 ADD (SAMPLE_DIMENSIONS  VARCHAR2(4000 BYTE));

ALTER TABLE CIR_SAMPLE_INFO
 ADD (SAMPLE_DIMENSIONS_CUI  VARCHAR2(30 BYTE));

ALTER TABLE CIR_SAMPLE_INFO
 ADD (SAMPLE_FORMAT_CUI  VARCHAR2(30 BYTE));

ALTER TABLE CIR_SAMPLE_INFO
 ADD (OTHER_SAMPLE_FORMAT  VARCHAR2(200 BYTE));

ALTER TABLE CIR_SAMPLE_INFO
 ADD (SAMP_GROSS_APPEAR_CUI  VARCHAR2(30 BYTE));

