set linesize 132
col OWNER format a12
col rname  format a26

spool step4_rem_obj_snap_group.log
SELECT owner, NAME, TYPE, rname 
FROM DBA_REFRESH_CHILDREN 
where NAME in('ES_SHOPPING_CART_DETAIL','ES_ARDAIS_ACCOUNT','ARD_OBJECTS',
'ES_ARDAIS_USER','ARD_USER_ACCESS_MODULE','ARD_LOOKUP_ALL',
'ARD_USER_ACCESS','ARD_WORKGROUP','ARD_WORKGROUP_OBJECTS')
/


begin
Dbms_repcat.drop_snapshot_repobject('ARDAIS_OWNER','ES_SHOPPING_CART_DETAIL','SNAPSHOT');
Dbms_repcat.drop_snapshot_repobject('ARDAIS_OWNER','ES_ARDAIS_ACCOUNT','SNAPSHOT');
Dbms_repcat.drop_snapshot_repobject('ARDAIS_OWNER','ARD_OBJECTS','SNAPSHOT');
Dbms_repcat.drop_snapshot_repobject('ARDAIS_OWNER','ES_ARDAIS_USER','SNAPSHOT');
Dbms_repcat.drop_snapshot_repobject('ARDAIS_OWNER','ARD_USER_ACCESS','SNAPSHOT');
Dbms_repcat.drop_snapshot_repobject('ARDAIS_OWNER','ARD_WORKGROUP','SNAPSHOT');
Dbms_repcat.drop_snapshot_repobject('ARDAIS_OWNER','ARD_WORKGROUP_OBJECTS','SNAPSHOT');
Dbms_repcat.drop_snapshot_repobject('ARDAIS_OWNER','ARD_USER_ACCESS_MODULE','SNAPSHOT');
Dbms_repcat.drop_snapshot_repobject('ARDAIS_OWNER','ARD_LOOKUP_ALL','SNAPSHOT');
--Dbms_repcat.drop_snapshot_repobject('ARDAIS_OWNER','ARD_CONCEPT_GRAPH','SNAPSHOT');
commit;
end;
/

commit
/

DROP MATERIALIZED VIEW ARDAIS_OWNER.ES_SHOPPING_CART_DETAIL;

DROP MATERIALIZED VIEW ARDAIS_OWNER.ES_ARDAIS_ACCOUNT;

DROP MATERIALIZED VIEW ARDAIS_OWNER.ARD_OBJECTS;

DROP MATERIALIZED VIEW ARDAIS_OWNER.ES_ARDAIS_USER;

DROP MATERIALIZED VIEW ARDAIS_OWNER.ARD_USER_ACCESS_MODULE;

DROP MATERIALIZED VIEW ARDAIS_OWNER.ARD_LOOKUP_ALL;

--DROP MATERIALIZED VIEW ARDAIS_OWNER.ARD_CONCEPT_GRAPH;

-- obsolete tables
DROP MATERIALIZED VIEW ARDAIS_OWNER.ARD_USER_ACCESS;

DROP MATERIALIZED VIEW ARDAIS_OWNER.ARD_WORKGROUP;

DROP MATERIALIZED VIEW ARDAIS_OWNER.ARD_WORKGROUP_OBJECTS;

commit
/

SELECT owner, NAME, TYPE, rname 
FROM DBA_REFRESH_CHILDREN 
where NAME in('ES_SHOPPING_CART_DETAIL','ES_ARDAIS_ACCOUNT','ARD_OBJECTS',
'ES_ARDAIS_USER','ARD_USER_ACCESS_MODULE','ARD_LOOKUP_ALL',
'ARD_USER_ACCESS','ARD_WORKGROUP','ARD_WORKGROUP_OBJECTS')
/

spool off

