set linesize 500
spool step9_mk_snap_lexprod.log


CREATE MATERIALIZED VIEW ARDAIS_OWNER.ES_ARDAIS_USER 
TABLESPACE ES_TBL_TBS
NOCACHE
NOLOGGING
NOPARALLEL
BUILD IMMEDIATE
USING INDEX
TABLESPACE USERS
REFRESH FORCE
WITH PRIMARY KEY
AS 
SELECT * FROM ARDAIS_OWNER.ES_ARDAIS_USER@GENREP;


CREATE MATERIALIZED VIEW ARDAIS_OWNER.ARD_OBJECTS 
TABLESPACE OTHER_TBL_TBS
NOCACHE
LOGGING
NOPARALLEL
BUILD IMMEDIATE
USING INDEX
TABLESPACE USERS
REFRESH FORCE
WITH PRIMARY KEY
AS 
SELECT * FROM ARD_OBJECTS@GENREP;

CREATE MATERIALIZED VIEW ARDAIS_OWNER.ES_ARDAIS_ACCOUNT 
TABLESPACE ES_TBL_TBS
NOCACHE
NOLOGGING
NOPARALLEL
BUILD IMMEDIATE
USING INDEX
TABLESPACE USERS
REFRESH FORCE
WITH PRIMARY KEY
AS 
SELECT * FROM ARDAIS_OWNER.ES_ARDAIS_ACCOUNT@GENREP;


CREATE MATERIALIZED VIEW ARDAIS_OWNER.ES_SHOPPING_CART_DETAIL 
TABLESPACE ES_TBL_TBS
NOCACHE
LOGGING
NOPARALLEL
BUILD IMMEDIATE
USING INDEX
TABLESPACE USERS
REFRESH FORCE
WITH PRIMARY KEY
AS 
SELECT * FROM ARDAIS_OWNER.ES_SHOPPING_CART_DETAIL@GENREP;

CREATE MATERIALIZED VIEW ARDAIS_OWNER.ARD_USER_ACCESS_MODULE 
TABLESPACE OTHER_TBL_TBS
NOCACHE
LOGGING
NOPARALLEL
BUILD IMMEDIATE
USING INDEX
TABLESPACE OTHER_IDX_TBS
REFRESH FORCE
WITH PRIMARY KEY
AS 
SELECT * FROM ARD_USER_ACCESS_MODULE@GENREP;

CREATE INDEX ARDAIS_OWNER.ARD_USER_ACCESS_MODULE_IN1 ON ARDAIS_OWNER.ARD_USER_ACCESS_MODULE
(OBJECT_ID)
NOLOGGING
TABLESPACE OTHER_IDX_TBS
NOPARALLEL;

CREATE MATERIALIZED VIEW ARDAIS_OWNER.ARD_LOOKUP_ALL 
TABLESPACE OTHER_TBL_TBS
NOCACHE
LOGGING
NOPARALLEL
BUILD IMMEDIATE
USING INDEX
TABLESPACE ILTDS_IDX_TBS
REFRESH FORCE
WITH PRIMARY KEY
AS 
SELECT * FROM ARDAIS_OWNER.ARD_LOOKUP_ALL@GENREP;

--CREATE MATERIALIZED VIEW ARDAIS_OWNER.ARD_CONCEPT_GRAPH 
--TABLESPACE OTHER_TBL_TBS
--NOCACHE
--NOLOGGING
--NOPARALLEL
--BUILD IMMEDIATE
--USING INDEX
--TABLESPACE OTHER_IDX_TBS
--REFRESH FORCE
--WITH PRIMARY KEY
--AS 
--SELECT * FROM ARDAIS_OWNER.ARD_CONCEPT_GRAPH@GENREP;

begin
Dbms_repcat.create_snapshot_repobject('ARDAIS_OWNER','ES_SHOPPING_CART_DETAIL','SNAPSHOT',NULL,NULL,'GENUITY_ARDAIS_OWNER');
Dbms_repcat.create_snapshot_repobject('ARDAIS_OWNER','ES_ARDAIS_ACCOUNT','SNAPSHOT',NULL,NULL,'GENUITY_ARDAIS_OWNER');
Dbms_repcat.create_snapshot_repobject('ARDAIS_OWNER','ARD_OBJECTS','SNAPSHOT',NULL,NULL,'GENUITY_ARDAIS_OWNER');
Dbms_repcat.create_snapshot_repobject('ARDAIS_OWNER','ES_ARDAIS_USER','SNAPSHOT',NULL,NULL,'GENUITY_ARDAIS_OWNER');
Dbms_repcat.create_snapshot_repobject('ARDAIS_OWNER','ARD_USER_ACCESS_MODULE','SNAPSHOT',NULL,NULL,'GENUITY_ARDAIS_OWNER');
Dbms_repcat.create_snapshot_repobject('ARDAIS_OWNER','ARD_LOOKUP_ALL','SNAPSHOT',NULL,NULL,'GENUITY_ARDAIS_OWNER');
--Dbms_repcat.create_snapshot_repobject('ARDAIS_OWNER','ARD_CONCEPT_GRAPH','SNAPSHOT',NULL,NULL,'GENUITY_ARDAIS_OWNER');
commit;
end;
/	

-- NOTE:
--  ILTDS_SAMPLE is here because it was its own refresh group bu accident
--  in sonsie patch and now it is back in GEN_TO_LEX_ARDAIS_RFSH_GRP
--  where is belongs
--

-- DESTROY a refresh group, make it cease to exist.
prompt DESTROY refresh group, ARDAIS_OWNER.ILTDS_SAMPLE

BEGIN
  DBMS_REFRESH.DESTROY(NAME => 'ARDAIS_OWNER.ILTDS_SAMPLE');
COMMIT;
END;
/

begin
Dbms_refresh.add('ARDAIS_owner.GEN_TO_LEX_ARDAIS_RFSH_GRP','ES_SHOPPING_CART_DETAIL');
Dbms_refresh.add('ARDAIS_owner.GEN_TO_LEX_ARDAIS_RFSH_GRP','ES_ARDAIS_ACCOUNT');
Dbms_refresh.add('ARDAIS_owner.GEN_TO_LEX_ARDAIS_RFSH_GRP','ARD_OBJECTS');
Dbms_refresh.add('ARDAIS_owner.GEN_TO_LEX_ARDAIS_RFSH_GRP','ES_ARDAIS_USER');
Dbms_refresh.add('ARDAIS_owner.GEN_TO_LEX_ARDAIS_RFSH_GRP','ARD_USER_ACCESS_MODULE');
Dbms_refresh.add('ARDAIS_owner.GEN_TO_LEX_ARDAIS_RFSH_GRP','ARD_LOOKUP_ALL');
--Dbms_refresh.add('ARDAIS_owner.GEN_TO_LEX_ARDAIS_RFSH_GRP','ARD_CONCEPT_GRAPH');
Dbms_refresh.add('ARDAIS_owner.GEN_TO_LEX_ARDAIS_RFSH_GRP','ARDAIS_OWNER.ILTDS_SAMPLE');
commit;
end;
/

set linesize 200
col OWNER format a12
col rname  format a26
SELECT owner, NAME, TYPE, rname 
FROM DBA_REFRESH_CHILDREN 
where NAME in('ES_SHOPPING_CART_DETAIL','ES_ARDAIS_ACCOUNT','ARD_OBJECTS',
'ES_ARDAIS_USER','ARD_USER_ACCESS_MODULE','ARD_LOOKUP_ALL',
'ARD_USER_ACCESS','ARD_WORKGROUP','ARD_WORKGROUP_OBJECTS','ILTDS_SAMPLE')
/


spool off
