spool step5_rem_obj_master_genprod.log

begin
Dbms_repcat.drop_master_repobject('ARDAIS_OWNER','ES_SHOPPING_CART_DETAIL','TABLE');
Dbms_repcat.drop_master_repobject('ARDAIS_OWNER','ES_ARDAIS_ACCOUNT','TABLE');
Dbms_repcat.drop_master_repobject('ARDAIS_OWNER','ARD_OBJECTS','TABLE');
Dbms_repcat.drop_master_repobject('ARDAIS_OWNER','ES_ARDAIS_USER','TABLE');
Dbms_repcat.drop_master_repobject('ARDAIS_OWNER','ARD_USER_ACCESS_MODULE','TABLE');
Dbms_repcat.drop_master_repobject('ARDAIS_OWNER','ARD_LOOKUP_ALL','TABLE');
--Dbms_repcat.drop_master_repobject('ARDAIS_OWNER','ARD_CONCEPT_GRAPH','TABLE');
Dbms_repcat.drop_master_repobject('ARDAIS_OWNER','ARD_USER_ACCESS','TABLE');
Dbms_repcat.drop_master_repobject('ARDAIS_OWNER','ARD_WORKGROUP','TABLE');
Dbms_repcat.drop_master_repobject('ARDAIS_OWNER','ARD_WORKGROUP_OBJECTS','TABLE');
commit;
end;
/

DROP SNAPSHOT LOG ON ARDAIS_OWNER.ES_SHOPPING_CART_DETAIL;

DROP SNAPSHOT LOG ON ARDAIS_OWNER.ES_ARDAIS_ACCOUNT;

DROP SNAPSHOT LOG ON ARDAIS_OWNER.ARD_OBJECTS;

DROP SNAPSHOT LOG ON ARDAIS_OWNER.ES_ARDAIS_USER;

DROP SNAPSHOT LOG ON ARDAIS_OWNER.ARD_USER_ACCESS_MODULE;

DROP SNAPSHOT LOG ON ARDAIS_OWNER.ARD_LOOKUP_ALL;

--DROP SNAPSHOT LOG ON ARDAIS_OWNER.ARD_CONCEPT_GRAPH;

-- obsolete tables
DROP MATERIALIZED VIEW LOG ON ARDAIS_OWNER.ARD_USER_ACCESS;

DROP MATERIALIZED VIEW LOG ON ARDAIS_OWNER.ARD_WORKGROUP;

DROP MATERIALIZED VIEW LOG ON ARDAIS_OWNER.ARD_WORKGROUP_OBJECTS;

commit
/

spool off
