set define off;
set echo on;

insert into pdc_lookup values('SAMPLE_INFO', 'CA12597C', 'Slide stain type', '', '', 'ARD_CAP', 'A', 'P', '', '1.54', '', 'stain_type', '1', 'Y', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '19', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12598C', 'Suspension Fluid Medium', '', '', 'ARD_CAP', 'A', 'P', '', '1.54', '', 'suspension_medium', '1', 'Y', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '19', '');
insert into pdc_lookup values('SAMPLE_TYPE', 'CA12603C', 'Coagulated Blood', '', '', 'ARD_CAP', 'A', 'P', '', '1.54', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '19', '');
insert into pdc_lookup values('SAMPLE_TYPE', 'CA12599C', 'Fine Needle Aspirate', '', '', 'ARD_CAP', 'A', 'P', '', '1.54', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '19', '');
insert into pdc_lookup values('SAMPLE_TYPE', 'CA12600C', 'Platelet', '', '', 'ARD_CAP', 'A', 'P', '', '1.54', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '19', '');
insert into pdc_lookup values('SAMPLE_TYPE', 'CA12601C', 'Platelet Poor Plasma', '', '', 'ARD_CAP', 'A', 'P', '', '1.54', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '19', '');
insert into pdc_lookup values('SAMPLE_TYPE', 'CA12602C', 'Platelet Rich Plasma', '', '', 'ARD_CAP', 'A', 'P', '', '1.54', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '19', '');
insert into pdc_lookup values('SAMPLE_TYPE', 'CA12605C', 'Stool', '', '', 'ARD_CAP', 'A', 'P', '', '1.54', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '19', '');
insert into pdc_lookup values('SAMPLE_TYPE', 'CA12606C', 'Tissue Microarray Block', '', '', 'ARD_CAP', 'A', 'P', '', '1.54', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '19', '');
insert into pdc_lookup values('SAMPLE_TYPE', 'CA12607C', 'Tissue Microarray Slide', '', '', 'ARD_CAP', 'A', 'P', '', '1.54', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '19', '');
insert into pdc_lookup values('SAMPLE_TYPE', 'CA12604C', 'Unstained Slide', '', '', 'ARD_CAP', 'A', 'P', '', '1.54', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '19', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12615C', 'SLIDE_STAIN_TYPE_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.54', '', '', '', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '19', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12616C', 'Alcian blue stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.54', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '19', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12617C', 'Diazonium blue stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.54', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '19', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12618C', 'Fontana-Masson stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.54', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '19', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12619C', 'Genta stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.54', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '19', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12620C', 'Giemsa Romanowsky stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.54', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '19', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12621C', 'Goldner trichrome stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.54', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '19', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12622C', 'Hales colloidal iron stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.54', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '19', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12623C', 'Hansel stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.54', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '19', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12624C', 'Hematoxylin and eosin  ~  H and E', '', '', 'ARD_CAP', 'A', 'P', '', '1.54', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '19', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12625C', 'HID stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.54', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '19', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12626C', 'Luxol fast blue stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.54', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '19', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12627C', 'Methylene blue stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.54', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '19', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12628C', 'Movat stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.54', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '19', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12629C', 'Oil red O stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.54', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '19', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12630C', 'Reticulin stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.54', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '19', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12631C', 'Sevier Munger stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.54', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '19', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12632C', 'Silver stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.54', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '19', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12633C', 'Sirius red stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.54', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '19', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12634C', 'Solochrome cyanine stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.54', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '19', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12635C', 'Special stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.54', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '19', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12636C', 'Thionin stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.54', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '19', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12637C', 'Toluidine blue stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.54', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '19', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12638C', 'Trichrome - Masson stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.54', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '19', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12639C', 'Trichrome - Masson stain, modified', '', '', 'ARD_CAP', 'A', 'P', '', '1.54', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '19', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12640C', 'Van Gieson stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.54', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '19', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12641C', 'Warthin-Starry stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.54', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '19', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12642C', 'Wright stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.54', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '19', '');
insert into pdc_lookup values('SLIDE_STAIN_TYPE', 'CA12643C', 'Other slide stain', '', '', 'ARD_CAP', 'A', 'P', '', '1.54', '', '', '', '', '', 'Y', 'Value', '', '', '', '', '', '', '', '', '19', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12608C', 'SUSPENSION_MEDIUM_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.54', '', '', '', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '19', '');
insert into pdc_lookup values('SUSPENSION_MEDIUM', 'CA12609C', 'Cytospin fluid', '', '', 'ARD_CAP', 'A', 'P', '', '1.54', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '19', '');
insert into pdc_lookup values('SUSPENSION_MEDIUM', 'CA12610C', 'Cell dissociation fluid', '', '', 'ARD_CAP', 'A', 'P', '', '1.54', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '19', '');
insert into pdc_lookup values('SUSPENSION_MEDIUM', 'CA12611C', 'Phosphate buffered saline', '', '', 'ARD_CAP', 'A', 'P', '', '1.54', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '19', '');
insert into pdc_lookup values('SUSPENSION_MEDIUM', 'CA12612C', 'Saline', '', '', 'ARD_CAP', 'A', 'P', '', '1.54', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '19', '');
insert into pdc_lookup values('SUSPENSION_MEDIUM', 'CA12613C', 'Formalin suspension medium', '', '', 'ARD_CAP', 'A', 'P', '', '1.54', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '19', '');
insert into pdc_lookup values('SUSPENSION_MEDIUM', 'CA12614C', 'Other suspension fluid medium', '', '', 'ARD_CAP', 'A', 'P', '', '1.54', '', '', '', '', '', 'Y', 'Value', '', '', '', '', '', '', '', '', '19', '');
commit;
