
REM ************************************************************************************
REM * Generated KnowledgeCapture database schema for DET version 33
REM ************************************************************************************

REM ************************************************************************************
REM * CREATE TABLE for category pt_info (conventional)
REM ************************************************************************************
CREATE TABLE CIR_PT_INFO (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,MRN VARCHAR2(4000)
,MRN_CUI VARCHAR2(30)
,OTHER_MRN VARCHAR2(4000)
,OTHER_MRN_CUI VARCHAR2(30)
,PARTICIPANT_ID VARCHAR2(4000)
,PARTICIPANT_ID_CUI VARCHAR2(30)
,PT_ID VARCHAR2(4000)
,PT_ID_CUI VARCHAR2(30)
,LAST_NAME VARCHAR2(4000)
,LAST_NAME_CUI VARCHAR2(30)
,MIDDLE_INITIAL VARCHAR2(4000)
,MIDDLE_INITIAL_CUI VARCHAR2(30)
,FIRST_NAME VARCHAR2(4000)
,FIRST_NAME_CUI VARCHAR2(30)
,SSN VARCHAR2(4000)
,SSN_CUI VARCHAR2(30)
,FORM_COMPLETED_BY VARCHAR2(4000)
,FORM_COMPLETED_BY_CUI VARCHAR2(30)
,DONOR_NOTE VARCHAR2(4000)
,DONOR_NOTE_CUI VARCHAR2(30)
,DONOR_CAP_FLDS_COMP_CUI VARCHAR2(30)
,DONOR_SOURCE_CUI VARCHAR2(30)
,GENDER_CUI VARCHAR2(30)
,OTHER_GENDER VARCHAR2(200)
,ETHNICITY_CUI VARCHAR2(30)
,DATE_BIRTH DATE
,DATE_BIRTH_CUI VARCHAR2(30)
,YEAR_BIRTH NUMBER
,YEAR_BIRTH_CUI VARCHAR2(30)
,AGE_VISIT NUMBER
,AGE_VISIT_CUI VARCHAR2(30)
,AGE_SURG NUMBER
,AGE_SURG_CUI VARCHAR2(30)
,CURRENT_AGE NUMBER
,CURRENT_AGE_CUI VARCHAR2(30)
,POSTAL_CODE VARCHAR2(4000)
,POSTAL_CODE_CUI VARCHAR2(30)
,GESTATIONAL_AGE NUMBER
,GESTATIONAL_AGE_CUI VARCHAR2(30)
,PT_CONSENTED_CUI VARCHAR2(30)
,DONATE_BLOOD_CUI VARCHAR2(30)
,AGREE_BLOOD_OBTAIN_CUI VARCHAR2(30)
,AGREE_NEEDLE_CUI VARCHAR2(30)
,DONATE_URINE_CUI VARCHAR2(30)
,DONATE_TISSUE_CUI VARCHAR2(30)
,DONATE_SALIVA_CUI VARCHAR2(30)
,DONATE_CSF_CUI VARCHAR2(30)
,DONATE_AMNIOTIC_CUI VARCHAR2(30)
,AGREE_GENE_TEST_CUI VARCHAR2(30)
,GENE_INFO_CUI VARCHAR2(30)
,REVIEW_MED_REC_CUI VARCHAR2(30)
,CONTACT_IN_FUTURE_CUI VARCHAR2(30)
,PERM_PI_CURR_RESE_CUI VARCHAR2(30)
,PERM_PI_FUTU_UNRE_CUI VARCHAR2(30)
,PERM_OTHR_PI_FUTU_CUI VARCHAR2(30)
)
;

ALTER TABLE CIR_PT_INFO ADD CONSTRAINT PK_CIR_PT_INFO PRIMARY KEY (ID);


CREATE TABLE CIR_PT_INFO_MULTI (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,OTHER_DATA_VALUE VARCHAR2(200)
)
;


ALTER TABLE CIR_PT_INFO_MULTI ADD CONSTRAINT PK_CIR_PT_INFO_M PRIMARY KEY (ID);

CREATE INDEX CIR_PT_INFO_I3 ON CIR_PT_INFO_MULTI (FORM_ID)
;

CREATE TABLE CIR_PT_INFO_NOTE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,NOTE VARCHAR2(4000)
)
;


ALTER TABLE CIR_PT_INFO_NOTE ADD CONSTRAINT PK_CIR_PT_INFO_N PRIMARY KEY (ID);

CREATE INDEX CIR_PT_INFO_I5 ON CIR_PT_INFO_NOTE (FORM_ID)
;

REM ************************************************************************************
REM * CREATE TABLE for category problem (conventional)
REM ************************************************************************************
CREATE TABLE CIR_PROBLEM (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DIAGNOSIS_CUI VARCHAR2(30)
,OTHER_DIAGNOSIS VARCHAR2(200)
,AGE_DIAG NUMBER
,AGE_DIAG_CUI VARCHAR2(30)
,CATEGORY_DIS_CUI VARCHAR2(30)
,IF_LUNG_OR_PLEU_INF_CUI VARCHAR2(30)
,TRAU_REQU_OR_INTE_CUI VARCHAR2(30)
)
;

ALTER TABLE CIR_PROBLEM ADD CONSTRAINT PK_CIR_PROBLEM PRIMARY KEY (ID);



CREATE TABLE CIR_PROBLEM_NOTE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,NOTE VARCHAR2(4000)
)
;


ALTER TABLE CIR_PROBLEM_NOTE ADD CONSTRAINT PK_CIR_PROBLEM_N PRIMARY KEY (ID);

CREATE INDEX CIR_PROBLEM_I5 ON CIR_PROBLEM_NOTE (FORM_ID)
;

REM ************************************************************************************
REM * CREATE TABLE for category clin_pres (conventional)
REM ************************************************************************************
CREATE TABLE CIR_CLIN_PRES (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,SYMPTOM_PRIMARY_CUI VARCHAR2(30)
,OTHER_SYMPTOM_PRIMARY VARCHAR2(200)
,CLIN_COMMENTS VARCHAR2(4000)
,CLIN_COMMENTS_CUI VARCHAR2(30)
,HEIGHT NUMBER
,HEIGHT_CUI VARCHAR2(30)
,HEIGHT_INCHES NUMBER
,HEIGHT_INCHES_CUI VARCHAR2(30)
,WEIGHT NUMBER
,WEIGHT_CUI VARCHAR2(30)
,WEIGHT_POUNDS NUMBER
,WEIGHT_POUNDS_CUI VARCHAR2(30)
,WEIG_LOSS_OVER3 NUMBER
,WEIG_LOSS_OVER3_CUI VARCHAR2(30)
,BMI NUMBER
,BMI_CUI VARCHAR2(30)
,BODY_SURF_AREA NUMBER
,BODY_SURF_AREA_CUI VARCHAR2(30)
,BLOO_PRES_SYST NUMBER
,BLOO_PRES_SYST_CUI VARCHAR2(30)
,BLOO_PRES_DIAS NUMBER
,BLOO_PRES_DIAS_CUI VARCHAR2(30)
,PULSE_PRESSURE NUMBER
,PULSE_PRESSURE_CUI VARCHAR2(30)
,PALPATED_PULSE NUMBER
,PALPATED_PULSE_CUI VARCHAR2(30)
,PULSE_OXIMETRY NUMBER
,PULSE_OXIMETRY_CUI VARCHAR2(30)
,WAIST_CIRCUMFERENCE NUMBER
,WAIST_CIRCUMFERENCE_CUI VARCHAR2(30)
,HEENT_CUI VARCHAR2(30)
,CNS_CUI VARCHAR2(30)
,NECK_CUI VARCHAR2(30)
,BREASTS_CUI VARCHAR2(30)
,CARDIOVASCULAR_CUI VARCHAR2(30)
,RESPIRATORY_CUI VARCHAR2(30)
,GASTROINTESTINAL_CUI VARCHAR2(30)
,URINARY_CUI VARCHAR2(30)
,GENITALIA_CUI VARCHAR2(30)
,MUSCULOSKELETAL_CUI VARCHAR2(30)
,NEUROLOGIC_CUI VARCHAR2(30)
,DERMATOLOGIC_CUI VARCHAR2(30)
,HEMA_LYMP_CUI VARCHAR2(30)
,ENDO_META_CUI VARCHAR2(30)
,PSYCHOLOGIC_CUI VARCHAR2(30)
)
;

ALTER TABLE CIR_CLIN_PRES ADD CONSTRAINT PK_CIR_CLIN_PRES PRIMARY KEY (ID);


CREATE TABLE CIR_CLIN_PRES_MULTI (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,OTHER_DATA_VALUE VARCHAR2(200)
)
;


ALTER TABLE CIR_CLIN_PRES_MULTI ADD CONSTRAINT PK_CIR_CLIN_PRES_M PRIMARY KEY (ID);

CREATE INDEX CIR_CLIN_PRES_I3 ON CIR_CLIN_PRES_MULTI (FORM_ID)
;

CREATE TABLE CIR_CLIN_PRES_NOTE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,NOTE VARCHAR2(4000)
)
;


ALTER TABLE CIR_CLIN_PRES_NOTE ADD CONSTRAINT PK_CIR_CLIN_PRES_N PRIMARY KEY (ID);

CREATE INDEX CIR_CLIN_PRES_I5 ON CIR_CLIN_PRES_NOTE (FORM_ID)
;

REM ************************************************************************************
REM * CREATE TABLE for category clin_dis_prog (eav)
REM ************************************************************************************
CREATE TABLE CIR_CLIN_DIS_PROG_EAV (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,DATA_VALUE_DATE DATE
,DATA_VALUE_DATE_DPC VARCHAR2(30)
,DATA_VALUE_CLOB CLOB
,DATA_VALUE_TEXT VARCHAR2(4000)
,DATA_VALUE NUMBER
,OTHER_DATA_VALUE VARCHAR(200)
)
;

ALTER TABLE CIR_CLIN_DIS_PROG_EAV ADD CONSTRAINT PK_CIR_CLIN_DIS_PROG_E PRIMARY KEY (ID);

CREATE INDEX CIR_CLIN_DIS_PROG_I7 ON CIR_CLIN_DIS_PROG_EAV (FORM_ID)
;

CREATE TABLE CIR_CLIN_DIS_PROG_MULTI (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,OTHER_DATA_VALUE VARCHAR2(200)
)
;


ALTER TABLE CIR_CLIN_DIS_PROG_MULTI ADD CONSTRAINT PK_CIR_CLIN_DIS_PROG_M PRIMARY KEY (ID);

CREATE INDEX CIR_CLIN_DIS_PROG_I3 ON CIR_CLIN_DIS_PROG_MULTI (FORM_ID)
;

CREATE TABLE CIR_CLIN_DIS_PROG_NOTE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,NOTE VARCHAR2(4000)
)
;


ALTER TABLE CIR_CLIN_DIS_PROG_NOTE ADD CONSTRAINT PK_CIR_CLIN_DIS_PROG_N PRIMARY KEY (ID);

CREATE INDEX CIR_CLIN_DIS_PROG_I5 ON CIR_CLIN_DIS_PROG_NOTE (FORM_ID)
;

REM ************************************************************************************
REM * CREATE TABLE for category treatment (conventional)
REM ************************************************************************************
CREATE TABLE CIR_TREATMENT (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,ELEC_THER_CUI VARCHAR2(30)
)
;

ALTER TABLE CIR_TREATMENT ADD CONSTRAINT PK_CIR_TREATMENT PRIMARY KEY (ID);


CREATE TABLE CIR_TREATMENT_MULTI (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,OTHER_DATA_VALUE VARCHAR2(200)
)
;


ALTER TABLE CIR_TREATMENT_MULTI ADD CONSTRAINT PK_CIR_TREATMENT_M PRIMARY KEY (ID);

CREATE INDEX CIR_TREATMENT_I3 ON CIR_TREATMENT_MULTI (FORM_ID)
;

CREATE TABLE CIR_TREATMENT_NOTE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,NOTE VARCHAR2(4000)
)
;


ALTER TABLE CIR_TREATMENT_NOTE ADD CONSTRAINT PK_CIR_TREATMENT_N PRIMARY KEY (ID);

CREATE INDEX CIR_TREATMENT_I5 ON CIR_TREATMENT_NOTE (FORM_ID)
;

REM ************************************************************************************
REM * CREATE TABLE for category ancillary_studies (eav)
REM ************************************************************************************
CREATE TABLE CIR_ANCILLARY_STUDIES_EAV (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,DATA_VALUE_DATE DATE
,DATA_VALUE_DATE_DPC VARCHAR2(30)
,DATA_VALUE_CLOB CLOB
,DATA_VALUE_TEXT VARCHAR2(4000)
,DATA_VALUE NUMBER
,OTHER_DATA_VALUE VARCHAR(200)
)
;

ALTER TABLE CIR_ANCILLARY_STUDIES_EAV ADD CONSTRAINT PK_CIR_ANCILLARY_STUDIES_E PRIMARY KEY (ID);

CREATE INDEX CIR_ANCILLARY_STUDIES_I7 ON CIR_ANCILLARY_STUDIES_EAV (FORM_ID)
;


CREATE TABLE CIR_ANCILLARY_STUDIES_NOTE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,NOTE VARCHAR2(4000)
)
;


ALTER TABLE CIR_ANCILLARY_STUDIES_NOTE ADD CONSTRAINT PK_CIR_ANCILLARY_STUDIES_N PRIMARY KEY (ID);

CREATE INDEX CIR_ANCILLARY_STUDIES_I5 ON CIR_ANCILLARY_STUDIES_NOTE (FORM_ID)
;

REM ************************************************************************************
REM * CREATE TABLE for category bloo_gase_arte (eav)
REM ************************************************************************************
CREATE TABLE CIR_BLOO_GASE_ARTE_EAV (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,DATA_VALUE_DATE DATE
,DATA_VALUE_DATE_DPC VARCHAR2(30)
,DATA_VALUE_CLOB CLOB
,DATA_VALUE_TEXT VARCHAR2(4000)
,DATA_VALUE NUMBER
,OTHER_DATA_VALUE VARCHAR(200)
)
;

ALTER TABLE CIR_BLOO_GASE_ARTE_EAV ADD CONSTRAINT PK_CIR_BLOO_GASE_ARTE_E PRIMARY KEY (ID);

CREATE INDEX CIR_BLOO_GASE_ARTE_I7 ON CIR_BLOO_GASE_ARTE_EAV (FORM_ID)
;


CREATE TABLE CIR_BLOO_GASE_ARTE_NOTE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,NOTE VARCHAR2(4000)
)
;


ALTER TABLE CIR_BLOO_GASE_ARTE_NOTE ADD CONSTRAINT PK_CIR_BLOO_GASE_ARTE_N PRIMARY KEY (ID);

CREATE INDEX CIR_BLOO_GASE_ARTE_I5 ON CIR_BLOO_GASE_ARTE_NOTE (FORM_ID)
;

REM ************************************************************************************
REM * CREATE TABLE for category chemistry_survey (eav)
REM ************************************************************************************
CREATE TABLE CIR_CHEMISTRY_SURVEY_EAV (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,DATA_VALUE_DATE DATE
,DATA_VALUE_DATE_DPC VARCHAR2(30)
,DATA_VALUE_CLOB CLOB
,DATA_VALUE_TEXT VARCHAR2(4000)
,DATA_VALUE NUMBER
,OTHER_DATA_VALUE VARCHAR(200)
)
;

ALTER TABLE CIR_CHEMISTRY_SURVEY_EAV ADD CONSTRAINT PK_CIR_CHEMISTRY_SURVEY_E PRIMARY KEY (ID);

CREATE INDEX CIR_CHEMISTRY_SURVEY_I7 ON CIR_CHEMISTRY_SURVEY_EAV (FORM_ID)
;


CREATE TABLE CIR_CHEMISTRY_SURVEY_NOTE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,NOTE VARCHAR2(4000)
)
;


ALTER TABLE CIR_CHEMISTRY_SURVEY_NOTE ADD CONSTRAINT PK_CIR_CHEMISTRY_SURVEY_N PRIMARY KEY (ID);

CREATE INDEX CIR_CHEMISTRY_SURVEY_I5 ON CIR_CHEMISTRY_SURVEY_NOTE (FORM_ID)
;

REM ************************************************************************************
REM * CREATE TABLE for category chemistry (eav)
REM ************************************************************************************
CREATE TABLE CIR_CHEMISTRY_EAV (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,DATA_VALUE_DATE DATE
,DATA_VALUE_DATE_DPC VARCHAR2(30)
,DATA_VALUE_CLOB CLOB
,DATA_VALUE_TEXT VARCHAR2(4000)
,DATA_VALUE NUMBER
,OTHER_DATA_VALUE VARCHAR(200)
)
;

ALTER TABLE CIR_CHEMISTRY_EAV ADD CONSTRAINT PK_CIR_CHEMISTRY_E PRIMARY KEY (ID);

CREATE INDEX CIR_CHEMISTRY_I7 ON CIR_CHEMISTRY_EAV (FORM_ID)
;


CREATE TABLE CIR_CHEMISTRY_NOTE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,NOTE VARCHAR2(4000)
)
;


ALTER TABLE CIR_CHEMISTRY_NOTE ADD CONSTRAINT PK_CIR_CHEMISTRY_N PRIMARY KEY (ID);

CREATE INDEX CIR_CHEMISTRY_I5 ON CIR_CHEMISTRY_NOTE (FORM_ID)
;

REM ************************************************************************************
REM * CREATE TABLE for category chromosome_studies (eav)
REM ************************************************************************************
CREATE TABLE CIR_CHROMOSOME_STUDIES_EAV (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,DATA_VALUE_DATE DATE
,DATA_VALUE_DATE_DPC VARCHAR2(30)
,DATA_VALUE_CLOB CLOB
,DATA_VALUE_TEXT VARCHAR2(4000)
,DATA_VALUE NUMBER
,OTHER_DATA_VALUE VARCHAR(200)
)
;

ALTER TABLE CIR_CHROMOSOME_STUDIES_EAV ADD CONSTRAINT PK_CIR_CHROMOSOME_STUDIES_E PRIMARY KEY (ID);

CREATE INDEX CIR_CHROMOSOME_STUDIES_I7 ON CIR_CHROMOSOME_STUDIES_EAV (FORM_ID)
;

CREATE TABLE CIR_CHROMOSOME_STUDIES_MULTI (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,OTHER_DATA_VALUE VARCHAR2(200)
)
;


ALTER TABLE CIR_CHROMOSOME_STUDIES_MULTI ADD CONSTRAINT PK_CIR_CHROMOSOME_STUDIES_M PRIMARY KEY (ID);

CREATE INDEX CIR_CHROMOSOME_STUDIES_I3 ON CIR_CHROMOSOME_STUDIES_MULTI (FORM_ID)
;

CREATE TABLE CIR_CHROMOSOME_STUDIES_NOTE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,NOTE VARCHAR2(4000)
)
;


ALTER TABLE CIR_CHROMOSOME_STUDIES_NOTE ADD CONSTRAINT PK_CIR_CHROMOSOME_STUDIES_N PRIMARY KEY (ID);

CREATE INDEX CIR_CHROMOSOME_STUDIES_I5 ON CIR_CHROMOSOME_STUDIES_NOTE (FORM_ID)
;

REM ************************************************************************************
REM * CREATE TABLE for category coagulation (eav)
REM ************************************************************************************
CREATE TABLE CIR_COAGULATION_EAV (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,DATA_VALUE_DATE DATE
,DATA_VALUE_DATE_DPC VARCHAR2(30)
,DATA_VALUE_CLOB CLOB
,DATA_VALUE_TEXT VARCHAR2(4000)
,DATA_VALUE NUMBER
,OTHER_DATA_VALUE VARCHAR(200)
)
;

ALTER TABLE CIR_COAGULATION_EAV ADD CONSTRAINT PK_CIR_COAGULATION_E PRIMARY KEY (ID);

CREATE INDEX CIR_COAGULATION_I7 ON CIR_COAGULATION_EAV (FORM_ID)
;


CREATE TABLE CIR_COAGULATION_NOTE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,NOTE VARCHAR2(4000)
)
;


ALTER TABLE CIR_COAGULATION_NOTE ADD CONSTRAINT PK_CIR_COAGULATION_N PRIMARY KEY (ID);

CREATE INDEX CIR_COAGULATION_I5 ON CIR_COAGULATION_NOTE (FORM_ID)
;

REM ************************************************************************************
REM * CREATE TABLE for category cytology (eav)
REM ************************************************************************************
CREATE TABLE CIR_CYTOLOGY_EAV (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,DATA_VALUE_DATE DATE
,DATA_VALUE_DATE_DPC VARCHAR2(30)
,DATA_VALUE_CLOB CLOB
,DATA_VALUE_TEXT VARCHAR2(4000)
,DATA_VALUE NUMBER
,OTHER_DATA_VALUE VARCHAR(200)
)
;

ALTER TABLE CIR_CYTOLOGY_EAV ADD CONSTRAINT PK_CIR_CYTOLOGY_E PRIMARY KEY (ID);

CREATE INDEX CIR_CYTOLOGY_I7 ON CIR_CYTOLOGY_EAV (FORM_ID)
;


CREATE TABLE CIR_CYTOLOGY_NOTE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,NOTE VARCHAR2(4000)
)
;


ALTER TABLE CIR_CYTOLOGY_NOTE ADD CONSTRAINT PK_CIR_CYTOLOGY_N PRIMARY KEY (ID);

CREATE INDEX CIR_CYTOLOGY_I5 ON CIR_CYTOLOGY_NOTE (FORM_ID)
;


CREATE TABLE CIR_GENE_STUDIES_MULTI (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,OTHER_DATA_VALUE VARCHAR2(200)
)
;


ALTER TABLE CIR_GENE_STUDIES_MULTI ADD CONSTRAINT PK_CIR_GENE_STUDIES_M PRIMARY KEY (ID);

CREATE INDEX CIR_GENE_STUDIES_I3 ON CIR_GENE_STUDIES_MULTI (FORM_ID)
;

CREATE TABLE CIR_GENE_STUDIES_NOTE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,NOTE VARCHAR2(4000)
)
;


ALTER TABLE CIR_GENE_STUDIES_NOTE ADD CONSTRAINT PK_CIR_GENE_STUDIES_N PRIMARY KEY (ID);

CREATE INDEX CIR_GENE_STUDIES_I5 ON CIR_GENE_STUDIES_NOTE (FORM_ID)
;

REM ************************************************************************************
REM * CREATE TABLE for category hematology_survey (eav)
REM ************************************************************************************
CREATE TABLE CIR_HEMATOLOGY_SURVEY_EAV (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,DATA_VALUE_DATE DATE
,DATA_VALUE_DATE_DPC VARCHAR2(30)
,DATA_VALUE_CLOB CLOB
,DATA_VALUE_TEXT VARCHAR2(4000)
,DATA_VALUE NUMBER
,OTHER_DATA_VALUE VARCHAR(200)
)
;

ALTER TABLE CIR_HEMATOLOGY_SURVEY_EAV ADD CONSTRAINT PK_CIR_HEMATOLOGY_SURVEY_E PRIMARY KEY (ID);

CREATE INDEX CIR_HEMATOLOGY_SURVEY_I7 ON CIR_HEMATOLOGY_SURVEY_EAV (FORM_ID)
;


CREATE TABLE CIR_HEMATOLOGY_SURVEY_NOTE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,NOTE VARCHAR2(4000)
)
;


ALTER TABLE CIR_HEMATOLOGY_SURVEY_NOTE ADD CONSTRAINT PK_CIR_HEMATOLOGY_SURVEY_N PRIMARY KEY (ID);

CREATE INDEX CIR_HEMATOLOGY_SURVEY_I5 ON CIR_HEMATOLOGY_SURVEY_NOTE (FORM_ID)
;

REM ************************************************************************************
REM * CREATE TABLE for category hematology (eav)
REM ************************************************************************************
CREATE TABLE CIR_HEMATOLOGY_EAV (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,DATA_VALUE_DATE DATE
,DATA_VALUE_DATE_DPC VARCHAR2(30)
,DATA_VALUE_CLOB CLOB
,DATA_VALUE_TEXT VARCHAR2(4000)
,DATA_VALUE NUMBER
,OTHER_DATA_VALUE VARCHAR(200)
)
;

ALTER TABLE CIR_HEMATOLOGY_EAV ADD CONSTRAINT PK_CIR_HEMATOLOGY_E PRIMARY KEY (ID);

CREATE INDEX CIR_HEMATOLOGY_I7 ON CIR_HEMATOLOGY_EAV (FORM_ID)
;


CREATE TABLE CIR_HEMATOLOGY_NOTE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,NOTE VARCHAR2(4000)
)
;


ALTER TABLE CIR_HEMATOLOGY_NOTE ADD CONSTRAINT PK_CIR_HEMATOLOGY_N PRIMARY KEY (ID);

CREATE INDEX CIR_HEMATOLOGY_I5 ON CIR_HEMATOLOGY_NOTE (FORM_ID)
;

REM ************************************************************************************
REM * CREATE TABLE for category histochemistry (eav)
REM ************************************************************************************
CREATE TABLE CIR_HISTOCHEMISTRY_EAV (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,DATA_VALUE_DATE DATE
,DATA_VALUE_DATE_DPC VARCHAR2(30)
,DATA_VALUE_CLOB CLOB
,DATA_VALUE_TEXT VARCHAR2(4000)
,DATA_VALUE NUMBER
,OTHER_DATA_VALUE VARCHAR(200)
)
;

ALTER TABLE CIR_HISTOCHEMISTRY_EAV ADD CONSTRAINT PK_CIR_HISTOCHEMISTRY_E PRIMARY KEY (ID);

CREATE INDEX CIR_HISTOCHEMISTRY_I7 ON CIR_HISTOCHEMISTRY_EAV (FORM_ID)
;


CREATE TABLE CIR_HISTOCHEMISTRY_NOTE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,NOTE VARCHAR2(4000)
)
;


ALTER TABLE CIR_HISTOCHEMISTRY_NOTE ADD CONSTRAINT PK_CIR_HISTOCHEMISTRY_N PRIMARY KEY (ID);

CREATE INDEX CIR_HISTOCHEMISTRY_I5 ON CIR_HISTOCHEMISTRY_NOTE (FORM_ID)
;

REM ************************************************************************************
REM * CREATE TABLE for category immunohistochemistry (eav)
REM ************************************************************************************
CREATE TABLE CIR_IMMUNOHISTOCHEMISTRY_EAV (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,DATA_VALUE_DATE DATE
,DATA_VALUE_DATE_DPC VARCHAR2(30)
,DATA_VALUE_CLOB CLOB
,DATA_VALUE_TEXT VARCHAR2(4000)
,DATA_VALUE NUMBER
,OTHER_DATA_VALUE VARCHAR(200)
)
;

ALTER TABLE CIR_IMMUNOHISTOCHEMISTRY_EAV ADD CONSTRAINT PK_CIR_IMMUNOHISTOCHEMISTRY_E PRIMARY KEY (ID);

CREATE INDEX CIR_IMMUNOHISTOCHEMISTRY_I7 ON CIR_IMMUNOHISTOCHEMISTRY_EAV (FORM_ID)
;


CREATE TABLE CIR_IMMUNOHISTOCHEMISTRY_NOTE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,NOTE VARCHAR2(4000)
)
;


ALTER TABLE CIR_IMMUNOHISTOCHEMISTRY_NOTE ADD CONSTRAINT PK_CIR_IMMUNOHISTOCHEMISTRY_N PRIMARY KEY (ID);

CREATE INDEX CIR_IMMUNOHISTOCHEMISTRY_I5 ON CIR_IMMUNOHISTOCHEMISTRY_NOTE (FORM_ID)
;

REM ************************************************************************************
REM * CREATE TABLE for category immunophenotype (eav)
REM ************************************************************************************
CREATE TABLE CIR_IMMUNOPHENOTYPE_EAV (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,DATA_VALUE_DATE DATE
,DATA_VALUE_DATE_DPC VARCHAR2(30)
,DATA_VALUE_CLOB CLOB
,DATA_VALUE_TEXT VARCHAR2(4000)
,DATA_VALUE NUMBER
,OTHER_DATA_VALUE VARCHAR(200)
)
;

ALTER TABLE CIR_IMMUNOPHENOTYPE_EAV ADD CONSTRAINT PK_CIR_IMMUNOPHENOTYPE_E PRIMARY KEY (ID);

CREATE INDEX CIR_IMMUNOPHENOTYPE_I7 ON CIR_IMMUNOPHENOTYPE_EAV (FORM_ID)
;


CREATE TABLE CIR_IMMUNOPHENOTYPE_NOTE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,NOTE VARCHAR2(4000)
)
;


ALTER TABLE CIR_IMMUNOPHENOTYPE_NOTE ADD CONSTRAINT PK_CIR_IMMUNOPHENOTYPE_N PRIMARY KEY (ID);

CREATE INDEX CIR_IMMUNOPHENOTYPE_I5 ON CIR_IMMUNOPHENOTYPE_NOTE (FORM_ID)
;

REM ************************************************************************************
REM * CREATE TABLE for category microbiology (eav)
REM ************************************************************************************
CREATE TABLE CIR_MICROBIOLOGY_EAV (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,DATA_VALUE_DATE DATE
,DATA_VALUE_DATE_DPC VARCHAR2(30)
,DATA_VALUE_CLOB CLOB
,DATA_VALUE_TEXT VARCHAR2(4000)
,DATA_VALUE NUMBER
,OTHER_DATA_VALUE VARCHAR(200)
)
;

ALTER TABLE CIR_MICROBIOLOGY_EAV ADD CONSTRAINT PK_CIR_MICROBIOLOGY_E PRIMARY KEY (ID);

CREATE INDEX CIR_MICROBIOLOGY_I7 ON CIR_MICROBIOLOGY_EAV (FORM_ID)
;


CREATE TABLE CIR_MICROBIOLOGY_NOTE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,NOTE VARCHAR2(4000)
)
;


ALTER TABLE CIR_MICROBIOLOGY_NOTE ADD CONSTRAINT PK_CIR_MICROBIOLOGY_N PRIMARY KEY (ID);

CREATE INDEX CIR_MICROBIOLOGY_I5 ON CIR_MICROBIOLOGY_NOTE (FORM_ID)
;

REM ************************************************************************************
REM * CREATE TABLE for category stains (eav)
REM ************************************************************************************
CREATE TABLE CIR_STAINS_EAV (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,DATA_VALUE_DATE DATE
,DATA_VALUE_DATE_DPC VARCHAR2(30)
,DATA_VALUE_CLOB CLOB
,DATA_VALUE_TEXT VARCHAR2(4000)
,DATA_VALUE NUMBER
,OTHER_DATA_VALUE VARCHAR(200)
)
;

ALTER TABLE CIR_STAINS_EAV ADD CONSTRAINT PK_CIR_STAINS_E PRIMARY KEY (ID);

CREATE INDEX CIR_STAINS_I7 ON CIR_STAINS_EAV (FORM_ID)
;


CREATE TABLE CIR_STAINS_NOTE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,NOTE VARCHAR2(4000)
)
;


ALTER TABLE CIR_STAINS_NOTE ADD CONSTRAINT PK_CIR_STAINS_N PRIMARY KEY (ID);

CREATE INDEX CIR_STAINS_I5 ON CIR_STAINS_NOTE (FORM_ID)
;

REM ************************************************************************************
REM * CREATE TABLE for category urinalysis (eav)
REM ************************************************************************************
CREATE TABLE CIR_URINALYSIS_EAV (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,DATA_VALUE_DATE DATE
,DATA_VALUE_DATE_DPC VARCHAR2(30)
,DATA_VALUE_CLOB CLOB
,DATA_VALUE_TEXT VARCHAR2(4000)
,DATA_VALUE NUMBER
,OTHER_DATA_VALUE VARCHAR(200)
)
;

ALTER TABLE CIR_URINALYSIS_EAV ADD CONSTRAINT PK_CIR_URINALYSIS_E PRIMARY KEY (ID);

CREATE INDEX CIR_URINALYSIS_I7 ON CIR_URINALYSIS_EAV (FORM_ID)
;

CREATE TABLE CIR_URINALYSIS_MULTI (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,OTHER_DATA_VALUE VARCHAR2(200)
)
;


ALTER TABLE CIR_URINALYSIS_MULTI ADD CONSTRAINT PK_CIR_URINALYSIS_M PRIMARY KEY (ID);

CREATE INDEX CIR_URINALYSIS_I3 ON CIR_URINALYSIS_MULTI (FORM_ID)
;

CREATE TABLE CIR_URINALYSIS_NOTE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,NOTE VARCHAR2(4000)
)
;


ALTER TABLE CIR_URINALYSIS_NOTE ADD CONSTRAINT PK_CIR_URINALYSIS_N PRIMARY KEY (ID);

CREATE INDEX CIR_URINALYSIS_I5 ON CIR_URINALYSIS_NOTE (FORM_ID)
;

REM ************************************************************************************
REM * CREATE TABLE for category imaging_studies (eav)
REM ************************************************************************************
CREATE TABLE CIR_IMAGING_STUDIES_EAV (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,DATA_VALUE_DATE DATE
,DATA_VALUE_DATE_DPC VARCHAR2(30)
,DATA_VALUE_CLOB CLOB
,DATA_VALUE_TEXT VARCHAR2(4000)
,DATA_VALUE NUMBER
,OTHER_DATA_VALUE VARCHAR(200)
)
;

ALTER TABLE CIR_IMAGING_STUDIES_EAV ADD CONSTRAINT PK_CIR_IMAGING_STUDIES_E PRIMARY KEY (ID);

CREATE INDEX CIR_IMAGING_STUDIES_I7 ON CIR_IMAGING_STUDIES_EAV (FORM_ID)
;

CREATE TABLE CIR_IMAGING_STUDIES_MULTI (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,OTHER_DATA_VALUE VARCHAR2(200)
)
;


ALTER TABLE CIR_IMAGING_STUDIES_MULTI ADD CONSTRAINT PK_CIR_IMAGING_STUDIES_M PRIMARY KEY (ID);

CREATE INDEX CIR_IMAGING_STUDIES_I3 ON CIR_IMAGING_STUDIES_MULTI (FORM_ID)
;

CREATE TABLE CIR_IMAGING_STUDIES_NOTE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,NOTE VARCHAR2(4000)
)
;


ALTER TABLE CIR_IMAGING_STUDIES_NOTE ADD CONSTRAINT PK_CIR_IMAGING_STUDIES_N PRIMARY KEY (ID);

CREATE INDEX CIR_IMAGING_STUDIES_I5 ON CIR_IMAGING_STUDIES_NOTE (FORM_ID)
;

REM ************************************************************************************
REM * CREATE TABLE for category skin_tests (eav)
REM ************************************************************************************
CREATE TABLE CIR_SKIN_TESTS_EAV (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,DATA_VALUE_DATE DATE
,DATA_VALUE_DATE_DPC VARCHAR2(30)
,DATA_VALUE_CLOB CLOB
,DATA_VALUE_TEXT VARCHAR2(4000)
,DATA_VALUE NUMBER
,OTHER_DATA_VALUE VARCHAR(200)
)
;

ALTER TABLE CIR_SKIN_TESTS_EAV ADD CONSTRAINT PK_CIR_SKIN_TESTS_E PRIMARY KEY (ID);

CREATE INDEX CIR_SKIN_TESTS_I7 ON CIR_SKIN_TESTS_EAV (FORM_ID)
;


CREATE TABLE CIR_SKIN_TESTS_NOTE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,NOTE VARCHAR2(4000)
)
;


ALTER TABLE CIR_SKIN_TESTS_NOTE ADD CONSTRAINT PK_CIR_SKIN_TESTS_N PRIMARY KEY (ID);

CREATE INDEX CIR_SKIN_TESTS_I5 ON CIR_SKIN_TESTS_NOTE (FORM_ID)
;

REM ************************************************************************************
REM * CREATE TABLE for category surgical_studies (eav)
REM ************************************************************************************
CREATE TABLE CIR_SURGICAL_STUDIES_EAV (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,DATA_VALUE_DATE DATE
,DATA_VALUE_DATE_DPC VARCHAR2(30)
,DATA_VALUE_CLOB CLOB
,DATA_VALUE_TEXT VARCHAR2(4000)
,DATA_VALUE NUMBER
,OTHER_DATA_VALUE VARCHAR(200)
)
;

ALTER TABLE CIR_SURGICAL_STUDIES_EAV ADD CONSTRAINT PK_CIR_SURGICAL_STUDIES_E PRIMARY KEY (ID);

CREATE INDEX CIR_SURGICAL_STUDIES_I7 ON CIR_SURGICAL_STUDIES_EAV (FORM_ID)
;

CREATE TABLE CIR_SURGICAL_STUDIES_MULTI (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,OTHER_DATA_VALUE VARCHAR2(200)
)
;


ALTER TABLE CIR_SURGICAL_STUDIES_MULTI ADD CONSTRAINT PK_CIR_SURGICAL_STUDIES_M PRIMARY KEY (ID);

CREATE INDEX CIR_SURGICAL_STUDIES_I3 ON CIR_SURGICAL_STUDIES_MULTI (FORM_ID)
;

CREATE TABLE CIR_SURGICAL_STUDIES_NOTE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,NOTE VARCHAR2(4000)
)
;


ALTER TABLE CIR_SURGICAL_STUDIES_NOTE ADD CONSTRAINT PK_CIR_SURGICAL_STUDIES_N PRIMARY KEY (ID);

CREATE INDEX CIR_SURGICAL_STUDIES_I5 ON CIR_SURGICAL_STUDIES_NOTE (FORM_ID)
;

REM ************************************************************************************
REM * CREATE TABLE for category past_medi_hist (conventional)
REM ************************************************************************************
CREATE TABLE CIR_PAST_MEDI_HIST (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,ALC_DRINK_PER_DAY_CUI VARCHAR2(30)
,TOBA_USE_INDI_CUI VARCHAR2(30)
,BORN_PREMATURELY_CUI VARCHAR2(30)
,CANCER_INDICATOR_CUI VARCHAR2(30)
,DIAB_MELL_INDI_CUI VARCHAR2(30)
,HYPE_INDI_CUI VARCHAR2(30)
,CERE_HIST_CUI VARCHAR2(30)
,RENA_INSU_HIST_CUI VARCHAR2(30)
,MULT_BIRTH_CUI VARCHAR2(30)
,GRAVIDA NUMBER
,GRAVIDA_CUI VARCHAR2(30)
,PARA NUMBER
,PARA_CUI VARCHAR2(30)
,AGE_FIRS_PREG NUMBER
,AGE_FIRS_PREG_CUI VARCHAR2(30)
,PREGNANT_NOW_CUI VARCHAR2(30)
,LACTATING_NOW_CUI VARCHAR2(30)
,AGE_MENA NUMBER
,AGE_MENA_CUI VARCHAR2(30)
,AGE_MENO NUMBER
,AGE_MENO_CUI VARCHAR2(30)
,LASTMENS_FIRSTDAY DATE
,LASTMENS_FIRSTDAY_CUI VARCHAR2(30)
,DAYS_SIN_LAST_MENS NUMBER
,DAYS_SIN_LAST_MENS_CUI VARCHAR2(30)
,DAYS_BETW_PERI NUMBER
,DAYS_BETW_PERI_CUI VARCHAR2(30)
,LENG_REPR_LIFE NUMBER
,LENG_REPR_LIFE_CUI VARCHAR2(30)
,HORM_CONT_USE_CUI VARCHAR2(30)
,HORM_REPL_THER_CUI VARCHAR2(30)
,EXERCISE_LEVEL_CUI VARCHAR2(30)
,CHEMO_HIST_CUI VARCHAR2(30)
,RADIATION_HIST_CUI VARCHAR2(30)
)
;

ALTER TABLE CIR_PAST_MEDI_HIST ADD CONSTRAINT PK_CIR_PAST_MEDI_HIST PRIMARY KEY (ID);


CREATE TABLE CIR_PAST_MEDI_HIST_MULTI (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,OTHER_DATA_VALUE VARCHAR2(200)
)
;


ALTER TABLE CIR_PAST_MEDI_HIST_MULTI ADD CONSTRAINT PK_CIR_PAST_MEDI_HIST_M PRIMARY KEY (ID);

CREATE INDEX CIR_PAST_MEDI_HIST_I3 ON CIR_PAST_MEDI_HIST_MULTI (FORM_ID)
;

CREATE TABLE CIR_PAST_MEDI_HIST_NOTE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,NOTE VARCHAR2(4000)
)
;


ALTER TABLE CIR_PAST_MEDI_HIST_NOTE ADD CONSTRAINT PK_CIR_PAST_MEDI_HIST_N PRIMARY KEY (ID);

CREATE INDEX CIR_PAST_MEDI_HIST_I5 ON CIR_PAST_MEDI_HIST_NOTE (FORM_ID)
;

REM ************************************************************************************
REM * CREATE TABLE for category hospitalization_info (conventional)
REM ************************************************************************************
CREATE TABLE CIR_HOSPITALIZATION_INFO (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,HOSPITAL VARCHAR2(4000)
,HOSPITAL_CUI VARCHAR2(30)
,HOSPITAL_POSTAL_CODE VARCHAR2(4000)
,HOSPITAL_POSTAL_CODE_CUI VARCHAR2(30)
,DATE_ADM DATE
,DATE_ADM_CUI VARCHAR2(30)
,DATE_DISCH DATE
,DATE_DISCH_CUI VARCHAR2(30)
,STATUS_DISCH_CUI VARCHAR2(30)
,STAT30_DAYS_AFTE_CUI VARCHAR2(30)
,LENGTH_STAY NUMBER
,LENGTH_STAY_CUI VARCHAR2(30)
,TIME_SINC_SURG_TREAT NUMBER
,TIME_SINC_SURG_TREAT_CUI VARCHAR2(30)
,CHEST_TUBE_IND_CUI VARCHAR2(30)
,DISPOSITION_CUI VARCHAR2(30)
,OTHER_DISPOSITION VARCHAR2(200)
,MEDICATIONS_CUI VARCHAR2(30)
,PAIN_SCORE_CUI VARCHAR2(30)
)
;

ALTER TABLE CIR_HOSPITALIZATION_INFO ADD CONSTRAINT PK_CIR_HOSPITALIZATION_INFO PRIMARY KEY (ID);


CREATE TABLE CIR_HOSPITALIZATION_INFO_MULTI (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,OTHER_DATA_VALUE VARCHAR2(200)
)
;


ALTER TABLE CIR_HOSPITALIZATION_INFO_MULTI ADD CONSTRAINT PK_CIR_HOSPITALIZATION_INFO_M PRIMARY KEY (ID);

CREATE INDEX CIR_HOSPITALIZATION_INFO_I3 ON CIR_HOSPITALIZATION_INFO_MULTI (FORM_ID)
;

CREATE TABLE CIR_HOSPITALIZATION_INFO_NOTE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,NOTE VARCHAR2(4000)
)
;


ALTER TABLE CIR_HOSPITALIZATION_INFO_NOTE ADD CONSTRAINT PK_CIR_HOSPITALIZATION_INFO_N PRIMARY KEY (ID);

CREATE INDEX CIR_HOSPITALIZATION_INFO_I5 ON CIR_HOSPITALIZATION_INFO_NOTE (FORM_ID)
;

REM ************************************************************************************
REM * CREATE TABLE for category case_info (conventional)
REM ************************************************************************************
CREATE TABLE CIR_CASE_INFO (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,CASE_ID VARCHAR2(4000)
,CASE_ID_CUI VARCHAR2(30)
,NUMBER_CASE VARCHAR2(4000)
,NUMBER_CASE_CUI VARCHAR2(30)
,DATE_SURG DATE
,DATE_SURG_CUI VARCHAR2(30)
,CASE_DX_CUI VARCHAR2(30)
,OTHER_CASE_DX VARCHAR2(200)
,SURGEON VARCHAR2(4000)
,SURGEON_CUI VARCHAR2(30)
,BLOOD_DRAWN_CUI VARCHAR2(30)
,PERI_TRAN NUMBER
,PERI_TRAN_CUI VARCHAR2(30)
,SPEC_NAME VARCHAR2(4000)
,SPEC_NAME_CUI VARCHAR2(30)
,NODE_POST_OP_CUI VARCHAR2(30)
,NODE_INTRA_OP_CUI VARCHAR2(30)
,PRIMARY_STS_PROC_CUI VARCHAR2(30)
,OTHER_PRIMARY_STS_PROC VARCHAR2(200)
,ASA_CLASS_CUI VARCHAR2(30)
,ISCHEMIC_TIME NUMBER
,ISCHEMIC_TIME_CUI VARCHAR2(30)
,TIME_PT_ENTE_OR_HOUR NUMBER
,TIME_PT_ENTE_OR_HOUR_CUI VARCHAR2(30)
,TIME_PT_ENTE_OR_MIN NUMBER
,TIME_PT_ENTE_OR_MIN_CUI VARCHAR2(30)
,TIME_SKIN_INCI_STAR NUMBER
,TIME_SKIN_INCI_STAR_CUI VARCHAR2(30)
,TIME_SKIN_INCI_STA NUMBER
,TIME_SKIN_INCI_STA_CUI VARCHAR2(30)
,TIME_SKIN_INCI_STOP NUMBER
,TIME_SKIN_INCI_STOP_CUI VARCHAR2(30)
,TIME_SKIN_INCI_STO NUMBER
,TIME_SKIN_INCI_STO_CUI VARCHAR2(30)
,TIME_PT_EXIT_OR_HOUR NUMBER
,TIME_PT_EXIT_OR_HOUR_CUI VARCHAR2(30)
,TIME_PT_EXITS_OR_MIN NUMBER
,TIME_PT_EXITS_OR_MIN_CUI VARCHAR2(30)
,MULTIDAY_OPERATION_CUI VARCHAR2(30)
,STATUS_OPERATION_CUI VARCHAR2(30)
,REOPERATION_CUI VARCHAR2(30)
,BLOO_TRAN_INTR_OP_CUI VARCHAR2(30)
,CASE_COMMENT CLOB
,CASE_COMMENT_CUI VARCHAR2(30)
,CASE_INFORMATION_CUI VARCHAR2(30)
,OTHER_CASE_INFORMATION VARCHAR2(200)
,REPORT_SURG_PATH_CUI VARCHAR2(30)
,RPT_SURG_PATH_COMP_CUI VARCHAR2(30)
)
;

ALTER TABLE CIR_CASE_INFO ADD CONSTRAINT PK_CIR_CASE_INFO PRIMARY KEY (ID);


CREATE TABLE CIR_CASE_INFO_MULTI (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,OTHER_DATA_VALUE VARCHAR2(200)
)
;


ALTER TABLE CIR_CASE_INFO_MULTI ADD CONSTRAINT PK_CIR_CASE_INFO_M PRIMARY KEY (ID);

CREATE INDEX CIR_CASE_INFO_I3 ON CIR_CASE_INFO_MULTI (FORM_ID)
;

CREATE TABLE CIR_CASE_INFO_NOTE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,NOTE VARCHAR2(4000)
)
;


ALTER TABLE CIR_CASE_INFO_NOTE ADD CONSTRAINT PK_CIR_CASE_INFO_N PRIMARY KEY (ID);

CREATE INDEX CIR_CASE_INFO_I5 ON CIR_CASE_INFO_NOTE (FORM_ID)
;

REM ************************************************************************************
REM * CREATE TABLE for category sample_info (conventional)
REM ************************************************************************************
CREATE TABLE CIR_SAMPLE_INFO (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,A260_A280_RATIO NUMBER
,A260_A280_RATIO_CUI VARCHAR2(30)
,BLADDER_TUMOR_GRADE_CUI VARCHAR2(30)
,BLOOD_TUBE_PLMI_CUI VARCHAR2(30)
,OTHER_BLOOD_TUBE_PLMI VARCHAR2(200)
,BLOOD_SAMPLE_SOURCE_CUI VARCHAR2(30)
,BLOOD_TUBE_CRI_CUI VARCHAR2(30)
,OTHER_BLOOD_TUBE_CRI VARCHAR2(200)
,BUFFER_TYPE_CUI VARCHAR2(30)
,OTHER_BUFFER_TYPE VARCHAR2(200)
,CELLS_PER_ML NUMBER
,CELLS_PER_ML_CUI VARCHAR2(30)
,CELL_TYPE_CUI VARCHAR2(30)
,OTHER_CELL_TYPE VARCHAR2(200)
,COLLECTION_FORMAT_CUI VARCHAR2(30)
,CONCENTRATION NUMBER
,CONCENTRATION_CUI VARCHAR2(30)
,COPATH_CASE VARCHAR2(4000)
,COPATH_CASE_CUI VARCHAR2(30)
,DATE_COLLECTION DATE
,DATE_COLLECTION_CUI VARCHAR2(30)
,DATE_PRESERVE DATE
,DATE_PRESERVE_CUI VARCHAR2(30)
,DERIV_OP_CUI VARCHAR2(30)
,EXTRACTION_METHOD_CUI VARCHAR2(30)
,ELUTION_BUFFER_CUI VARCHAR2(30)
,OTHER_ELUTION_BUFFER VARCHAR2(200)
,EXP_DISTRIBUTION_CUI VARCHAR2(30)
,EXT_INVESTIGATOR_CUI VARCHAR2(30)
,CRI_FIXATIVE_CUI VARCHAR2(30)
,FIXATIVE_TYPE_CUI VARCHAR2(30)
,FIXED_TISSUE_PREP_CUI VARCHAR2(30)
,FORMAT_DETAIL_CUI VARCHAR2(30)
,FREEZING_MEDIA VARCHAR2(4000)
,FREEZING_MEDIA_CUI VARCHAR2(30)
,FROZEN_TISSUE_PREP_CUI VARCHAR2(30)
,OTHER_FROZEN_TISSUE_PREP VARCHAR2(200)
,GROSS_APPEAR_CUI VARCHAR2(30)
,HEMOLYZED_STATUS_CUI VARCHAR2(30)
,INVESTIGATOR_ID_CUI VARCHAR2(30)
,OTHER_INVESTIGATOR_ID VARCHAR2(200)
,NA_BUFFER_CUI VARCHAR2(30)
,OTHER_NA_BUFFER VARCHAR2(200)
,QUALIFIES_FOR_TCGA_CUI VARCHAR2(30)
,PARENT_TISSUE_DETAIL_CUI VARCHAR2(30)
,PERCENT_VIABLE NUMBER
,PERCENT_VIABLE_CUI VARCHAR2(30)
,PHENOTYPIC_PATTERN_CUI VARCHAR2(30)
,PREPARED_BY VARCHAR2(4000)
,PREPARED_BY_CUI VARCHAR2(30)
,PRESERVATION_METHOD_CUI VARCHAR2(30)
,PROJECT_NUMBER VARCHAR2(4000)
,PROJECT_NUMBER_CUI VARCHAR2(30)
,PROTEIN_BUFFER_CUI VARCHAR2(30)
,OTHER_PROTEIN_BUFFER VARCHAR2(200)
,PROJECT_REQUEST VARCHAR2(4000)
,PROJECT_REQUEST_CUI VARCHAR2(30)
,SAMPLE_COMMENT CLOB
,SAMPLE_COMMENT_CUI VARCHAR2(30)
,SAMPLE_DIMENSIONS VARCHAR2(4000)
,SAMPLE_DIMENSIONS_CUI VARCHAR2(30)
,SAMPLE_FORMAT_CUI VARCHAR2(30)
,OTHER_SAMPLE_FORMAT VARCHAR2(200)
,SAMP_GROSS_APPEAR_CUI VARCHAR2(30)
,SAMPLE_SOURCE VARCHAR2(4000)
,SAMPLE_SOURCE_CUI VARCHAR2(30)
,SAMPLE_SUBTYPE VARCHAR2(4000)
,SAMPLE_SUBTYPE_CUI VARCHAR2(30)
,SAMPLE_TYPE_CUI VARCHAR2(30)
,SAMPLE_VOLUME NUMBER
,SAMPLE_VOLUME_CUI VARCHAR2(30)
,SAMPLE_VOLUME_UNIT_CUI VARCHAR2(30)
,SAMPLE_WEIGHT NUMBER
,SAMPLE_WEIGHT_CUI VARCHAR2(30)
,SAMPLE_WEIGHT_UNIT_CUI VARCHAR2(30)
,SLIDE_PREP_CUI VARCHAR2(30)
,OTHER_SLIDE_PREP VARCHAR2(200)
,STAIN_TYPE_CUI VARCHAR2(30)
,OTHER_STAIN_TYPE VARCHAR2(200)
,SPECIES_CUI VARCHAR2(30)
,OTHER_SPECIES VARCHAR2(200)
,SPECIMEN_DIMENSIONS VARCHAR2(4000)
,SPECIMEN_DIMENSIONS_CUI VARCHAR2(30)
,SPECIMEN_DIM_UNIT_CUI VARCHAR2(30)
,STORAGE_FORM_CUI VARCHAR2(30)
,OTHER_STORAGE_FORM VARCHAR2(200)
,STORAGE_TYPE_CUI VARCHAR2(30)
,OTHER_STORAGE_TYPE VARCHAR2(200)
,SUSPENSION_MEDIUM_CUI VARCHAR2(30)
,OTHER_SUSPENSION_MEDIUM VARCHAR2(200)
,TCGA_COLLECTION_PROC_CUI VARCHAR2(30)
,TCGA_COMMENT CLOB
,TCGA_COMMENT_CUI VARCHAR2(30)
,TCGA_SOURCE_HOSPITAL_CUI VARCHAR2(30)
,OTHER_TCGA_SOURCE_HOSPITAL VARCHAR2(200)
,TCGA_SURGERY_CUI VARCHAR2(30)
,TCGA_VOLUME NUMBER
,TCGA_VOLUME_CUI VARCHAR2(30)
,SAMPLE_TECHNIQUE_CUI VARCHAR2(30)
,OTHER_SAMPLE_TECHNIQUE VARCHAR2(200)
,TIME_BLOOD_DRAW_CUI VARCHAR2(30)
,TIME_COLLECT_AMPM_CUI VARCHAR2(30)
,TIME_COLLECT_HOUR NUMBER
,TIME_COLLECT_HOUR_CUI VARCHAR2(30)
,TIME_COLLECT_MIN NUMBER
,TIME_COLLECT_MIN_CUI VARCHAR2(30)
,TIME_PRESERVE_AMPM_CUI VARCHAR2(30)
,TIME_PRESERVE_HOUR NUMBER
,TIME_PRESERVE_HOUR_CUI VARCHAR2(30)
,TIME_PRESERVE_MIN NUMBER
,TIME_PRESERVE_MIN_CUI VARCHAR2(30)
,TOTAL_CELLS_EXPONENT_CUI VARCHAR2(30)
,TOTAL_NUM_CELLS NUMBER
,TOTAL_NUM_CELLS_CUI VARCHAR2(30)
,YIELD NUMBER
,YIELD_CUI VARCHAR2(30)
)
;

ALTER TABLE CIR_SAMPLE_INFO ADD CONSTRAINT PK_CIR_SAMPLE_INFO PRIMARY KEY (ID);



CREATE TABLE CIR_SAMPLE_INFO_NOTE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,NOTE VARCHAR2(4000)
)
;


ALTER TABLE CIR_SAMPLE_INFO_NOTE ADD CONSTRAINT PK_CIR_SAMPLE_INFO_N PRIMARY KEY (ID);

CREATE INDEX CIR_SAMPLE_INFO_I5 ON CIR_SAMPLE_INFO_NOTE (FORM_ID)
;

REM ************************************************************************************
REM * CREATE TABLE for category surgical_pathology (conventional)
REM ************************************************************************************
CREATE TABLE CIR_SURGICAL_PATHOLOGY (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PATH_REPO_DIAG_CUI VARCHAR2(30)
,OTHER_PATH_REPO_DIAG VARCHAR2(200)
,PATH_REPO_TEXT CLOB
,PATH_REPO_TEXT_CUI VARCHAR2(30)
,TISSUE_ORIG_CUI VARCHAR2(30)
,OTHER_TISSUE_ORIG VARCHAR2(200)
,SITE_FIND_CUI VARCHAR2(30)
,OTHER_SITE_FIND VARCHAR2(200)
,SURGICAL_PROCEDURE_CUI VARCHAR2(30)
,OTHER_SURGICAL_PROCEDURE VARCHAR2(200)
,NEED_BIOP_NUMB NUMBER
,NEED_BIOP_NUMB_CUI VARCHAR2(30)
,NUMB_CORE_POS NUMBER
,NUMB_CORE_POS_CUI VARCHAR2(30)
,NUMB_CORE_TAKE NUMBER
,NUMB_CORE_TAKE_CUI VARCHAR2(30)
,PERC_CORE_POS NUMBER
,PERC_CORE_POS_CUI VARCHAR2(30)
,PATH_STG_APPL_IND_CUI VARCHAR2(30)
,PATH_COMMENTS VARCHAR2(4000)
,PATH_COMMENTS_CUI VARCHAR2(30)
,LESI_DIAM1 NUMBER
,LESI_DIAM1_CUI VARCHAR2(30)
,LESI_DIAM2 NUMBER
,LESI_DIAM2_CUI VARCHAR2(30)
,LESI_DIAM3 NUMBER
,LESI_DIAM3_CUI VARCHAR2(30)
,HEART_WEIGHT NUMBER
,HEART_WEIGHT_CUI VARCHAR2(30)
,LEFT_ATRI_DIAM NUMBER
,LEFT_ATRI_DIAM_CUI VARCHAR2(30)
,LEFT_VENT_DIAM NUMBER
,LEFT_VENT_DIAM_CUI VARCHAR2(30)
,LEFT_VENT_WALL_THIC NUMBER
,LEFT_VENT_WALL_THIC_CUI VARCHAR2(30)
,RIGH_ATRI_DIAM NUMBER
,RIGH_ATRI_DIAM_CUI VARCHAR2(30)
,RIGH_VENT_DIAM NUMBER
,RIGH_VENT_DIAM_CUI VARCHAR2(30)
,RIGH_VENT_WALL_THIC NUMBER
,RIGH_VENT_WALL_THIC_CUI VARCHAR2(30)
,NUMB_POLYPS NUMBER
,NUMB_POLYPS_CUI VARCHAR2(30)
,SIZE_LEUK_CUI VARCHAR2(30)
,A6_PATH_TUMO_STG_CUI VARCHAR2(30)
,MACF_PATH_TUMO_STG_CUI VARCHAR2(30)
,A6_PATH_LYM_NODE_STG_CUI VARCHAR2(30)
,HAN_PATH_LN_LOCA_CUI VARCHAR2(30)
,LYM_NODE_INVO NUMBER
,LYM_NODE_INVO_CUI VARCHAR2(30)
,NUMBER_STG_NODES NUMBER
,NUMBER_STG_NODES_CUI VARCHAR2(30)
,NUMB_POS_STAG_NODE NUMBER
,NUMB_POS_STAG_NODE_CUI VARCHAR2(30)
,NUMB_MEDI_NODE NUMBER
,NUMB_MEDI_NODE_CUI VARCHAR2(30)
,NUMB_POS_MEDI_NODE NUMBER
,NUMB_POS_MEDI_NODE_CUI VARCHAR2(30)
,NUMB_RESE_NODE NUMBER
,NUMB_RESE_NODE_CUI VARCHAR2(30)
,NUMB_POS_RESE_NODE NUMBER
,NUMB_POS_RESE_NODE_CUI VARCHAR2(30)
,NUMB_TOT_NODE_EXAM NUMBER
,NUMB_TOT_NODE_EXAM_CUI VARCHAR2(30)
,NUMB_TOT_POS_NODE NUMBER
,NUMB_TOT_POS_NODE_CUI VARCHAR2(30)
,MACF_PATH_LN_STG_CUI VARCHAR2(30)
,MF_PATH_LYM_NODE_STG_CUI VARCHAR2(30)
,PERC_LYM_NODE_INVO NUMBER
,PERC_LYM_NODE_INVO_CUI VARCHAR2(30)
,AJCC6_PATH_CUI VARCHAR2(30)
,KADISH_STAGE_CUI VARCHAR2(30)
,MACF_PATH_MET_STG_CUI VARCHAR2(30)
,THOR_ESOP_PATH_MET_CUI VARCHAR2(30)
,A6_PATH_STG_GROUP_CUI VARCHAR2(30)
,BURK_LYMP_PATH_CUI VARCHAR2(30)
,EXGONGERM_PATHSG_CUI VARCHAR2(30)
,MACF_PATH_STG_GROUP_CUI VARCHAR2(30)
,MASA_THYM_STG_GROUP_CUI VARCHAR2(30)
,OLEP_STG_GROUP_CUI VARCHAR2(30)
,BIL_CIRR_PATH_E_CUI VARCHAR2(30)
,AP_ALLO_GLOM_SCOR_CUI VARCHAR2(30)
,AP_ART_HYAL_THK_SCOR_CUI VARCHAR2(30)
,AP_E_ALLOGLOM_SCOR_CUI VARCHAR2(30)
,AP_INTIM_THICK_SCOR_CUI VARCHAR2(30)
,AP_INTE_FIBR_SCOR_CUI VARCHAR2(30)
,AP_INTI_ARTE_SCOR_CUI VARCHAR2(30)
,AP_MESMATR_INCR_SCOR_CUI VARCHAR2(30)
,AP_MC_IN_INFLAM_SCOR_CUI VARCHAR2(30)
,AP_TUBU_ATRO_SCOR_CUI VARCHAR2(30)
,ALLO_PATH_TUBU_SCOR_CUI VARCHAR2(30)
,BANF97_REN_ALLO_CLAS_CUI VARCHAR2(30)
,BONEGIANT_TUM_GRAD_CUI VARCHAR2(30)
,BRAA_BRAA_ALZH_STG_CUI VARCHAR2(30)
,BRAA_BRAA_PARK_STG_CUI VARCHAR2(30)
,BRESLOWS_THICKNESS NUMBER
,BRESLOWS_THICKNESS_CUI VARCHAR2(30)
,CANC_UK_PRIPATH_CLAS_CUI VARCHAR2(30)
,OTHER_CANC_UK_PRIPATH_CLAS VARCHAR2(200)
,CARC_HIST_CLAS_CUI VARCHAR2(30)
,CERA_PLAQ_SCOR_CUI VARCHAR2(30)
,CERV_INTR_NEOP_GRAD_CUI VARCHAR2(30)
,CHONDROSARCOMA_GRADE_CUI VARCHAR2(30)
,CHRO_GAST_TYPE_CUI VARCHAR2(30)
,CLARK_LEVEL_CUI VARCHAR2(30)
,DEPTH_TUMOR_INVA_CUI VARCHAR2(30)
,ENDO_ADEN_HIST_GRAD_CUI VARCHAR2(30)
,ENNE_STAG_MUSC_SARC_CUI VARCHAR2(30)
,ESOP_DYSP_GRAD_CUI VARCHAR2(30)
,FIBROSIS_GRADE_CUI VARCHAR2(30)
,FIBROSIS_SCORE_CUI VARCHAR2(30)
,FOLL_LYMP_HIST_GRAD_CUI VARCHAR2(30)
,GLAS_GLOM_JUGU_CLAS_CUI VARCHAR2(30)
,GLEA_PRIMARY_SCORE NUMBER
,GLEA_PRIMARY_SCORE_CUI VARCHAR2(30)
,GLEA_SECOND_SCORE NUMBER
,GLEA_SECOND_SCORE_CUI VARCHAR2(30)
,GLEASON_SCORE NUMBER
,GLEASON_SCORE_CUI VARCHAR2(30)
,HISTOLOGIC_GRADE_CUI VARCHAR2(30)
,HUNT_DIS_PATH_GRAD_CUI VARCHAR2(30)
,IMMA_TERA_HIST_GRAD_CUI VARCHAR2(30)
,INTR_NECR_CUI VARCHAR2(30)
,JAP_CLASS_DYSP_CUI VARCHAR2(30)
,LYMPHATIC_INVASION_CUI VARCHAR2(30)
,NIA_REAG_NEUR_CRIT_CUI VARCHAR2(30)
,NOTT_COMB_HIST_GRAD_CUI VARCHAR2(30)
,NUMB_INDI_TUMO_PRES NUMBER
,NUMB_INDI_TUMO_PRES_CUI VARCHAR2(30)
,OLEP_PATHOLOGY_CUI VARCHAR2(30)
,PADO_INTE_DYSP_CLAS_CUI VARCHAR2(30)
,PERC_TISSUE_POS NUMBER
,PERC_TISSUE_POS_CUI VARCHAR2(30)
,PERIPORTAL_NECROSIS_CUI VARCHAR2(30)
,PERITONEAL_DISS_CUI VARCHAR2(30)
,PORTAL_INFLAMMATION_CUI VARCHAR2(30)
,RESIDUAL_TUMOR_CUI VARCHAR2(30)
,SEROSAL_INVASION_CUI VARCHAR2(30)
,SHIMADA_CLASS_CUI VARCHAR2(30)
,TUMOR_LATERALITY_CUI VARCHAR2(30)
,TUMOR_GRADE_CUI VARCHAR2(30)
,OTHER_TUMOR_GRADE VARCHAR2(200)
,UTER_DEGR_DIFF_CUI VARCHAR2(30)
,VAGI_INTR_NEOP_GRAD_CUI VARCHAR2(30)
,VENOUS_INVASION_CUI VARCHAR2(30)
,VIENNA_DYSP_CLASS_CUI VARCHAR2(30)
,VULV_INTR_NEOP_GRAD_CUI VARCHAR2(30)
,WHO_CNS_GRAD_CUI VARCHAR2(30)
,WHO_HISTCLAS_DCNEO_CUI VARCHAR2(30)
,WHO_HISTCLAS_MYELDIS_CUI VARCHAR2(30)
,WHO_MDS_HIST_CLAS_CUI VARCHAR2(30)
,WHO_NASO_CARC_GRAD_CUI VARCHAR2(30)
,WHO_PNS_GRAD_CUI VARCHAR2(30)
,WHO_THYM_CLAS_CUI VARCHAR2(30)
,AGNOR_COUNT NUMBER
,AGNOR_COUNT_CUI VARCHAR2(30)
,APOPTOSIS_CUI VARCHAR2(30)
,OTHER_APOPTOSIS VARCHAR2(200)
,AVER_MITO_PER_HPF_CUI VARCHAR2(30)
,CALCIFICATION_CUI VARCHAR2(30)
,CELL_ORIGIN_CUI VARCHAR2(30)
,OTHER_CELL_ORIGIN VARCHAR2(200)
,CELL_PROLIF_EL_CUI VARCHAR2(30)
,CELL_SIZE_CUI VARCHAR2(30)
,OTHER_CELL_SIZE VARCHAR2(200)
,FIBROCYSTIC_CHANGES_CUI VARCHAR2(30)
,MITOTIC_INDEX_CUI VARCHAR2(30)
,MYEL_CELL_MASS NUMBER
,MYEL_CELL_MASS_CUI VARCHAR2(30)
,PLAS_CELL_INDE_CUI VARCHAR2(30)
,PROLIFERATION_INDEX NUMBER
,PROLIFERATION_INDEX_CUI VARCHAR2(30)
,SPHASE_CUI VARCHAR2(30)
,TELOMERASE_ACTIVITY_CUI VARCHAR2(30)
,TUMO_MASS_SIZE_MICRO NUMBER
,TUMO_MASS_SIZE_MICRO_CUI VARCHAR2(30)
,TUMOR_NECROSIS_CUI VARCHAR2(30)
,ELEC_MICR_REPO CLOB
,ELEC_MICR_REPO_CUI VARCHAR2(30)
)
;

ALTER TABLE CIR_SURGICAL_PATHOLOGY ADD CONSTRAINT PK_CIR_SURGICAL_PATHOLOGY PRIMARY KEY (ID);


CREATE TABLE CIR_SURGICAL_PATHOLOGY_MULTI (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,OTHER_DATA_VALUE VARCHAR2(200)
)
;


ALTER TABLE CIR_SURGICAL_PATHOLOGY_MULTI ADD CONSTRAINT PK_CIR_SURGICAL_PATHOLOGY_M PRIMARY KEY (ID);

CREATE INDEX CIR_SURGICAL_PATHOLOGY_I3 ON CIR_SURGICAL_PATHOLOGY_MULTI (FORM_ID)
;

CREATE TABLE CIR_SURGICAL_PATHOLOGY_NOTE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,NOTE VARCHAR2(4000)
)
;


ALTER TABLE CIR_SURGICAL_PATHOLOGY_NOTE ADD CONSTRAINT PK_CIR_SURGICAL_PATHOLOGY_N PRIMARY KEY (ID);

CREATE INDEX CIR_SURGICAL_PATHOLOGY_I5 ON CIR_SURGICAL_PATHOLOGY_NOTE (FORM_ID)
;

REM ************************************************************************************
REM * CREATE TABLE for category path_verification (conventional)
REM ************************************************************************************
CREATE TABLE CIR_PATH_VERIFICATION (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,SAMPLE_DX_CUI VARCHAR2(30)
,OTHER_SAMPLE_DX VARCHAR2(200)
,SAMPLE_TOO_CUI VARCHAR2(30)
,OTHER_SAMPLE_TOO VARCHAR2(200)
,SAMPLE_SOF_CUI VARCHAR2(30)
,OTHER_SAMPLE_SOF VARCHAR2(200)
,CELL_SOURCE_CUI VARCHAR2(30)
,OTHER_CELL_SOURCE VARCHAR2(200)
,NORMA NUMBER
,NORMA_CUI VARCHAR2(30)
,LESION NUMBER
,LESION_CUI VARCHAR2(30)
,TUMOR NUMBER
,TUMOR_CUI VARCHAR2(30)
,NO_NL_ARCH_IN_LESION_CUI VARCHAR2(30)
,CELLULAR_STROMA NUMBER
,CELLULAR_STROMA_CUI VARCHAR2(30)
,HYPO_STROMA NUMBER
,HYPO_STROMA_CUI VARCHAR2(30)
,NECROSIS NUMBER
,NECROSIS_CUI VARCHAR2(30)
,TOTAL_PERCENT NUMBER
,TOTAL_PERCENT_CUI VARCHAR2(30)
,APPEARANCE_CUI VARCHAR2(30)
,OTHER_APPEARANCE VARCHAR2(200)
,SLIDE_ALIAS VARCHAR2(4000)
,SLIDE_ALIAS_CUI VARCHAR2(30)
,SUPPLIER_NOTE VARCHAR2(4000)
,SUPPLIER_NOTE_CUI VARCHAR2(30)
,INTERNAL_NOTE VARCHAR2(4000)
,INTERNAL_NOTE_CUI VARCHAR2(30)
)
;

ALTER TABLE CIR_PATH_VERIFICATION ADD CONSTRAINT PK_CIR_PATH_VERIFICATION PRIMARY KEY (ID);


CREATE TABLE CIR_PATH_VERIFICATION_MULTI (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,OTHER_DATA_VALUE VARCHAR2(200)
)
;


ALTER TABLE CIR_PATH_VERIFICATION_MULTI ADD CONSTRAINT PK_CIR_PATH_VERIFICATION_M PRIMARY KEY (ID);

CREATE INDEX CIR_PATH_VERIFICATION_I3 ON CIR_PATH_VERIFICATION_MULTI (FORM_ID)
;

CREATE TABLE CIR_PATH_VERIFICATION_NOTE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,NOTE VARCHAR2(4000)
)
;


ALTER TABLE CIR_PATH_VERIFICATION_NOTE ADD CONSTRAINT PK_CIR_PATH_VERIFICATION_N PRIMARY KEY (ID);

CREATE INDEX CIR_PATH_VERIFICATION_I5 ON CIR_PATH_VERIFICATION_NOTE (FORM_ID)
;

REM ************************************************************************************
REM * CREATE TABLE for category followup_info (conventional)
REM ************************************************************************************
CREATE TABLE CIR_FOLLOWUP_INFO (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATE_LAST_FOLLOWUP DATE
,DATE_LAST_FOLLOWUP_CUI VARCHAR2(30)
,TIME_SINC_LAST_SURG NUMBER
,TIME_SINC_LAST_SURG_CUI VARCHAR2(30)
,TIME_SINC_LAST_DATE NUMBER
,TIME_SINC_LAST_DATE_CUI VARCHAR2(30)
,VITAL_STATUS_CUI VARCHAR2(30)
,VITAL_STATUS_WO_ADE_CUI VARCHAR2(30)
,DATE_DEATH DATE
,DATE_DEATH_CUI VARCHAR2(30)
,RECUR_CUI VARCHAR2(30)
,MD_COMMENTS VARCHAR2(4000)
,MD_COMMENTS_CUI VARCHAR2(30)
)
;

ALTER TABLE CIR_FOLLOWUP_INFO ADD CONSTRAINT PK_CIR_FOLLOWUP_INFO PRIMARY KEY (ID);



CREATE TABLE CIR_FOLLOWUP_INFO_NOTE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,NOTE VARCHAR2(4000)
)
;


ALTER TABLE CIR_FOLLOWUP_INFO_NOTE ADD CONSTRAINT PK_CIR_FOLLOWUP_INFO_N PRIMARY KEY (ID);

CREATE INDEX CIR_FOLLOWUP_INFO_I5 ON CIR_FOLLOWUP_INFO_NOTE (FORM_ID)
;

REM ************************************************************************************
REM * CREATE TABLE for category blank_fields (conventional)
REM ************************************************************************************
CREATE TABLE CIR_BLANK_FIELDS (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,BLANK_CV1_ONE_CUI VARCHAR2(30)
,BLANK_CV1_TWO_CUI VARCHAR2(30)
,BLANK_CV1_THREE_CUI VARCHAR2(30)
,BLANK_CV1_FOUR_CUI VARCHAR2(30)
,BLANK_CV1_FIVE_CUI VARCHAR2(30)
,OTHER_BLANK_CV1_FIVE VARCHAR2(200)
,BLANK_TEXT_ONE VARCHAR2(4000)
,BLANK_TEXT_ONE_CUI VARCHAR2(30)
,BLANK_TEXT_TWO VARCHAR2(4000)
,BLANK_TEXT_TWO_CUI VARCHAR2(30)
,BLANK_TEXT_THREE VARCHAR2(4000)
,BLANK_TEXT_THREE_CUI VARCHAR2(30)
,BLANK_TEXT_FOUR VARCHAR2(4000)
,BLANK_TEXT_FOUR_CUI VARCHAR2(30)
,BLANK_TEXT_FIVE VARCHAR2(4000)
,BLANK_TEXT_FIVE_CUI VARCHAR2(30)
,BLANK_REPORT_ONE CLOB
,BLANK_REPORT_ONE_CUI VARCHAR2(30)
,BLANK_REPORT_TWO CLOB
,BLANK_REPORT_TWO_CUI VARCHAR2(30)
,BLANK_REPORT_THREE CLOB
,BLANK_REPORT_THREE_CUI VARCHAR2(30)
,BLANK_DATE_ONE DATE
,BLANK_DATE_ONE_CUI VARCHAR2(30)
,BLANK_DATE_TWO DATE
,BLANK_DATE_TWO_CUI VARCHAR2(30)
,BLANK_DATE_THREE DATE
,BLANK_DATE_THREE_CUI VARCHAR2(30)
,BLANK_FLOAT_ONE NUMBER
,BLANK_FLOAT_ONE_CUI VARCHAR2(30)
,BLANK_FLOAT_TWO NUMBER
,BLANK_FLOAT_TWO_CUI VARCHAR2(30)
,BLANK_FLOAT_THREE NUMBER
,BLANK_FLOAT_THREE_CUI VARCHAR2(30)
,BLANK_INTEGER_ONE NUMBER
,BLANK_INTEGER_ONE_CUI VARCHAR2(30)
,BLANK_INTEGER_TWO NUMBER
,BLANK_INTEGER_TWO_CUI VARCHAR2(30)
,BLANK_INTEGER_THREE NUMBER
,BLANK_INTEGER_THREE_CUI VARCHAR2(30)
,BLANK_YN_CUI VARCHAR2(30)
,BLANK_YNDK_CUI VARCHAR2(30)
,BLANK_AR_ONE_CUI VARCHAR2(30)
,BLANK_AR_TWO_CUI VARCHAR2(30)
,BLANK_AR_THREE_CUI VARCHAR2(30)
,BLANK_PERC_FLOAT_ONE NUMBER
,BLANK_PERC_FLOAT_ONE_CUI VARCHAR2(30)
,BLANK_PERC_FLOAT_TWO NUMBER
,BLANK_PERC_FLOAT_TWO_CUI VARCHAR2(30)
,BLANK_PERC_INT_ONE NUMBER
,BLANK_PERC_INT_ONE_CUI VARCHAR2(30)
,BLANK_PERC_INT_TWO NUMBER
,BLANK_PERC_INT_TWO_CUI VARCHAR2(30)
,BLANK_FLOAT_FOUR NUMBER
,BLANK_FLOAT_FOUR_CUI VARCHAR2(30)
,BLANK_FLOAT_FIVE NUMBER
,BLANK_FLOAT_FIVE_CUI VARCHAR2(30)
,BLANK_INTEGER_FOUR NUMBER
,BLANK_INTEGER_FOUR_CUI VARCHAR2(30)
,BLANK_INTEGER_FIVE NUMBER
,BLANK_INTEGER_FIVE_CUI VARCHAR2(30)
,BLANK_CV1_DATE_ADE_CUI VARCHAR2(30)
,BLANK_CV1_ADE_ONE_CUI VARCHAR2(30)
,BLANK_CV1_ADE_TWO_CUI VARCHAR2(30)
,OTHER_BLANK_CV1_ADE_TWO VARCHAR2(200)
,BLANK_FLOAT_DATE_ADE NUMBER
,BLANK_FLOAT_DATE_ADE_CUI VARCHAR2(30)
,BLANK_FLOAT_ADE NUMBER
,BLANK_FLOAT_ADE_CUI VARCHAR2(30)
,BLANK_CV1_ST_RPT_ADE_CUI VARCHAR2(30)
)
;

ALTER TABLE CIR_BLANK_FIELDS ADD CONSTRAINT PK_CIR_BLANK_FIELDS PRIMARY KEY (ID);


CREATE TABLE CIR_BLANK_FIELDS_MULTI (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,OTHER_DATA_VALUE VARCHAR2(200)
)
;


ALTER TABLE CIR_BLANK_FIELDS_MULTI ADD CONSTRAINT PK_CIR_BLANK_FIELDS_M PRIMARY KEY (ID);

CREATE INDEX CIR_BLANK_FIELDS_I3 ON CIR_BLANK_FIELDS_MULTI (FORM_ID)
;

CREATE TABLE CIR_BLANK_FIELDS_NOTE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,NOTE VARCHAR2(4000)
)
;


ALTER TABLE CIR_BLANK_FIELDS_NOTE ADD CONSTRAINT PK_CIR_BLANK_FIELDS_N PRIMARY KEY (ID);

CREATE INDEX CIR_BLANK_FIELDS_I5 ON CIR_BLANK_FIELDS_NOTE (FORM_ID)
;

CREATE TABLE CIR_DATE_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATE_ELEMENT DATE
,DATE_ELEMENT_DPC VARCHAR2(30)
)
;

ALTER TABLE CIR_DATE_ADE ADD CONSTRAINT PK_CIR_DATE_ADE PRIMARY KEY (ID);

CREATE TABLE CIR_PHYSICAL_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,AGE_FIND_APPE NUMBER
)
;

ALTER TABLE CIR_PHYSICAL_ADE ADD CONSTRAINT PK_CIR_PHYSICAL_ADE PRIMARY KEY (ID);

CREATE TABLE CIR_SX_SCORE_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,SYMPTOM_SCORE_CUI VARCHAR2(30)
)
;

ALTER TABLE CIR_SX_SCORE_ADE ADD CONSTRAINT PK_CIR_SX_SCORE_ADE PRIMARY KEY (ID);

CREATE TABLE CIR_CA_RX_RESPONSE_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATE_RX_START DATE
,DATE_RX_START_DPC VARCHAR2(30)
,DATE_RECENT_RX DATE
,DATE_RECENT_RX_DPC VARCHAR2(30)
,RX_RESPONSE_CUI VARCHAR2(30)
,OTHER_RX_RESPONSE VARCHAR2(200)
)
;

ALTER TABLE CIR_CA_RX_RESPONSE_ADE ADD CONSTRAINT PK_CIR_CA_RX_RESPONSE_ADE PRIMARY KEY (ID);

CREATE TABLE CIR_CHEMO_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,TIMING_CHEMO_CUI VARCHAR2(30)
,DATE_CHEMO_START DATE
,DATE_CHEMO_START_DPC VARCHAR2(30)
,DATE_CHEMO_END DATE
,DATE_CHEMO_END_DPC VARCHAR2(30)
,DAYS_SINCLST_CHEMO NUMBER
,ROUT_ADMI_CUI VARCHAR2(30)
,OTHER_ROUT_ADMI VARCHAR2(200)
,RESP_CHEMO_CUI VARCHAR2(30)
,OTHER_RESP_CHEMO VARCHAR2(200)
,OFF_TREAT_REASON_CUI VARCHAR2(30)
,OTHER_OFF_TREAT_REASON VARCHAR2(200)
)
;

ALTER TABLE CIR_CHEMO_ADE ADD CONSTRAINT PK_CIR_CHEMO_ADE PRIMARY KEY (ID);

CREATE TABLE CIR_MEDICATION_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATE_MEDI_START DATE
,DATE_MEDI_START_DPC VARCHAR2(30)
,DATE_MEDI_END DATE
,DATE_MEDI_END_DPC VARCHAR2(30)
,DAYS_SINCLST_MEDI NUMBER
,RESP_MEDI_CUI VARCHAR2(30)
,OTHER_RESP_MEDI VARCHAR2(200)
)
;

ALTER TABLE CIR_MEDICATION_ADE ADD CONSTRAINT PK_CIR_MEDICATION_ADE PRIMARY KEY (ID);

CREATE TABLE CIR_MED_DATES_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATE_MEDS_START DATE
,DATE_MEDS_START_DPC VARCHAR2(30)
,DATE_RECENT_MEDS DATE
,DATE_RECENT_MEDS_DPC VARCHAR2(30)
)
;

ALTER TABLE CIR_MED_DATES_ADE ADD CONSTRAINT PK_CIR_MED_DATES_ADE PRIMARY KEY (ID);

CREATE TABLE CIR_TREATMENT_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATE_TREAT DATE
,DATE_TREAT_DPC VARCHAR2(30)
,RESP_TREAT_CUI VARCHAR2(30)
,OTHER_RESP_TREAT VARCHAR2(200)
)
;

ALTER TABLE CIR_TREATMENT_ADE ADD CONSTRAINT PK_CIR_TREATMENT_ADE PRIMARY KEY (ID);

CREATE TABLE CIR_RADIOTHERAPY_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,TIMING_RADIOTHERAPY_CUI VARCHAR2(30)
,DATE_RADIO_START DATE
,DATE_RADIO_START_DPC VARCHAR2(30)
,DATE_RADIO_END DATE
,DATE_RADIO_END_DPC VARCHAR2(30)
,DAYS_SINCLST_RADIO NUMBER
,TOTL_RADIO_DOS NUMBER
,RESP_RADIO_CUI VARCHAR2(30)
,OTHER_RESP_RADIO VARCHAR2(200)
)
;

ALTER TABLE CIR_RADIOTHERAPY_ADE ADD CONSTRAINT PK_CIR_RADIOTHERAPY_ADE PRIMARY KEY (ID);

CREATE TABLE CIR_RADIOTHERAPY_ADE_MULTI (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER NOT NULL
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,OTHER_DATA_VALUE VARCHAR2(200)
)
;

ALTER TABLE CIR_RADIOTHERAPY_ADE_MULTI ADD CONSTRAINT PK_CIR_RADIOTHERAPY_ADE_M PRIMARY KEY (ID);
CREATE TABLE CIR_SURGERY_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATE_OF_SURGERY DATE
,DATE_OF_SURGERY_DPC VARCHAR2(30)
,OPERATIVE_NOTE CLOB
)
;

ALTER TABLE CIR_SURGERY_ADE ADD CONSTRAINT PK_CIR_SURGERY_ADE PRIMARY KEY (ID);

CREATE TABLE CIR_TRANSPLANT_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATE_TRANSPLANT DATE
,DATE_TRANSPLANT_DPC VARCHAR2(30)
,TRANSPLANT_SOURCE_CUI VARCHAR2(30)
,OTHER_TRANSPLANT_SOURCE VARCHAR2(200)
,TRANS_OPERAT_NOTE CLOB
)
;

ALTER TABLE CIR_TRANSPLANT_ADE ADD CONSTRAINT PK_CIR_TRANSPLANT_ADE PRIMARY KEY (ID);

CREATE TABLE CIR_BLOOD_DRAW_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,TIMING_BLOOD_DRAW_CUI VARCHAR2(30)
)
;

ALTER TABLE CIR_BLOOD_DRAW_ADE ADD CONSTRAINT PK_CIR_BLOOD_DRAW_ADE PRIMARY KEY (ID);

CREATE TABLE CIR_ESOPH_PH_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATE_OF_ESOPH_PH DATE
,DEMEESTER_SCORE NUMBER
)
;

ALTER TABLE CIR_ESOPH_PH_ADE ADD CONSTRAINT PK_CIR_ESOPH_PH_ADE PRIMARY KEY (ID);

CREATE TABLE CIR_ESOPH_US_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATE_OF_ESOPH_US DATE
,US_T_STAGE_CUI VARCHAR2(30)
,US_N_STAGE_CUI VARCHAR2(30)
,ESOPH_US_REPORT CLOB
)
;

ALTER TABLE CIR_ESOPH_US_ADE ADD CONSTRAINT PK_CIR_ESOPH_US_ADE PRIMARY KEY (ID);

CREATE TABLE CIR_LAB_CT_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATE_OF_CT DATE
,LAB_CT_TIMEPOINT_CUI VARCHAR2(30)
,LIVER_MET_CUI VARCHAR2(30)
,LUNG_MET_CUI VARCHAR2(30)
,LAB_CT_REPORT CLOB
,CT_COMMENT CLOB
)
;

ALTER TABLE CIR_LAB_CT_ADE ADD CONSTRAINT PK_CIR_LAB_CT_ADE PRIMARY KEY (ID);

CREATE TABLE CIR_LAB_CT_ADE_MULTI (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER NOT NULL
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,OTHER_DATA_VALUE VARCHAR2(200)
)
;

ALTER TABLE CIR_LAB_CT_ADE_MULTI ADD CONSTRAINT PK_CIR_LAB_CT_ADE_M PRIMARY KEY (ID);
CREATE TABLE CIR_LAB_PET_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATE_OF_PET DATE
,LAB_PET_TIMEPOINT_CUI VARCHAR2(30)
,LAB_PET_REPORT CLOB
,PET_COMMENT CLOB
)
;

ALTER TABLE CIR_LAB_PET_ADE ADD CONSTRAINT PK_CIR_LAB_PET_ADE PRIMARY KEY (ID);

CREATE TABLE CIR_LAB_PET_MASS_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,SUV NUMBER
)
;

ALTER TABLE CIR_LAB_PET_MASS_ADE ADD CONSTRAINT PK_CIR_LAB_PET_MASS_ADE PRIMARY KEY (ID);

CREATE TABLE CIR_OBJ_STUDY_REPORT_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATE_OBJECT_STUDY DATE
,OBJECT_STUDY_CUI VARCHAR2(30)
,OTHER_OBJECT_STUDY VARCHAR2(200)
,OBJECT_STUDY_RPRT CLOB
)
;

ALTER TABLE CIR_OBJ_STUDY_REPORT_ADE ADD CONSTRAINT PK_CIR_OBJ_STUDY_REPORT_ADE PRIMARY KEY (ID);

CREATE TABLE CIR_STUDY_REPORT_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATE_STUDY DATE
,STUDY_RPRT CLOB
)
;

ALTER TABLE CIR_STUDY_REPORT_ADE ADD CONSTRAINT PK_CIR_STUDY_REPORT_ADE PRIMARY KEY (ID);

CREATE TABLE CIR_LAB_NUMERIC_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATE_NUME_RESU_TEST DATE
,DATE_NUME_RESU_TEST_DPC VARCHAR2(30)
,CLIN_TEST_RESU_CUI VARCHAR2(30)
,TEST_NORM_RANG CLOB
)
;

ALTER TABLE CIR_LAB_NUMERIC_ADE ADD CONSTRAINT PK_CIR_LAB_NUMERIC_ADE PRIMARY KEY (ID);

CREATE TABLE CIR_LAB_TECHNIQUE_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATE_TECH_SPEC_TEST DATE
,DATE_TECH_SPEC_TEST_DPC VARCHAR2(30)
,TEST_TECHNIQUE_CUI VARCHAR2(30)
,OTHER_TEST_TECHNIQUE VARCHAR2(200)
)
;

ALTER TABLE CIR_LAB_TECHNIQUE_ADE ADD CONSTRAINT PK_CIR_LAB_TECHNIQUE_ADE PRIMARY KEY (ID);

CREATE TABLE CIR_LAB_MICRO_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATE_MICR_TEST DATE
,CULTURE_RESULT_CUI VARCHAR2(30)
)
;

ALTER TABLE CIR_LAB_MICRO_ADE ADD CONSTRAINT PK_CIR_LAB_MICRO_ADE PRIMARY KEY (ID);

CREATE TABLE CIR_ALCOHOL_HX_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,ALCOHOL_AMOUNT NUMBER
,ALCOHOL_DURATION NUMBER
)
;

ALTER TABLE CIR_ALCOHOL_HX_ADE ADD CONSTRAINT PK_CIR_ALCOHOL_HX_ADE PRIMARY KEY (ID);

CREATE TABLE CIR_TOBACCO_HX_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,TOBACCO_AMOUNT NUMBER
,TIMING_SMOKING_CUI VARCHAR2(30)
,TOBACCO_STOPPED DATE
,TOBACCO_STOPPED_DPC VARCHAR2(30)
,YEAR_NOT_SMOK NUMBER
)
;

ALTER TABLE CIR_TOBACCO_HX_ADE ADD CONSTRAINT PK_CIR_TOBACCO_HX_ADE PRIMARY KEY (ID);

CREATE TABLE CIR_TOBACCO_HX_ADE_MULTI (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER NOT NULL
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,OTHER_DATA_VALUE VARCHAR2(200)
)
;

ALTER TABLE CIR_TOBACCO_HX_ADE_MULTI ADD CONSTRAINT PK_CIR_TOBACCO_HX_ADE_M PRIMARY KEY (ID);
CREATE TABLE CIR_OCCUPATION_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,YEARS_AT_OCC NUMBER
,YEARS_SINCE_OCC NUMBER
)
;

ALTER TABLE CIR_OCCUPATION_ADE ADD CONSTRAINT PK_CIR_OCCUPATION_ADE PRIMARY KEY (ID);

CREATE TABLE CIR_EXPOSURE_HX_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,YEAR_EXPOSED NUMBER
,YEAR_SINC_EXPOSED NUMBER
)
;

ALTER TABLE CIR_EXPOSURE_HX_ADE ADD CONSTRAINT PK_CIR_EXPOSURE_HX_ADE PRIMARY KEY (ID);

CREATE TABLE CIR_CANCER_HX_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATE_DIAG DATE
,DATE_DIAG_DPC VARCHAR2(30)
,AGE_AT_DIAGNOSIS NUMBER
,CANCER_STATUS_CUI VARCHAR2(30)
)
;

ALTER TABLE CIR_CANCER_HX_ADE ADD CONSTRAINT PK_CIR_CANCER_HX_ADE PRIMARY KEY (ID);

CREATE TABLE CIR_CANCER_HX_ADE_MULTI (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER NOT NULL
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,OTHER_DATA_VALUE VARCHAR2(200)
)
;

ALTER TABLE CIR_CANCER_HX_ADE_MULTI ADD CONSTRAINT PK_CIR_CANCER_HX_ADE_M PRIMARY KEY (ID);
CREATE TABLE CIR_DIABETES_HX_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,DIAB_MELL_DUR NUMBER
,DIAB_MELL_TYPE_CUI VARCHAR2(30)
,OTHER_DIAB_MELL_TYPE VARCHAR2(200)
,DIAB_MELL_CONT_CUI VARCHAR2(30)
)
;

ALTER TABLE CIR_DIABETES_HX_ADE ADD CONSTRAINT PK_CIR_DIABETES_HX_ADE PRIMARY KEY (ID);

CREATE TABLE CIR_DIABETES_HX_ADE_MULTI (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER NOT NULL
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,OTHER_DATA_VALUE VARCHAR2(200)
)
;

ALTER TABLE CIR_DIABETES_HX_ADE_MULTI ADD CONSTRAINT PK_CIR_DIABETES_HX_ADE_M PRIMARY KEY (ID);
CREATE TABLE CIR_HCU_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATE_HCU_START DATE
,DATE_HCU_START_DPC VARCHAR2(30)
,DATE_RECENT_HCU DATE
,DATE_RECENT_HCU_DPC VARCHAR2(30)
,DAYS_SINC_HCU NUMBER
,DURATION_TREATMENT NUMBER
)
;

ALTER TABLE CIR_HCU_ADE ADD CONSTRAINT PK_CIR_HCU_ADE PRIMARY KEY (ID);

CREATE TABLE CIR_HCU_ADE_MULTI (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER NOT NULL
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,OTHER_DATA_VALUE VARCHAR2(200)
)
;

ALTER TABLE CIR_HCU_ADE_MULTI ADD CONSTRAINT PK_CIR_HCU_ADE_M PRIMARY KEY (ID);
CREATE TABLE CIR_HRT_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATE_HRT_START DATE
,DATE_HRT_START_DPC VARCHAR2(30)
,DATE_RECENT_HRT DATE
,DATE_RECENT_HRT_DPC VARCHAR2(30)
,DAYS_SINC_HRT NUMBER
)
;

ALTER TABLE CIR_HRT_ADE ADD CONSTRAINT PK_CIR_HRT_ADE PRIMARY KEY (ID);

CREATE TABLE CIR_HRT_ADE_MULTI (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER NOT NULL
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,OTHER_DATA_VALUE VARCHAR2(200)
)
;

ALTER TABLE CIR_HRT_ADE_MULTI ADD CONSTRAINT PK_CIR_HRT_ADE_M PRIMARY KEY (ID);
CREATE TABLE CIR_HYPERTENSION_HX_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,HYPE_DUR NUMBER
,HYPERTENSION_TYPE_CUI VARCHAR2(30)
)
;

ALTER TABLE CIR_HYPERTENSION_HX_ADE ADD CONSTRAINT PK_CIR_HYPERTENSION_HX_ADE PRIMARY KEY (ID);

CREATE TABLE CIR_PAST_CONDITIONS_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATE_ONSET DATE
,DATE_ONSET_DPC VARCHAR2(30)
,AGE_DIAG_PAST_COND NUMBER
)
;

ALTER TABLE CIR_PAST_CONDITIONS_ADE ADD CONSTRAINT PK_CIR_PAST_CONDITIONS_ADE PRIMARY KEY (ID);

CREATE TABLE CIR_FAMILY_HX_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,AGE_DIAG_FAMI_HIST NUMBER
,DEGR_RELAT_CUI VARCHAR2(30)
)
;

ALTER TABLE CIR_FAMILY_HX_ADE ADD CONSTRAINT PK_CIR_FAMILY_HX_ADE PRIMARY KEY (ID);

CREATE TABLE CIR_CHEMO_HX_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATE_PR_CHEMO_START DATE
,DATE_PR_CHEMO_START_DPC VARCHAR2(30)
,DATE_PR_CHEMO_END DATE
,DATE_PR_CHEMO_END_DPC VARCHAR2(30)
,DAYS_SINCLSTPR_CHEMO NUMBER
,RESP_PRIO_CHEMO_CUI VARCHAR2(30)
,OTHER_RESP_PRIO_CHEMO VARCHAR2(200)
)
;

ALTER TABLE CIR_CHEMO_HX_ADE ADD CONSTRAINT PK_CIR_CHEMO_HX_ADE PRIMARY KEY (ID);

CREATE TABLE CIR_RADIOTHERAPY_HX_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATE_PR_RADIO_START DATE
,DATE_PR_RADIO_START_DPC VARCHAR2(30)
,DATE_PR_RADIO_END DATE
,DATE_PR_RADIO_END_DPC VARCHAR2(30)
,DAYS_SINCLSTPR_RADIO NUMBER
,RESP_PRIO_RADIO_CUI VARCHAR2(30)
,OTHER_RESP_PRIO_RADIO VARCHAR2(200)
)
;

ALTER TABLE CIR_RADIOTHERAPY_HX_ADE ADD CONSTRAINT PK_CIR_RADIOTHERAPY_HX_ADE PRIMARY KEY (ID);

CREATE TABLE CIR_CHEST_TUBE_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,DISC_WITH_CHES_TUBE_CUI VARCHAR2(30)
,DATE_CHEST_TUBE_DC DATE
,NUMB_CHES_TUBE_DAYS NUMBER
)
;

ALTER TABLE CIR_CHEST_TUBE_ADE ADD CONSTRAINT PK_CIR_CHEST_TUBE_ADE PRIMARY KEY (ID);

CREATE TABLE CIR_DEATH_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATE_DEAT DATE
)
;

ALTER TABLE CIR_DEATH_ADE ADD CONSTRAINT PK_CIR_DEATH_ADE PRIMARY KEY (ID);

CREATE TABLE CIR_PAIN_SCORE_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATE_PAIN_SCORE DATE
,TIME_SINC_PAIN_SCOR NUMBER
)
;

ALTER TABLE CIR_PAIN_SCORE_ADE ADD CONSTRAINT PK_CIR_PAIN_SCORE_ADE PRIMARY KEY (ID);

CREATE TABLE CIR_PRIMARY_PROC_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,APPROACH_CUI VARCHAR2(30)
,OTHER_APPROACH VARCHAR2(200)
,LATERALITY_CUI VARCHAR2(30)
)
;

ALTER TABLE CIR_PRIMARY_PROC_ADE ADD CONSTRAINT PK_CIR_PRIMARY_PROC_ADE PRIMARY KEY (ID);

CREATE TABLE CIR_BIOMARKER_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,BIOMARKER_SCORE_CUI VARCHAR2(30)
)
;

ALTER TABLE CIR_BIOMARKER_ADE ADD CONSTRAINT PK_CIR_BIOMARKER_ADE PRIMARY KEY (ID);

CREATE TABLE CIR_PERCENT_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,PERCENT_INCLUSIVE NUMBER
)
;

ALTER TABLE CIR_PERCENT_ADE ADD CONSTRAINT PK_CIR_PERCENT_ADE PRIMARY KEY (ID);

CREATE TABLE CIR_INFLAM_SEVERITY_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,SEVERITY_CUI VARCHAR2(30)
)
;

ALTER TABLE CIR_INFLAM_SEVERITY_ADE ADD CONSTRAINT PK_CIR_INFLAM_SEVERITY_ADE PRIMARY KEY (ID);

CREATE TABLE CIR_RECUR_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,RECUR_STATUS_CUI VARCHAR2(30)
,DATE_RECUR DATE
,RECUR_TYPE_CUI VARCHAR2(30)
)
;

ALTER TABLE CIR_RECUR_ADE ADD CONSTRAINT PK_CIR_RECUR_ADE PRIMARY KEY (ID);

CREATE TABLE CIR_RECUR_ADE_MULTI (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER NOT NULL
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,OTHER_DATA_VALUE VARCHAR2(200)
)
;

ALTER TABLE CIR_RECUR_ADE_MULTI ADD CONSTRAINT PK_CIR_RECUR_ADE_M PRIMARY KEY (ID);
CREATE TABLE CIR_BLANK_ADE_ONE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,BLANK_ADE_E1_CUI VARCHAR2(30)
)
;

ALTER TABLE CIR_BLANK_ADE_ONE ADD CONSTRAINT PK_CIR_BLANK_ADE_ONE PRIMARY KEY (ID);

CREATE TABLE CIR_BLANK_ADE_ONE_MULTI (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER NOT NULL
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,OTHER_DATA_VALUE VARCHAR2(200)
)
;

ALTER TABLE CIR_BLANK_ADE_ONE_MULTI ADD CONSTRAINT PK_CIR_BLANK_ADE_ONE_M PRIMARY KEY (ID);
CREATE TABLE CIR_BLANK_ADE_TWO (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,BLANK_ADE_E3_CUI VARCHAR2(30)
,BLANK_ADE_E4_CUI VARCHAR2(30)
,BLANK_ADE_E6 NUMBER
)
;

ALTER TABLE CIR_BLANK_ADE_TWO ADD CONSTRAINT PK_CIR_BLANK_ADE_TWO PRIMARY KEY (ID);

CREATE TABLE CIR_BLANK_ADE_TWO_MULTI (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER NOT NULL
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,OTHER_DATA_VALUE VARCHAR2(200)
)
;

ALTER TABLE CIR_BLANK_ADE_TWO_MULTI ADD CONSTRAINT PK_CIR_BLANK_ADE_TWO_M PRIMARY KEY (ID);
CREATE TABLE CIR_BLANK_ADE_THREE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,BLANK_ADE_E7_CUI VARCHAR2(30)
)
;

ALTER TABLE CIR_BLANK_ADE_THREE ADD CONSTRAINT PK_CIR_BLANK_ADE_THREE PRIMARY KEY (ID);

CREATE TABLE CIR_BLANK_ADE_THREE_MULTI (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER NOT NULL
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,OTHER_DATA_VALUE VARCHAR2(200)
)
;

ALTER TABLE CIR_BLANK_ADE_THREE_MULTI ADD CONSTRAINT PK_CIR_BLANK_ADE_THREE_M PRIMARY KEY (ID);
CREATE TABLE CIR_BLANK_ADE_FOUR (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,BLANK_ADE_E9_CUI VARCHAR2(30)
,BLANK_ADE_E10_CUI VARCHAR2(30)
,BLANK_ADE_E12 NUMBER
)
;

ALTER TABLE CIR_BLANK_ADE_FOUR ADD CONSTRAINT PK_CIR_BLANK_ADE_FOUR PRIMARY KEY (ID);

CREATE TABLE CIR_BLANK_ADE_FOUR_MULTI (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER NOT NULL
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,OTHER_DATA_VALUE VARCHAR2(200)
)
;

ALTER TABLE CIR_BLANK_ADE_FOUR_MULTI ADD CONSTRAINT PK_CIR_BLANK_ADE_FOUR_M PRIMARY KEY (ID);
CREATE TABLE CIR_BLANK_ADE_FIVE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,BLANK_ADE_E13_CUI VARCHAR2(30)
)
;

ALTER TABLE CIR_BLANK_ADE_FIVE ADD CONSTRAINT PK_CIR_BLANK_ADE_FIVE PRIMARY KEY (ID);

CREATE TABLE CIR_BLANK_ADE_FIVE_MULTI (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER NOT NULL
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,OTHER_DATA_VALUE VARCHAR2(200)
)
;

ALTER TABLE CIR_BLANK_ADE_FIVE_MULTI ADD CONSTRAINT PK_CIR_BLANK_ADE_FIVE_M PRIMARY KEY (ID);

CREATE SEQUENCE CIR_SEQ START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE CACHE 20;
