SET DEFINE OFF;
SET ECHO ON;
insert into pdc_lookup values('SAMPLE_INFO', 'CA12944C', 'Blood Sample Source', '', '', 'ARD_CAP', 'A', 'P', '', '1.63', '', 'blood_sample_source', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '25', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12936C', 'Collection Format', '', '', 'ARD_CAP', 'A', 'P', '', '1.63', '', 'collection_format', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '25', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12926C', 'Fixative', '', '', 'ARD_CAP', 'A', 'P', '', '1.63', '', 'cri_fixative', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '25', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12931C', 'Parent Tissue Detail', '', '', 'ARD_CAP', 'A', 'P', '', '1.63', '', 'parent_tissue_detail', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '25', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12947C', 'Species', '', '', 'ARD_CAP', 'A', 'P', '', '1.63', '', 'species', '1', 'Y', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '25', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12939C', 'Specimen Dimensions', '', '', 'ARD_CAP', 'A', 'P', '', '1.63', '', 'specimen_dimensions', '1', 'N', 'text', '', 'Element', '', '', '', '', '', '', 'N', '', '25', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12940C', 'Specimen Dimensions Units', '', '', 'ARD_CAP', 'A', 'P', '', '1.63', '', 'specimen_dim_unit', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '25', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12958C', 'BLOOD_SAMPLE_SOURCE_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.63', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '25', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12945C', 'Peripheral', '', '', 'ARD_CAP', 'A', 'P', '', '1.63', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '25', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12946C', 'Central Line', '', '', 'ARD_CAP', 'A', 'P', '', '1.63', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '25', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12956C', 'COLLECTION_FORMAT_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.63', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '25', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12937C', 'Dry Tube', '', '', 'ARD_CAP', 'A', 'P', '', '1.63', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '25', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12938C', 'RNA Stabilizer', '', '', 'ARD_CAP', 'A', 'P', '', '1.63', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '25', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12954C', 'CRI_FIXATIVE_DET', '', '', 'ARD_CAP', 'A', 'P', 'CRI fixative type', '1.63', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '25', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12927C', '70% Ethanol', '', '', 'ARD_CAP', 'A', 'P', '', '1.63', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '25', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12928C', '10% Neutral Buffered Formalin', '', '', 'ARD_CAP', 'A', 'P', '', '1.63', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '25', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12929C', 'Acid Alcohol 10% Unbuffered Formalin', '', '', 'ARD_CAP', 'A', 'P', '', '1.63', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '25', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12930C', 'Air Dried', '', '', 'ARD_CAP', 'A', 'P', '', '1.63', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '25', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12955C', 'PARENT_TISSUE_DETAIL_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.63', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '25', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12932C', 'Flash(Snap) Frozen', '', '', 'ARD_CAP', 'A', 'P', '', '1.63', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '25', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12933C', 'OCT', '', '', 'ARD_CAP', 'A', 'P', '', '1.63', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '25', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12934C', 'Paraffin Tissue', '', '', 'ARD_CAP', 'A', 'P', '', '1.63', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '25', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12935C', 'Tissue Microarray Block', '', '', 'ARD_CAP', 'A', 'P', '', '1.63', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '25', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12957C', 'SPECIMEN_DIMENSIONS_UNITS_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.63', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '25', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12942C', 'mm', '', '', 'ARD_CAP', 'A', 'P', '', '1.63', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '25', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12941C', 'cm', '', '', 'ARD_CAP', 'A', 'P', '', '1.63', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '25', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12959C', 'CRI_SPECIES_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.63', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '25', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12948C', 'Human', '', '', 'ARD_CAP', 'A', 'P', '', '1.63', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '25', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12949C', 'Mouse', '', '', 'ARD_CAP', 'A', 'P', '', '1.63', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '25', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12950C', 'Rat', '', '', 'ARD_CAP', 'A', 'P', '', '1.63', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '25', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12951C', 'Fly', '', '', 'ARD_CAP', 'A', 'P', '', '1.63', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '25', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12952C', 'Fish', '', '', 'ARD_CAP', 'A', 'P', '', '1.63', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '25', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12953C', 'Other Species', '', '', 'ARD_CAP', 'A', 'P', '', '1.63', '', '', '', '', '', 'Y', 'Value', '', '', '', '', '', '', '', '', '25', '');
commit;
update pdc_lookup set OCE_YN='Y' where LOOKUP_TYPE_CD='CA12710C';
insert into pdc_lookup values('FROZEN_PREP', 'CA12960C', 'Other', '', '', 'ARD_CAP', 'A', 'P', '', '1.63', '', '', '', '', '', 'Y', 'Value', '', '', '', '', '', '', '', '', '25', '');
commit;