set define off

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('10_ILTDS_005_CONSLINK', 'Initial Consent Linked', TO_DATE('04/09/2001 17:52:18', 'MM/DD/YYYY HH24:MI:SS'), 'satty', TO_DATE('04/09/2001 17:52:18', 'MM/DD/YYYY HH24:MI:SS'), 'satty', 'ILTDS', '/iltds/consent/createCaseStart.do?resetForm=true&linked=true', 'Donor Institution - Case Management', 'Consent', 'M', '10_ILTDS_005_CONSLINK');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('10_ILTDS_010_CONSVERF', 'Consent Verification', TO_DATE('04/09/2001 17:52:18', 'MM/DD/YYYY HH24:MI:SS'), 'satty', TO_DATE('04/09/2001 17:52:18', 'MM/DD/YYYY HH24:MI:SS'), 'satty', 'ILTDS', '/iltds/Dispatch?op=ConsentStartVerify&title=Consent%20Verification', 'Donor Institution - Case Management', 'Consent', 'M', '10_ILTDS_010_CONSVERF');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('10_ILTDS_015_CONSREVC', 'Consent Revocation', TO_DATE('04/09/2001 17:52:18', 'MM/DD/YYYY HH24:MI:SS'), 'satty', TO_DATE('04/09/2001 17:52:18', 'MM/DD/YYYY HH24:MI:SS'), 'satty', 'ILTDS', '/iltds/consent/selectCaseToRevoke.do', 'Donor Institution - Case Management', 'Consent', 'M', '10_ILTDS_015_CONSREVC');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('10_ILTDS_020_UNLINKEN', 'Initial Unlinked Entry', TO_DATE('04/09/2001 17:52:18', 'MM/DD/YYYY HH24:MI:SS'), 'satty', TO_DATE('04/09/2001 17:52:18', 'MM/DD/YYYY HH24:MI:SS'), 'satty', 'ILTDS', '/iltds/consent/createCaseStart.do?resetForm=true&linked=false', 'Donor Institution - Case Management', 'SUB_MENU', 'M', '10_ILTDS_020_UNLINKEN');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('10_ILTDS_025_CASERELE', 'Case Release', TO_DATE('04/09/2001 17:52:18', 'MM/DD/YYYY HH24:MI:SS'), 'satty', TO_DATE('04/09/2001 17:52:18', 'MM/DD/YYYY HH24:MI:SS'), 'satty', 'ILTDS', '/iltds/Dispatch?op=CaseReleaseStart&title=Case%20Release', 'Donor Institution - Case Management', 'SUB_MENU', 'M', '10_ILTDS_025_CASERELE');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('10_ILTDS_030_CASEPULL', 'Case Pull', TO_DATE('04/09/2001 17:52:18', 'MM/DD/YYYY HH24:MI:SS'), 'satty', TO_DATE('04/09/2001 17:52:18', 'MM/DD/YYYY HH24:MI:SS'), 'satty', 'ILTDS', '/iltds/consent/selectCaseToPull.do', 'Donor Institution - Case Management', 'SUB_MENU', 'M', '10_ILTDS_030_CASEPULL');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('10_ILTDS_035_ASMINIT', 'ASM Initial Link', TO_DATE('04/09/2001 17:52:18', 'MM/DD/YYYY HH24:MI:SS'), 'satty', TO_DATE('04/09/2001 17:52:18', 'MM/DD/YYYY HH24:MI:SS'), 'satty', 'ILTDS', '/iltds/Dispatch?op=ASMStartLink&title=ASM%20Start%20Link', 'Donor Institution - Sample Management', 'ASM', 'M', '10_ILTDS_035_ASMINIT');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('10_ILTDS_040_ASMDATA', 'ASM Form Data Entry', TO_DATE('04/09/2001 17:52:18', 'MM/DD/YYYY HH24:MI:SS'), 'satty', TO_DATE('04/09/2001 17:52:18', 'MM/DD/YYYY HH24:MI:SS'), 'satty', 'ILTDS', '/iltds/Dispatch?op=ASMStartLookup&title=ASM%20Form%20ID%20Lookup', 'Donor Institution - Sample Management', 'ASM', 'M', '10_ILTDS_040_ASMDATA');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('10_ILTDS_095_MVTOPATH', 'Move Samples to Pathology', TO_DATE('04/09/2001 17:52:18', 'MM/DD/YYYY HH24:MI:SS'), 'satty', TO_DATE('04/09/2001 17:52:18', 'MM/DD/YYYY HH24:MI:SS'), 'satty', 'ILTDS', '/iltds/Dispatch?op=CheckOutBoxStart&title=Move%20Samples%20to%20Pathology&location=AR&tx=MvPath', 'Owner - Sample Mgmt', 'Storage', 'M', '10_ILTDS_095_MVTOPATH');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('10_ILTDS_200_PRJNEW', 'New Project', TO_DATE('03/20/2002 20:59:07', 'MM/DD/YYYY HH24:MI:SS'), 'Mark', TO_DATE('03/20/2002 20:59:07', 'MM/DD/YYYY HH24:MI:SS'), 'Mark', 'ILTDS', '/iltds/Dispatch?op=PtsProjectEditPrepare', 'Project Tracking System', 'SUB_MENU', 'M', '10_ILTDS_200_PRJNEW');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('10_ILTDS_205_PRJMNG', 'Manage Project', TO_DATE('03/20/2002 20:59:07', 'MM/DD/YYYY HH24:MI:SS'), 'Mark', TO_DATE('03/20/2002 20:59:07', 'MM/DD/YYYY HH24:MI:SS'), 'Mark', 'ILTDS', '/iltds/Dispatch?op=PtsProjectSearchPrepare&ctx=mng', 'Project Tracking System', 'SUB_MENU', 'M', '10_ILTDS_205_PRJMNG');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('10_ILTDS_210_PRJADD', 'Add Samples to Project', TO_DATE('03/20/2002 20:59:07', 'MM/DD/YYYY HH24:MI:SS'), 'Mark', TO_DATE('03/20/2002 20:59:07', 'MM/DD/YYYY HH24:MI:SS'), 'Mark', 'ILTDS', '/iltds/Dispatch?op=PtsProjectSearchPrepare&ctx=add', 'Project Tracking System', 'SUB_MENU', 'M', '10_ILTDS_210_PRJADD');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('10_ILTDS_225_PRJHOLD', 'Place Samples on Hold', TO_DATE('03/20/2002 20:59:07', 'MM/DD/YYYY HH24:MI:SS'), 'Mark', TO_DATE('03/20/2002 20:59:07', 'MM/DD/YYYY HH24:MI:SS'), 'Mark', 'ILTDS', '/iltds/Dispatch?op=PtsProjectSearchPrepare&ctx=hld', 'Project Tracking System', 'SUB_MENU', 'M', '10_ILTDS_225_PRJHOLD');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('10_ILTDS_226_PRJRHLD', 'Remove Samples from Hold', TO_DATE('03/20/2002 20:59:07', 'MM/DD/YYYY HH24:MI:SS'), 'Mark', TO_DATE('03/20/2002 20:59:07', 'MM/DD/YYYY HH24:MI:SS'), 'Mark', 'ILTDS', '/iltds/Dispatch?op=PtsProjectSearchPrepare&ctx=rhd', 'Project Tracking System', 'SUB_MENU', 'M', '10_ILTDS_226_PRJRHLD');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('10_ILTDS_230_PRJRMV', 'Remove Samples from Project', TO_DATE('03/20/2002 20:59:07', 'MM/DD/YYYY HH24:MI:SS'), 'Mark', TO_DATE('03/20/2002 20:59:07', 'MM/DD/YYYY HH24:MI:SS'), 'Mark', 'ILTDS', '/iltds/Dispatch?op=PtsProjectSearchPrepare&ctx=rmv', 'Project Tracking System', 'SUB_MENU', 'M', '10_ILTDS_230_PRJRMV');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('15_ES_025_VIEWORDS', 'View Order Status', TO_DATE('04/09/2001 17:52:17', 'MM/DD/YYYY HH24:MI:SS'), 'satty', TO_DATE('04/09/2001 17:52:17', 'MM/DD/YYYY HH24:MI:SS'), 'satty', 'BIGR Library', '/library/orderList.do', 'Order Management', 'SUB_MENU', 'M', '15_ES_025_VIEWORDS');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('15_ES_HOLD_RNA_ADDRMV', 'Privilege: Add/Remove RNA from Hold List', TO_DATE('05/29/2003 09:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'damon', TO_DATE('05/29/2003 09:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'damon', 'BIGR Library', 'P', '15_ES_HOLD_RNA_ADDRMV');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('15_ES_HOLD_RNA_CUSTM', 'Privilege: Specify Custom Amounts for RNA Hold', TO_DATE('05/29/2003 09:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'damon', TO_DATE('05/29/2003 09:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'damon', 'BIGR Library', 'P', '15_ES_HOLD_RNA_CUSTM');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('15_ES_PSA_DRE', 'Privilege: Query PSA and DRE', TO_DATE('08/05/2005 18:13:48', 'MM/DD/YYYY HH24:MI:SS'), 'mark', TO_DATE('08/05/2005 18:13:48', 'MM/DD/YYYY HH24:MI:SS'), 'mark', 'BIGR Library', 'P', '15_ES_PSA_DRE');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('20_LIMS_005_LABELGEN', 'Label Generation', TO_DATE('04/09/2001 17:52:17', 'MM/DD/YYYY HH24:MI:SS'), 'satty', TO_DATE('04/05/2003 09:04:09', 'MM/DD/YYYY HH24:MI:SS'), 'satty', 'LIMS', '/lims/limsLabelGenStart.do', 'Histology', 'SUB_MENU', 'M', '20_LIMS_005_LABELGEN');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('20_LIMS_008_HISTOQC', 'Histology QC', TO_DATE('04/05/2003 09:04:11', 'MM/DD/YYYY HH24:MI:SS'), 'dkostiew', TO_DATE('04/05/2003 09:04:11', 'MM/DD/YYYY HH24:MI:SS'), 'dkostiew', 'LIMS', '/lims/limsHistoQCStart.do', 'Histology', 'SUB_MENU', 'M', '20_LIMS_008_HISTOQC');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('20_LIMS_010_SLIDEPATH', 'Slide Path Lab', TO_DATE('04/05/2003 09:04:09', 'MM/DD/YYYY HH24:MI:SS'), 'Nagaraja', TO_DATE('04/05/2003 09:04:09', 'MM/DD/YYYY HH24:MI:SS'), 'LIMS', '/lims/limsPathLabStart.do', 'Histology', 'SUB_MENU', 'M', '20_LIMS_010_SLIDEPATH');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('20_LIMS_015_SLIDELOC', 'Set Slide Location', TO_DATE('04/05/2003 09:04:09', 'MM/DD/YYYY HH24:MI:SS'), 'Nagaraja', TO_DATE('04/05/2003 09:04:09', 'MM/DD/YYYY HH24:MI:SS'), 'LIMS', '/lims/limsSetLocationStart.do', 'Histology', 'SUB_MENU', 'M', '20_LIMS_015_SLIDELOC');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('20_LIMS_020_PRINTLBL', 'Print Slide Label', TO_DATE('04/05/2003 09:04:09', 'MM/DD/YYYY HH24:MI:SS'), 'Nagaraja', TO_DATE('04/05/2003 09:04:09', 'MM/DD/YYYY HH24:MI:SS'), 'LIMS', '/lims/limsPrintSlideLabelStart.do', 'Histology', 'SUB_MENU', 'M', '20_LIMS_020_PRINTLBL');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('20_LIMS_025_PATHVER', 'Pathology Verification', TO_DATE('04/09/2001 17:52:17', 'MM/DD/YYYY HH24:MI:SS'), 'satty', TO_DATE('04/05/2003 09:04:10', 'MM/DD/YYYY HH24:MI:SS'), 'satty', 'LIMS', '/lims/limsPvStart.do', 'Pathology', 'SUB_MENU', 'M', '20_LIMS_025_PATHVER');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('20_LIMS_032_PATHQC', 'Pathology QC', TO_DATE('04/05/2003 09:04:10', 'MM/DD/YYYY HH24:MI:SS'), 'Nagaraja', TO_DATE('04/05/2003 09:04:10', 'MM/DD/YYYY HH24:MI:SS'), 'LIMS', '/lims/limsPathQcStart.do', 'Pathology', 'SUB_MENU', 'M', '20_LIMS_032_PATHQC');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('20_LIMS_040_THRUREPT', 'PV Throughput Report', TO_DATE('04/05/2003 09:04:10', 'MM/DD/YYYY HH24:MI:SS'), 'Nagaraja', TO_DATE('04/05/2003 09:04:10', 'MM/DD/YYYY HH24:MI:SS'), 'LIMS', '/lims/limsPvThroughputReportStart.do', 'LIMS Reporting', 'SUB_MENU', 'M', '20_LIMS_040_THRUREPT');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('20_LIMS_QCPOST_UNPOST', 'Privilege: QCPost/UnQCPost', TO_DATE('04/05/2003 09:04:12', 'MM/DD/YYYY HH24:MI:SS'), 'jesielionis', TO_DATE('04/05/2003 09:04:12', 'MM/DD/YYYY HH24:MI:SS'), 'jesielionis', 'LIMS', 'P', '20_LIMS_QCPOST_UNPOST');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('20_LIMS_INC_FOR_REPV', 'Privilege: Incident required for Re-PV', TO_DATE('07/12/2003 11:10:53', 'MM/DD/YYYY HH24:MI:SS'), 'JEsielionis', TO_DATE('07/12/2003 11:10:53', 'MM/DD/YYYY HH24:MI:SS'), 'JEsielionis', 'LIMS', 'P', '20_LIMS_INC_FOR_REPV');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('25_PDC_025_CASPRF', 'Case Profile Entry', TO_DATE('09/07/2002 09:20:17', 'MM/DD/YYYY HH24:MI:SS'), 'Mark', TO_DATE('09/07/2002 09:20:17', 'MM/DD/YYYY HH24:MI:SS'), 'Mark', 'DDC', '/ddc/Dispatch?op=SelectDonorPrepare&ctx=cpr', 'DDC', 'SUB_MENU', 'M', '25_PDC_025_CASPRF');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('25_PDC_030_PTHFULL', 'Path Report Full Text', TO_DATE('09/07/2002 09:20:19', 'MM/DD/YYYY HH24:MI:SS'), 'Mark', TO_DATE('09/07/2002 09:20:19', 'MM/DD/YYYY HH24:MI:SS'), 'Mark', 'DDC', '/ddc/Dispatch?op=SelectDonorPrepare&ctx=pfl', 'DDC', 'SUB_MENU', 'M', '25_PDC_030_PTHFULL');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('25_PDC_035_PTHAB', 'Path Report Abstraction', TO_DATE('09/07/2002 09:20:21', 'MM/DD/YYYY HH24:MI:SS'), 'Mark', TO_DATE('09/07/2002 09:20:21', 'MM/DD/YYYY HH24:MI:SS'), 'Mark', 'DDC', '/ddc/Dispatch?op=SelectDonorPrepare&ctx=pab', 'DDC', 'SUB_MENU', 'M', '25_PDC_035_PTHAB');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('25_PDC_040_CDE', 'Clinical Data Extraction', TO_DATE('09/07/2002 09:20:23', 'MM/DD/YYYY HH24:MI:SS'), 'Mark', TO_DATE('09/07/2002 09:20:23', 'MM/DD/YYYY HH24:MI:SS'), 'Mark', 'DDC', '/ddc/Dispatch?op=SelectDonorPrepare&ctx=cde', 'DDC', 'SUB_MENU', 'M', '25_PDC_040_CDE');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('25_PDC_020_DNRPRF', 'Donor Information', TO_DATE('09/07/2002 09:20:15', 'MM/DD/YYYY HH24:MI:SS'), 'Mark', TO_DATE('09/07/2002 09:20:15', 'MM/DD/YYYY HH24:MI:SS'), 'Mark', 'DDC', '/ddc/Dispatch?op=SelectDonorPrepare&ctx=dpr', 'DDC', 'SUB_MENU', 'M', '25_PDC_020_DNRPRF');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('25_PDC_042_CLIN_FND', 'Clinical Findings', TO_DATE('08/05/2005 18:13:31', 'MM/DD/YYYY HH24:MI:SS'), 'JEsielionis', TO_DATE('08/05/2005 18:13:31', 'MM/DD/YYYY HH24:MI:SS'), 'DDC', '/iltds/clinicalFindings/clinicalFindingsStart.do ', 'DDC', 'SUB_MENU', 'M', '25_PDC_042_CLIN_FND');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('30_ORM_040_OTHER', 'Other Code Editor', TO_DATE('09/12/2006 15:23:33', 'MM/DD/YYYY HH24:MI:SS'), 'sthomashow', TO_DATE('09/12/2006 15:23:33', 'MM/DD/YYYY HH24:MI:SS'), 'sthomashow', 'ORM', '/ddc/Dispatch?op=OcePrepare', 'Informatics', 'SUB_MENU', 'M', '30_ORM_040_OTHER');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('40_ORM_012_LBLPRINT', 'Print User Label', TO_DATE('04/05/2003 09:04:11', 'MM/DD/YYYY HH24:MI:SS'), 'Nagaraja', TO_DATE('04/05/2003 09:04:11', 'MM/DD/YYYY HH24:MI:SS'), 'Nagaraja', 'ORM', '/orm/Dispatch?op=GetUser', 'BIGR Administration', 'SUB_MENU', 'M', '40_ORM_012_LBLPRINT');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('40_ORM_50_BUSOBJ', 'Business Objects Reports', TO_DATE('05/15/2004 10:02:36', 'MM/DD/YYYY HH24:MI:SS'), 'sthomashow', TO_DATE('05/15/2004 10:02:36', 'MM/DD/YYYY HH24:MI:SS'), 'sthomashow', 'ORM', '/orm/reports/busObjStart.do?', 'TOP_MENU', 'SUB_MENU', 'M', '40_ORM_50_BUSOBJ');