set define off

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('10_ILTDS_045_NBOXSCAN', 'Box Scan', TO_DATE('04/09/2001 17:52:18', 'MM/DD/YYYY HH24:MI:SS'), 'satty', TO_DATE('04/09/2001 17:52:18', 'MM/DD/YYYY HH24:MI:SS'), 'satty', 'ILTDS', '/iltds/Dispatch?op=BoxScan&title=Box%20Scan', 'Donor Institution - Sample Management', 'Storage', 'M', '10_ILTDS_045_NBOXSCAN');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('10_ILTDS_050_CKOUTINV', 'Check Box out of Inventory', TO_DATE('04/09/2001 17:52:18', 'MM/DD/YYYY HH24:MI:SS'), 'satty', TO_DATE('04/09/2001 17:52:18', 'MM/DD/YYYY HH24:MI:SS'), 'satty', 'ILTDS', '/iltds/Dispatch?op=CheckOutBoxStart&title=Check%20Box%20Out%20Of%20Inventory&location=MI&tx=ardCo', 'Donor Institution - Sample Management', 'Storage', 'M', '10_ILTDS_050_CKOUTINV');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('10_ILTDS_055_UPDBXLOC', 'Update Box Location', TO_DATE('04/09/2001 17:52:18', 'MM/DD/YYYY HH24:MI:SS'), 'satty', TO_DATE('04/09/2001 17:52:18', 'MM/DD/YYYY HH24:MI:SS'), 'satty', 'ILTDS', '/iltds/Dispatch?op=UpdateBoxLocation&title=Update%20Box%20Location&location=MI&popup=false', 'Donor Institution - Sample Management', 'Storage', 'M', '10_ILTDS_055_UPDBXLOC');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('10_ILTDS_085_ABOXSCAN', 'Owner Box Scan', TO_DATE('04/09/2001 17:52:18', 'MM/DD/YYYY HH24:MI:SS'), 'satty', TO_DATE('04/09/2001 17:52:18', 'MM/DD/YYYY HH24:MI:SS'), 'satty', 'ILTDS', '/iltds/Dispatch?op=BoxScan&title=Owner%20Box%20Scan', 'Owner - Sample Mgmt', 'Storage', 'M', '10_ILTDS_085_ABOXSCAN');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('10_ILTDS_090_ACOINV', 'Check Samples out of Inventory', TO_DATE('04/09/2001 17:52:18', 'MM/DD/YYYY HH24:MI:SS'), 'satty', TO_DATE('04/09/2001 17:52:18', 'MM/DD/YYYY HH24:MI:SS'), 'satty', 'ILTDS', '/iltds/Dispatch?op=CheckOutBoxStart&title=Check%20Samples%20Out%20Of%20Inventory&location=AR&tx=CoInv', 'Owner - Sample Mgmt', 'Storage', 'M', '10_ILTDS_090_ACOINV');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('10_ILTDS_100_UPDBXLOC', 'Update Box Location at Owner', TO_DATE('04/09/2001 17:52:18', 'MM/DD/YYYY HH24:MI:SS'), 'satty', TO_DATE('04/09/2001 17:52:18', 'MM/DD/YYYY HH24:MI:SS'), 'satty', 'ILTDS', '/iltds/Dispatch?op=UpdateBoxLocation&title=Update%20Box%20Location&location=AR&popup=false', 'Owner - Sample Mgmt', 'Storage', 'M', '10_ILTDS_100_UPDBXLOC');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('10_ILTDS_104_CRTMAN', 'Create Manifest', TO_DATE('05/15/2004 10:01:50', 'MM/DD/YYYY HH24:MI:SS'), 'sthomashow', TO_DATE('05/15/2004 10:01:50', 'MM/DD/YYYY HH24:MI:SS'), 'sthomashow', 'ILTDS', '/iltds/shipping/createManifestStart.do', 'Shipping', 'SUB_MENU', 'M', '10_ILTDS_104_CRTMAN');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('10_ILTDS_107_SCANPACK', 'Scan and Package', TO_DATE('05/15/2004 10:01:50', 'MM/DD/YYYY HH24:MI:SS'), 'sthomashow', TO_DATE('05/15/2004 10:01:50', 'MM/DD/YYYY HH24:MI:SS'), 'sthomashow', 'ILTDS', '/iltds/shipping/scanAndPackageStart.do', 'Shipping', 'SUB_MENU', 'M', '10_ILTDS_107_SCANPACK');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('10_ILTDS_114_PRNMNFT', 'Print Manifests', TO_DATE('05/15/2004 10:01:50', 'MM/DD/YYYY HH24:MI:SS'), 'sthomashow', TO_DATE('05/15/2004 10:01:50', 'MM/DD/YYYY HH24:MI:SS'), 'sthomashow', 'ILTDS', '/iltds/Dispatch?op=ShippingPrintManifests&title=Print%20Manifests', 'Shipping', 'SUB_MENU', 'M', '10_ILTDS_114_PRNMNFT');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('10_ILTDS_120_RCPTVERF', 'Receipt Verification', TO_DATE('05/15/2004 10:01:50', 'MM/DD/YYYY HH24:MI:SS'), 'sthomashow', TO_DATE('05/15/2004 10:01:50', 'MM/DD/YYYY HH24:MI:SS'), 'sthomashow', 'ILTDS', '/iltds/receipt/verification.do', 'Receiving', 'SUB_MENU', 'M', '10_ILTDS_120_RCPTVERF');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('10_ILTDS_122_SCANSTOR', 'Scan and Store', TO_DATE('05/15/2004 10:01:50', 'MM/DD/YYYY HH24:MI:SS'), 'sthomashow', TO_DATE('05/15/2004 10:01:50', 'MM/DD/YYYY HH24:MI:SS'), 'sthomashow', 'ILTDS', '/iltds/receipt/scanAndStore.do', 'Receiving', 'SUB_MENU', 'M', '10_ILTDS_122_SCANSTOR');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('10_ILTDS_145_ICP', 'ICP', TO_DATE('04/02/2002 10:56:51', 'MM/DD/YYYY HH24:MI:SS'), 'jake', TO_DATE('04/02/2002 10:56:51', 'MM/DD/YYYY HH24:MI:SS'), 'jake', 'ILTDS', '/iltds/Dispatch?op=IcpStart', 'TOP_MENU', 'SUB_MENU', 'M', '10_ILTDS_145_ICP');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('10_ILTDS_147_ICP_SUSR', 'Privilege: ICP Super User', TO_DATE('08/15/2006 16:47:46', 'MM/DD/YYYY HH24:MI:SS'), 'JEsielionis', TO_DATE('08/15/2006 16:47:46', 'MM/DD/YYYY HH24:MI:SS'), 'JEsielionis', 'ILTDS', 'P', '10_ILTDS_147_ICP_SUSR');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('10_ILTDS_150_TXNOTE', 'Add History Note', TO_DATE('08/05/2005 18:04:19', 'MM/DD/YYYY HH24:MI:SS'), 'dkostiew', TO_DATE('08/05/2005 18:04:19', 'MM/DD/YYYY HH24:MI:SS'), 'dkostiew', 'ILTDS', '/iltds/icp/historyNoteStart.do', 'TOP_MENU', 'SUB_MENU', 'M', '10_ILTDS_150_TXNOTE');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('12_ILTDS_10_MNGREQS', 'Manage Requests', TO_DATE('05/15/2004 10:01:49', 'MM/DD/YYYY HH24:MI:SS'), 'sthomashow', TO_DATE('05/15/2004 10:01:49', 'MM/DD/YYYY HH24:MI:SS'), 'sthomashow', 'ILTDS', '/iltds/manageRequestsStart.do', 'Request Management', 'SUB_MENU', 'M', '12_ILTDS_10_MNGREQS');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('12_ILTDS_10_REQSAMP', 'Request Samples', TO_DATE('08/05/2005 18:04:19', 'MM/DD/YYYY HH24:MI:SS'), 'JEsielionis', TO_DATE('08/05/2005 18:04:19', 'MM/DD/YYYY HH24:MI:SS'), 'JEsielionis', 'ILTDS', '/library/start.do?txType=TxRequestSamples', 'Request Management', 'SUB_MENU', 'M', '12_ILTDS_10_REQSAMP');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('12_ILTDS_10_VIEWREQS', 'View Requests', TO_DATE('05/15/2004 10:01:49', 'MM/DD/YYYY HH24:MI:SS'), 'sthomashow', TO_DATE('05/15/2004 10:01:49', 'MM/DD/YYYY HH24:MI:SS'), 'sthomashow', 'ILTDS', '/iltds/viewRequestsStart.do', 'Request Management', 'SUB_MENU', 'M', '12_ILTDS_10_VIEWREQS');

Insert into ard_objects    
	(OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
('12_ILTDS_21_PATH_REQ', 'Privilege: Create Pathology Requests', sysdate, 'SThomashow', sysdate, 'SThomashow', 'ILTDS', null, null, null, 'P', '12_ILTDS_21_PATH_REQ');    

Insert into ard_objects    
	(OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
('12_ILTDS_22_RAND_REQ', 'Privilege: Create RandD Requests', sysdate, 'SThomashow', sysdate, 'SThomashow', 'ILTDS', null, null, null, 'P', '12_ILTDS_22_RAND_REQ'); 

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('15_ES_006_SS', 'Sample Selection', TO_DATE('04/05/2003 09:04:11', 'MM/DD/YYYY HH24:MI:SS'), 'mark', TO_DATE('04/05/2003 09:04:11', 'MM/DD/YYYY HH24:MI:SS'), 'mark', 'BIGR Library', '/library/start.do?txType=TxSampSel', 'Browse/Select Samples', 'SUB_MENU', 'M', '15_ES_006_SS');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('15_ES_010_VIEWITEM', 'View Selected Items', TO_DATE('04/09/2001 17:52:17', 'MM/DD/YYYY HH24:MI:SS'), 'satty', TO_DATE('04/09/2001 17:52:17', 'MM/DD/YYYY HH24:MI:SS'), 'satty', 'BIGR Library', '/library/holdView.do?txType=TxSampSel', 'Browse/Select Samples', 'SUB_MENU', 'M', '15_ES_010_VIEWITEM');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('15_ES_050_PROFILE', 'Change Your Profile', TO_DATE('04/09/2001 17:52:18', 'MM/DD/YYYY HH24:MI:SS'), 'satty', TO_DATE('04/09/2001 17:52:18', 'MM/DD/YYYY HH24:MI:SS'), 'satty', 'BIGR Library', '/orm/users/changeProfileStart.do', 'Account Management', 'SUB_MENU', 'M', '15_ES_050_PROFILE');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('15_ES_SQL_TAB', 'Privilege: Show SQL Tab', TO_DATE('04/05/2003 09:04:12', 'MM/DD/YYYY HH24:MI:SS'), 'sahibul', TO_DATE('04/05/2003 09:04:12', 'MM/DD/YYYY HH24:MI:SS'), 'sahibul', 'BIGR Library', 'P', '15_ES_SQL_TAB');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('15_ES_HOLDLIST_ADDRMV', 'Privilege: Add/Remove from Hold List', TO_DATE('01/23/2003 08:16:30', 'MM/DD/YYYY HH24:MI:SS'), 'sahibul', TO_DATE('01/23/2003 08:16:30', 'MM/DD/YYYY HH24:MI:SS'), 'sahibul', 'BIGR Library', 'P', '15_ES_HOLDLIST_ADDRMV');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('15_ES_HOLDSOLD_USER', 'Privilege: Hold/Sold User', TO_DATE('07/12/2003 11:08:56', 'MM/DD/YYYY HH24:MI:SS'), 'sahibul', TO_DATE('07/12/2003 11:08:56', 'MM/DD/YYYY HH24:MI:SS'), 'sahibul', 'BIGR Library', 'P', '15_ES_HOLDSOLD_USER');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('15_ES_HOLDSOLD_ACCNT', 'Privilege: Hold/Sold Account', TO_DATE('07/12/2003 11:08:56', 'MM/DD/YYYY HH24:MI:SS'), 'sahibul', TO_DATE('07/12/2003 11:08:56', 'MM/DD/YYYY HH24:MI:SS'), 'sahibul', 'BIGR Library', 'P', '15_ES_HOLDSOLD_ACCNT');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('15_ES_CONSENT_VIEW', 'Privilege: View Consent', TO_DATE('11/08/2003 10:21:52', 'MM/DD/YYYY HH24:MI:SS'), 'sthomashow', TO_DATE('11/08/2003 10:21:52', 'MM/DD/YYYY HH24:MI:SS'), 'sthomashow', 'BIGR Library', 'P', '15_ES_CONSENT_VIEW');

Insert into ARD_OBJECTS 
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID) 
 Values 
   ('30_ORM_050_DETVIEWER', 'DET Viewer', sysdate, 'mcacciapouti', sysdate, 'mcacciapouti', 'ORM', '/orm/informatics/detViewer.do', 'Informatics', 'SUB_MENU', 'M', '30_ORM_050_DETVIEWER');

INSERT INTO ARD_OBJECTS 
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
VALUES 
   ('30_ORM_070_VIEWGBOSS', 'View GBOSS Data', TO_DATE('09/12/2007 10:51:52', 'MM/DD/YYYY HH24:MI:SS'), 'JEsielionis', TO_DATE('09/12/2007 10:51:52', 'MM/DD/YYYY HH24:MI:SS'), 'ORM', '/orm/gboss/viewGboss.do', 'Informatics', 'SUB_MENU', 'M', '30_ORM_070_VIEWGBOSS');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('40_ORM_005_ACCTMNG', 'Account Management', TO_DATE('04/09/2001 17:52:19', 'MM/DD/YYYY HH24:MI:SS'), 'satty', TO_DATE('04/09/2001 17:52:19', 'MM/DD/YYYY HH24:MI:SS'), 'satty', 'ORM', '/orm/accounts/findAccountsStart.do', 'BIGR Administration', 'SUB_MENU', 'M', '40_ORM_005_ACCTMNG');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('40_ORM_010_USERMNG', 'User Management', TO_DATE('04/09/2001 17:52:19', 'MM/DD/YYYY HH24:MI:SS'), 'satty', TO_DATE('04/09/2001 17:52:19', 'MM/DD/YYYY HH24:MI:SS'), 'satty', 'ORM', '/orm/users/findUsersStart.do', 'BIGR Administration', 'SUB_MENU', 'M', '40_ORM_010_USERMNG');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('40_ORM_030_PLCYMGR', 'Maintain Policies', TO_DATE('07/30/2004 18:59:10', 'MM/DD/YYYY HH24:MI:SS'), 'sthomashow', TO_DATE('07/30/2004 18:59:10', 'MM/DD/YYYY HH24:MI:SS'), 'sthomashow', 'ORM', '/orm/policy/maintainPolicyStart.do?resetForm=true', 'BIGR Administration', 'SUB_MENU', 'M', '40_ORM_030_PLCYMGR');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('40_ORM_035_MAINTLR', 'Maintain Inventory Groups', TO_DATE('02/07/2004 08:30:28', 'MM/DD/YYYY HH24:MI:SS'), 'gyost', TO_DATE('02/07/2004 08:30:28', 'MM/DD/YYYY HH24:MI:SS'), 'gyost', 'ORM', '/orm/logicalRepository/maintainLogicalReposStart.do?resetForm=true', 'BIGR Administration', 'SUB_MENU', 'M', '40_ORM_035_MAINTLR');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('40_ORM_037_ADDTOIG', 'Add Samples To Inventory Group', TO_DATE('08/11/2005 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SIslam', TO_DATE('08/11/2005 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'ORM', '/orm/moveByIg/moveByIgStart.do?action=Add', 'BIGR Administration', 'SUB_MENU', 'M', '40_ORM_037_ADDTOIG');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('40_ORM_038_MOVEFROMIG', 'Remove Samples From Inventory Group', TO_DATE('08/11/2005 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SIslam', TO_DATE('08/11/2005 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'ORM', '/orm/moveByIg/moveByIgStart.do?action=Remove', 'BIGR Administration', 'SUB_MENU', 'M', '40_ORM_038_MOVEFROMIG');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('40_ORM_040_MAINBXLYS', 'Maintain Box Layouts', TO_DATE('04/01/2005 16:39:10', 'MM/DD/YYYY HH24:MI:SS'), 'dkostiew', TO_DATE('04/01/2005 16:39:10', 'MM/DD/YYYY HH24:MI:SS'), 'dkostiew', 'ORM', '/orm/boxLayout/maintainBoxLayoutStart.do?resetForm=true', 'BIGR Administration', 'SUB_MENU', 'M', '40_ORM_040_MAINBXLYS');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('40_ORM_VIEW_ALL_LRS', 'Privilege: View All Logical Repositories', TO_DATE('02/07/2004 08:44:55', 'MM/DD/YYYY HH24:MI:SS'), 'JEsielionis', TO_DATE('02/07/2004 08:44:55', 'MM/DD/YYYY HH24:MI:SS'), 'JEsielionis', 'ORM', 'P', '40_ORM_VIEW_ALL_LRS');


Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('40_ORM_062_FORMCREATE', 'Form Designer', TO_DATE('08/07/2006 18:31:13', 'MM/DD/YYYY HH24:MI:SS'), 'mcacciapouti', TO_DATE('08/07/2006 18:31:13', 'MM/DD/YYYY HH24:MI:SS'), 'mcacciapouti', 'ORM', '/kc/formdef/start.do', 'BIGR Administration', 'SUB_MENU', 'M', '40_ORM_062_FORMCREATE');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('40_ORM_065_VIEWSYSCFG', 'View System Configuration', TO_DATE('05/13/2006 10:51:52', 'MM/DD/YYYY HH24:MI:SS'), 'JEsielionis', TO_DATE('05/13/2006 10:51:52', 'MM/DD/YYYY HH24:MI:SS'), 'ORM', '/orm/systemConfiguration/viewSystemConfiguration.do', 'BIGR Administration', 'SUB_MENU', 'M', '40_ORM_065_VIEWSYSCFG');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('40_ORM_060_MAINTURLS', 'Maintain URLs', TO_DATE('08/05/2005 18:04:18', 'MM/DD/YYYY HH24:MI:SS'), 'JEsielionis', TO_DATE('08/05/2005 18:04:18', 'MM/DD/YYYY HH24:MI:SS'), 'JEsielionis', 'ORM', '/orm/url/maintainAccountUrlStart.do?resetForm=true', 'BIGR Administration', 'SUB_MENU', 'M', '40_ORM_060_MAINTURLS');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('50_IMP_10_CREATEDONOR', 'Create Donor (SR)', TO_DATE('04/01/2005 16:43:43', 'MM/DD/YYYY HH24:MI:SS'), 'JEsielionis', TO_DATE('04/01/2005 16:43:43', 'MM/DD/YYYY HH24:MI:SS'), 'JEsielionis', 'Sample Registration', '/dataImport/createDonorStart.do', 'Sample Registration', 'Donor Management', 'M', '50_IMP_10_CREATEDONOR');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('50_IMP_15_MODIFYDONOR', 'Modify Donor (SR)', TO_DATE('04/01/2005 16:43:43', 'MM/DD/YYYY HH24:MI:SS'), 'JEsielionis', TO_DATE('04/01/2005 16:43:43', 'MM/DD/YYYY HH24:MI:SS'), 'JEsielionis', 'Sample Registration', '/dataImport/modifyDonorStart.do', 'Sample Registration', 'Donor Management', 'M', '50_IMP_15_MODIFYDONOR');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('50_IMP_20_CREATECASE', 'Create Case (SR)', TO_DATE('04/01/2005 16:43:43', 'MM/DD/YYYY HH24:MI:SS'), 'JEsielionis', TO_DATE('04/01/2005 16:43:43', 'MM/DD/YYYY HH24:MI:SS'), 'JEsielionis', 'Sample Registration', '/dataImport/createCaseStart.do?validate=false', 'Sample Registration', 'Case Management', 'M', '50_IMP_20_CREATECASE');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('50_IMP_25_MODIFYCASE', 'Modify Case (SR)', TO_DATE('04/01/2005 16:43:43', 'MM/DD/YYYY HH24:MI:SS'), 'JEsielionis', TO_DATE('04/01/2005 16:43:43', 'MM/DD/YYYY HH24:MI:SS'), 'JEsielionis', 'Sample Registration', '/dataImport/selectCaseToModify.do', 'Sample Registration', 'Case Management', 'M', '50_IMP_25_MODIFYCASE');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('50_IMP_30_CASEPULL', 'Pull Case (SR)', TO_DATE('04/01/2005 16:43:43', 'MM/DD/YYYY HH24:MI:SS'), 'JEsielionis', TO_DATE('04/01/2005 16:43:43', 'MM/DD/YYYY HH24:MI:SS'), 'JEsielionis', 'Sample Registration', '/dataImport/selectCaseToPull.do', 'Sample Registration', 'Case Management', 'M', '50_IMP_30_CASEPULL');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('50_IMP_40_MODIFYSAMP', 'Modify Sample (SR)', TO_DATE('04/01/2005 16:43:43', 'MM/DD/YYYY HH24:MI:SS'), 'JEsielionis', TO_DATE('04/01/2005 16:43:43', 'MM/DD/YYYY HH24:MI:SS'), 'JEsielionis', 'Sample Registration', '/dataImport/selectSampleToModify.do', 'Sample Registration', 'Sample Management', 'M', '50_IMP_40_MODIFYSAMP');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('50_IMP_45_CASEPRF', 'Case Profile Entry (SR)', TO_DATE('04/01/2005 16:43:43', 'MM/DD/YYYY HH24:MI:SS'), 'JEsielionis', TO_DATE('04/01/2005 16:43:43', 'MM/DD/YYYY HH24:MI:SS'), 'JEsielionis', 'Sample Registration', '/dataImport/caseProfileEntryStart.do', 'Sample Registration', 'Clinical Data Management', 'M', '50_IMP_45_CASEPRF');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('50_IMP_50_PATHREPFULL', 'Path Report Full Text (SR)', TO_DATE('04/01/2005 16:43:43', 'MM/DD/YYYY HH24:MI:SS'), 'JEsielionis', TO_DATE('04/01/2005 16:43:43', 'MM/DD/YYYY HH24:MI:SS'), 'JEsielionis', 'Sample Registration', '/dataImport/pathReportFullTextStart.do', 'Sample Registration', 'Clinical Data Management', 'M', '50_IMP_50_PATHREPFULL');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('50_IMP_55_PATHREPABS', 'Path Report Abstraction (SR)', TO_DATE('04/01/2005 16:43:43', 'MM/DD/YYYY HH24:MI:SS'), 'JEsielionis', TO_DATE('04/01/2005 16:43:43', 'MM/DD/YYYY HH24:MI:SS'), 'JEsielionis', 'Sample Registration', '/dataImport/pathReportAbstractionStart.do', 'Sample Registration', 'Clinical Data Management', 'M', '50_IMP_55_PATHREPABS');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('50_IMP_60_CLINDATAEXT', 'Clinical Data Extraction (SR)', TO_DATE('04/01/2005 16:43:43', 'MM/DD/YYYY HH24:MI:SS'), 'JEsielionis', TO_DATE('04/01/2005 16:43:43', 'MM/DD/YYYY HH24:MI:SS'), 'JEsielionis', 'Sample Registration', '/dataImport/clinicalDataExtractionStart.do', 'Sample Registration', 'Clinical Data Management', 'M', '50_IMP_60_CLINDATAEXT');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('50_IMP_35_CREATESAMP', 'Create Sample (SR)', TO_DATE('04/01/2005 16:43:43', 'MM/DD/YYYY HH24:MI:SS'), 'JEsielionis', TO_DATE('04/01/2005 16:43:43', 'MM/DD/YYYY HH24:MI:SS'), 'JEsielionis', 'Sample Registration', '/dataImport/createSampleStart.do', 'Sample Registration', 'Sample Management', 'M', '50_IMP_35_CREATESAMP');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('50_IMP_65_FINDBYID', 'Find by Id (SR)', TO_DATE('04/01/2005 16:43:43', 'MM/DD/YYYY HH24:MI:SS'), 'JEsielionis', TO_DATE('04/01/2005 16:43:43', 'MM/DD/YYYY HH24:MI:SS'), 'JEsielionis', 'Sample Registration', '/dataImport/findByIdStart.do', 'Sample Registration', 'SUB_MENU', 'M', '50_IMP_65_FINDBYID');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('50_IMP_70_DERIV', 'Derivative Operations', TO_DATE('09/12/2006 15:23:33', 'MM/DD/YYYY HH24:MI:SS'), 'sthomashow', TO_DATE('09/12/2006 15:23:33', 'MM/DD/YYYY HH24:MI:SS'), 'sthomashow', 'Sample Registration', '/iltds/derivation/derivationBatchStart.do', 'Sample Registration', 'SUB_MENU', 'M', '50_IMP_70_DERIV');

Insert into ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 Values
   ('50_IMP_90_PRNTLBLS', 'Print Labels', TO_DATE('09/18/2008 16:43:43', 'MM/DD/YYYY HH24:MI:SS'), 'JEsielionis', TO_DATE('09/18/2008 16:43:43', 'MM/DD/YYYY HH24:MI:SS'), 'JEsielionis', 'Sample Registration', '/dataImport/printLabelsStart.do','Sample Registration', 'SUB_MENU', 'M', '50_IMP_90_PRNTLBLS');

INSERT INTO ARD_OBJECTS 
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID) 
 VALUES ('40_ORM_015_MAINTROLES', 'Maintain Roles', TO_DATE('10/01/2009 09:39:14', 'MM/DD/YYYY HH24:MI:SS'), 'JEsielionis', TO_DATE('10/01/2009 09:39:14', 'MM/DD/YYYY HH24:MI:SS'), 'JEsielionis','ORM', '/orm/role/maintainRoleStart.do?resetForm=true', 'BIGR Administration', 'SUB_MENU', 'M', '40_ORM_015_MAINTROLES');

INSERT INTO ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 VALUES ('40_ORM_SHARE_VIEW', 'View Admin', TO_DATE('08/28/2012 14:18:00', 'MM/DD/YYYY HH24:MI:SS'), 'RBoris', TO_DATE('08/28/2012 14:18:01', 'MM/DD/YYYY HH24:MI:SS'), 'RBoris', 'ORM', null, null, null, 'P', '40_ORM_SHARE_VIEW');

INSERT INTO ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 VALUES ('40_ORM_20_SAMPLEVIEW', 'Sample View', TO_DATE('09/06/2012 12:04:00', 'MM/DD/YYYY HH24:MI:SS'), 'RBoris', TO_DATE('09/06/2012 12:04:01', 'MM/DD/YYYY HH24:MI:SS'), 'RBoris', 'ORM', null, null, null, 'P', '40_ORM_20_SAMPLEVIEW');

INSERT INTO ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 VALUES ('40_ORM_20_DONORVIEW', 'Donor View', TO_DATE('09/06/2012 12:04:00', 'MM/DD/YYYY HH24:MI:SS'), 'RBoris', TO_DATE('09/06/2012 12:04:01', 'MM/DD/YYYY HH24:MI:SS'), 'RBoris', 'ORM', null, null, null, 'P', '40_ORM_20_DONORVIEW');

INSERT INTO ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 VALUES ('40_ORM_20_CASEVIEW', 'Case View', TO_DATE('09/06/2012 12:04:00', 'MM/DD/YYYY HH24:MI:SS'), 'RBoris', TO_DATE('09/06/2012 12:04:01', 'MM/DD/YYYY HH24:MI:SS'), 'RBoris', 'ORM', null, null, null, 'P', '40_ORM_20_CASEVIEW');

INSERT INTO ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 VALUES ('40_ORM_20_VIEWMNG', 'Manage View', TO_DATE('09/06/2012 12:04:00', 'MM/DD/YYYY HH24:MI:SS'), 'RBoris', TO_DATE('09/06/2012 12:04:01', 'MM/DD/YYYY HH24:MI:SS'), 'RBoris', 'ORM', null, null, null, 'P', '40_ORM_20_VIEWMNG');

INSERT INTO ARD_OBJECTS
   (OBJECT_ID, OBJECT_DESCRIPTION, CREATE_DATE, CREATED_BY, UPDATE_DATE, UPDATED_BY, LONG_DESCRIPTION, URL, TOP_MENU, SUB_MENU, OBJECT_TYPE, PRIVILEGE_ID)
 VALUES ('85_REPORT_01_STORAGE', 'Storage Report', TO_DATE('05/16/2013 12:48:25', 'MM/DD/YYYY HH24:MI:SS'), 'RBoris', TO_DATE('05/16/2013 12:48:24', 'MM/DD/YYYY HH24:MI:SS'), 'RBoris', 'Storage Report', '/reports/storageReport.do', 'Reports', 'SUB_MENU', 'M', '85_REPORT_01_STORAGE');

--  DEPENDED PRIVILEGES
INSERT INTO DEPENDED_PRIVILEGES(PRIVILEGE_ID, DEPENDED_PRIVILEGE_ID) VALUES ('85_REPORT_01_STORAGE', '50_IMP_35_CREATESAMP');
INSERT INTO DEPENDED_PRIVILEGES(PRIVILEGE_ID, DEPENDED_PRIVILEGE_ID) VALUES ('85_REPORT_01_STORAGE', '50_IMP_40_MODIFYSAMP');
INSERT INTO DEPENDED_PRIVILEGES(PRIVILEGE_ID, DEPENDED_PRIVILEGE_ID) VALUES ('85_REPORT_01_STORAGE', '10_ILTDS_145_ICP');
INSERT INTO DEPENDED_PRIVILEGES(PRIVILEGE_ID, DEPENDED_PRIVILEGE_ID) VALUES ('85_REPORT_01_STORAGE', '10_ILTDS_122_SCANSTOR');
INSERT INTO DEPENDED_PRIVILEGES(PRIVILEGE_ID, DEPENDED_PRIVILEGE_ID) VALUES ('85_REPORT_01_STORAGE', '10_ILTDS_085_ABOXSCAN');
INSERT INTO DEPENDED_PRIVILEGES(PRIVILEGE_ID, DEPENDED_PRIVILEGE_ID) VALUES ('85_REPORT_01_STORAGE', '10_ILTDS_100_UPDBXLOC');