set define off;

update pdc_lookup set no_cui_yn='Y', annotation='added NoVal', rev='1.50', drev='17' where lookup_type_cd ='CA08247C';
update pdc_lookup set lookup_type_cd_desc ='Esophageal Bravo pH monitoring', system_name = 'esop_bravo_ph_moni', annotation='change name, sysname', rev='1.50', drev='17' where lookup_type_cd ='CA06033C';
update pdc_lookup set lookup_type_cd_desc ='Upper esophagus', annotation='change name', rev='1.50', drev='17' where lookup_type_cd ='CA11493C';
update pdc_lookup set lookup_type_cd_desc ='Mid esophagus', annotation='change name', rev='1.50', drev='17' where lookup_type_cd ='CA11494C';
update pdc_lookup set lookup_type_cd_desc ='Lower esophagus (not including GEJ)', annotation='change name', rev='1.50', drev='17' where lookup_type_cd ='CA11495C';
update pdc_lookup set lookup_type_cd_desc ='Lower esophagus (including GEJ)', annotation='change name', rev='1.50', drev='17' where lookup_type_cd ='CA11496C';
update pdc_lookup set lookup_type_cd_desc ='No lymphadenopathy', annotation='change name', rev='1.50', drev='17' where lookup_type_cd ='CA08166C';

update pdc_dx_tc_hierarchy set parent_code ='128348002^^', order_by ='1775', grp ='ANDIG', rev = '1.50' where owner_code = '37657006^25723000^';
update pdc_lookup set domain_ref ='128348002^^', rev='1.50', drev='17' where lookup_type_cd ='37657006^25723000^';

delete from pdc_lookup where lookup_type_cd = 'CA08497C';
delete from pdc_lookup where lookup_type_cd = 'CA11251C';
delete from pdc_lookup where lookup_type_cd = 'CA11252C';
delete from pdc_lookup where lookup_type_cd = 'CA11255C';
delete from pdc_lookup where lookup_type_cd = 'CA11256C';
delete from pdc_lookup where lookup_type_cd = 'CA11258C';
delete from pdc_lookup where lookup_type_cd = 'CA11261C';
delete from pdc_lookup where lookup_type_cd = 'CA11263C';
delete from pdc_lookup where lookup_type_cd = 'CA11517C';
delete from pdc_lookup where lookup_type_cd = 'CA11277C';

insert into pdc_dx_tc_hierarchy values ('CA12546C', 'Antireflux procedure', '118673008', '2', 'P', '505', '', 'A', 'P', 'DIG', '1.50', '');
insert into pdc_dx_tc_hierarchy values ('CA12554C', 'Endomucosal resection  ~  EMR', '118673008', '2', 'P', '645', '', 'A', 'P', 'DIG', '1.50', '');
insert into pdc_dx_tc_hierarchy values ('CA12547C', 'Esophagectomy, en-bloc', '118673008', '2', 'P', '651', '', 'A', 'P', 'DIG', '1.50', '');
insert into pdc_dx_tc_hierarchy values ('CA12548C', 'Esophagectomy, Ivor-Lewis', '118673008', '2', 'P', '653', '', 'A', 'P', 'DIG', '1.50', '');
insert into pdc_dx_tc_hierarchy values ('CA12549C', 'Esophagectomy, laparoscopic', '118673008', '2', 'P', '654', '', 'A', 'P', 'DIG', '1.50', '');
insert into pdc_dx_tc_hierarchy values ('CA12550C', 'Esophagectomy, minimally invasive  ~  MIE', '118673008', '2', 'P', '656', '', 'A', 'P', 'DIG', '1.50', '');
insert into pdc_dx_tc_hierarchy values ('CA12552C', 'Esophagectomy, transhiatal', '118673008', '2', 'P', '657', '', 'A', 'P', 'DIG', '1.50', '');
insert into pdc_dx_tc_hierarchy values ('CA12551C', 'Esophagectomy, transthoracic with cervical anastomosis', '118673008', '2', 'P', '658', '', 'A', 'P', 'DIG', '1.50', '');
insert into pdc_dx_tc_hierarchy values ('CA12553C', 'Esophagectomy, vagal sparing', '118673008', '2', 'P', '659', '', 'A', 'P', 'DIG', '1.50', '');
insert into pdc_dx_tc_hierarchy values ('CA12507C', 'Hysterectomy with salpingo-oophorectomy', '118675001', '2', 'P', '1055', '', 'A', 'P', 'FRS', '1.50', '');
insert into pdc_dx_tc_hierarchy values ('CA12569C', 'Esophagus, cardiac mucosa', '86762007', '2', 'T', '703 ', '', 'A', 'P', 'DIG', '1.50', '');
insert into pdc_dx_tc_hierarchy values ('CA12570C', 'Esophagus, oxyntocardiac mucosa', '86762007', '2', 'T', '707 ', '', 'A', 'P', 'DIG', '1.50', '');
insert into pdc_dx_tc_hierarchy values ('126839008^35917007^', 'Adenocarcinoma of cecum', '128348002^^', '3', 'D', '755', '1', 'A', 'P', 'ANDIG', '1.50', '');
insert into pdc_dx_tc_hierarchy values ('CA01800D^35917007^8707003', 'Adenocarcinoma, metastatic, consistent with pancreas or biliary primary', '128348002^^', '3', 'D', '1175', '1', 'A', 'P', 'ANDIG', '1.50', '');
insert into pdc_dx_tc_hierarchy values ('CA12510C^90282004^8707003', 'Adenocarcinoma, papillary serous, metastatic, consistent with ovarian or peritoneum primary', '128348002^^', '3', 'D', '1225', '1', 'A', 'P', 'ANDIG', '1.50', '');
insert into pdc_dx_tc_hierarchy values ('126859007^CA12509C^', 'Cystadenoma of pancreas, serous, microcystic', '128348002^^', '3', 'D', '1772', '1', 'A', 'P', 'ANDIG', '1.50', '');
insert into pdc_dx_tc_hierarchy values ('37657006^25723000^395530002', 'Dysplasia of esophagus, high grade', '128348002^^', '3', 'D', '1776', '1', 'A', 'P', 'ANDIG', '1.50', '');
insert into pdc_dx_tc_hierarchy values ('37657006^25723000^399415002', 'Dysplasia of esophagus, low grade', '128348002^^', '3', 'D', '1777', '1', 'A', 'P', 'ANDIG', '1.50', '');
insert into pdc_dx_tc_hierarchy values ('37657006^25723000^82334004', 'Dysplasia of esophagus, indeterminate', '128348002^^', '3', 'D', '1778', '2', 'A', 'P', 'ANDIG', '1.50', '');
insert into pdc_dx_tc_hierarchy values ('126817006^CA00142M^', 'Tumor of esophagus', '128348002^^', '3', 'D', '2045', '1', 'A', 'P', 'ANDIG', '1.50', '');
insert into pdc_dx_tc_hierarchy values ('126832004^CA12508C^', 'Tumor of small intestine, gastrinoma, neuroendocrine', '128348002^^', '3', 'D', '2185', '1', 'A', 'P', 'ANDIG', '1.50', '');
insert into pdc_dx_tc_hierarchy values ('126824007^CA00142M^', 'Tumor of stomach', '128348002^^', '3', 'D', '2187', '1', 'A', 'P', 'ANDIG', '1.50', '');
insert into pdc_dx_tc_hierarchy values ('126788000^27230006^', 'Adenoma of parotid gland, basal cell', '255055008^^', '3', 'D', '4785', '1', 'A', 'P', 'ANHAN', '1.50', '');
insert into pdc_dx_tc_hierarchy values ('37657006^399617002^', 'Carditis of esophagus', '53619000^^', '3', 'D', '10155', '2', 'A', 'P', 'DDIG', '1.50', '');
insert into pdc_dx_tc_hierarchy values ('CA12572C^^', 'Columnar lined esophagus', '53619000^^', '3', 'D', '10435', '2', 'A', 'P', 'DDIG', '1.50', '');
insert into pdc_dx_tc_hierarchy values ('51615001^112674009^', 'Fibrosis of lung', '50043002^^', '3', 'D', '14265', '3', 'A', 'P', 'DRES', '1.50', '');

insert into pdc_lookup values('PATIENT_INFORMATION', 'CA12406C', 'Donor notes', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'donor_note', '1', 'N', 'text', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('DEMOGRAPHIC_DATA', 'CA12407C', 'Ethnicity', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'ethnicity', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('DEMOGRAPHIC_DATA', 'CA12408C', 'Year of birth', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'year_birth', '1', 'N', 'int', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('PATIENT_INFORMATION', 'CA12521C', 'Age at visit', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'age_visit', '1', 'N', 'int', '', 'Element', '', '', '125', 'Y', 'Y', '', 'N', '', '17', '');
insert into pdc_lookup values('PATIENT_INFORMATION', 'CA12327C', 'Consent type', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'consent_type', 'N', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('CLINICAL_SYMPTOM', 'CA12522C', 'Primary symptom', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'symptom_primary', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('CLINICAL_SYMPTOM', 'CA12523C', 'Secondary symptoms', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'symptom_secondary', 'N', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('MEDICATION', 'CA12524C', 'Lab GI medication', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'lab_gi_med', 'N', 'Y', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('GASTROINTESTINAL_STUDY', 'CA12328C', 'Esophageal impedance', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'esoph_impedance', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('GASTROINTESTINAL_STUDY', 'CA12329C', 'Esophageal 24 hour pH monitor', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'esop_hr_ph_moni', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('LAB_IMAGING', 'CA12330C', 'Lab PET mass', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'lab_pet_mass', 'N', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('ENDOSCOPIC_STUDY', 'CA12331C', 'Endoscopy case ID', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'endo_case_id', '1', 'N', 'text', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('ENDOSCOPIC_STUDY', 'CA12332C', 'Timing of endoscopy', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'timing_endo', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('ENDOSCOPIC_STUDY', 'CA12333C', 'Date of endoscopy', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'date_of_endo', '1', 'N', 'date', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('ENDOSCOPIC_STUDY', 'CA12334C', 'Endoscopy finding', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'endo_finding', 'N', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('ENDOSCOPIC_STUDY', 'CA12335C', 'Distance to GE junction', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'distance_to_gej', '1', 'N', 'float', '', 'Element', 'CA05620C', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('CHEMOTHERAPY_HISTORY', 'CA12525C', 'Chemotherapy history 2', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'chemo_hx_two', 'N', 'Y', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('MEDICATION_HISTORY', 'CA12336C', 'Gastrointestinal medication history - NO ADE', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'gast_med_his_no_ade', 'N', 'Y', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('RADIOTHERAPY_HISTORY', 'CA12526C', 'Radiotherapy history 2', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'radi_ther_hist_two', 'N', 'Y', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('CASE_INFORMATION', 'CA12412C', 'Case diagnosis', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'case_dx', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('CASE_INFORMATION', 'CA12413C', 'Case comment', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'case_comment', '1', 'N', 'report', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('TOPIC', 'CA12414C', 'Sample Information', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'sample_info', '', 'N', '', '', 'Category', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12415C', 'Buffer type', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'buffer_type', '1', 'Y', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12416C', 'Cells per ml', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'cells_per_ml', '1', 'N', 'int', '', 'Element', '', '', '', 'N', '', '', 'N', '', '17', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12417C', 'Concentration', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'concentration', '1', 'N', 'float', '', 'Element', 'CA09398C', '', '', 'N', '', '', 'N', '', '17', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12418C', 'Date of collection', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'date_collection', '1', 'N', 'date', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12419C', 'Time of collection - hour', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'time_collect_hour', '1', 'N', 'int', '', 'Element', '', '', '23', 'Y', 'Y', '', 'N', '', '17', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12420C', 'Time of collection - min', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'time_collect_min', '1', 'N', 'int', '', 'Element', '', '', '59', 'Y', 'Y', '', 'N', '', '17', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12421C', 'Time of collection - am pm', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'time_collect_ampm', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12422C', 'Date of preservation', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'date_preserve', '1', 'N', 'date', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12423C', 'Time of preservation - hour', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'time_preserve_hour', '1', 'N', 'int', '', 'Element', '', '', '23', 'Y', 'Y', '', 'N', '', '17', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12424C', 'Time of preservation - min', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'time_preserve_min', '1', 'N', 'int', '', 'Element', '', '', '59', 'Y', 'Y', '', 'N', '', '17', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12425C', 'Time of preservation - am pm', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'time_preserve_ampm', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12426C', 'Derivation operation', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'deriv_op', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12427C', 'Fixative type', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'fixative_type', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12428C', 'Format detail', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'format_detail', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12429C', 'Gross appearance', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'gross_appear', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12430C', 'Percent viability', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'percent_viable', '1', 'N', 'float', '', 'Element', 'CA05658C', '', '100', 'Y', 'Y', '', 'N', '', '17', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12431C', 'Prepared by', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'prepared_by', '1', 'N', 'text', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12432C', 'Sample comment', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'sample_comment', '1', 'N', 'report', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12433C', 'Sample source', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'sample_source', '1', 'N', 'text', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12434C', 'Sample type', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'sample_type', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12435C', 'Sample volume', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'sample_volume', '1', 'N', 'int', '', 'Element', '', '', '', 'N', '', '', 'N', '', '17', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12436C', 'Sample volume units', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'sample_volume_unit', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12437C', 'Sample weight', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'sample_weight', '1', 'N', 'float', '', 'Element', '', '', '', 'N', '', '', 'N', '', '17', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12438C', 'Sample weight units', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'sample_weight_unit', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12439C', 'Storage type', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'storage_type', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12440C', 'Total number of cells', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'total_num_cells', '1', 'N', 'int', '', 'Element', '', '', '', 'N', '', '', 'N', '', '17', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12499C', 'Total cells exponent', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'total_cells_exponent', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12441C', 'Yield', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'yield', '1', 'N', 'float', '', 'Element', 'CA09559C', '', '', 'Y', '', '', 'N', '', '17', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12527C', 'Time of blood draw', '', '', 'ARD_CAP', 'A', 'P', 'for reg form', '1.50', '', 'time_blood_draw', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('PATHOLOGY_REPORT', 'CA12511C', 'Secondary diagnoses', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'secondary_dx', 'N', 'Y', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('PATHOLOGIC_DISEASE_PROGRESSION_MEASURE', 'CA12346C', 'Positive tumor margins', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'pos_tumor_margin', 'N', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12445C', 'Blank AR field 1', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'blank_ar_one', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12446C', 'Blank AR field 2', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'blank_ar_two', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12447C', 'Blank AR field 3', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'blank_ar_three', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12451C', 'Blank percent float field 1', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'blank_perc_float_one', '1', 'N', 'float', '', 'Element', 'CA05658C', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12452C', 'Blank percent float field 2', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'blank_perc_float_two', '1', 'N', 'float', '', 'Element', 'CA05658C', '', '100', 'Y', 'Y', '', 'N', '', '17', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12453C', 'Blank percent integer field 1', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'blank_perc_int_one', '1', 'N', 'int', '', 'Element', 'CA05658C', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12454C', 'Blank percent integer field 2', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'blank_perc_int_two', '1', 'N', 'int', '', 'Element', 'CA05658C', '', '100', 'Y', 'Y', '', 'N', '', '17', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12455C', 'Blank float field 4', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'blank_float_four', '1', 'N', 'float', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12456C', 'Blank float field 5', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'blank_float_five', '1', 'N', 'float', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12457C', 'Blank integer field 4', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'blank_integer_four', '1', 'N', 'int', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12458C', 'Blank integer field 5', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'blank_integer_five', '1', 'N', 'int', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12459C', 'Blank cv1 date ade field', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'blank_cv1_date_ade', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12460C', 'Blank cv1 blank ade field 1', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'blank_cv1_ade_one', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12461C', 'Blank cv1 blank ade field 2', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'blank_cv1_ade_two', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12462C', 'Blank cvN date ade field', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'blank_cvn_date_ade', 'N', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12463C', 'Blank cvN blank ade field 1', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'blank_cvn_ade_one', 'N', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12464C', 'Blank cvN blank ade field 2', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'blank_cvn_ade_two', 'N', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12465C', 'Blank float date ade field', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'blank_float_date_ade', '1', 'N', 'float', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12466C', 'Blank float blank ade field', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'blank_float_ade', '1', 'N', 'float', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12467C', 'Blank cv1 study report ade field', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'blank_cv1_st_rpt_ade', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('ADE_NAME', 'CA12559C', 'Sx Score', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'sx_score_ade', '', 'N', '', '', 'ADE', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('ADE_PARAMETER', 'CA12560C', 'Symptom score', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'symptom_score', '1', 'N', 'cv', '', 'ADEElement', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('ADE_NAME', 'CA12555C', 'Cancer Rx Response', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'ca_rx_response_ade', '', 'N', '', '', 'ADE', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('ADE_PARAMETER', 'CA12556C', 'Date rx started', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'date_rx_start', '1', 'N', 'VPD', '', 'ADEElement', '', '', 'today', '', 'Y', '', 'N', '', '17', '');
insert into pdc_lookup values('ADE_PARAMETER', 'CA12557C', 'Date most recent rx', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'date_recent_rx', '1', 'N', 'VPD', '', 'ADEElement', '', '', 'today', '', 'Y', '', 'N', '', '17', '');
insert into pdc_lookup values('ADE_PARAMETER', 'CA12558C', 'Rx response', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'rx_response', '1', 'N', 'cv', '', 'ADEElement', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('ADE_NAME', 'CA12573C', 'Med Dates', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'med_dates_ade', '', 'N', '', '', 'ADE', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('ADE_PARAMETER', 'CA12574C', 'Date meds started', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'date_meds_start', '1', 'N', 'VPD', '', 'ADEElement', '', '', 'today', '', 'Y', '', 'N', '', '17', '');
insert into pdc_lookup values('ADE_PARAMETER', 'CA12575C', 'Date most recent meds', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'date_recent_meds', '1', 'N', 'VPD', '', 'ADEElement', '', '', 'today', '', 'Y', '', 'N', '', '17', '');
insert into pdc_lookup values('ADE_NAME', 'CA12337C', 'Esophageal pH', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'esoph_ph_ade', '', 'N', '', '', 'ADE', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('ADE_PARAMETER', 'CA12512C', 'Date of esophageal pH', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'date_of_esoph_ph', '1', 'N', 'date', '', 'ADEElement', '', '', 'today', '', 'Y', '', 'N', '', '17', '');
insert into pdc_lookup values('ADE_PARAMETER', 'CA12338C', 'DeMeester score', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'demeester_score', '1', 'N', 'float', '', 'ADEElement', '', '', '200', 'Y', 'Y', '', 'N', '', '17', '');
insert into pdc_lookup values('ADE_NAME', 'CA12339C', 'Esophageal US', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'esoph_us_ade', '', 'N', '', '', 'ADE', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('ADE_PARAMETER', 'CA12513C', 'Date of esophageal US', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'date_of_esoph_us', '1', 'N', 'date', '', 'ADEElement', '', '', 'today', '', 'Y', '', 'N', '', '17', '');
insert into pdc_lookup values('ADE_PARAMETER', 'CA12340C', 'Ultrasound T stage', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'us_t_stage', '1', 'N', 'cv', '', 'ADEElement', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('ADE_PARAMETER', 'CA12341C', 'Ultrasound N stage', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'us_n_stage', '1', 'N', 'cv', '', 'ADEElement', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('ADE_PARAMETER', 'CA12516C', 'Esophageal US report', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'esoph_us_report', '1', 'N', 'report', '', 'ADEElement', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('ADE_PARAMETER', 'CA12514C', 'Date of CT', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'date_of_ct', '1', 'N', 'date', '', 'ADEElement', '', '', 'today', '', 'Y', '', 'N', '', '17', '');
insert into pdc_lookup values('ADE_PARAMETER', 'CA12518C', 'Lab CT timepoint', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'lab_ct_timepoint', '1', 'N', 'cv', '', 'ADEElement', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('ADE_PARAMETER', 'CA12343C', 'Esophageal mass', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'esophageal_mass', 'N', 'N', 'cv', '', 'ADEElement', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('ADE_PARAMETER', 'CA12344C', 'Liver metastasis', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'liver_met', '1', 'N', 'cv', '', 'ADEElement', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('ADE_PARAMETER', 'CA12345C', 'Lung metastasis', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'lung_met', '1', 'N', 'cv', '', 'ADEElement', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('ADE_PARAMETER', 'CA12517C', 'Lab CT report', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'lab_ct_report', '1', 'N', 'report', '', 'ADEElement', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('ADE_PARAMETER', 'CA12515C', 'Date of PET', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'date_of_pet', '1', 'N', 'date', '', 'ADEElement', '', '', 'today', '', 'Y', '', 'N', '', '17', '');
insert into pdc_lookup values('ADE_PARAMETER', 'CA12520C', 'Lab PET timepoint', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'lab_pet_timepoint', '1', 'N', 'cv', '', 'ADEElement', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('ADE_PARAMETER', 'CA12519C', 'Lab PET report', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'lab_pet_report', '1', 'N', 'report', '', 'ADEElement', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('ADE_NAME', 'CA12404C', 'Lab PET Mass', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'lab_pet_mass_ade', '', 'N', '', '', 'ADE', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('ADE_NAME', 'CA12468C', 'Blank ADE 1', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'blank_ade_one', '', 'N', '', '', 'ADE', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('ADE_PARAMETER', 'CA12469C', 'Blank ADE E1', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'blank_ade_e1', '1', 'N', 'cv', '', 'ADEElement', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('ADE_PARAMETER', 'CA12470C', 'Blank ADE E2', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'blank_ade_e2', 'N', 'N', 'cv', '', 'ADEElement', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('ADE_NAME', 'CA12471C', 'Blank ADE 2', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'blank_ade_two', '', 'N', '', '', 'ADE', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('ADE_PARAMETER', 'CA12472C', 'Blank ADE E3', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'blank_ade_e3', '1', 'N', 'cv', '', 'ADEElement', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('ADE_PARAMETER', 'CA12473C', 'Blank ADE E4', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'blank_ade_e4', '1', 'N', 'cv', '', 'ADEElement', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('ADE_PARAMETER', 'CA12474C', 'Blank ADE E5', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'blank_ade_e5', 'N', 'N', 'cv', '', 'ADEElement', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('ADE_PARAMETER', 'CA12475C', 'Blank ADE E6', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'blank_ade_e6', '1', 'N', 'float', '', 'ADEElement', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('ADE_NAME', 'CA12476C', 'Blank ADE 3', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'blank_ade_three', '', 'N', '', '', 'ADE', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('ADE_PARAMETER', 'CA12477C', 'Blank ADE E7', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'blank_ade_e7', '1', 'N', 'cv', '', 'ADEElement', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('ADE_PARAMETER', 'CA12478C', 'Blank ADE E8', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'blank_ade_e8', 'N', 'N', 'cv', '', 'ADEElement', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('ADE_NAME', 'CA12479C', 'Blank ADE 4', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'blank_ade_four', '', 'N', '', '', 'ADE', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('ADE_PARAMETER', 'CA12480C', 'Blank ADE E9', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'blank_ade_e9', '1', 'N', 'cv', '', 'ADEElement', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('ADE_PARAMETER', 'CA12481C', 'Blank ADE E10', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'blank_ade_e10', '1', 'N', 'cv', '', 'ADEElement', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('ADE_PARAMETER', 'CA12482C', 'Blank ADE E11', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'blank_ade_e11', 'N', 'N', 'cv', '', 'ADEElement', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('ADE_PARAMETER', 'CA12483C', 'Blank ADE E12', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'blank_ade_e12', '1', 'N', 'float', '', 'ADEElement', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('ADE_NAME', 'CA12484C', 'Blank ADE 5', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'blank_ade_five', '', 'N', '', '', 'ADE', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('ADE_PARAMETER', 'CA12485C', 'Blank ADE E13', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'blank_ade_e13', '1', 'N', 'cv', '', 'ADEElement', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('ADE_PARAMETER', 'CA12486C', 'Blank ADE E14', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', 'blank_ade_e14', 'N', 'N', 'cv', '', 'ADEElement', '', '', '', '', '', '', 'N', '', '17', '');
insert into pdc_lookup values('CONSENT_TYPE', 'CA12351C', 'CONSENT_TYPE_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', 'N', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('CONSENT_TYPE', 'CA12352C', 'General tissue banking', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('CONSENT_TYPE', 'CA12353C', 'TAP study', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('CONSENT_TYPE', 'CA12354C', 'Tissue microarray', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('CONSENT_TYPE', 'CA12355C', 'TMA consent waiver', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('ETHNIC_BACKGROUND', 'CA12409C', 'ETHNICITY_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('ETHNIC_BACKGROUND', 'CA12410C', 'Hispanic, Latino or Spanish origin', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('ETHNIC_BACKGROUND', 'CA12411C', 'Not Hispanic, Latino or Spanish origin', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('PHYSICAL_EXAM_FINDING', 'CA12543C', 'Abnormal heart rhythm', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('PHYSICAL_EXAM_FINDING', 'CA12542C', 'Decreased breath sounds', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('PHYSICAL_EXAM_FINDING', 'CA12356C', 'Hematemesis', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('PHYSICAL_EXAM_FINDING', 'CA12357C', 'Melena', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('PHYSICAL_EXAM_FINDING', 'CA12358C', 'Odynophagia', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('PHYSICAL_EXAM_FINDING', 'CA12544C', 'Palpable mass', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('PHYSICAL_EXAM_FINDING', 'CA12359C', 'Supraclavicular lymphadenopathy', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('CLINICAL_SYMPTOM', 'CA12568C', 'Coughing blood', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('CLINICAL_SYMPTOM', '288939007', 'Difficulty swallowing', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('CLINICAL_SYMPTOM', '89362005', 'Loss of weight', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('CLINICAL_SYMPTOM', 'CA12363C', 'Nausea', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('CLINICAL_SYMPTOM', '30233002', 'Painful swallowing', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('CLINICAL_SYMPTOM', 'CA12561C', 'SYMPTOM_SCORE_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('CLINICAL_SYMPTOM', 'CA12562C', '0 Asymptomatic', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('CLINICAL_SYMPTOM', 'CA12563C', '1 Symptom occurs less than once per month.', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('CLINICAL_SYMPTOM', 'CA12564C', '2 Symptom occurs less than once per week.', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('CLINICAL_SYMPTOM', 'CA12565C', '3 Symptom occurs less than once per day.', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('CLINICAL_SYMPTOM', 'CA12566C', '4 Symptom occurs daily.', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('G_VALUE_SET_NAME', 'CA12576C', 'RX_RESPONSE_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('TREATMENT_RESPONSE_DISEASE', 'CA12587C', 'Disease regression', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('TREATMENT_RESPONSE_DISEASE', 'CA12567C', 'Disease undetectable', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('PROCEDURE', 'CA12546C', 'Antireflux procedure', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('PROCEDURE', 'CA12554C', 'Endomucosal resection  ~  EMR', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('PROCEDURE', 'CA12547C', 'Esophagectomy, en-bloc', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('PROCEDURE', 'CA12548C', 'Esophagectomy, Ivor-Lewis', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('PROCEDURE', 'CA12549C', 'Esophagectomy, laparoscopic', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('PROCEDURE', 'CA12550C', 'Esophagectomy, minimally invasive  ~  MIE', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('PROCEDURE', 'CA12552C', 'Esophagectomy, transhiatal', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('PROCEDURE', 'CA12551C', 'Esophagectomy, transthoracic with cervical anastomosis', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('PROCEDURE', 'CA12553C', 'Esophagectomy, vagal sparing', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('SURGICAL_PROCEDURE', 'CA12507C', 'Hysterectomy with salpingo-oophorectomy', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('G_VALUE_SET_NAME', 'CA12364C', 'ENDOSCOPY_FINDING_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', 'N', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('CASE_INFORMATION', 'CA12365C', 'No visual abnormality', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('CASE_INFORMATION', 'CA12366C', 'Upper esophageal mass', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('CASE_INFORMATION', 'CA12367C', 'Mid esophageal mass', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('CASE_INFORMATION', 'CA12368C', 'Lower esophageal mass', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('CASE_INFORMATION', 'CA12528C', 'Erosive esophagitis', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('CASE_INFORMATION', 'CA12369C', 'Esophageal columnar epithelium', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('CASE_INFORMATION', 'CA12529C', 'Flat epithelial abnormality', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('CASE_INFORMATION', 'CA12370C', 'Stricture or narrowing', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('CASE_INFORMATION', 'CA12371C', 'Ulceration', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('CASE_INFORMATION', 'CA12372C', 'Other endoscopic finding', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('CASE_INFORMATION', 'CA12530C', 'ESOPHAGEAL_MANOMETRY_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', 'N', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('CASE_INFORMATION', 'CA12531C', 'Normal', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('CASE_INFORMATION', 'CA12532C', 'Abnormal LES tone', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('CASE_INFORMATION', 'CA12533C', 'Achalasia', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('CASE_INFORMATION', 'CA12534C', 'Aperistalsis', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('CASE_INFORMATION', 'CA12535C', 'Distal esophageal spasm', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('CASE_INFORMATION', 'CA12536C', 'Functional outflow obstruction', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('CASE_INFORMATION', 'CA12537C', 'Hypertensive pattern', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('CASE_INFORMATION', 'CA12538C', 'Peristaltic dysfunction, mild', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('CASE_INFORMATION', 'CA12539C', 'Peristaltic dysfunction, severe', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('CASE_INFORMATION', 'CA12540C', 'Sclerodermatous pattern', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('G_VALUE_SET_NAME', 'CA12373C', 'ESOPHAGEAL_MASS_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', 'N', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('CASE_INFORMATION', 'CA12374C', 'No esophageal mass', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('CASE_INFORMATION', 'CA12375C', 'Upper third', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('CASE_INFORMATION', 'CA12376C', 'Mid third', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('CASE_INFORMATION', 'CA12377C', 'Lower third', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('CASE_INFORMATION', 'CA12378C', 'Gastroesophageal junction', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('CASE_INFORMATION', 'CA12379C', 'Gastric', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('STUDY_TIMEPOINT', 'CA12380C', 'STUDY_TIMEPOINT_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('STUDY_TIMEPOINT', 'CA12381C', 'Staging', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('STUDY_TIMEPOINT', 'CA12382C', 'Response', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('STUDY_TIMEPOINT', 'CA12383C', 'Restaging', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('BLOOD_DRAW_TIMING', 'CA12405C', 'At procedure time', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('TIMING_ENDO', 'CA12384C', 'TIMING_OF_ENDOSCOPY_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('TIMING_ENDO', 'CA12385C', 'No medication', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('TIMING_ENDO', 'CA12386C', 'Post medication', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('TIMING_ENDO', 'CA12387C', 'Post surgery', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('US_T_STAGE', 'CA12388C', 'ULTRASOUND_T_STAGE_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('US_T_STAGE', 'CA12389C', 'uT0', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('US_T_STAGE', 'CA12390C', 'uT1', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('US_T_STAGE', 'CA12391C', 'uT2', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('US_T_STAGE', 'CA12392C', 'uT3', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('US_N_STAGE', 'CA12393C', 'ULTRASOUND_N_STAGE_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('US_N_STAGE', 'CA12394C', 'uN0', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('US_N_STAGE', 'CA12395C', 'uN1', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12579C', 'BUFFER_TYPE_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12586C', 'DERIVATION_OPERATION_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12580C', 'EXP_CELLS_PER_ML_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12577C', 'FIXATIVE_TYPE_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12584C', 'GROSS_APPEARANCE_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12500C', 'Gross diseased', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12501C', 'Gross mixed', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12502C', 'Gross normal', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12503C', 'Gross unknown', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12578C', 'SAMPLE_FORMAT_DETAIL_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12581C', 'SAMPLE_TYPE_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12504C', 'Bronchoalveolar Lavage', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12505C', 'Nasal Swab', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12582C', 'SAMPLE_VOLUME_UNIT_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12583C', 'SAMPLE_WEIGHT_UNIT_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12585C', 'STORAGE_TYPE_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12571C', 'TIME_OF_BLOOD_DRAW_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('MASS_LOCATION', 'CA12396C', 'Lower Esophagus (uncertain GEJ involvement)', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('MASS_LOCATION', 'CA12397C', 'Gastric (not including GEJ)', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('MASS_LOCATION', 'CA12398C', 'Uncertain, no residual tumor', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('HISTOLOGIC_TYPE', 'CA12541C', 'Endocrine tumor', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('MICROSCOPIC_FINDING', 'CA12399C', 'Atrophic gastritis', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('MICROSCOPIC_FINDING', 'CA12400C', 'Barretts esophagus', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('MICROSCOPIC_FINDING', 'CA12401C', 'Reflux carditis', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('MICROSCOPIC_FINDING', 'CA12402C', 'Reflux esophagitis', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('VALUE_SET_NAME', 'CA12347C', 'POSITIVE_TUMOR_MARGINS_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', 'N', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('POSITIVE_TUMOR_MARGINS', 'CA12348C', 'Distal margin', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('POSITIVE_TUMOR_MARGINS', 'CA12349C', 'Proximal margin', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('POSITIVE_TUMOR_MARGINS', 'CA12350C', 'Radial margin', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('LYMPH_NODE', 'CA12545C', 'Gastrohepatic nodes', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('LYMPH_NODE', 'CA12403C', 'Perigastric nodes', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('PATH_VERIFICATION', 'CA12506C', 'Ductal epithelium', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('STANDARD_VS', 'CA12442C', 'AMPM_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('STANDARD_VS', 'CA12443C', 'AM', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('STANDARD_VS', 'CA12444C', 'PM', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('STANDARD_VS', 'CA12448C', 'AR_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('STANDARD_VS', 'CA12449C', 'Accept', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('STANDARD_VS', 'CA12450C', 'Reject', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12487C', 'BLANK_ADE_E1_VS_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12488C', 'BLANK_ADE_E2_VS_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12489C', 'BLANK_ADE_E3_VS_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12490C', 'BLANK_ADE_E4_VS_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12491C', 'BLANK_ADE_E5_VS_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', 'N', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12492C', 'BLANK_ADE_E6_VS_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12493C', 'BLANK_ADE_E7_VS_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12494C', 'BLANK_ADE_E8_VS_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12495C', 'BLANK_ADE_E9_VS_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12496C', 'BLANK_ADE_E10_VS_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', 'N', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12497C', 'BLANK_ADE_E11_VS_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12498C', 'BLANK_ADE_E12_VS_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('TISSUE_LIST', 'CA12569C', 'Esophagus, cardiac mucosa', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('TISSUE_LIST', 'CA12570C', 'Esophagus, oxyntocardiac mucosa', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('DIAGNOSIS', '126839008^35917007^', 'Adenocarcinoma of cecum', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('DIAGNOSIS', 'CA01800D^35917007^8707003', 'Adenocarcinoma, metastatic, consistent with biliary or pancreas primary', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('DIAGNOSIS', '126859007^CA12509C^', 'Cystadenoma of pancreas, serous, microcystic', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('DIAGNOSIS', '37657006^25723000^82334004', 'Dysplasia of esophagus, indeterminate', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('DIAGNOSIS', '37657006^25723000^395530002', 'Dysplasia of esophagus, high grade', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('DIAGNOSIS', '37657006^25723000^399415002', 'Dysplasia of esophagus, low grade', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('DIAGNOSIS', '126832004^CA12508C^', 'Tumor of small intestine, gastrinoma, neuroendocrine', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('DIAGNOSIS', '126817006^CA00142M^', 'Tumor of esophagus', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('DIAGNOSIS', '126824007^CA00142M^', 'Tumor of stomach', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('DIAGNOSIS', 'CA12510C^90282004^8707003', 'Adenocarcinoma, papillary serous, metastatic, consistent with ovarian or peritoneum primary', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('DIAGNOSIS', '126788000^27230006^', 'Adenoma of parotid gland, basal cell', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('DIAGNOSIS', '37657006^399617002^', 'Carditis of esophagus', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('DIAGNOSIS', 'CA12572C', 'Columnar lined esophagus', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('DIAGNOSIS', '51615001^112674009^', 'Fibrosis of lung', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '17', '');
insert into pdc_lookup values('G_VALUE_SET_NAME', 'CA12588C', 'STUDY_RESULT_DET_NO_ADE', '', '', 'ARD_CAP', 'A', 'P', '', '1.50', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '17', '');
commit;
