-- DET17 schema upgrade
-- 
-- This upgrade only modifies the schema from DET16 and does not migrate 
-- any existing data.  Theerfore any existing data will be lost!
--
-- Drop ADE tables and columns that were in DET16 but are no longer in DET17.
-- This is safe since we know that no current customers use these tables and
-- columns.
--
drop table CIR_LAB_MET_IMAGE_ADE;
drop table CIR_LAB_PET_ADE_MULTI;
alter table CIR_LAB_CT_ADE drop (CT_SIZE_LYMPH_NODE, CT_SIZE_TUMOR, HEAD_MET_CUI);
alter table CIR_LAB_PET_ADE drop (SUV);

-- Add new columns.
--
alter table CIR_PT_INFO add (
AGE_VISIT NUMBER,
AGE_VISIT_CUI VARCHAR2(30),
DONOR_NOTE VARCHAR2(4000),
DONOR_NOTE_CUI VARCHAR2(30),
ETHNICITY_CUI VARCHAR2(30),
YEAR_BIRTH NUMBER,
YEAR_BIRTH_CUI VARCHAR2(30)
);

alter table CIR_CASE_INFO add (
CASE_DX_CUI VARCHAR2(30),
CASE_COMMENT CLOB,
CASE_COMMENT_CUI VARCHAR2(30),
OTHER_CASE_DX VARCHAR2(200)
);

alter table CIR_CLIN_PRES add (
SYMPTOM_PRIMARY_CUI VARCHAR2(30),
OTHER_SYMPTOM_PRIMARY VARCHAR2(200)
);

alter table CIR_LAB_CT_ADE add (
DATE_OF_CT DATE,
LAB_CT_TIMEPOINT_CUI VARCHAR2(30),
LIVER_MET_CUI VARCHAR2(30),
LUNG_MET_CUI VARCHAR2(30),
LAB_CT_REPORT CLOB
);

alter table CIR_LAB_PET_ADE add (
DATE_OF_PET DATE,
LAB_PET_TIMEPOINT_CUI VARCHAR2(30),
LAB_PET_REPORT CLOB
);

alter table CIR_BLANK_FIELDS add (
BLANK_AR_ONE_CUI VARCHAR2(30),
BLANK_AR_TWO_CUI VARCHAR2(30),
BLANK_AR_THREE_CUI VARCHAR2(30),
BLANK_CV1_DATE_ADE_CUI VARCHAR2(30),
BLANK_CV1_ADE_ONE_CUI VARCHAR2(30),
BLANK_CV1_ADE_TWO_CUI VARCHAR2(30),
BLANK_CV1_ST_RPT_ADE_CUI VARCHAR2(30),
BLANK_FLOAT_DATE_ADE NUMBER,
BLANK_FLOAT_DATE_ADE_CUI VARCHAR2(30),
BLANK_FLOAT_ADE NUMBER,
BLANK_FLOAT_ADE_CUI VARCHAR2(30),
BLANK_FLOAT_FOUR NUMBER,
BLANK_FLOAT_FOUR_CUI VARCHAR2(30),
BLANK_FLOAT_FIVE NUMBER,
BLANK_FLOAT_FIVE_CUI VARCHAR2(30),
BLANK_INTEGER_FOUR NUMBER,
BLANK_INTEGER_FOUR_CUI VARCHAR2(30),
BLANK_INTEGER_FIVE NUMBER,
BLANK_INTEGER_FIVE_CUI VARCHAR2(30),
BLANK_PERC_FLOAT_ONE NUMBER,
BLANK_PERC_FLOAT_ONE_CUI VARCHAR2(30),
BLANK_PERC_FLOAT_TWO NUMBER,
BLANK_PERC_FLOAT_TWO_CUI VARCHAR2(30),
BLANK_PERC_INT_ONE NUMBER,
BLANK_PERC_INT_ONE_CUI VARCHAR2(30),
BLANK_PERC_INT_TWO NUMBER,
BLANK_PERC_INT_TWO_CUI VARCHAR2(30),
OTHER_BLANK_CV1_ADE_TWO VARCHAR2(200)
);

-- Add new tables.
--
CREATE TABLE CIR_BLANK_ADE_ONE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,BLANK_ADE_E1_CUI VARCHAR2(30)
)
TABLESPACE CIR_TBL_TBS
PCTUSED    85
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;

CREATE UNIQUE INDEX PK_CIR_BLANK_ADE_ONE ON CIR_BLANK_ADE_ONE (ID)
TABLESPACE CIR_IDX_TBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX CIR_BLANK_ADE_ONE_I8 ON CIR_BLANK_ADE_ONE (FORM_ID)
LOGGING
TABLESPACE CIR_IDX_TBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
;

ALTER TABLE CIR_BLANK_ADE_ONE ADD CONSTRAINT PK_CIR_BLANK_ADE_ONE PRIMARY KEY (ID);

CREATE TABLE CIR_BLANK_ADE_ONE_MULTI (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER NOT NULL
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,OTHER_DATA_VALUE VARCHAR2(200)
)
TABLESPACE CIR_TBL_TBS
PCTUSED    85
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;

CREATE UNIQUE INDEX PK_CIR_BLANK_ADE_ONE_M ON CIR_BLANK_ADE_ONE_MULTI (ID)
TABLESPACE CIR_IDX_TBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX CIR_BLANK_ADE_ONE_I9 ON CIR_BLANK_ADE_ONE_MULTI (FORM_ID)
LOGGING
TABLESPACE CIR_IDX_TBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
;

ALTER TABLE CIR_BLANK_ADE_ONE_MULTI ADD CONSTRAINT PK_CIR_BLANK_ADE_ONE_M PRIMARY KEY (ID);
CREATE TABLE CIR_BLANK_ADE_TWO (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,BLANK_ADE_E3_CUI VARCHAR2(30)
,BLANK_ADE_E4_CUI VARCHAR2(30)
,BLANK_ADE_E6 NUMBER
)
TABLESPACE CIR_TBL_TBS
PCTUSED    85
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;

CREATE UNIQUE INDEX PK_CIR_BLANK_ADE_TWO ON CIR_BLANK_ADE_TWO (ID)
TABLESPACE CIR_IDX_TBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX CIR_BLANK_ADE_TWO_I8 ON CIR_BLANK_ADE_TWO (FORM_ID)
LOGGING
TABLESPACE CIR_IDX_TBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
;

ALTER TABLE CIR_BLANK_ADE_TWO ADD CONSTRAINT PK_CIR_BLANK_ADE_TWO PRIMARY KEY (ID);

CREATE TABLE CIR_BLANK_ADE_TWO_MULTI (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER NOT NULL
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,OTHER_DATA_VALUE VARCHAR2(200)
)
TABLESPACE CIR_TBL_TBS
PCTUSED    85
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;

CREATE UNIQUE INDEX PK_CIR_BLANK_ADE_TWO_M ON CIR_BLANK_ADE_TWO_MULTI (ID)
TABLESPACE CIR_IDX_TBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX CIR_BLANK_ADE_TWO_I9 ON CIR_BLANK_ADE_TWO_MULTI (FORM_ID)
LOGGING
TABLESPACE CIR_IDX_TBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
;

ALTER TABLE CIR_BLANK_ADE_TWO_MULTI ADD CONSTRAINT PK_CIR_BLANK_ADE_TWO_M PRIMARY KEY (ID);
CREATE TABLE CIR_BLANK_ADE_THREE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,BLANK_ADE_E7_CUI VARCHAR2(30)
)
TABLESPACE CIR_TBL_TBS
PCTUSED    85
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;

CREATE UNIQUE INDEX PK_CIR_BLANK_ADE_THREE ON CIR_BLANK_ADE_THREE (ID)
TABLESPACE CIR_IDX_TBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX CIR_BLANK_ADE_THREE_I8 ON CIR_BLANK_ADE_THREE (FORM_ID)
LOGGING
TABLESPACE CIR_IDX_TBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
;

ALTER TABLE CIR_BLANK_ADE_THREE ADD CONSTRAINT PK_CIR_BLANK_ADE_THREE PRIMARY KEY (ID);

CREATE TABLE CIR_BLANK_ADE_THREE_MULTI (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER NOT NULL
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,OTHER_DATA_VALUE VARCHAR2(200)
)
TABLESPACE CIR_TBL_TBS
PCTUSED    85
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;

CREATE UNIQUE INDEX PK_CIR_BLANK_ADE_THREE_M ON CIR_BLANK_ADE_THREE_MULTI (ID)
TABLESPACE CIR_IDX_TBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX CIR_BLANK_ADE_THREE_I9 ON CIR_BLANK_ADE_THREE_MULTI (FORM_ID)
LOGGING
TABLESPACE CIR_IDX_TBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
;

ALTER TABLE CIR_BLANK_ADE_THREE_MULTI ADD CONSTRAINT PK_CIR_BLANK_ADE_THREE_M PRIMARY KEY (ID);
CREATE TABLE CIR_BLANK_ADE_FOUR (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,BLANK_ADE_E9_CUI VARCHAR2(30)
,BLANK_ADE_E10_CUI VARCHAR2(30)
,BLANK_ADE_E12 NUMBER
)
TABLESPACE CIR_TBL_TBS
PCTUSED    85
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;

CREATE UNIQUE INDEX PK_CIR_BLANK_ADE_FOUR ON CIR_BLANK_ADE_FOUR (ID)
TABLESPACE CIR_IDX_TBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX CIR_BLANK_ADE_FOUR_I8 ON CIR_BLANK_ADE_FOUR (FORM_ID)
LOGGING
TABLESPACE CIR_IDX_TBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
;

ALTER TABLE CIR_BLANK_ADE_FOUR ADD CONSTRAINT PK_CIR_BLANK_ADE_FOUR PRIMARY KEY (ID);

CREATE TABLE CIR_BLANK_ADE_FOUR_MULTI (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER NOT NULL
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,OTHER_DATA_VALUE VARCHAR2(200)
)
TABLESPACE CIR_TBL_TBS
PCTUSED    85
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;

CREATE UNIQUE INDEX PK_CIR_BLANK_ADE_FOUR_M ON CIR_BLANK_ADE_FOUR_MULTI (ID)
TABLESPACE CIR_IDX_TBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX CIR_BLANK_ADE_FOUR_I9 ON CIR_BLANK_ADE_FOUR_MULTI (FORM_ID)
LOGGING
TABLESPACE CIR_IDX_TBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
;

ALTER TABLE CIR_BLANK_ADE_FOUR_MULTI ADD CONSTRAINT PK_CIR_BLANK_ADE_FOUR_M PRIMARY KEY (ID);

CREATE TABLE CIR_BLANK_ADE_FIVE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,BLANK_ADE_E13_CUI VARCHAR2(30)
)
TABLESPACE CIR_TBL_TBS
PCTUSED    85
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;

CREATE UNIQUE INDEX PK_CIR_BLANK_ADE_FIVE ON CIR_BLANK_ADE_FIVE (ID)
TABLESPACE CIR_IDX_TBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX CIR_BLANK_ADE_FIVE_I8 ON CIR_BLANK_ADE_FIVE (FORM_ID)
LOGGING
TABLESPACE CIR_IDX_TBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
;

ALTER TABLE CIR_BLANK_ADE_FIVE ADD CONSTRAINT PK_CIR_BLANK_ADE_FIVE PRIMARY KEY (ID);

CREATE TABLE CIR_BLANK_ADE_FIVE_MULTI (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER NOT NULL
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,OTHER_DATA_VALUE VARCHAR2(200)
)
TABLESPACE CIR_TBL_TBS
PCTUSED    85
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;

CREATE UNIQUE INDEX PK_CIR_BLANK_ADE_FIVE_M ON CIR_BLANK_ADE_FIVE_MULTI (ID)
TABLESPACE CIR_IDX_TBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX CIR_BLANK_ADE_FIVE_I9 ON CIR_BLANK_ADE_FIVE_MULTI (FORM_ID)
LOGGING
TABLESPACE CIR_IDX_TBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
;

ALTER TABLE CIR_BLANK_ADE_FIVE_MULTI ADD CONSTRAINT PK_CIR_BLANK_ADE_FIVE_M PRIMARY KEY (ID);

CREATE TABLE CIR_CA_RX_RESPONSE_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATE_RX_START DATE
,DATE_RX_START_DPC VARCHAR2(30)
,DATE_RECENT_RX DATE
,DATE_RECENT_RX_DPC VARCHAR2(30)
,RX_RESPONSE_CUI VARCHAR2(30)
,OTHER_RX_RESPONSE VARCHAR2(200)
)
TABLESPACE CIR_TBL_TBS
PCTUSED    85
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;

CREATE UNIQUE INDEX PK_CIR_CA_RX_RESPONSE_ADE ON CIR_CA_RX_RESPONSE_ADE (ID)
TABLESPACE CIR_IDX_TBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX CIR_CA_RX_RESPONSE_ADE_I8 ON CIR_CA_RX_RESPONSE_ADE (FORM_ID)
LOGGING
TABLESPACE CIR_IDX_TBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
;

ALTER TABLE CIR_CA_RX_RESPONSE_ADE ADD CONSTRAINT PK_CIR_CA_RX_RESPONSE_ADE PRIMARY KEY (ID);

CREATE TABLE CIR_ESOPH_PH_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATE_OF_ESOPH_PH DATE
,DEMEESTER_SCORE NUMBER
)
TABLESPACE CIR_TBL_TBS
PCTUSED    85
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;

CREATE UNIQUE INDEX PK_CIR_ESOPH_PH_ADE ON CIR_ESOPH_PH_ADE (ID)
TABLESPACE CIR_IDX_TBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX CIR_ESOPH_PH_ADE_I8 ON CIR_ESOPH_PH_ADE (FORM_ID)
LOGGING
TABLESPACE CIR_IDX_TBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
;

ALTER TABLE CIR_ESOPH_PH_ADE ADD CONSTRAINT PK_CIR_ESOPH_PH_ADE PRIMARY KEY (ID);

CREATE TABLE CIR_ESOPH_US_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATE_OF_ESOPH_US DATE
,US_T_STAGE_CUI VARCHAR2(30)
,US_N_STAGE_CUI VARCHAR2(30)
,ESOPH_US_REPORT CLOB
)
TABLESPACE CIR_TBL_TBS
PCTUSED    85
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;

CREATE UNIQUE INDEX PK_CIR_ESOPH_US_ADE ON CIR_ESOPH_US_ADE (ID)
TABLESPACE CIR_IDX_TBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX CIR_ESOPH_US_ADE_I8 ON CIR_ESOPH_US_ADE (FORM_ID)
LOGGING
TABLESPACE CIR_IDX_TBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
;

ALTER TABLE CIR_ESOPH_US_ADE ADD CONSTRAINT PK_CIR_ESOPH_US_ADE PRIMARY KEY (ID);

CREATE TABLE CIR_IMAGING_STUDIES_MULTI (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,OTHER_DATA_VALUE VARCHAR2(200)
)
TABLESPACE CIR_TBL_TBS
PCTUSED    85
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;

CREATE UNIQUE INDEX PK_CIR_IMAGING_STUDIES_M ON CIR_IMAGING_STUDIES_MULTI (ID)
TABLESPACE CIR_IDX_TBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

ALTER TABLE CIR_IMAGING_STUDIES_MULTI ADD CONSTRAINT PK_CIR_IMAGING_STUDIES_M PRIMARY KEY (ID);

CREATE INDEX CIR_IMAGING_STUDIES_I3 ON CIR_IMAGING_STUDIES_MULTI (FORM_ID)
LOGGING
TABLESPACE CIR_IDX_TBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
;

CREATE TABLE CIR_LAB_PET_MASS_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,SUV NUMBER
)
TABLESPACE CIR_TBL_TBS
PCTUSED    85
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;

CREATE UNIQUE INDEX PK_CIR_LAB_PET_MASS_ADE ON CIR_LAB_PET_MASS_ADE (ID)
TABLESPACE CIR_IDX_TBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX CIR_LAB_PET_MASS_ADE_I8 ON CIR_LAB_PET_MASS_ADE (FORM_ID)
LOGGING
TABLESPACE CIR_IDX_TBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
;

ALTER TABLE CIR_LAB_PET_MASS_ADE ADD CONSTRAINT PK_CIR_LAB_PET_MASS_ADE PRIMARY KEY (ID);

CREATE TABLE CIR_MED_DATES_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATE_MEDS_START DATE
,DATE_MEDS_START_DPC VARCHAR2(30)
,DATE_RECENT_MEDS DATE
,DATE_RECENT_MEDS_DPC VARCHAR2(30)
)
TABLESPACE CIR_TBL_TBS
PCTUSED    85
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;

CREATE UNIQUE INDEX PK_CIR_MED_DATES_ADE ON CIR_MED_DATES_ADE (ID)
TABLESPACE CIR_IDX_TBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX CIR_MED_DATES_ADE_I8 ON CIR_MED_DATES_ADE (FORM_ID)
LOGGING
TABLESPACE CIR_IDX_TBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
;

ALTER TABLE CIR_MED_DATES_ADE ADD CONSTRAINT PK_CIR_MED_DATES_ADE PRIMARY KEY (ID);

CREATE TABLE CIR_SAMPLE_INFO (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,BUFFER_TYPE_CUI VARCHAR2(30)
,OTHER_BUFFER_TYPE VARCHAR2(200)
,CELLS_PER_ML NUMBER
,CELLS_PER_ML_CUI VARCHAR2(30)
,CONCENTRATION NUMBER
,CONCENTRATION_CUI VARCHAR2(30)
,DATE_COLLECTION DATE
,DATE_COLLECTION_CUI VARCHAR2(30)
,TIME_COLLECT_HOUR NUMBER
,TIME_COLLECT_HOUR_CUI VARCHAR2(30)
,TIME_COLLECT_MIN NUMBER
,TIME_COLLECT_MIN_CUI VARCHAR2(30)
,TIME_COLLECT_AMPM_CUI VARCHAR2(30)
,DATE_PRESERVE DATE
,DATE_PRESERVE_CUI VARCHAR2(30)
,TIME_PRESERVE_HOUR NUMBER
,TIME_PRESERVE_HOUR_CUI VARCHAR2(30)
,TIME_PRESERVE_MIN NUMBER
,TIME_PRESERVE_MIN_CUI VARCHAR2(30)
,TIME_PRESERVE_AMPM_CUI VARCHAR2(30)
,DERIV_OP_CUI VARCHAR2(30)
,FIXATIVE_TYPE_CUI VARCHAR2(30)
,FORMAT_DETAIL_CUI VARCHAR2(30)
,GROSS_APPEAR_CUI VARCHAR2(30)
,PERCENT_VIABLE NUMBER
,PERCENT_VIABLE_CUI VARCHAR2(30)
,PREPARED_BY VARCHAR2(4000)
,PREPARED_BY_CUI VARCHAR2(30)
,SAMPLE_COMMENT CLOB
,SAMPLE_COMMENT_CUI VARCHAR2(30)
,SAMPLE_SOURCE VARCHAR2(4000)
,SAMPLE_SOURCE_CUI VARCHAR2(30)
,SAMPLE_TYPE_CUI VARCHAR2(30)
,SAMPLE_VOLUME NUMBER
,SAMPLE_VOLUME_CUI VARCHAR2(30)
,SAMPLE_VOLUME_UNIT_CUI VARCHAR2(30)
,SAMPLE_WEIGHT NUMBER
,SAMPLE_WEIGHT_CUI VARCHAR2(30)
,SAMPLE_WEIGHT_UNIT_CUI VARCHAR2(30)
,STORAGE_TYPE_CUI VARCHAR2(30)
,TOTAL_NUM_CELLS NUMBER
,TOTAL_NUM_CELLS_CUI VARCHAR2(30)
,TOTAL_CELLS_EXPONENT_CUI VARCHAR2(30)
,YIELD NUMBER
,YIELD_CUI VARCHAR2(30)
,TIME_BLOOD_DRAW_CUI VARCHAR2(30)
)
TABLESPACE CIR_TBL_TBS
PCTUSED    85
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;

CREATE UNIQUE INDEX PK_CIR_SAMPLE_INFO ON CIR_SAMPLE_INFO (ID)
TABLESPACE CIR_IDX_TBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX CIR_SAMPLE_INFO_I1 ON CIR_SAMPLE_INFO (FORM_ID)
LOGGING
TABLESPACE CIR_IDX_TBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
;

ALTER TABLE CIR_SAMPLE_INFO ADD CONSTRAINT PK_CIR_SAMPLE_INFO PRIMARY KEY (ID);



CREATE TABLE CIR_SAMPLE_INFO_NOTE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,NOTE VARCHAR2(4000)
)
TABLESPACE CIR_TBL_TBS
PCTUSED    85
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;

CREATE UNIQUE INDEX PK_CIR_SAMPLE_INFO_N ON CIR_SAMPLE_INFO_NOTE (ID)
TABLESPACE CIR_IDX_TBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

ALTER TABLE CIR_SAMPLE_INFO_NOTE ADD CONSTRAINT PK_CIR_SAMPLE_INFO_N PRIMARY KEY (ID);

CREATE INDEX CIR_SAMPLE_INFO_I5 ON CIR_SAMPLE_INFO_NOTE (FORM_ID)
LOGGING
TABLESPACE CIR_IDX_TBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
;

CREATE TABLE CIR_SURGICAL_STUDIES_MULTI (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,DATA_ELEMENT_CUI VARCHAR2(30)
,DATA_VALUE_CUI VARCHAR2(30)
,OTHER_DATA_VALUE VARCHAR2(200)
)
TABLESPACE CIR_TBL_TBS
PCTUSED    85
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;

CREATE UNIQUE INDEX PK_CIR_SURGICAL_STUDIES_M ON CIR_SURGICAL_STUDIES_MULTI (ID)
TABLESPACE CIR_IDX_TBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

ALTER TABLE CIR_SURGICAL_STUDIES_MULTI ADD CONSTRAINT PK_CIR_SURGICAL_STUDIES_M PRIMARY KEY (ID);

CREATE INDEX CIR_SURGICAL_STUDIES_I3 ON CIR_SURGICAL_STUDIES_MULTI (FORM_ID)
LOGGING
TABLESPACE CIR_IDX_TBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
;

CREATE TABLE CIR_SX_SCORE_ADE (
ID NUMBER NOT NULL
,FORM_ID VARCHAR2(10)
,PARENT_ID NUMBER
,DATA_ELEMENT_CUI VARCHAR2(30)
,SYMPTOM_SCORE_CUI VARCHAR2(30)
)
TABLESPACE CIR_TBL_TBS
PCTUSED    85
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;

CREATE UNIQUE INDEX PK_CIR_SX_SCORE_ADE ON CIR_SX_SCORE_ADE (ID)
TABLESPACE CIR_IDX_TBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX CIR_SX_SCORE_ADE_I8 ON CIR_SX_SCORE_ADE (FORM_ID)
LOGGING
TABLESPACE CIR_IDX_TBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
;

ALTER TABLE CIR_SX_SCORE_ADE ADD CONSTRAINT PK_CIR_SX_SCORE_ADE PRIMARY KEY (ID);


