---------------------------------------------------------------------------------
--	File:		compile_db_code.sql
--	Author:		Dean Marsh
--	Date:		03/25/2002
--	
--	Comments:	This file is used as part of the build process to compile
--			all database code in a release.  It can be run from NT
--			or from UNIX.
--
--	Parameters:	None
--
---------------------------------------------------------------------------------


----------Compile Functions--------

@FN_LAST_DATETIME.FNC
@FN_LAST_STATUS.FNC
@HEXTODEC.FNC
@GET_NEW_LINE.FNC
@GET_NEXT_DELIM.FNC
@GET_DESC_FROM_DX_TC_HIERARCHY.FNC
@GET_DESC_FROM_PDC_LOOKUP.FNC

----------Compile Views------------

@LIMS_ADS_ILTDS_V.sql
@LIMS_BIGR_LIBRARY_V.sql
@RNA_HOLD_AMOUNT_V.sql
@ACCOUNT_V.sql
@BOX_V.sql
@BOX_V_E.sql
@CASE_V.sql
@CASE_V_E.sql
@CUI_MAPPING_V.sql
@DERIVATION_V.sql
@DERIVATION_V_E.sql
@DONOR_V.sql
@FORM_V.sql
@INVENTORY_GROUP_SAMPLE_V.sql
@INVENTORY_GROUP_USER_V.sql
@INVENTORY_GROUP_V.sql
@LOCATION_V.sql
@SAMPLE_GENEALOGY_V.sql
@SAMPLE_LOCATION_V.sql
@SAMPLE_LOCATION_V_E.sql
@SAMPLE_V.sql
@SAMPLE_V_E.sql
@STORAGE_V.sql
@STORAGE_V_E.sql
@USER_V.sql
@kc_generated_views.sql
@ROLE_V.sql
@ROLE_USER_V.sql
@ROLE_PRIVILEGE_V.sql

--------Compile PLSQL-------------

@BASE_CONVERT.pkg
@DDC.pkg
@BTX.pkg
@SAMPLE_STATUS_TRG_PKG.pkg
@LANG_INTEGER.pkg
@BIGR_DATA_UTILS.pkg
@Sample_Triggers.pkg
@CONSENT_TRIGGERS.pkg
@AGE_AT_COLLECTION_TRG.pkg

@BIGR_USE_ID_NAMESPACE.PRC
@BIGR_ASSIGN_SAMPLE_IDS.PRC
@BIGR_GET_ROLE_ID.PRC
@BIGR_INITIALIZE_CLEAN_DATABASE.PRC
@BIGR_REMOVE_FROM_HOLD.PRC
@DATA_IMPORT_GET_ASM_ID.PRC
@DATA_IMPORT_GET_CONSENT_ID.PRC
@DATA_IMPORT_GET_DONOR_ID.PRC
@LIMS_GET_EVALUATIONID.PRC
@LIMS_GET_INCIDENTID.PRC
@LIMS_GET_SLIDELABELS.PRC
@FIND_CONCEPT_EXCEPT_CIR.PRC

----------Compile Triggers---------
@ARD_BRANDING_PK_TRG.TRG
@ARD_LOGICAL_REPOS_BMS_YN_AUR.TRG
@ARD_LOGICAL_REPOS_BMS_YN_AUS.TRG
@ARD_LOGICAL_REPOS_BMS_YN_BUS.TRG
@ARD_LOGICAL_REPOS_ITEM_AIUDR.TRG
@ARD_LOGICAL_REPOS_ITEM_AIUDS.TRG
@ARD_LOGICAL_REPOS_ITEM_BIUDS.TRG
@ARD_LOGICAL_REPOS_ITEM_PK_TRG.TRG
@ARD_LOGICAL_REPOS_PK_TRG.TRG
@ARD_LOGICAL_REPOS_USER_PK_TRG.TRG
@ARD_POLICY_PK_TRG.TRG
@ARD_URLS_PK_TRG.TRG
@BIGR_ROLE_PRIVILEGE_PK_TRG.TRG
@BIGR_ROLE_USER_PK_TRG.TRG
@CIR_FORM_PK_TRG.TRG
@CIR_FORM_DEF_PK_TRG.TRG
@CIR_FORM_DEF_TAGS_PK_TRG.TRG
@ES_ARDAIS_ACCOUNT_AUR.TRG
@ES_ARDAIS_USER_AIR.TRG
@ES_ARDAIS_USER_PASSWORD_BIUR.TRG
@ILTDS_ACCT_BX_LAYOUT_PK_TRG.TRG
@ILTDS_ATTACHMENTS_PK_TRG.TRG
@ILTDS_ASM_AIUDR.TRG
@ILTDS_ASM_AIUDS.TRG
@ILTDS_ASM_BIUDS.TRG
@ILTDS_ASM_CID_AID_BUR.TRG
@ILTDS_BOX_LAYOUT_PK_TRG.TRG
@ILTDS_DERIVATION_PK_TRG.TRG
@ILTDS_INFORMED_CONSENT_AIUDR.TRG
@ILTDS_INFORMED_CONSENT_AIUDS.TRG
@ILTDS_INFORMED_CONSENT_BIUDR.TRG
@ILTDS_INFORMED_CONSENT_BIUDS.TRG
@ILTDS_REQUEST_BOX_PK_TRG.TRG
@ILTDS_REQUEST_ITEM_PK_TRG.TRG
@ILTDS_SAMPLE_AIUR.TRG
@ILTDS_SAMPLE_AIUS.TRG
@ILTDS_SAMPLE_BEST_PFIN_BIUR.TRG
@ILTDS_SAMPLE_BIUS.TRG
@ILTDS_SAMPLE_CID_AID_BIUR.TRG
@ILTDS_SAMPLE_COLLEC_DATE_AIUR.TRG
@ILTDS_SAMPLE_COLLEC_DATE_AIUS.TRG
@ILTDS_SAMPLE_COLLEC_DATE_BIUS.TRG
@ILTDS_SAMPLE_GENEALOGY_PK_TRG.TRG
@ILTDS_SAMPLE_STATUS_AIR.TRG
@ILTDS_SAMPLE_STATUS_AUDR.TRG
@ILTDS_SAMPLE_STATUS_AUDS.TRG
@ILTDS_SAMPLE_STATUS_BUDS.TRG
@ILTDS_SAMPLE_STATUS_PK_TRG.TRG
@ILTDS_SHIPPING_PARTNERS_PK_TRG.TRG
@LIMS_PATH_EVALUATION_AIUDR.TRG
@LIMS_PATH_EVALUATION_AIUDS.TRG
@LIMS_PATH_EVALUATION_BIUDS.TRG
@LIMS_PATH_EVAL_UPDATE_RNA.TRG
@LIMS_SLIDE_AIUDR.TRG
@PDC_ARDAIS_DONOR_AIUDR.TRG
@PDC_ARDAIS_DONOR_AIUDS.TRG
@PDC_ARDAIS_DONOR_BIUDS.TRG
@PDC_PATHOLOGY_REPORT_AIUDR.TRG
@PDC_PATHOLOGY_REPORT_AIUDS.TRG
@PDC_PATHOLOGY_REPORT_BIUDS.TRG
@PDC_PATH_REPORT_DIAG_HIST_AUDR.TRG
@PDC_PATH_REPORT_HISTORY_AUDR.TRG
@PDC_PATH_REPORT_SECTION_AIUDR.TRG
@PDC_PATH_REP_DIAGNOSTICS_PK_TRG.TRG
@PDC_PATH_REP_SECTION_HIST_AUDR.TRG
@PDC_PATH_REP_SET_BESTDX_AIUR.TRG
@RNA_BATCH_DETAIL_AIUDR.TRG
@RNA_BATCH_DETAIL_AIUDS.TRG
@RNA_BATCH_DETAIL_BIUDS.TRG
@SHARED_VIEWS_PK_TRG.TRG
@PERSONAL_FILTERS_PK_TRG.TRG
@APERIOIMAGE_BIGRSAMPLE_PK_TRG.TRG