SET DEFINE OFF;
SET ECHO ON;
insert into pdc_lookup values('PATIENT_INFORMATION', 'CA12871C', 'Gestational Age', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', 'gestational_age', '1', 'N', 'int', '', 'Element', '', '', '', '', '', '', 'N', '', '24', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12872C', 'Blood Tube Type', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', 'blood_tube_cri', '1', 'Y', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '24', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12881C', 'DNA Extraction Method', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', 'extraction_method', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '24', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12918C', 'Hemolyzed Status', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', 'hemolyzed_status', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '24', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12889C', 'Preservation Method', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', 'preservation_method', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '24', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12894C', 'Protein Buffer', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', 'protein_buffer', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '24', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12899C', 'NA Buffer', '', '', 'ARD_CAP', 'A', 'P', 'DNA RNA Buffer', '1.62', '', 'na_buffer', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '24', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12907C', 'Slide Preparation', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', 'slide_prep', '1', 'Y', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '24', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12912C', 'Storage Form', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', 'storage_form', '1', 'Y', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '24', '');
insert into pdc_lookup values('ETHNIC_BACKGROUND', 'CA12923C', 'Unavailable', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '24', '');
insert into pdc_lookup values('ETHNIC_BACKGROUND', 'CA12924C', 'Declined', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '24', '');
insert into pdc_lookup values('RACE', 'CA12922C', 'Multi-racial/Multi-cultural', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '24', '');
insert into pdc_lookup values('RACE', 'CA12920C', 'Unavailable', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '24', '');
insert into pdc_lookup values('RACE', 'CA12921C', 'Declined', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '24', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12873C', 'CRI_BLOOD_TUBE_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '24', '');
insert into pdc_lookup values('BLOOD_TUBE_CRI', 'CA12874C', 'No Additive (Red)', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '24', '');
insert into pdc_lookup values('BLOOD_TUBE_CRI', 'CA12875C', 'K2 EDTA (Purple)', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '24', '');
insert into pdc_lookup values('BLOOD_TUBE_CRI', 'CA12876C', 'Li Heparin (Light Green)', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '24', '');
insert into pdc_lookup values('BLOOD_TUBE_CRI', 'CA12877C', 'Na Citrate (Light Blue)', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '24', '');
insert into pdc_lookup values('BLOOD_TUBE_CRI', 'CA12878C', 'Na Heparin (Dark Green)', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '24', '');
insert into pdc_lookup values('BLOOD_TUBE_CRI', 'CA12879C', 'Serum Separator (SST - Gold)', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '24', '');
insert into pdc_lookup values('BLOOD_TUBE_CRI', 'CA12880C', 'Other blood collection tube', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', '', '', '', '', 'Y', 'Value', '', '', '', '', '', '', '', '', '24', '');
insert into pdc_lookup values('DERIVATION_OPERATION', 'CA12925C', 'Shavings', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '24', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12882C', 'EXTRACTION_METHOD_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '24', '');
insert into pdc_lookup values('EXTRACTION_METHOD', 'CA12883C', 'Auto pure', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '24', '');
insert into pdc_lookup values('EXTRACTION_METHOD', 'CA12884C', 'EZ bots', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '24', '');
insert into pdc_lookup values('EXTRACTION_METHOD', 'CA12885C', 'Manual', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '24', '');
insert into pdc_lookup values('EXTRACTION_METHOD', 'CA12886C', 'Maxwell', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '24', '');
insert into pdc_lookup values('EXTRACTION_METHOD', 'CA12887C', 'Other', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '24', '');
insert into pdc_lookup values('TYPE_OF_FIXATIVE', 'CA12919C', 'Other', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '24', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12890C', 'PRESERVATION_METHOD_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '24', '');
insert into pdc_lookup values('PRESERVATION_METHOD', 'CA12891C', 'Air Dried', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '24', '');
insert into pdc_lookup values('PRESERVATION_METHOD', 'CA12892C', 'Fixed in alcohol', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '24', '');
insert into pdc_lookup values('PRESERVATION_METHOD', 'CA12893C', 'Fixed in formalin', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '24', '');
insert into pdc_lookup values('SAMPLE_TYPE', 'CA12888C', 'Shavings', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '24', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12908C', 'SLIDE_PREP_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '24', '');
insert into pdc_lookup values('SLIDE_PREP', 'CA12909C', 'FFPE', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '24', '');
insert into pdc_lookup values('SLIDE_PREP', 'CA12910C', 'Cryo-OCT', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '24', '');
insert into pdc_lookup values('SLIDE_PREP', 'CA12911C', 'Other', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', '', '', '', '', 'Y', 'Value', '', '', '', '', '', '', '', '', '24', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12900C', 'NA_BUFFER_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '24', '');
insert into pdc_lookup values('NA_BUFFER', 'CA12901C', 'Blot', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '24', '');
insert into pdc_lookup values('NA_BUFFER', 'CA12902C', 'Low TE', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '24', '');
insert into pdc_lookup values('NA_BUFFER', 'CA12903C', 'Pellet', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '24', '');
insert into pdc_lookup values('NA_BUFFER', 'CA12904C', 'Solid', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '24', '');
insert into pdc_lookup values('NA_BUFFER', 'CA12905C', 'Water', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '24', '');
insert into pdc_lookup values('NA_BUFFER', 'CA12906C', 'Other', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', '', '', '', '', 'Y', 'Value', '', '', '', '', '', '', '', '', '24', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12895C', 'PROTEIN_BUFFER_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '24', '');
insert into pdc_lookup values('PROTEIN_BUFFER', 'CA12896C', 'Complete (Roche without EDTA)', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '24', '');
insert into pdc_lookup values('PROTEIN_BUFFER', 'CA12897C', 'Complete (Roche with EDTA)', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '24', '');
insert into pdc_lookup values('PROTEIN_BUFFER', 'CA12898C', 'Laemmli', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '24', '');
insert into pdc_lookup values('SAMPLE_INFO', 'CA12913C', 'STORAGE_FORM_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', '', '1', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '24', '');
insert into pdc_lookup values('STORAGE_FORM', 'CA12914C', 'Liquid', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '24', '');
insert into pdc_lookup values('STORAGE_FORM', 'CA12915C', 'Pellet', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '24', '');
insert into pdc_lookup values('STORAGE_FORM', 'CA12916C', 'Slide', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '24', '');
insert into pdc_lookup values('STORAGE_FORM', 'CA12917C', 'Other', '', '', 'ARD_CAP', 'A', 'P', '', '1.62', '', '', '', '', '', 'Y', 'Value', '', '', '', '', '', '', '', '', '24', '');
commit;
