
ALTER TABLE CIR_PT_INFO
 ADD (GESTATIONAL_AGE  NUMBER);

ALTER TABLE CIR_SAMPLE_INFO
 ADD (OTHER_STORAGE_FORM  VARCHAR2(200 BYTE));

ALTER TABLE CIR_SAMPLE_INFO
 ADD (OTHER_BLOOD_TUBE_CRI  VARCHAR2(200 BYTE));

ALTER TABLE CIR_SAMPLE_INFO
 ADD (OTHER_SLIDE_PREP  VARCHAR2(200 BYTE));

ALTER TABLE CIR_SAMPLE_INFO
 ADD (EXTRACTION_METHOD_CUI  VARCHAR2(30 BYTE));

ALTER TABLE CIR_SAMPLE_INFO
 ADD (SLIDE_PREP_CUI  VARCHAR2(30 BYTE));

ALTER TABLE CIR_PT_INFO
 ADD (GESTATIONAL_AGE_CUI  VARCHAR2(30 BYTE));

ALTER TABLE CIR_SAMPLE_INFO
 ADD (BLOOD_TUBE_CRI_CUI  VARCHAR2(30 BYTE));

ALTER TABLE CIR_SAMPLE_INFO
 ADD (PROTEIN_BUFFER_CUI  VARCHAR2(30 BYTE));

ALTER TABLE CIR_SAMPLE_INFO
 ADD (PRESERVATION_METHOD_CUI  VARCHAR2(30 BYTE));

ALTER TABLE CIR_SAMPLE_INFO
 ADD (STORAGE_FORM_CUI  VARCHAR2(30 BYTE));

ALTER TABLE CIR_SAMPLE_INFO
 ADD (NA_BUFFER_CUI  VARCHAR2(30 BYTE));

ALTER TABLE CIR_SAMPLE_INFO
 ADD (HEMOLYZED_STATUS_CUI  VARCHAR2(30 BYTE));

ALTER TABLE CIR_SAMPLE_INFO
 ADD (OTHER_NA_BUFFER  VARCHAR2(200 BYTE));