set define off;
update pdc_lookup set lookup_type_cd_desc ='Lesion list', system_name='lesion_list', rev='1.46', drev='15' where lookup_type_cd ='CA11759C';
insert into pdc_lookup values('BIGR_GBOSS', 'CA12177C', 'TYPE_OF_FIXATIVE', '', '10', 'ARD_CAP', 'A', 'P', '', '1.46', '', '', '', '', '', '', 'BIGR_GBOSS_Value_Set', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('BIGR_GBOSS', 'CA12178C', 'SAMPLE_FORMAT_DETAIL', '', '10', 'ARD_CAP', 'A', 'P', '', '1.46', '', '', '', '', '', '', 'BIGR_GBOSS_Value_Set', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('BIGR_GBOSS', 'CA12179C', 'BUFFER_TYPE', '', '10', 'ARD_CAP', 'A', 'P', '', '1.46', '', '', '', '', '', '', 'BIGR_GBOSS_Value_Set', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('BIGR_GBOSS', 'CA12180C', 'EXP_CELLS_PER_ML', '', '10', 'ARD_CAP', 'A', 'P', '', '1.46', '', '', '', '', '', '', 'BIGR_GBOSS_Value_Set', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('BIGR_GBOSS', 'CA12181C', 'LIMS_INFLAMMATION', '', '10', 'ARD_CAP', 'A', 'P', '', '1.46', '', '', '', '', '', '', 'BIGR_GBOSS_Value_Set', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('BIGR_GBOSS', 'CA12182C', 'LIMS_TUMOR_FEATURES', '', '10', 'ARD_CAP', 'A', 'P', '', '1.46', '', '', '', '', '', '', 'BIGR_GBOSS_Value_Set', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('BIGR_GBOSS', 'CA12183C', 'LIMS_TUMOR_STROMA_CELLULAR_FEATURES', '', '10', 'ARD_CAP', 'A', 'P', '', '1.46', '', '', '', '', '', '', 'BIGR_GBOSS_Value_Set', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('BIGR_GBOSS', 'CA12184C', 'LIMS_TUMOR_STROMA_HYPOACELLULAR_FEATURES', '', '10', 'ARD_CAP', 'A', 'P', '', '1.46', '', '', '', '', '', '', 'BIGR_GBOSS_Value_Set', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('BIGR_GBOSS', 'CA12185C', 'SURGICAL_REMOVAL_TIME_ACCURACY', '', '10', 'ARD_CAP', 'A', 'P', '', '1.46', '', '', '', '', '', '', 'BIGR_GBOSS_Value_Set', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('BIGR_GBOSS', 'CA12186C', 'PARAFFIN_DIMENSIONS', '', '10', 'ARD_CAP', 'A', 'P', '', '1.46', '', '', '', '', '', '', 'BIGR_GBOSS_Value_Set', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('BIGR_GBOSS', 'CA12187C', 'PARAFFIN_FEATURE', '', '10', 'ARD_CAP', 'A', 'P', '', '1.46', '', '', '', '', '', '', 'BIGR_GBOSS_Value_Set', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('BIGR_GBOSS', 'CA12188C', 'SAMPLE_TYPE', '', '10', 'ARD_CAP', 'A', 'P', '', '1.46', '', '', '', '', '', '', 'BIGR_GBOSS_Value_Set', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('BIGR_GBOSS', 'CA12189C', 'LIMS_RE_PV_REASON', '', '10', 'ARD_CAP', 'A', 'P', '', '1.46', '', '', '', '', '', '', 'BIGR_GBOSS_Value_Set', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('BIGR_GBOSS', 'CA12190C', 'LIMS_RE_PV_SOURCE', '', '10', 'ARD_CAP', 'A', 'P', '', '1.46', '', '', '', '', '', '', 'BIGR_GBOSS_Value_Set', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('BIGR_GBOSS', 'CA12191C', 'LIMS_INCIDENT_ACTION', '', '10', 'ARD_CAP', 'A', 'P', '', '1.46', '', '', '', '', '', '', 'BIGR_GBOSS_Value_Set', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('BIGR_GBOSS', 'CA12192C', 'LIMS_PULL_REASON', '', '10', 'ARD_CAP', 'A', 'P', '', '1.46', '', '', '', '', '', '', 'BIGR_GBOSS_Value_Set', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('BIGR_GBOSS', 'CA12193C', 'LIMS_EXTERNAL_FEATURES', '', '10', 'ARD_CAP', 'A', 'P', '', '1.46', '', '', '', '', '', '', 'BIGR_GBOSS_Value_Set', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('BIGR_GBOSS', 'CA12194C', 'LIMS_INTERNAL_QUALITY_ISSUES', '', '10', 'ARD_CAP', 'A', 'P', '', '1.46', '', '', '', '', '', '', 'BIGR_GBOSS_Value_Set', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('BIGR_GBOSS', 'CA12195C', 'HISTO_REEMBED_REASON', '', '10', 'ARD_CAP', 'A', 'P', '', '1.46', '', '', '', '', '', '', 'BIGR_GBOSS_Value_Set', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('BIGR_GBOSS', 'CA12196C', 'PATH_SECTION_ID', '', '10', 'ARD_CAP', 'A', 'P', '', '1.46', '', '', '', '', '', '', 'BIGR_GBOSS_Value_Set', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('BIGR_GBOSS', 'CA12197C', 'SAMPLE_VOLUME_UNIT', '', '10', 'ARD_CAP', 'A', 'P', '', '1.46', '', '', '', '', '', '', 'BIGR_GBOSS_Value_Set', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('BIGR_GBOSS', 'CA12198C', 'SAMPLE_WEIGHT_UNIT', '', '10', 'ARD_CAP', 'A', 'P', '', '1.46', '', '', '', '', '', '', 'BIGR_GBOSS_Value_Set', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('BIGR_GBOSS', 'CA12199C', 'MEDICAL_RECORD_SECTION', '', '10', 'ARD_CAP', 'A', 'P', '', '1.46', '', '', '', '', '', '', 'BIGR_GBOSS_Value_Set', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('BIGR_GBOSS', 'CA12200C', 'COUNTRY', '', '10', 'ARD_CAP', 'A', 'P', '', '1.46', '', '', '', '', '', '', 'BIGR_GBOSS_Value_Set', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('BIGR_GBOSS', 'CA12201C', 'ETHNICITY', '', '10', 'ARD_CAP', 'A', 'P', '', '1.46', '', '', '', '', '', '', 'BIGR_GBOSS_Value_Set', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('BIGR_GBOSS', 'CA12202C', 'RACE', '', '10', 'ARD_CAP', 'A', 'P', '', '1.46', '', '', '', '', '', '', 'BIGR_GBOSS_Value_Set', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('BIGR_GBOSS', 'CA12203C', 'DISEASE_TYPE', '', '10', 'ARD_CAP', 'A', 'P', '', '1.46', '', '', '', '', '', '', 'BIGR_GBOSS_Value_Set', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('BIGR_GBOSS', 'CA12204C', 'GROSS_APPEARANCE', '', '10', 'ARD_CAP', 'A', 'P', '', '1.46', '', '', '', '', '', '', 'BIGR_GBOSS_Value_Set', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('BIGR_GBOSS', 'CA12205C', 'MICROSCOPIC_APPEARANCE', '', '10', 'ARD_CAP', 'A', 'P', '', '1.46', '', '', '', '', '', '', 'BIGR_GBOSS_Value_Set', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('BIGR_GBOSS', 'CA12206C', 'CELL_INFILTRATE_AMT', '', '10', 'ARD_CAP', 'A', 'P', '', '1.46', '', '', '', '', '', '', 'BIGR_GBOSS_Value_Set', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('BIGR_GBOSS', 'CA12207C', 'EXTRANODAL_SPREAD', '', '10', 'ARD_CAP', 'A', 'P', '', '1.46', '', '', '', '', '', '', 'BIGR_GBOSS_Value_Set', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('BIGR_GBOSS', 'CA12208C', 'EXTENSIVE_INTRADUCTAL_COMPONENT', '', '10', 'ARD_CAP', 'A', 'P', '', '1.46', '', '', '', '', '', '', 'BIGR_GBOSS_Value_Set', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('BIGR_GBOSS', 'CA12209C', 'INFLAMMATORY_CELL_INFILTRATE', '', '10', 'ARD_CAP', 'A', 'P', '', '1.46', '', '', '', '', '', '', 'BIGR_GBOSS_Value_Set', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('BIGR_GBOSS', 'CA12210C', 'JOINT_COMPONENT', '', '10', 'ARD_CAP', 'A', 'P', '', '1.46', '', '', '', '', '', '', 'BIGR_GBOSS_Value_Set', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('BIGR_GBOSS', 'CA12211C', 'LYMPHATIC_VASCULAR_INVASION', '', '10', 'ARD_CAP', 'A', 'P', '', '1.46', '', '', '', '', '', '', 'BIGR_GBOSS_Value_Set', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('BIGR_GBOSS', 'CA12212C', 'PERINEURAL_INVASION_IND', '', '10', 'ARD_CAP', 'A', 'P', '', '1.46', '', '', '', '', '', '', 'BIGR_GBOSS_Value_Set', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('BIGR_GBOSS', 'CA12213C', 'VENOUS_VESSEL_INVASION', '', '10', 'ARD_CAP', 'A', 'P', '', '1.46', '', '', '', '', '', '', 'BIGR_GBOSS_Value_Set', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('PATH_VERIFICATION', 'CA12214C', 'Lesion', '', '', 'ARD_CAP', 'A', 'P', '', '1.46', '', 'lesion', '1', 'N', 'int', '', 'Element', 'CA05658C', '0', '100', 'Y', 'Y', '', 'N', '', '15', '');
insert into pdc_lookup values('PATH_VERIFICATION', 'CA12215C', 'Other special characteristics', '', '', 'ARD_CAP', 'A', 'P', '', '1.46', '', '', '', '', '', 'Y', 'Value', '', '', '', '', '', '', '', '', '15', '');
insert into pdc_lookup values('PATH_VERIFICATION', 'CA12216C', 'No normal architecture in lesional component', '', '', 'ARD_CAP', 'A', 'P', '', '1.46', '', 'no_nl_arch_in_lesion', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '15', '');
insert into pdc_lookup values('BIGR_GBOSS', 'CA12217C', 'TUMOR_CONFIGURATION', '', '10', 'ARD_CAP', 'A', 'P', '', '1.46', '', '', '', '', '', '', 'BIGR_GBOSS_Value_Set', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('TOPIC', 'CA12218C', 'Blank Fields', '', '', 'ARD_CAP', 'A', 'P', '', '1.46', '', 'blank_fields', '', '', '', '', 'Category', '', '', '', '', '', '', 'N', '', '15', '');
insert into pdc_lookup values('BIGR_GBOSS', 'CA12219C', 'TUMOR_STAGE_TYPE', '', '10', 'ARD_CAP', 'A', 'P', '', '1.46', '', '', '', '', '', '', 'BIGR_GBOSS_Value_Set', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12220C', 'Blank text field 1', '', '', 'ARD_CAP', 'A', 'P', '', '1.46', '', 'blank_text_one', '1', 'N', 'report', '', 'Element', '', '', '', '', '', '', 'N', '', '15', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12221C', 'Blank text field 2', '', '', 'ARD_CAP', 'A', 'P', '', '1.46', '', 'blank_text_two', '1', 'N', 'report', '', 'Element', '', '', '', '', '', '', 'N', '', '15', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12222C', 'Blank text field 3', '', '', 'ARD_CAP', 'A', 'P', '', '1.46', '', 'blank_text_three', '1', 'N', 'report', '', 'Element', '', '', '', '', '', '', 'N', '', '15', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12223C', 'Blank text field 4', '', '', 'ARD_CAP', 'A', 'P', '', '1.46', '', 'blank_text_four', '1', 'N', 'report', '', 'Element', '', '', '', '', '', '', 'N', '', '15', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12224C', 'Blank text field 5', '', '', 'ARD_CAP', 'A', 'P', '', '1.46', '', 'blank_text_five', '1', 'N', 'report', '', 'Element', '', '', '', '', '', '', 'N', '', '15', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12225C', 'Blank report field 1', '', '', 'ARD_CAP', 'A', 'P', '', '1.46', '', 'blank_report_one', '1', 'N', 'report', '', 'Element', '', '', '', '', '', '', 'N', '', '15', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12226C', 'Blank report field 2', '', '', 'ARD_CAP', 'A', 'P', '', '1.46', '', 'blank_report_two', '1', 'N', 'report', '', 'Element', '', '', '', '', '', '', 'N', '', '15', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12227C', 'Blank report field 3', '', '', 'ARD_CAP', 'A', 'P', '', '1.46', '', 'blank_report_three', '1', 'N', 'report', '', 'Element', '', '', '', '', '', '', 'N', '', '15', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12228C', 'Blank date field 1', '', '', 'ARD_CAP', 'A', 'P', '', '1.46', '', 'blank_date_one', '1', 'N', 'date', '', 'Element', '', '', '', '', '', '', 'N', '', '15', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12229C', 'Blank date field 2', '', '', 'ARD_CAP', 'A', 'P', '', '1.46', '', 'blank_date_two', '1', 'N', 'date', '', 'Element', '', '', '', '', '', '', 'N', '', '15', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12230C', 'Blank date field 3', '', '', 'ARD_CAP', 'A', 'P', '', '1.46', '', 'blank_date_three', '1', 'N', 'date', '', 'Element', '', '', '', '', '', '', 'N', '', '15', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12231C', 'Blank float field 1', '', '', 'ARD_CAP', 'A', 'P', '', '1.46', '', 'blank_float_one', '1', 'N', 'float', '', 'Element', '', '', '', '', '', '', 'N', '', '15', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12232C', 'Blank float field 2', '', '', 'ARD_CAP', 'A', 'P', '', '1.46', '', 'blank_float_two', '1', 'N', 'float', '', 'Element', '', '', '', '', '', '', 'N', '', '15', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12233C', 'Blank float field 3', '', '', 'ARD_CAP', 'A', 'P', '', '1.46', '', 'blank_float_three', '1', 'N', 'float', '', 'Element', '', '', '', '', '', '', 'N', '', '15', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12234C', 'Blank integer field 1', '', '', 'ARD_CAP', 'A', 'P', '', '1.46', '', 'blank_integer_one', '1', 'N', 'int', '', 'Element', '', '', '', '', '', '', 'N', '', '15', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12235C', 'Blank integer field 2', '', '', 'ARD_CAP', 'A', 'P', '', '1.46', '', 'blank_integer_two', '1', 'N', 'int', '', 'Element', '', '', '', '', '', '', 'N', '', '15', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12236C', 'Blank integer field 3', '', '', 'ARD_CAP', 'A', 'P', '', '1.46', '', 'blank_integer_three', '1', 'N', 'int', '', 'Element', '', '', '', '', '', '', 'N', '', '15', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12237C', 'Blank YN field', '', '', 'ARD_CAP', 'A', 'P', '', '1.46', '', 'blank_yn', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '15', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12238C', 'Blank YNDK field', '', '', 'ARD_CAP', 'A', 'P', '', '1.46', '', 'blank_yndk', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '15', '');
insert into pdc_lookup values('BIGR_GBOSS', 'CA12239C', 'HISTOLOGICAL_NUCLEAR_GRADE', '', '10', 'ARD_CAP', 'A', 'P', '', '1.46', '', '', '', '', '', '', 'BIGR_GBOSS_Value_Set', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('BIGR_GBOSS', 'CA12240C', 'STORAGE_TYPE', '', '10', 'ARD_CAP', 'A', 'P', '', '1.46', '', '', '', '', '', '', 'BIGR_GBOSS_Value_Set', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('BIGR_GBOSS', 'CA12241C', 'HISTOLOGICAL_NUCLEAR_GRADE_DUKE', '', '10', 'ARD_CAP', 'A', 'P', '', '1.46', '', '', '', '', '', '', 'BIGR_GBOSS_Value_Set', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('BIGR_GBOSS', 'CA12242C', 'DERIVATION_OPERATIONS', '', '10', 'ARD_CAP', 'A', 'P', '', '1.46', '', '', '', '', '', '', 'BIGR_GBOSS_Value_Set', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('ALLERGEN', 'CA12243C', 'ALLERGEN_DET_NO_ADE', '', '', 'ARD_CAP', 'A', 'P', '', '1.46', '', '', '', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '15', '');
insert into pdc_lookup values('BIGR_GBOSS', 'CA12246C', 'HISTOLOGICAL_TYPE', '', '10', 'ARD_CAP', 'A', 'P', '', '1.46', '', '', '', '', '', '', 'BIGR_GBOSS_Value_Set', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('PATH_VERIFICATION', 'CA12252C', 'Tumor features', '', '', 'ARD_CAP', 'A', 'P', '', '1.46', '', 'tumor_feature', 'N', 'Y', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '15', '');
insert into pdc_lookup values('PATH_VERIFICATION', 'CA12253C', 'Cellular stroma features', '', '', 'ARD_CAP', 'A', 'P', '', '1.46', '', 'cell_stroma_feature', 'N', 'Y', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '15', '');
insert into pdc_lookup values('PATH_VERIFICATION', 'CA12254C', 'Hypo/acellular stroma features', '', '', 'ARD_CAP', 'A', 'P', '', '1.46', '', 'hypo_stroma_feature', 'N', 'Y', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '15', '');
insert into pdc_lookup values('STORAGE_TYPE', 'CA12255C', '4C Refrigerator', '', '10', 'ARD_CAP', 'A', 'P', '', '1.46', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('FOLLOWUP_INFORMATION', 'CA12256C', 'Vital status - WITHOUT ADE', '', '', 'ARD_CAP', 'A', 'P', '', '1.46', '', 'vital_status_wo_ade', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '15', '');
insert into pdc_lookup values('VITAL_STATUS', 'CA12257C', 'VITAL_STATUS_WITHOUT_ADE_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.46', '', '', '', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '15', '');

update pdc_lookup set lookup_type_cd_desc ='Tumor grade', system_name='tumor_grade', rev='1.46', drev='15' where lookup_type_cd ='CA12172C';
update pdc_lookup set lookup_type_cd_desc ='TUMOR_GRADE_DET', rev='1.46', drev='15' where lookup_type_cd ='CA12173C';
update pdc_lookup set lookup_type_cd_desc ='Appearance', system_name='appearance', rev='1.46', drev='15' where lookup_type_cd ='CA11770C';
update pdc_lookup set lookup_type_cd_desc ='APPEARANCE_DET', rev='1.46', drev='15' where lookup_type_cd ='CA11905C';
update pdc_lookup set lookup_type_cd_desc ='Supplier note', system_name='supplier_note', rev='1.46', drev='15' where lookup_type_cd ='CA12169C';
update pdc_lookup set lookup_type_cd_desc ='Special characteristics', system_name='special_char', oce_yn='Y',rev='1.46', drev='15' where lookup_type_cd ='CA11768C';
update pdc_lookup set lookup_type_cd_desc ='SPECIAL_CHARACTERISTICS_DET', rev='1.46', drev='15' where lookup_type_cd ='CA11893C';
update pdc_lookup set lookup_type_cd_desc ='Quality issues', system_name='quality_issue', rev='1.46', drev='15' where lookup_type_cd ='CA11769C';
update pdc_lookup set lookup_type_cd_desc ='QUALITY_ISSUES_DET', rev='1.46', drev='15' where lookup_type_cd ='CA11899C';
update pdc_lookup set lookup_type_cd_desc ='cg3: Double contours affecting more than 50% of periph cap loops in most affected of non-scler glom', rev='1.46', drev='15' where lookup_type_cd ='CA08965C';
update pdc_lookup set lookup_type_cd_desc ='v3: Arterial fibrinoid change and/or transmural arteritis with med smooth mus nec with lymph infl', rev='1.46', drev='15' where lookup_type_cd ='CA08954C';
update pdc_lookup set lookup_type_cd_desc ='Stage I: Compl resect any site, en bloc coccygect for sacrococ tum, nl tum marg, mark lev nl or el', rev='1.46', drev='15' where lookup_type_cd ='CA08432C';
update pdc_lookup set lookup_type_cd_desc ='Metastatic CUP to lymph nodes', rev='1.46', drev='15' where lookup_type_cd ='CA08526C';
update pdc_lookup set lookup_type_cd_desc ='Stage III: Gross residual disease or bx only, retroper node nl or inc with met dis, mark lev nl or el', rev='1.46', drev='15' where lookup_type_cd ='CA08430C';
update pdc_lookup set lookup_type_cd_desc ='Metastatic CUP of peritoneal cavity', rev='1.46', drev='15' where lookup_type_cd ='CA08524C';
update pdc_lookup set lookup_type_cd_desc ='t3: Foci with >10 cells/tub cross section, or at least 2 areas of tub base memb destr accomp by', rev='1.46', drev='15' where lookup_type_cd ='CA08944C';
update pdc_lookup set lookup_type_cd_desc ='Metastatic CUP to the lungs', rev='1.46', drev='15' where lookup_type_cd ='CA08529C';

update pdc_lookup set category_domain='MEDICAL_RECORD_SECTION', rev='1.46', drev='15' where lookup_type_cd = 'CA11979C';

update pdc_lookup set multiplicity = '1', oce_yn = 'N', datatype = 'int', unit_cui = 'CA05658C', min_value = '0', max_value ='100', min_inclusive_yn = 'Y', max_inclusive_yn='Y', rev='1.46', drev='15' where lookup_type_cd ='CA11763C';
update pdc_lookup set multiplicity = '1', oce_yn = 'N', datatype = 'int', unit_cui = 'CA05658C', min_value = '0', max_value ='100', min_inclusive_yn = 'Y', max_inclusive_yn='Y', rev='1.46', drev='15' where lookup_type_cd ='CA11764C';
update pdc_lookup set multiplicity = '1', oce_yn = 'N', datatype = 'int', unit_cui = 'CA05658C', min_value = '0', max_value ='100', min_inclusive_yn = 'Y', max_inclusive_yn='Y', rev='1.46', drev='15' where lookup_type_cd ='CA11765C';

update pdc_dx_tc_hierarchy set fully_specified_name='Adenocarcinoma of stomach, intestinal type', rev='1.46' where owner_code ='126824007^25190001^';

commit;
