set define off;

delete from pdc_lookup where lookup_type_cd = 'CA11785C';
delete from pdc_lookup where lookup_type_cd = 'CA11891C';
delete from pdc_lookup where lookup_type_cd = 'CA11947C';
delete from pdc_lookup where lookup_type_cd = 'CA06587C';
delete from pdc_lookup where lookup_type_cd = 'CA02387C';
delete from pdc_lookup where lookup_type_cd = 'CA09801C';
delete from pdc_lookup where lookup_type_cd = 'CA09829C';
delete from pdc_lookup where lookup_type_cd = 'CA09835C';
delete from pdc_lookup where lookup_type_cd = 'CA09824C';
delete from pdc_lookup where lookup_type_cd = 'CA09840C';
delete from pdc_lookup where lookup_type_cd = 'CA09841C';
delete from pdc_lookup where lookup_type_cd = 'CA09842C';
delete from pdc_lookup where lookup_type_cd = 'CA01552C';
delete from pdc_lookup where lookup_type_cd = 'CA06685C';
delete from pdc_lookup where lookup_type_cd = 'CA09834C';
delete from pdc_lookup where lookup_type_cd = 'CA01553C';

update pdc_lookup set lookup_type_cd_desc ='Endometrium', annotation='change name', rev='1.48', drev='16' where lookup_type_cd ='CA11842C';
update pdc_lookup set lookup_type_cd_desc ='Desmoplastic reaction', annotation='corrected spelling', rev='1.48', drev='16' where lookup_type_cd ='CA11937C';
update pdc_lookup set other_cui_yn='Y', rev='1.48', drev='16' where lookup_type_cd ='91723000';
update pdc_lookup set datatype='text', rev='1.48', drev='16' where lookup_type_cd ='CA11565C';
update pdc_lookup set datatype='text', rev='1.48', drev='16' where lookup_type_cd ='CA11229C';
update pdc_lookup set datatype='text', rev='1.48', drev='16' where lookup_type_cd ='CA11566C';
update pdc_lookup set datatype='text', rev='1.48', drev='16' where lookup_type_cd ='CA11567C';
update pdc_lookup set datatype='text', rev='1.48', drev='16' where lookup_type_cd ='CA11568C';
update pdc_lookup set datatype='text', rev='1.48', drev='16' where lookup_type_cd ='CA11190C';
update pdc_lookup set datatype='text', rev='1.48', drev='16' where lookup_type_cd ='CA11582C';
update pdc_lookup set datatype='text', rev='1.48', drev='16' where lookup_type_cd ='CA11241C';
update pdc_lookup set datatype='text', rev='1.48', drev='16' where lookup_type_cd ='CA11235C';
update pdc_lookup set datatype='text', rev='1.48', drev='16' where lookup_type_cd ='CA11227C';
update pdc_lookup set datatype='text', rev='1.48', drev='16' where lookup_type_cd ='CA12168C';
update pdc_lookup set datatype='text', rev='1.48', drev='16' where lookup_type_cd ='CA12169C';
update pdc_lookup set datatype='text', rev='1.48', drev='16' where lookup_type_cd ='CA12170C';
update pdc_lookup set datatype='text', rev='1.48', drev='16' where lookup_type_cd ='CA11212C';
update pdc_lookup set datatype='text', rev='1.48', drev='16' where lookup_type_cd ='CA12220C';
update pdc_lookup set datatype='text', rev='1.48', drev='16' where lookup_type_cd ='CA12221C';
update pdc_lookup set datatype='text', rev='1.48', drev='16' where lookup_type_cd ='CA12222C';
update pdc_lookup set datatype='text', rev='1.48', drev='16' where lookup_type_cd ='CA12223C';
update pdc_lookup set datatype='text', rev='1.48', drev='16' where lookup_type_cd ='CA12224C';

insert into pdc_lookup values('TOPIC', 'CA12258C', 'Sample pathology', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', 'sample_path', '', '', '', '', 'Category', '', '', '', '', '', '', 'N', '', '16', '');
insert into pdc_lookup values('PATH_VERIFICATION', 'CA12259C', 'Sample diagnosis', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', 'sample_dx', '1', 'Y', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '16', '');
insert into pdc_lookup values('PATH_VERIFICATION', 'CA12260C', 'Sample tissue of origin', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', 'sample_too', '1', 'Y', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '16', '');
insert into pdc_lookup values('PATH_VERIFICATION', 'CA12261C', 'Sample site of finding', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', 'sample_sof', '1', 'Y', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '16', '');
insert into pdc_lookup values('AJCC6_PATH_STAGE_GROUP', 'CA11891C', 'Not applicable', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '16', '');
insert into pdc_lookup values('PATH_VERIFICATION', 'CA11947C', 'Strange orientation', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '16', '');
insert into pdc_lookup values('PATH_VERIFICATION', 'CA12244C', 'Superficial section', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '16', '');
insert into pdc_lookup values('BODY_SYSTEM', 'CA12247C', 'BODY_SYSTEM_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '16', '');
insert into pdc_lookup values('DIAGNOSIS_GROUP', 'CA12248C', 'DIAGNOSIS_GROUP_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '16', '');
insert into pdc_lookup values('SPECIES', 'CA12249C', 'SPECIES_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '16', '');
insert into pdc_lookup values('STATE', 'CA12250C', 'STATE_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '16', '');
insert into pdc_lookup values('TREATMENT_FREQUENCY', 'CA12251C', 'TREATMENT_FREQUENCY_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '16', '');
insert into pdc_lookup values('DIAGNOSIS', '126851005^19929002^', 'Angiomyolipoma of liver', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '16', '');
insert into pdc_lookup values('DIAGNOSIS', '126859007^59367005^', 'Carcinoma of pancreas, adenosquamous', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '16', '');
insert into pdc_lookup values('DIAGNOSIS', '126908007^30289006^', 'Adenocarcinoma of uterus, endometrioid', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '16', '');
insert into pdc_lookup values('DIAGNOSIS', '277844007^^', 'Lymphangioleiomyomatosis of lung', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '16', '');
insert into pdc_lookup values('GRAPH_CONTEXT_NAME', 'CA12262C', 'RNA Protein Profile', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'BIGR_GBOSS_Value_Set', '', '', '', '', '', '', '', '', '16', '');

insert into pdc_dx_tc_hierarchy values ('126851005^19929002^', 'Angiomyolipoma of liver', '128348002^^', '3', 'D', '1415', '1', 'A', 'P', 'ANDIG', '1.48', '');
insert into pdc_dx_tc_hierarchy values ('126859007^59367005^', 'Carcinoma of pancreas, adenosquamous', '128348002^^', '3', 'D', '1605', '1', 'A', 'P', 'ANDIG', '1.48', '');
insert into pdc_dx_tc_hierarchy values ('126908007^30289006^', 'Adenocarcinoma of uterus, endometrioid', '126907002^^', '3', 'D', '3295', '1', 'A', 'P', 'ANFRS', '1.48', '');
insert into pdc_dx_tc_hierarchy values ('277844007^^', 'Lymphangioleiomyomatosis of lung', '126667002^^', '3', 'D', '7845', '1', 'A', 'P', 'ANRES', '1.48', '');

delete from bigr_data_fixes where attrib1 in ('CA00625C', 'CA00688C', 'CA00775C', 'CA079834', 'CA079843', 'CA080142', 'CA080167');
delete from bigr_data_fixes where attrib3 in ('62302004', '73735000', '117617002', 'CA00681C');

delete from pdc_path_report_diag_hist where diagnostics_concept_id = '48493000';
delete from pdc_path_report_diag_hist where diagnostics_concept_id = '62302004';
delete from pdc_path_report_diag_hist where diagnostics_concept_id = '73735000';
delete from pdc_path_report_diag_hist where diagnostics_concept_id = '117617002';
delete from pdc_path_report_diag_hist where diagnostics_concept_id = 'CA00632C';
delete from pdc_path_report_diag_hist where diagnostics_concept_id = 'CA00674C';
delete from pdc_path_report_diag_hist where diagnostics_concept_id = 'CA00681C';
delete from pdc_path_report_diag_hist where diagnostics_concept_id = 'CA00688C';
delete from pdc_path_report_diag_hist where diagnostics_concept_id = 'CA00692C';
delete from pdc_path_report_diag_hist where diagnostics_concept_id = 'CA00745C';
delete from pdc_path_report_diag_hist where diagnostics_concept_id = 'CA00748C';
delete from pdc_path_report_diag_hist where diagnostics_concept_id = 'CA00754C';
delete from pdc_path_report_diag_hist where diagnostics_concept_id = 'CA00775C';
delete from pdc_path_report_diag_hist where diagnostics_concept_id = 'CA00939C';
delete from pdc_path_report_diag_hist where diagnostics_concept_id = 'CA00941C';
delete from pdc_path_report_diag_hist where diagnostics_concept_id = 'CA00944C';
delete from pdc_path_report_diag_hist where diagnostics_concept_id = 'CA00950C';
delete from pdc_path_report_diag_hist where diagnostics_concept_id = 'CA00951C';
delete from pdc_path_report_diag_hist where diagnostics_concept_id = 'CA00952C';
delete from pdc_path_report_diag_hist where diagnostics_concept_id = 'CA00953C';
delete from pdc_path_report_diag_hist where diagnostics_concept_id = 'CA00955C';
delete from pdc_path_report_diag_hist where diagnostics_concept_id = 'CA00969C';
delete from pdc_path_report_diag_hist where diagnostics_concept_id = 'CA02018C';
delete from pdc_path_report_diag_hist where diagnostics_concept_id = 'CA02019C';
delete from pdc_path_report_diag_hist where diagnostics_concept_id = 'CA02026C';
delete from pdc_path_report_diag_hist where diagnostics_concept_id = 'CA02058C';
delete from pdc_path_report_diag_hist where diagnostics_concept_id = 'CA02066C';
delete from pdc_path_report_diag_hist where diagnostics_concept_id = 'CA02067C';
delete from pdc_path_report_diag_hist where diagnostics_concept_id = 'CA02579C';
delete from pdc_path_report_diag_hist where diagnostics_concept_id = 'CA02580C';
delete from pdc_path_report_diag_hist where diagnostics_concept_id = 'CA02581C';
delete from pdc_path_report_diag_hist where diagnostics_concept_id = 'CA02582C';
delete from pdc_path_report_diag_hist where diagnostics_concept_id = 'CA02583C';
delete from pdc_path_report_diag_hist where diagnostics_concept_id = 'CA02589C';
delete from pdc_path_report_diag_hist where diagnostics_concept_id = 'CA02596C';
delete from pdc_path_report_diag_hist where diagnostics_concept_id = 'CA04138C';
delete from pdc_path_report_diag_hist where diagnostics_concept_id = 'CA079777';
delete from pdc_path_report_diag_hist where diagnostics_concept_id = 'CA079781';
delete from pdc_path_report_diag_hist where diagnostics_concept_id = 'CA079783';
delete from pdc_path_report_diag_hist where diagnostics_concept_id = 'CA079785';
delete from pdc_path_report_diag_hist where diagnostics_concept_id = 'CA079798';
delete from pdc_path_report_diag_hist where diagnostics_concept_id = 'CA079834';
delete from pdc_path_report_diag_hist where diagnostics_concept_id = 'CA079840';
delete from pdc_path_report_diag_hist where diagnostics_concept_id = 'CA079843';
delete from pdc_path_report_diag_hist where diagnostics_concept_id = 'CA080142';
delete from pdc_path_report_diag_hist where diagnostics_concept_id = 'CA080167';

delete from pdc_lookup where lookup_type_cd = '0';
delete from pdc_lookup where lookup_type_cd = '9';
delete from pdc_lookup where lookup_type_cd = '8';
delete from pdc_lookup where lookup_type_cd = '7';
delete from pdc_lookup where lookup_type_cd = '6';
delete from pdc_lookup where lookup_type_cd = '5';
delete from pdc_lookup where lookup_type_cd = '4';
delete from pdc_lookup where lookup_type_cd = '3';
delete from pdc_lookup where lookup_type_cd = '2';
delete from pdc_lookup where lookup_type_cd = '1';
delete from pdc_lookup where lookup_type_cd = '8319008';
delete from pdc_lookup where lookup_type_cd = '8928004';
delete from pdc_lookup where lookup_type_cd = '10664000';
delete from pdc_lookup where lookup_type_cd = '28870006';
delete from pdc_lookup where lookup_type_cd = '37117007';
delete from pdc_lookup where lookup_type_cd = '46055009';
delete from pdc_lookup where lookup_type_cd = '48493000';
delete from pdc_lookup where lookup_type_cd = '51185008';
delete from pdc_lookup where lookup_type_cd = '53074004';
delete from pdc_lookup where lookup_type_cd = '53966003';
delete from pdc_lookup where lookup_type_cd = '56185007';
delete from pdc_lookup where lookup_type_cd = '58130000';
delete from pdc_lookup where lookup_type_cd = '62302004';
delete from pdc_lookup where lookup_type_cd = '62683002';
delete from pdc_lookup where lookup_type_cd = '68171009';
delete from pdc_lookup where lookup_type_cd = '73735000';
delete from pdc_lookup where lookup_type_cd = '76838003';
delete from pdc_lookup where lookup_type_cd = '81124000';
delete from pdc_lookup where lookup_type_cd = '81132008';
delete from pdc_lookup where lookup_type_cd = '85097005';
delete from pdc_lookup where lookup_type_cd = '85119005';
delete from pdc_lookup where lookup_type_cd = '91394001';
delete from pdc_lookup where lookup_type_cd = '117617002';
delete from pdc_lookup where lookup_type_cd = '245285004';
delete from pdc_lookup where lookup_type_cd = 'CA00027T';
delete from pdc_lookup where lookup_type_cd = 'CA00028T';
delete from pdc_lookup where lookup_type_cd = 'CA00029T';
delete from pdc_lookup where lookup_type_cd = 'CA00030T';
delete from pdc_lookup where lookup_type_cd = 'CA00304C';
delete from pdc_lookup where lookup_type_cd = 'CA00352C';
delete from pdc_lookup where lookup_type_cd = 'CA00624C';
delete from pdc_lookup where lookup_type_cd = 'CA00625C';
delete from pdc_lookup where lookup_type_cd = 'CA00632C';
delete from pdc_lookup where lookup_type_cd = 'CA00673C';
delete from pdc_lookup where lookup_type_cd = 'CA00674C';
delete from pdc_lookup where lookup_type_cd = 'CA00681C';
delete from pdc_lookup where lookup_type_cd = 'CA00688C';
delete from pdc_lookup where lookup_type_cd = 'CA00692C';
delete from pdc_lookup where lookup_type_cd = 'CA00722C';
delete from pdc_lookup where lookup_type_cd = 'CA00745C';
delete from pdc_lookup where lookup_type_cd = 'CA00748C';
delete from pdc_lookup where lookup_type_cd = 'CA00754C';
delete from pdc_lookup where lookup_type_cd = 'CA00775C';
delete from pdc_lookup where lookup_type_cd = 'CA00850C';
delete from pdc_lookup where lookup_type_cd = 'CA00939C';
delete from pdc_lookup where lookup_type_cd = 'CA00941C';
delete from pdc_lookup where lookup_type_cd = 'CA00943C';
delete from pdc_lookup where lookup_type_cd = 'CA00944C';
delete from pdc_lookup where lookup_type_cd = 'CA00950C';
delete from pdc_lookup where lookup_type_cd = 'CA00951C';
delete from pdc_lookup where lookup_type_cd = 'CA00952C';
delete from pdc_lookup where lookup_type_cd = 'CA00953C';
delete from pdc_lookup where lookup_type_cd = 'CA00955C';
delete from pdc_lookup where lookup_type_cd = 'CA00957C';
delete from pdc_lookup where lookup_type_cd = 'CA00958C';
delete from pdc_lookup where lookup_type_cd = 'CA00959C';
delete from pdc_lookup where lookup_type_cd = 'CA00960C';
delete from pdc_lookup where lookup_type_cd = 'CA00961C';
delete from pdc_lookup where lookup_type_cd = 'CA00963C';
delete from pdc_lookup where lookup_type_cd = 'CA00964C';
delete from pdc_lookup where lookup_type_cd = 'CA00969C';
delete from pdc_lookup where lookup_type_cd = 'CA00986C';
delete from pdc_lookup where lookup_type_cd = 'CA01101C';
delete from pdc_lookup where lookup_type_cd = 'CA01135C';
delete from pdc_lookup where lookup_type_cd = 'CA01539C';
delete from pdc_lookup where lookup_type_cd = 'CA02013C';
delete from pdc_lookup where lookup_type_cd = 'CA02016C';
delete from pdc_lookup where lookup_type_cd = 'CA02017C';
delete from pdc_lookup where lookup_type_cd = 'CA02018C';
delete from pdc_lookup where lookup_type_cd = 'CA02019C';
delete from pdc_lookup where lookup_type_cd = 'CA02021C';
delete from pdc_lookup where lookup_type_cd = 'CA02022C';
delete from pdc_lookup where lookup_type_cd = 'CA02023C';
delete from pdc_lookup where lookup_type_cd = 'CA02026C';
delete from pdc_lookup where lookup_type_cd = 'CA02029C';
delete from pdc_lookup where lookup_type_cd = 'CA02030C';
delete from pdc_lookup where lookup_type_cd = 'CA02032C';
delete from pdc_lookup where lookup_type_cd = 'CA02033C';
delete from pdc_lookup where lookup_type_cd = 'CA02035C';
delete from pdc_lookup where lookup_type_cd = 'CA02037C';
delete from pdc_lookup where lookup_type_cd = 'CA02043C';
delete from pdc_lookup where lookup_type_cd = 'CA02044C';
delete from pdc_lookup where lookup_type_cd = 'CA02047C';
delete from pdc_lookup where lookup_type_cd = 'CA02050C';
delete from pdc_lookup where lookup_type_cd = 'CA02053C';
delete from pdc_lookup where lookup_type_cd = 'CA02054C';
delete from pdc_lookup where lookup_type_cd = 'CA02056C';
delete from pdc_lookup where lookup_type_cd = 'CA02057C';
delete from pdc_lookup where lookup_type_cd = 'CA02058C';
delete from pdc_lookup where lookup_type_cd = 'CA02059C';
delete from pdc_lookup where lookup_type_cd = 'CA02061C';
delete from pdc_lookup where lookup_type_cd = 'CA02062C';
delete from pdc_lookup where lookup_type_cd = 'CA02064C';
delete from pdc_lookup where lookup_type_cd = 'CA02066C';
delete from pdc_lookup where lookup_type_cd = 'CA02067C';
delete from pdc_lookup where lookup_type_cd = 'CA02068C';
delete from pdc_lookup where lookup_type_cd = 'CA02070C';
delete from pdc_lookup where lookup_type_cd = 'CA02073C';
delete from pdc_lookup where lookup_type_cd = 'CA02318C';
delete from pdc_lookup where lookup_type_cd = 'CA02575C';
delete from pdc_lookup where lookup_type_cd = 'CA02576C';
delete from pdc_lookup where lookup_type_cd = 'CA02577C';
delete from pdc_lookup where lookup_type_cd = 'CA02578C';
delete from pdc_lookup where lookup_type_cd = 'CA02579C';
delete from pdc_lookup where lookup_type_cd = 'CA02580C';
delete from pdc_lookup where lookup_type_cd = 'CA02581C';
delete from pdc_lookup where lookup_type_cd = 'CA02582C';
delete from pdc_lookup where lookup_type_cd = 'CA02583C';
delete from pdc_lookup where lookup_type_cd = 'CA02584C';
delete from pdc_lookup where lookup_type_cd = 'CA02585C';
delete from pdc_lookup where lookup_type_cd = 'CA02588C';
delete from pdc_lookup where lookup_type_cd = 'CA02589C';
delete from pdc_lookup where lookup_type_cd = 'CA02590C';
delete from pdc_lookup where lookup_type_cd = 'CA02591C';
delete from pdc_lookup where lookup_type_cd = 'CA02592C';
delete from pdc_lookup where lookup_type_cd = 'CA02593C';
delete from pdc_lookup where lookup_type_cd = 'CA02595C';
delete from pdc_lookup where lookup_type_cd = 'CA02596C';
delete from pdc_lookup where lookup_type_cd = 'CA02597C';
delete from pdc_lookup where lookup_type_cd = 'CA02598C';
delete from pdc_lookup where lookup_type_cd = 'CA03071C';
delete from pdc_lookup where lookup_type_cd = 'CA03167C';
delete from pdc_lookup where lookup_type_cd = 'CA03173C';
delete from pdc_lookup where lookup_type_cd = 'CA03174C';
delete from pdc_lookup where lookup_type_cd = 'CA03175C';
delete from pdc_lookup where lookup_type_cd = 'CA03178C';
delete from pdc_lookup where lookup_type_cd = 'CA03207C';
delete from pdc_lookup where lookup_type_cd = 'CA03208C';
delete from pdc_lookup where lookup_type_cd = 'CA03209C';
delete from pdc_lookup where lookup_type_cd = 'CA03210C';
delete from pdc_lookup where lookup_type_cd = 'CA03211C';
delete from pdc_lookup where lookup_type_cd = 'CA03212C';
delete from pdc_lookup where lookup_type_cd = 'CA03214C';
delete from pdc_lookup where lookup_type_cd = 'CA03215C';
delete from pdc_lookup where lookup_type_cd = 'CA03216C';
delete from pdc_lookup where lookup_type_cd = 'CA03217C';
delete from pdc_lookup where lookup_type_cd = 'CA03221C';
delete from pdc_lookup where lookup_type_cd = 'CA03222C';
delete from pdc_lookup where lookup_type_cd = 'CA03233C';
delete from pdc_lookup where lookup_type_cd = 'CA03520C';
delete from pdc_lookup where lookup_type_cd = 'CA03565C';
delete from pdc_lookup where lookup_type_cd = 'CA04133C';
delete from pdc_lookup where lookup_type_cd = 'CA04134C';
delete from pdc_lookup where lookup_type_cd = 'CA04138C';
delete from pdc_lookup where lookup_type_cd = 'CA04139C';
delete from pdc_lookup where lookup_type_cd = 'CA04140C';
delete from pdc_lookup where lookup_type_cd = 'CA04141C';
delete from pdc_lookup where lookup_type_cd = 'CA04145C';
delete from pdc_lookup where lookup_type_cd = 'CA04146C';
delete from pdc_lookup where lookup_type_cd = 'CA05552C';
delete from pdc_lookup where lookup_type_cd = 'CA05558C';
delete from pdc_lookup where lookup_type_cd = 'CA05559C';
delete from pdc_lookup where lookup_type_cd = 'CA05561C';
delete from pdc_lookup where lookup_type_cd = 'CA05581C';
delete from pdc_lookup where lookup_type_cd = 'CA05583C';
delete from pdc_lookup where lookup_type_cd = 'CA05584C';
delete from pdc_lookup where lookup_type_cd = 'CA05586C';
delete from pdc_lookup where lookup_type_cd = 'CA05600C';
delete from pdc_lookup where lookup_type_cd = 'CA05669C';
delete from pdc_lookup where lookup_type_cd = 'CA05670C';
delete from pdc_lookup where lookup_type_cd = 'CA05671C';
delete from pdc_lookup where lookup_type_cd = 'CA05673C';
delete from pdc_lookup where lookup_type_cd = 'CA05674C';
delete from pdc_lookup where lookup_type_cd = 'CA05675C';
delete from pdc_lookup where lookup_type_cd = 'CA05676C';
delete from pdc_lookup where lookup_type_cd = 'CA05677C';
delete from pdc_lookup where lookup_type_cd = 'CA05678C';
delete from pdc_lookup where lookup_type_cd = 'CA05679C';
delete from pdc_lookup where lookup_type_cd = 'CA05680C';
delete from pdc_lookup where lookup_type_cd = 'CA05681C';
delete from pdc_lookup where lookup_type_cd = 'CA05682C';
delete from pdc_lookup where lookup_type_cd = 'CA05683C';
delete from pdc_lookup where lookup_type_cd = 'CA05684C';
delete from pdc_lookup where lookup_type_cd = 'CA05685C';
delete from pdc_lookup where lookup_type_cd = 'CA05686C';
delete from pdc_lookup where lookup_type_cd = 'CA05687C';
delete from pdc_lookup where lookup_type_cd = 'CA05688C';
delete from pdc_lookup where lookup_type_cd = 'CA05689C';
delete from pdc_lookup where lookup_type_cd = 'CA05690C';
delete from pdc_lookup where lookup_type_cd = 'CA05691C';
delete from pdc_lookup where lookup_type_cd = 'CA05692C';
delete from pdc_lookup where lookup_type_cd = 'CA05693C';
delete from pdc_lookup where lookup_type_cd = 'CA05767C';
delete from pdc_lookup where lookup_type_cd = 'CA05768C';
delete from pdc_lookup where lookup_type_cd = 'CA05769C';
delete from pdc_lookup where lookup_type_cd = 'CA05781C';
delete from pdc_lookup where lookup_type_cd = 'CA05948C';
delete from pdc_lookup where lookup_type_cd = 'CA06019C';
delete from pdc_lookup where lookup_type_cd = 'CA06501C';
delete from pdc_lookup where lookup_type_cd = 'CA07619C';
delete from pdc_lookup where lookup_type_cd = 'CA079777';
delete from pdc_lookup where lookup_type_cd = 'CA079781';
delete from pdc_lookup where lookup_type_cd = 'CA079783';
delete from pdc_lookup where lookup_type_cd = 'CA079785';
delete from pdc_lookup where lookup_type_cd = 'CA079798';
delete from pdc_lookup where lookup_type_cd = 'CA079834';
delete from pdc_lookup where lookup_type_cd = 'CA079840';
delete from pdc_lookup where lookup_type_cd = 'CA079843';
delete from pdc_lookup where lookup_type_cd = 'CA079875';
delete from pdc_lookup where lookup_type_cd = 'CA079916';
delete from pdc_lookup where lookup_type_cd = 'CA079923';
delete from pdc_lookup where lookup_type_cd = 'CA079925';
delete from pdc_lookup where lookup_type_cd = 'CA079926';
delete from pdc_lookup where lookup_type_cd = 'CA079927';
delete from pdc_lookup where lookup_type_cd = 'CA079965';
delete from pdc_lookup where lookup_type_cd = 'CA079966';
delete from pdc_lookup where lookup_type_cd = 'CA079967';
delete from pdc_lookup where lookup_type_cd = 'CA079968';
delete from pdc_lookup where lookup_type_cd = 'CA080142';
delete from pdc_lookup where lookup_type_cd = 'CA080167';
delete from pdc_lookup where lookup_type_cd = 'CA08411C';
delete from pdc_lookup where lookup_type_cd = 'CA08412C';
delete from pdc_lookup where lookup_type_cd = 'CA08413C';
delete from pdc_lookup where lookup_type_cd = 'CA08414C';
delete from pdc_lookup where lookup_type_cd = 'CA08506C';
delete from pdc_lookup where lookup_type_cd = 'CA08507C';
delete from pdc_lookup where lookup_type_cd = 'CA08508C';
delete from pdc_lookup where lookup_type_cd = 'CA08509C';
delete from pdc_lookup where lookup_type_cd = 'CA08510C';
delete from pdc_lookup where lookup_type_cd = 'CA08511C';
delete from pdc_lookup where lookup_type_cd = 'CA08512C';
delete from pdc_lookup where lookup_type_cd = 'CA08513C';
delete from pdc_lookup where lookup_type_cd = 'CA08514C';
delete from pdc_lookup where lookup_type_cd = 'CA08515C';
delete from pdc_lookup where lookup_type_cd = 'CA08516C';
delete from pdc_lookup where lookup_type_cd = 'CA08517C';
delete from pdc_lookup where lookup_type_cd = 'CA08518C';
delete from pdc_lookup where lookup_type_cd = 'CA08519C';
delete from pdc_lookup where lookup_type_cd = 'CA08520C';
delete from pdc_lookup where lookup_type_cd = 'CA08521C';
delete from pdc_lookup where lookup_type_cd = 'CA08522C';
delete from pdc_lookup where lookup_type_cd = 'CA09620C';
delete from pdc_lookup where lookup_type_cd = 'CA09627C';
delete from pdc_lookup where lookup_type_cd = 'CA09628C';
delete from pdc_lookup where lookup_type_cd = 'CA09629C';
delete from pdc_lookup where lookup_type_cd = 'CA09634C';
delete from pdc_lookup where lookup_type_cd = 'CA09638C';
delete from pdc_lookup where lookup_type_cd = 'CA09648C';
delete from pdc_lookup where lookup_type_cd = 'CA09649C';
delete from pdc_lookup where lookup_type_cd = 'CA09650C';
delete from pdc_lookup where lookup_type_cd = 'CA09655C';
delete from pdc_lookup where lookup_type_cd = 'CA09657C';
delete from pdc_lookup where lookup_type_cd = 'CA09658C';
delete from pdc_lookup where lookup_type_cd = 'CA09660C';
delete from pdc_lookup where lookup_type_cd = 'CA09661C';
delete from pdc_lookup where lookup_type_cd = 'CA09665C';
delete from pdc_lookup where lookup_type_cd = 'CA09668C';
delete from pdc_lookup where lookup_type_cd = 'CA09674C';
delete from pdc_lookup where lookup_type_cd = 'CA09677C';
delete from pdc_lookup where lookup_type_cd = 'CA09681C';
delete from pdc_lookup where lookup_type_cd = 'CA09683C';
delete from pdc_lookup where lookup_type_cd = 'CA09684C';
delete from pdc_lookup where lookup_type_cd = 'CA09686C';
delete from pdc_lookup where lookup_type_cd = 'CA09687C';
delete from pdc_lookup where lookup_type_cd = 'CA09689C';
delete from pdc_lookup where lookup_type_cd = 'CA09690C';
delete from pdc_lookup where lookup_type_cd = 'CA10413C';
delete from pdc_lookup where lookup_type_cd = 'CA11535C';
delete from pdc_lookup where lookup_type_cd = 'CA11550C';
delete from pdc_lookup where lookup_type_cd = 'CA12243C';

insert into pdc_lookup values('BLANK_FIELDS', 'CA12263C', 'Blank cv1 field 1', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', 'blank_cv1_one', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '16', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12264C', 'Blank cv1 field 2', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', 'blank_cv1_two', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '16', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12265C', 'Blank cv1 field 3', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', 'blank_cv1_three', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '16', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12266C', 'Blank cv1 field 4', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', 'blank_cv1_four', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '16', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12267C', 'Blank cv1 field 5', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', 'blank_cv1_five', '1', 'Y', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '16', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12268C', 'Blank cvN field 1', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', 'blank_cvN_one', 'N', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '16', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12269C', 'Blank cvN field 2', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', 'blank_cvN_two', 'N', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '16', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12270C', 'Blank cvN field 3', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', 'blank_cvN_three', 'N', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '16', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12271C', 'Blank cvN field 4', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', 'blank_cvN_four', 'N', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '16', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12272C', 'Blank cvN field 5', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', 'blank_cvN_five', 'N', 'Y', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '16', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12273C', 'BLANK_CV1_FIELD_1_VS_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '16', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12274C', 'BLANK_CV1_FIELD_2_VS_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '16', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12275C', 'BLANK_CV1_FIELD_3_VS_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '16', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12276C', 'BLANK_CV1_FIELD_4_VS_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '16', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12277C', 'BLANK_CV1_FIELD_5_VS_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '16', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12278C', 'BLANK_CVN_FIELD_1_VS_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '16', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12279C', 'BLANK_CVN_FIELD_2_VS_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '16', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12280C', 'BLANK_CVN_FIELD_3_VS_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '16', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12281C', 'BLANK_CVN_FIELD_4_VS_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '16', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12282C', 'BLANK_CVN_FIELD_5_VS_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '16', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12283C', 'Blank value 1', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '16', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12284C', 'Blank value 2', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '16', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12285C', 'Blank value 3', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '16', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12286C', 'Blank value 4', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '16', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12287C', 'Blank value 5', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '16', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12288C', 'Blank value 6', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '16', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12289C', 'Blank value 7', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '16', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12290C', 'Blank value 8', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '16', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12291C', 'Blank value 9', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '16', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12292C', 'Blank value 10', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '16', '');
insert into pdc_lookup values('BLANK_FIELDS', 'CA12293C', 'Other blank value', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', 'Y', 'Value', '', '', '', '', '', '', '', '', '16', '');

insert into pdc_lookup values('G_VALUE_SET_NAME', 'CA12294C', 'YNNA_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '16', '');

insert into pdc_lookup values('TOPIC', 'CA12307C', 'Identifiers', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', 'identifiers', '', '', '', '', 'Category', '', '', '', '', '', '', 'N', '', '16', '');
insert into pdc_lookup values('TOPIC', 'CA12308C', 'Demographics', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', 'demographics', '', '', '', '', 'Category', '', '', '', '', '', '', 'N', '', '16', '');
insert into pdc_lookup values('TOPIC', 'CA12309C', 'Consent', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', 'consent', '', '', '', '', 'Category', '', '', '', '', '', '', 'N', '', '16', '');
insert into pdc_lookup values('PATIENT_INFORMATION', 'CA12295C', 'I agree to donate blood for this project', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', 'donate_blood', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '16', '');
insert into pdc_lookup values('PATIENT_INFORMATION', 'CA12296C', 'I agree that a blood sample may be obtained at the time of my routine blood drawing or surgery', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', 'agree_blood_obtain', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '16', '');
insert into pdc_lookup values('PATIENT_INFORMATION', 'CA12297C', 'I agree to allow an additional needle stick if necessary to obtain a blood sample', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', 'agree_needle', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '16', '');
insert into pdc_lookup values('PATIENT_INFORMATION', 'CA12298C', 'I agree to donate urine for this project', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', 'donate_urine', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '16', '');
insert into pdc_lookup values('PATIENT_INFORMATION', 'CA12299C', 'I agree to donate tissue for this project', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', 'donate_tissue', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '16', '');
insert into pdc_lookup values('PATIENT_INFORMATION', 'CA12300C', 'I agree to donate saliva for this project', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', 'donate_saliva', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '16', '');
insert into pdc_lookup values('PATIENT_INFORMATION', 'CA12301C', 'I agree to donate cerebral spinal fluid for this project', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', 'donate_csf', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '16', '');
insert into pdc_lookup values('PATIENT_INFORMATION', 'CA12302C', 'I agree to donate amniotic fluid for this project', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', 'donate_amniotic', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '16', '');
insert into pdc_lookup values('PATIENT_INFORMATION', 'CA12303C', 'I agree that you can use my specimen for genetic testing for this project', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', 'agree_gene_test', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '16', '');
insert into pdc_lookup values('PATIENT_INFORMATION', 'CA12304C', 'If genetic disease information is or becomes available, I wish to be notified of the results', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', 'gene_info', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '16', '');
insert into pdc_lookup values('PATIENT_INFORMATION', 'CA12305C', 'I am willing to have you review my medical record in the future', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', 'review_med_rec', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '16', '');
insert into pdc_lookup values('PATIENT_INFORMATION', 'CA12306C', 'I am willing to be contacted by bank staff or Beaumont Hospitals researchers in the future', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', 'contact_in_future', '1', 'N', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '16', '');

insert into pdc_lookup values('SAMPLE_TYPE', 'CA12310C', 'Amniotic Fluid', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('SAMPLE_TYPE', 'CA12311C', 'Protein', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('SAMPLE_TYPE', 'CA12312C', 'Saliva', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('SAMPLE_TYPE', 'CA12313C', 'Stained Slide', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('SAMPLE_TYPE', 'CA12314C', 'Cell Prep Slide: Cytospin', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('SAMPLE_TYPE', 'CA12315C', 'Cell Prep Slide: Scraping', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '', '');
insert into pdc_lookup values('SAMPLE_TYPE', 'CA12316C', 'Cell Prep Slide: Smear', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '', '');

insert into pdc_lookup values('CELL_SOURCE', 'CA12317C', 'Cell source', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', 'cell_source', '1', 'Y', 'cv', '', 'Element', '', '', '', '', '', '', 'N', '', '16', '');
insert into pdc_lookup values('CELL_SOURCE', 'CA12318C', 'Blood', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '16', '');
insert into pdc_lookup values('CELL_SOURCE', 'CA12319C', 'Buccal', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '16', '');
insert into pdc_lookup values('CELL_SOURCE', 'CA12320C', 'Buffy coat', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '16', '');
insert into pdc_lookup values('CELL_SOURCE', 'CA12321C', 'Fecal', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '16', '');
insert into pdc_lookup values('CELL_SOURCE', 'CA12322C', 'Ovarian', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '16', '');
insert into pdc_lookup values('CELL_SOURCE', 'CA12323C', 'Saliva', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '16', '');
insert into pdc_lookup values('CELL_SOURCE', 'CA12324C', 'Synovial fluid', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'Value', '', '', '', '', '', '', '', '', '16', '');
insert into pdc_lookup values('CELL_SOURCE', 'CA12325C', 'Other cell source', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', 'Y', 'Value', '', '', '', '', '', '', '', '', '16', '');
insert into pdc_lookup values('CELL_SOURCE', 'CA12326C', 'CELL_SOURCE_DET', '', '', 'ARD_CAP', 'A', 'P', '', '1.48', '', '', '', '', '', '', 'ValueSetGraphContext', '', '', '', '', '', '', '', '', '16', '');

commit;
